import 'fake-indexeddb/auto';
import { it, expect } from 'vitest';
import { writeFileSync, readFileSync } from 'node:fs';
import { createProject, createEntity, newId, validateProject } from '../src/domain/model';
import type { Entity, ProjectData } from '../src/domain/types';
import { startTrial, stepTrial, pinTrialRecord, checkTrialForeshadows, trialNarrativeOccurrences } from '../src/domain/runtime';
import { assessPresentationClaims } from '../src/domain/narrative';
import { startTrialVerified, replaySavedTraceVerified } from '../src/domain/runtimeVerified';
import { preparePartialCheckpoint, previewCheckpointMigration, confirmedCheckpointMigration } from '../src/domain/checkpoints';
import { prepareTraceReconfirmation, confirmTraceReconfirmation, traceRevisionChanges } from '../src/domain/traceReconfirmation';
import { startChapterReading, presentNextChapterScene, pinChapterReadingRecord } from '../src/domain/presentation';
import { ScenarioStore, cloneProject } from '../src/storage/store';
import { exportScenario, inspectScenario } from '../src/storage/archive';
import { sha256, jsonBytes } from '../src/storage/json';
const out='/tmp/shinariokanri-independent-rb05-narrative-5c28c04/independent/fixtures';
const save=(id:string,data:unknown)=>writeFileSync(`${out}/${id}.json`,JSON.stringify(data,null,2)+'\n');
function fixture(){
 const p=createProject('独立 版境界'),s=createEntity(p.projectId,'scene','開始場面',{body:[{id:newId(),kind:'paragraph',text:'😀世界の旧稿。'}]}),v=createEntity(p.projectId,'variable','金額',{key:'money',valueType:'integer',initial:{type:'integer',value:2},allowed:{min:0,max:100},scope:'across_runs'}),entry=createEntity(p.projectId,'flow_node','入口',{nodeType:'entry',sceneId:s.id}),end=createEntity(p.projectId,'flow_node','終端',{nodeType:'terminal',terminalReason:'作者が定めた終わり'}),add=createEntity(p.projectId,'effect','金額+1',{operation:'add',targetId:v.id,value:{type:'integer',value:1}}),edge=createEntity(p.projectId,'flow_edge','終端へ',{fromId:entry.id,toId:end.id,effectIds:[add.id]}),graph=createEntity(p.projectId,'flow_graph','本編',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});
 p.entities.push(s,v,entry,end,add,edge,graph);return{p,s,v,entry,end,edge};
}
async function pin(p:ProjectData,session:ReturnType<typeof startTrial>){
 const ids={checkpointId:newId(),snapshotId:newId()},r=pinTrialRecord(session,ids),cp={...createEntity(p.projectId,'checkpoint','旧開始',r.checkpoint),id:ids.checkpointId},trace=createEntity(p.projectId,'trace','旧経路',r.trace);p.entities.push(cp,trace);p.snapshots.push({id:ids.snapshotId,content:r.content,contentHash:await sha256(jsonBytes(r.content)),createdAt:'2026-10-08T07:00:00Z',versionLabel:'旧証跡'});return{cp,trace};
}
it('EN01 initial variable stubs remain declared stubs when reconfirming the same path',async()=>{
 const f=fixture(),initial=startTrial(f.p,{entryId:f.entry.id,stub:{variables:{[f.v.id]:{type:'integer',value:8}}}}),old=await pin(f.p,stepTrial(f.p,initial,{edgeId:f.edge.id}));f.s.data.body[0].text='改訂稿';f.p.revision='2';const plan=await prepareTraceReconfirmation(f.p,old.trace.id),cp=plan.entities.find((e):e is Entity<'checkpoint'>=>e.kind==='checkpoint')!,trace=plan.entities.find((e):e is Entity<'trace'>=>e.kind==='trace')!;save('EN01',{project:f.p,validation:validateProject(f.p),old,plan});expect(validateProject(f.p).ok).toBe(true);expect(old.cp.data.runtimeState.provenance).toBe('stub');expect(cp.data.runtimeState.provenance).toBe('stub');expect(cp.data.runtimeState.variableValues[f.v.id]).toEqual({type:'integer',value:8});expect(trace.data.externalMode).toBe('stub');
});
it('EN02 a rejected named item instance is not carried into the changed edition',async()=>{
 const f=fixture(),type=createEntity(f.p.projectId,'item','鍵型',{itemMode:'type'}),individual=createEntity(f.p.projectId,'item','唯一の青い鍵',{itemMode:'instance',typeId:type.id});f.p.entities.push(type,individual);const cp=await preparePartialCheckpoint(f.p,{entryId:f.entry.id});cp.checkpoint.data.runtimeState.itemInstances=[{instanceId:individual.id,typeId:type.id,quantity:1,ownerId:null,locationId:null,consumed:false}];f.p.entities.push(cp.checkpoint);f.p.snapshots.push(...cp.snapshots);individual.status='rejected';f.p.revision='2';const plan=await previewCheckpointMigration(f.p,cp.checkpoint.id,{entryId:f.entry.id});save('EN02',{project:f.p,validation:validateProject(f.p),plan});expect(validateProject(f.p).ok).toBe(true);expect(plan.migrated.checkpoint.data.runtimeState.itemInstances).toEqual([]);expect(plan.changes.some(x=>x.id===individual.id&&x.action==='drop')).toBe(true);
});
it('EN03 a selected two-scene chapter path is not expanded to its whole chapter during reconfirmation',async()=>{
 const f=fixture(),second=createEntity(f.p.projectId,'scene','第二場面'),third=createEntity(f.p.projectId,'scene','選択していない第三場面'),chapter=createEntity(f.p.projectId,'chapter','章',{sceneIds:[f.s.id,second.id,third.id]});f.p.entities.push(second,third,chapter);for(const s of[f.s,second,third])s.data.chapterId=chapter.id;let session=await startChapterReading(f.p,{sceneIds:[second.id,f.s.id]});while(session.status==='ready')session=presentNextChapterScene(f.p,session);const ids={checkpointId:newId(),snapshotId:newId()},r=pinChapterReadingRecord(session,ids),cp={...createEntity(f.p.projectId,'checkpoint','旧章開始',r.checkpoint),id:ids.checkpointId},trace=createEntity(f.p.projectId,'trace','二場面だけの順序',r.trace);f.p.entities.push(cp,trace);f.p.snapshots.push({id:ids.snapshotId,content:r.content,contentHash:await sha256(jsonBytes(r.content)),createdAt:'2026-10-08T07:00:00Z',versionLabel:'選択経路'});f.s.data.body[0].text='章の改訂';f.p.revision='2';const plan=await prepareTraceReconfirmation(f.p,trace.id),next=plan.entities.find((e):e is Entity<'trace'>=>e.kind==='trace')!;save('EN03',{project:f.p,validation:validateProject(f.p),old:trace,plan});expect(validateProject(f.p).ok).toBe(true);expect(next.data.readingPath!.sceneIds).toEqual([second.id,f.s.id]);expect(next.data.readingPath!.sceneIds).not.toContain(third.id);
});
it('EN04 a chapter path with author supplied initial knowledge or values needs explicit migration or recreation',async()=>{
 const f=fixture(),initial=await startChapterReading(f.p,{sceneIds:[f.s.id]});initial.state.variableValues[f.v.id]={type:'integer',value:8};initial.startState.variableValues[f.v.id]={type:'integer',value:8};const session=presentNextChapterScene(f.p,initial),ids={checkpointId:newId(),snapshotId:newId()},r=pinChapterReadingRecord(session,ids),cp={...createEntity(f.p.projectId,'checkpoint','個別章開始',r.checkpoint),id:ids.checkpointId},trace=createEntity(f.p.projectId,'trace','途中値あり章経路',r.trace);f.p.entities.push(cp,trace);f.p.snapshots.push({id:ids.snapshotId,content:r.content,contentHash:await sha256(jsonBytes(r.content)),createdAt:'2026-10-08T07:00:00Z',versionLabel:'途中値'});f.s.data.body[0].text='新稿';f.p.revision='2';let plan:Awaited<ReturnType<typeof prepareTraceReconfirmation>>|undefined,error='';try{plan=await prepareTraceReconfirmation(f.p,trace.id);}catch(e){error=(e as Error).message;}save('EN04',{project:f.p,validation:validateProject(f.p),old:{cp,trace},plan,error});expect(validateProject(f.p).ok).toBe(true);expect(error).toMatch(/途中|開始状態|移行|再作成/);
});
it('EN05 metadata-only saves leave source semantics unchanged; actual/mixed cannot be converted to stub evidence',async()=>{
 const f=fixture(),old=await pin(f.p,stepTrial(f.p,startTrial(f.p),{edgeId:f.edge.id}));f.p.entities.push(createEntity(f.p.projectId,'collection','回帰集合',{mode:'fixed',purpose:'regression',memberIds:[old.trace.id]}));f.p.revision='4';expect(traceRevisionChanges(f.p,old.trace)).toEqual([]);const errors=[];for(const mode of['actual','mixed']as const){old.trace.data.externalMode=mode;try{await prepareTraceReconfirmation(f.p,old.trace.id);}catch(e){errors.push((e as Error).message);}}save('EN05',{project:f.p,errors});expect(errors).toHaveLength(2);expect(errors.every(e=>e.includes('受領証跡'))).toBe(true);
});
it('EN06 preview changes and stale revisions are rejected without mutating stored source evidence',async()=>{
 const f=fixture(),old=await pin(f.p,stepTrial(f.p,startTrial(f.p),{edgeId:f.edge.id})),before=structuredClone(f.p),plan=await prepareTraceReconfirmation(f.p,old.trace.id),forged=structuredClone(plan);forged.entities.find(e=>e.kind==='trace')!.name='偽の確認';await expect(confirmTraceReconfirmation(f.p,forged)).rejects.toThrow('変更');f.p.revision='1';await expect(confirmTraceReconfirmation(f.p,plan)).rejects.toThrow('更新');f.p.revision=before.revision;save('EN06',{project:f.p,plan,before});expect(f.p).toEqual(before);
});
it('EN07 migrated partial starts, old proof and new proof survive atomic reload, native restore and clone',async()=>{
 const f=fixture(),old=await pin(f.p,stepTrial(f.p,startTrial(f.p),{edgeId:f.edge.id})),partial=await preparePartialCheckpoint(f.p,{entryId:f.entry.id});partial.checkpoint.data.runtimeState.variableValues[f.v.id]={type:'integer',value:8};f.p.entities.push(partial.checkpoint);f.p.snapshots.push(...partial.snapshots);f.s.data.body[0].text='現在本文';f.p.revision='2';const migration=await confirmedCheckpointMigration(f.p,await previewCheckpointMigration(f.p,partial.checkpoint.id,{entryId:f.entry.id}),'migrate');f.p.entities.push(migration.checkpoint);f.p.snapshots.push(...migration.snapshots);const renewed=await confirmTraceReconfirmation(f.p,await prepareTraceReconfirmation(f.p,old.trace.id,{checkpointId:migration.checkpoint.id}));const p={...f.p,entities:[...f.p.entities.filter(e=>!renewed.entities.some(n=>n.id===e.id)),...renewed.entities],snapshots:[...f.p.snapshots,...renewed.snapshots]},newTrace=renewed.entities.find((e):e is Entity<'trace'>=>e.kind==='trace')!;const db=new ScenarioStore({databaseName:'independent-narrative-'+newId()});try{await db.importScenario(await inspectScenario(await exportScenario(f.p)),{mode:'new'});const saved=(await db.saveProject(p,{reason:'独立 原子保存'})).project,reloaded=(await db.getProject(p.projectId))!,archive=await exportScenario(reloaded),restored=(await inspectScenario(archive)).project,clone=await cloneProject(restored),results=[];for(const target of[reloaded,restored,clone.project]){const map=target===clone.project?clone.idMap:undefined,a=await replaySavedTraceVerified(target,map?.[old.trace.id]??old.trace.id),b=await replaySavedTraceVerified(target,map?.[newTrace.id]??newTrace.id);results.push({validation:validateProject(target).ok,old:a.state.variableValues[map?.[f.v.id]??f.v.id],next:b.state.variableValues[map?.[f.v.id]??f.v.id],oldStatus:a.status,nextStatus:b.status,nextProvenance:b.state.provenance});}save('EN07',{project:p,validation:validateProject(p),savedRevision:saved.revision,reloaded,restored,clone,results,archiveByteSize:archive.byteLength});expect(results).toEqual(Array.from({length:3},()=>({validation:true,old:{type:'integer',value:3},next:{type:'integer',value:9},oldStatus:'terminal',nextStatus:'terminal',nextProvenance:'partial'})));expect(reloaded.entities.find(e=>e.id===old.trace.id)).toEqual(old.trace);}finally{await db.deleteDatabase();}
});
it('EN08 Unicode deadlines and statement acquisition survive store restart, native bytes and cloned ID correspondence',async()=>{
 const results=[];
 for(const id of['NP02','NP03']){
  const f=JSON.parse(readFileSync(out+'/'+id+'.json','utf8')),p:ProjectData=f.project,recorded=await pin(p,f.session),databaseName='independent-narrative-content-'+newId(),db=new ScenarioStore({databaseName});let cold:ScenarioStore|undefined;
  try{
   await db.saveProject(p,{reason:'独立 提示証跡の原子保存'});db.close();cold=new ScenarioStore({databaseName});const reloaded=(await cold.getProject(p.projectId))!,bytes=await exportScenario(reloaded),restored=(await inspectScenario(bytes)).project,cloned=await cloneProject(restored),observed=[];
   for(const target of[reloaded,restored,cloned.project]){
    const traceId=target===cloned.project?cloned.idMap[recorded.trace.id]:recorded.trace.id,session=await replaySavedTraceVerified(target,traceId),claims=assessPresentationClaims(session.content,trialNarrativeOccurrences(session)),findings=checkTrialForeshadows(target,session);observed.push({valid:validateProject(target).ok,status:session.status,knowledge:claims.map(c=>c.knowledge),deadlineFindings:findings.filter(x=>x.message.includes('指定提示位置')).map(x=>x.status)});
   }
   results.push({id,project:p,reloaded,restored,clone:cloned,observed,archiveBytes:bytes.byteLength});expect(observed.every(v=>v.valid&&v.status==='terminal')).toBe(true);if(id==='NP02')expect(observed.map(v=>v.knowledge)).toEqual([['acquired'],['acquired'],['acquired']]);else expect(observed.map(v=>v.deadlineFindings)).toEqual([['candidate'],['candidate'],['candidate']]);
  }finally{cold?.close();await db.deleteDatabase();}
 }
 save('EN08',{results});
});
