import 'fake-indexeddb/auto';
import {beforeAll,it,expect} from 'vitest';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createProject,createEntity,newId,textToRichText,validateProject} from '../src/domain/model';
import {checkProductionRules,verifyProductionSources,productionCheckView} from '../src/domain/productionChecks';
import {createWorldSnapshot} from '../src/domain/world';
import {prepareReuse,resolveReuseContent} from '../src/domain/reuse';
import {ScenarioStore} from '../src/storage/store';
import {inspectScenario,worldSnapshotContents} from '../src/storage/archive';
import type {ProjectData,Entity,ProjectContent} from '../src/domain/types';
const root='/tmp/shinariokanri-independent-rb07-22bd75a/independent/fixtures';
const original=()=>JSON.parse(readFileSync(root+'/ui-fixed-speaker-production.json','utf8'))as{project:ProjectData;ids:Record<string,string>};
const report=(id:string,data:unknown)=>writeFileSync(root+'/'+id+'.json',JSON.stringify(data,null,2)+'\n');
let reusable:{project:ProjectData;ids:Record<string,string>},worlds:{project:ProjectData;worldA:ProjectData;worldB:ProjectData;ids:Record<string,string>;registry:Record<string,ProjectContent>};
beforeAll(async()=>{
 const reusePath=root+'/reuse-production.json';if(existsSync(reusePath))reusable=JSON.parse(readFileSync(reusePath,'utf8'));else{
  let {project:p,ids}=original();const use=createEntity(p.projectId,'scene','旧共通台詞の使用先',{chapterId:ids.chapter});use.status='confirmed';p.entities.push(use);p=(await prepareReuse(p,{ownerId:use.id,sourceId:ids.scene,mode:'reference'})).candidate;
  const owner=p.entities.find(e=>e.id===use.id)as Entity<'scene'>,borrowedLine=owner.data.reuse!.bindings![ids.line],borrowedBlock=owner.data.reuse!.bindings![ids.blockId],inner=owner.data.reuse!.pinnedSnapshotId;
  p=await createWorldSnapshot(p,'共通元を含む外側固定版');const outer=p.snapshots.at(-1)!.id,frame=p.entities.find(e=>e.id===ids.frame)as Entity<'storyboard_frame'>;frame.data.anchor={entityId:borrowedLine,lineId:borrowedLine,blockId:borrowedBlock,start:3,end:5,sourceVersionId:outer};frame.data.cueIds=[];
  expect(validateProject(p).ok).toBe(true);reusable={project:p,ids:{...ids,use:use.id,borrowedLine,borrowedBlock,inner,outer}};writeFileSync(reusePath,JSON.stringify(reusable,null,2)+'\n');
 }
 const worldPath=root+'/world-production.json';if(existsSync(worldPath))worlds=JSON.parse(readFileSync(worldPath,'utf8'));else{
  let worldB=createProject('独立・声の共通元世界B');const a=createEntity(worldB.projectId,'character','固定世界話者A'),b=createEntity(worldB.projectId,'character','後の世界話者B'),line=createEntity(worldB.projectId,'dialogue_line','世界の元台詞',{speakerId:a.id,text:textToRichText('😀旧版の世界台詞')}),rule=createEntity(worldB.projectId,'voice_rule','固定世界Aの基準',{characterId:a.id,firstPerson:'私',validity:{worldRange:{start:'10',end:'20'},routeCondition:null,presentationAnchor:null}});[a,b,line,rule].forEach(e=>e.status='confirmed');worldB.entities.push(a,b,line,rule);worldB=await createWorldSnapshot(worldB,'話者Aの旧世界');const old=worldB.snapshots.at(-1)!;
  let worldA=createProject('独立・参照世界A');worldA.worldReferences=[{projectId:worldB.projectId,immutableSnapshotId:old.id,contentHash:old.contentHash}];worldA=await createWorldSnapshot(worldA,'Bの旧世界を参照するA');const parent=worldA.snapshots.at(-1)!;
  const current=worldB.entities.find(e=>e.id===line.id)as Entity<'dialogue_line'>;current.data.speakerId=b.id;worldB=await createWorldSnapshot(worldB,'話者Bの新世界');const newest=worldB.snapshots.at(-1)!;
  const p=createProject('独立・推移世界字幕の作品'),frame=createEntity(p.projectId,'storyboard_frame','推移旧世界の字幕',{anchor:{entityId:line.id,lineId:line.id,blockId:line.data.text[0].id,sourceVersionId:old.id},caption:textToRichText('😀字幕は現在コマの本文'),cueIds:[]});frame.status='confirmed';p.entities.push(frame);p.worldReferences=[{projectId:worldA.projectId,immutableSnapshotId:parent.id,contentHash:parent.contentHash}];
  const registry={[parent.id]:parent.content,[old.id]:old.content,[newest.id]:newest.content};expect(validateProject(p,{worldSnapshots:registry}).ok).toBe(true);worlds={project:p,worldA,worldB,ids:{a:a.id,b:b.id,line:line.id,rule:rule.id,frame:frame.id,old:old.id,parent:parent.id,newest:newest.id},registry};writeFileSync(worldPath,JSON.stringify(worlds,null,2)+'\n');
 }
});
it('R7D18 unverified/missing/corrupt source is never current substitute or known truth',async()=>{
 const {project:p,ids}=original();const raw=checkProductionRules(p,{at:'10'}).filter(x=>x.lineId===ids.frame);expect(raw.filter(x=>x.kind==='voice')).toHaveLength(1);expect(raw.every(x=>x.value==='unknown')).toBe(true);
 const verified=await verifyProductionSources(p);expect(verified.has(ids.pin)).toBe(true);expect(checkProductionRules(p,{at:'10',verifiedVersionIds:verified}).filter(x=>x.lineId===ids.frame&&x.kind==='voice')[0].value).toBe('true');
 const corrupt=structuredClone(p);corrupt.snapshots.find(s=>s.id===ids.pin)!.content.entities.find(e=>e.id===ids.line)!.name='改ざん';await expect(verifyProductionSources(corrupt)).rejects.toThrow('固定版hash');await expect(productionCheckView(corrupt)).rejects.toThrow();
 const missing=structuredClone(p);missing.snapshots=missing.snapshots.filter(s=>s.id!==ids.pin);await expect(verifyProductionSources(missing)).rejects.toThrow('固定版hash');expect(checkProductionRules(missing,{at:'10'}).filter(x=>x.lineId===ids.frame).every(x=>x.value==='unknown')).toBe(true);report('R7D18',{raw,verified:[...verified],corruptRefused:true,missingRefused:true});
});
it('R7D19 transitive fixed world speaker remains old across newer world, empty archive and clone without canonical borrowed copies',async()=>{
 const {project:p,ids,registry}=structuredClone(worlds),before=structuredClone(p),view=await productionCheckView(p,registry),checks=checkProductionRules(view.project,{...view,at:'10'}).filter(x=>x.lineId===ids.frame&&x.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({ruleId:ids.rule,value:'true',sourceAnchor:{entityId:ids.line,sourceVersionId:ids.old},ruleAnchor:{entityId:ids.rule,sourceVersionId:ids.old}});expect(p).toEqual(before);expect(p.entities).toHaveLength(1);
 const broken=structuredClone(registry);delete broken[ids.old];await expect(productionCheckView(p,broken)).rejects.toThrow();const corrupt=structuredClone(registry);corrupt[ids.old].entities.find(e=>e.id===ids.line)!.name='改ざん';await expect(productionCheckView(p,corrupt)).rejects.toThrow();
 const db=new ScenarioStore({databaseName:'production-world-'+newId()});try{
  await db.saveProject(worlds.worldB,{reason:'声の共通元世界'});await db.saveProject(worlds.worldA,{reason:'推移固定世界',worldPin:{world:worlds.worldB,snapshotId:ids.old}});const saved=(await db.saveProject(p,{reason:'推移世界の字幕だけ',worldPin:{world:worlds.worldA,snapshotId:ids.parent,dependencies:{[ids.old]:worlds.worldB}}})).project,prepared=await inspectScenario(await db.exportProject(p.projectId),{worker:false});
  for(const mode of ['new','clone']as const){const target=new ScenarioStore({databaseName:'production-world-restore-'+newId()});try{const restored=(await target.importScenario(prepared,{mode})).project,restoredView=await productionCheckView(restored,worldSnapshotContents(await target.listWorldSnapshots())),frame=restored.entities.find(e=>e.kind==='storyboard_frame')!,found=checkProductionRules(restoredView.project,{...restoredView,at:'10'}).filter(x=>x.lineId===frame.id&&x.kind==='voice');expect(found).toHaveLength(1);expect(found[0].value).toBe('true');expect(restored.entities).toHaveLength(1);}finally{await target.deleteDatabase();}}
  report('R7D19',{checks,sourceUnchanged:true,savedRevision:saved.revision,emptyAndClone:true,canonicalCount:1,missingAndCorruptRefused:true});
 }finally{await db.deleteDatabase();}
});
it('R7D20 fixed outer edition resolves its borrowed source line and speaker rather than using current original',async()=>{
 const {project:p,ids}=structuredClone(reusable),current=p.entities.find(e=>e.id===ids.line)as Entity<'dialogue_line'>;current.data.speakerId=ids.other;expect(validateProject(p).ok).toBe(true);const before=structuredClone(p),view=await productionCheckView(p),checks=checkProductionRules(view.project,{...view,at:'10'}).filter(x=>x.lineId===ids.frame&&x.kind==='voice');report('R7D20',{checks,allFrameChecks:checkProductionRules(view.project,{...view,at:'10'}).filter(x=>x.lineId===ids.frame),oldBorrowedSource:resolveReuseContent(p.snapshots.find(s=>s.id===ids.outer)!.content,p.snapshots).entities.find(e=>e.id===ids.borrowedLine),viewContainsBorrowed:view.project.entities.some(e=>e.id===ids.borrowedLine)});expect(p).toEqual(before);expect(checks).toHaveLength(1);expect(checks[0].value).toBe('true');
});
it('R7D21 production view refuses altered local reuse dependencies even without a caption source pin',async()=>{
 const {project:p,ids}=structuredClone(reusable);const frame=p.entities.find(e=>e.id===ids.frame)as Entity<'storyboard_frame'>;frame.data.anchor={entityId:ids.line};p.snapshots.find(s=>s.id===ids.inner)!.content.entities.find(e=>e.id===ids.line)!.name='共通元改ざん';const before=structuredClone(p);await expect(productionCheckView(p)).rejects.toThrow();expect(p).toEqual(before);
});
it('R7D22 saved old-world expected hash authorizes the same old caption after adopting a newer world; descriptor absence/corruption refuses',async()=>{
 const input=JSON.parse(readFileSync(root+'/world-new-current-production.json','utf8'))as{project:ProjectData;ids:Record<string,string>;world:ProjectData;registry:Record<string,ProjectContent>};const {project:p,ids,registry}=input,pins=input.world.snapshots,before=structuredClone(p);expect(validateProject(p,{worldSnapshots:registry}).ok).toBe(true);
 await expect(productionCheckView(p,registry)).rejects.toThrow('INTEGRITY_FAILED');const damaged=structuredClone(pins);damaged.find(s=>s.id===ids.old)!.contentHash='0'.repeat(64);await expect(productionCheckView(p,registry,damaged)).rejects.toThrow('INTEGRITY_FAILED');
 const view=await productionCheckView(p,registry,pins),checks=checkProductionRules(view.project,{...view,at:'10'}).filter(x=>x.lineId===ids.frame&&x.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({value:'true',sourceAnchor:{entityId:ids.line,sourceVersionId:ids.old},ruleAnchor:{entityId:ids.rule,sourceVersionId:ids.old}});expect(view.project.entities.find(e=>e.id===ids.line)).toMatchObject({data:{speakerId:ids.b}});expect(p).toEqual(before);report('R7D22',{checks,oldDescriptorHash:pins.find(s=>s.id===ids.old)!.contentHash,missingAndWrongDescriptorRefused:true,currentWorldSpeakerB:true,canonicalUnchanged:true});
 const db=new ScenarioStore({databaseName:'historical-world-caption-'+newId()});try{
  await db.saveProject(worlds.worldB,{reason:'世界原稿保存'});await db.saveProject(worlds.worldA,{reason:'Aの旧B依存保存',worldPin:{world:worlds.worldB,snapshotId:ids.old}});const oldWork=(await db.saveProject(worlds.project,{reason:'旧A/B世界を使う字幕作品',worldPin:{world:worlds.worldA,snapshotId:ids.parent,dependencies:{[ids.old]:worlds.worldB}}})).project;
  const candidate:ProjectData=structuredClone({...oldWork,history:[]});candidate.history=oldWork.history;candidate.worldReferences=p.worldReferences;const saved=(await db.saveProject(candidate,{reason:'本編の採用世界のみ新版へ',worldPin:{world:worlds.worldB,snapshotId:ids.newest}})).project;const prepared=await inspectScenario(await db.exportProject(saved.projectId),{worker:false});
  for(const mode of ['new','clone']as const){const target=new ScenarioStore({databaseName:'historical-caption-restore-'+newId()});try{const restored=(await target.importScenario(prepared,{mode})).project,worldRecords=await target.listWorldSnapshots(),restoredView=await productionCheckView(restored,worldSnapshotContents(worldRecords),Object.values(worldRecords).flatMap(w=>w.snapshots)),frame=restored.entities.find(e=>e.kind==='storyboard_frame')!,found=checkProductionRules(restoredView.project,{...restoredView,at:'10'}).filter(x=>x.lineId===frame.id&&x.kind==='voice');expect(found).toHaveLength(1);expect(found[0]).toMatchObject({value:'true',sourceAnchor:{sourceVersionId:ids.old},ruleAnchor:{sourceVersionId:ids.old}});expect(restored.entities).toHaveLength(1);}finally{await target.deleteDatabase();}}
  report('R7D22-native',{savedRevision:saved.revision,archiveEmptyNewAndClone:true,oldPin:ids.old,newPin:ids.newest,canonicalCount:1});
 }finally{await db.deleteDatabase();}
});
it('R7D23 complete archive includes the explicitly cited old world even when the work itself never adopted it as current world',async()=>{
 const input=JSON.parse(readFileSync(root+'/world-new-current-production.json','utf8'))as{project:ProjectData;ids:Record<string,string>;world:ProjectData;registry:Record<string,ProjectContent>};const {project:p,ids}=input;const db=new ScenarioStore({databaseName:'fresh-historical-caption-'+newId()});try{
  await db.saveProject(worlds.worldB,{reason:'世界原稿保存'});await db.saveProject(worlds.worldA,{reason:'別作品の旧Bを固定登録',worldPin:{world:worlds.worldB,snapshotId:ids.old}});const saved=(await db.saveProject(p,{reason:'新世界を採用し旧台詞だけ引用',worldPin:{world:worlds.worldB,snapshotId:ids.newest}})).project,worldRecords=await db.listWorldSnapshots(),view=await productionCheckView(saved,worldSnapshotContents(worldRecords),Object.values(worldRecords).flatMap(w=>w.snapshots)),checks=checkProductionRules(view.project,{...view,at:'10'}).filter(x=>x.lineId===ids.frame&&x.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0].value).toBe('true');report('R7D23-before',{saved,checks,worldPinIds:Object.keys(worldRecords)});
  const prepared=await inspectScenario(await db.exportProject(saved.projectId),{worker:false});expect(worldSnapshotContents(prepared.worlds)[ids.old]).toBeDefined();for(const mode of ['new','clone']as const){const target=new ScenarioStore({databaseName:'fresh-historical-restore-'+newId()});try{const restored=(await target.importScenario(prepared,{mode})).project,records=await target.listWorldSnapshots(),restoredView=await productionCheckView(restored,worldSnapshotContents(records),Object.values(records).flatMap(w=>w.snapshots)),frame=restored.entities.find(e=>e.kind==='storyboard_frame')!;expect(checkProductionRules(restoredView.project,{...restoredView,at:'10'}).filter(x=>x.lineId===frame.id&&x.kind==='voice')[0].value).toBe('true');expect(restored.entities).toHaveLength(1);report('R7D23-'+mode,{sourceChecks:checks,restoredKnown:true,oldPinIncluded:true,canonicalCount:1});}finally{await target.deleteDatabase();}}
 }finally{await db.deleteDatabase();}
});
