import json,hashlib,subprocess,datetime
from pathlib import Path
r=Path('/tmp/shinariokanri-independent-rb07-297f19a');old=Path('/tmp/shinariokanri-independent-rb07-1b7b508');repo=Path('/workspace/shinariokanri-rb07');c='297f19a64040179e9165caa6c48fa20044d43f05';tree='dd992811f03701d63014dcedeff04185d0cfeb9a';base='b310800c98bc9a89b93182ad721380a0be99d2d3'
sha=lambda b:hashlib.sha256(b).hexdigest();read=lambda name:json.loads((r/name).read_text())
def write(name,data):(r/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
def gitdata(commit,name):return subprocess.check_output(['git','show',commit+':'+name],cwd=repo)
previous=json.loads((old/'INDEPENDENT_REVIEW.json').read_text());oldbind=json.loads((old/'SOURCE_COMMIT_BINDING.json').read_text());oldsha=sha((old/'INDEPENDENT_REVIEW.json').read_bytes());assert oldsha=='1187500088167f5d76df09e42212a4dc5461b051fb433db8e4631a1847b8aa0b';oldartifacts=json.loads((old/'ARTIFACT_BINDING.json').read_text())['artifacts'];assert all(sha((old/x['file']).read_bytes())==x['sha256']for x in oldartifacts)
m=read('source-manifest.json');files=[];oldsrc={x['file']:x['sha256']for x in oldbind['files']};changed=[]
for row in m['files']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name));files.append({'file':name,'sha256':h,'manifestMatches':True,'commitMatches':True})
 if oldsrc.get(name)!=h:changed.append(name)
assert len(files)==169
norm=[]
for row in oldbind['originalContracts']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name))==sha(gitdata(base,name));norm.append({**row,'baseMatches':True,'commitMatches':True,'originalHashMatches':True})
legacy=[]
for row in oldbind['legacyFixtureInputs']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name));legacy.append({**row,'notExecutedInThisRB07Review':True})
inputs=[]
for row in oldbind['independentInputs']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256'];item={'file':name,'sha256':h,'sameBytesAs1b':True,'regenerated':False}
 if name.startswith('tests/'):assert h==sha(gitdata(c,name));item['commitMatches']=True
 inputs.append(item)
write('SOURCE_COMMIT_BINDING.json',{'commit':c,'tree':tree,'base':base,'sourceFileCount':169,'all169Match':True,'files':files,'changedSourceFrom1b':changed,'originalContracts':norm,'legacyFixtureInputs':legacy,'independentInputs':inputs,'historical1bReportSha256':oldsha,'historical109ArtifactsUnchanged':True})
assert 'Tests  18 passed (18)'in(r/'independent/domain-reinspection.log').read_text();assert 'Tests  1 failed | 6 passed (7)'in(r/'independent/domain-production-view.log').read_text();world=read('independent/browser-world.json');local=read('independent/browser-local-rule.json');assert all(x['status']=='passed'for x in world['results']);assert local['results'][0]['status']=='failed'
finding=previous['findings'][1];finding['actual']={'component':read('independent/fixtures/R7D24.json'),'normalApp':local['results'][0]};finding['cause']['sha256']=next(x['sha256']for x in files if x['file']=='src/domain/productionChecks.ts');finding['evidence']=['tests/independent-rb07-local-rule-anchor.test.ts','independent/domain-production-view.log','independent/browser-local-rule.json','independent/browser-local-rule.log','independent/fixtures/world-local-rule-production.json','independent/fixtures/R7D24.json','independent/fixtures/R7U13-observation.json']
report={'target':{'commit':c,'tree':tree,'base':base,'source169AllMatch':True,'frozenAt':m['frozenAt'],'verifiedAt':datetime.datetime.now(datetime.timezone.utc).isoformat()},'purpose':'Intermediate frozen independent RB07 repair review. Full104/116/24/6/RB07 not graded.','results':{'originalComponents':{'passed':17,'failed':0,'fixtureValidityPassed':1,'notAcceptance':True,'log':'independent/domain-reinspection.log'},'additionalComponents':{'passed':6,'failed':1,'cases':[{'id':f'R7D{i}','status':'failed'if i==24 else'passed'}for i in range(18,25)],'log':'independent/domain-production-view.log','archiveBoundary':'Fresh first-save work current newerB + historical olderB citation; complete archiveempty/new/clone known old caption and canonical count1.'},'selectedNormalApp':{'passed':2,'failed':1,'cases':world['results']+local['results'],'classification':'Actual App/native IndexedDB/Chromium151 dedicated5347, same frozen bytes/normal author check/cold/old source/complete file/rule root'},'otherNormalApp':'not_run at this intermediate source; prior1b10success is historical evidence, not current target success','production':'not_run at this intermediate source; newer frozen390 final candidate scheduled for full relevant production reinspection'},'findings':[finding],'resolvedFindings':previous['resolvedFindings']+[{'id':'R7D23/R7U12','historicalCommit':previous['target']['commit'],'historicalReportSha256':oldsha,'status':'passed_same_frozen_input_correct_expectation','actual':{'new':read('independent/fixtures/R7D23-new.json'),'clone':read('independent/fixtures/R7D23-clone.json'),'normalFileDownload':world['results'][1]}}],'descriptorContract':previous['descriptorContract'],'environment':{**previous['environment'],'ports':'Vite5347 stopped; production preview not started'},'originalContracts':previous['originalContracts'],'harnessHistory':'Exact10 fixed inputs reused. D23 added its originally requested clone mode after the formerly failing export became available. No product or original REQ/AT change.','historicalNegativeEvidence':previous['historicalNegativeEvidence']+[{'directory':str(old),'reportSha256':oldsha,'artifactCount':len(oldartifacts),'allArtifactsUnchanged':True}],'unexecuted':previous['unexecuted'],'productRepositoryWrites':False,'evidenceBinding':'SOURCE_COMMIT_BINDING169src/15originaldocs/4legacyhashonly/sameinputs; ARTIFACT_BINDING contains reviewer source/raw/results with trailing whitespace retained.'}
write('INDEPENDENT_REVIEW.json',report);(r/'INDEPENDENT_REVIEW.md').write_text(f'''RB07中間候補 `{c}` / tree `{tree}` の選択した再検査を確定した。原17部品＋fixture妥当性1件は成功。追加部品6成功・1負例、通常App2成功・1負例。旧世界を現在採用した履歴のない新規作品の明示旧字幕引用も、完全保存→empty new/cloneで旧版を保持し、通常cold検査・旧本文・完全保存downloadは成功した。\n\nR7D24/R7U13の作品ローカル用語の根拠を旧世界pinへ結ぶ負例は残る。元fixture/正期待/rawを保持し、390最終補修候補で同じ検査を継続する。中間297の他通常10群/productionは未実行で、1bの成功を現行へ流用しない。169src・原15資料・旧4fixture hash（今回未実行）・10固定入力・成果物SHAを結合し、1b109artifact/過去負例は不変。原104/116/24/6・全RB07・実端末/実Files/録音/支援技術/性能/長時間/実Auth/APIは未判定。repo製品・証拠・commitは編集していない。\n''')
paths={r/'source-manifest.json',r/'SOURCE_COMMIT_BINDING.json',r/'INDEPENDENT_REVIEW.json',r/'INDEPENDENT_REVIEW.md',r/'write-final-review.py',r/'independent-playwright.config.ts'};paths.update(f for f in(r/'independent').rglob('*')if f.is_file());paths.update(r.glob('tests/independent*.test.ts'));paths.update(f for f in r.glob('independent-app*')if f.is_file());a=[{'file':str(f.relative_to(r)),'sha256':sha(f.read_bytes()),'bytes':len(f.read_bytes())}for f in sorted(paths)];write('ARTIFACT_BINDING.json',{'commit':c,'tree':tree,'artifactCount':len(a),'artifacts':a,'source169AllMatch':True,'rawLogsTrailingWhitespacePreserved':True,'notEntirePlanPass':True});assert all(sha((r/x['file']).read_bytes())==x['sha256']for x in a)
print(json.dumps({'commit':c,'tree':tree,'originalParts':17,'additional':'6 passed/1 failed','selectedApp':'2 passed/1 failed','artifactCount':len(a),'reportSha256':sha((r/'INDEPENDENT_REVIEW.json').read_bytes())},ensure_ascii=False))
