import 'fake-indexeddb/auto';
import { expect, it } from 'vitest';
import { createProject, createEntity, emptyValidity, newId, validateProject } from '../src/domain/model';
import { initializeRuntimeState } from '../src/domain/conditions';
import { presentContent, startChapterReading, presentNextChapterScene, pinChapterReadingRecord, replayChapterReading } from '../src/domain/presentation';
import { startTrialVerified, replaySavedTraceVerified } from '../src/domain/runtimeVerified';
import { stepTrial, pinTrialRecord } from '../src/domain/runtime';
import { sha256, jsonBytes } from '../src/storage/json';
import { inspectScenario, exportScenario } from '../src/storage/archive';
import { cloneProject } from '../src/storage/store';

function fixture() {
 const p=createProject('Initial exception'),scene=createEntity(p.projectId,'scene','first'),last=createEntity(p.projectId,'scene','last'),entry=createEntity(p.projectId,'flow_node','entry',{nodeType:'entry',sceneId:scene.id,executionPolicy:'first_match'}),end=createEntity(p.projectId,'flow_node','end',{nodeType:'terminal',sceneId:last.id,terminalReason:'end'}),edge=createEntity(p.projectId,'flow_edge','next',{fromId:entry.id,toId:end.id,edgeType:'automatic',priority:0}),evidence=createEntity(p.projectId,'source','Evidence',{locator:'Synthetic section 1'}),q=createEntity(p.projectId,'variable','Quest',{key:'quest',valueType:'integer',initial:{type:'integer',value:0},allowed:{min:0,max:3},transitionRules:[{from:{type:'integer',value:0},to:{type:'integer',value:1}}]}),money=createEntity(p.projectId,'variable','Money',{key:'money',valueType:'integer',initial:{type:'integer',value:10},allowed:{min:0,max:20}}),f=createEntity(p.projectId,'foreshadow','Question',{resolutionPolicy:'this_work'});evidence.status='confirmed';
 const gain=createEntity(p.projectId,'effect','Gain',{operation:'add',targetId:money.id,value:{type:'integer',value:2}}),effect=createEntity(p.projectId,'effect','Intentional exception',{operation:'set',targetId:q.id,value:{type:'integer',value:3},exceptionDetails:{reason:'intentional route',targetScope:{projectId:p.projectId},validity:{...emptyValidity(),worldRange:{start:'0',end:'10'}},evidenceIds:[evidence.id]}}),disclosure=createEntity(p.projectId,'disclosure','Opening disclosure',{foreshadowId:f.id,anchor:{entityId:scene.id},stage:'hint',role:'clue',knowledgeEffects:[gain.id,effect.id]});p.entities.push(scene,last,entry,end,edge,evidence,q,money,f,gain,effect,disclosure);expect(validateProject(p).ok).toBe(true);return{p,q,money,entry,scene,last,disclosure};
}
async function saveRecord(p:any,record:any,checkpointId:string,snapshotId:string) {
 const saved=structuredClone(p),trace=createEntity(p.projectId,'trace','Saved trace',record.trace),checkpoint={...createEntity(p.projectId,'checkpoint','Start',record.checkpoint),id:checkpointId};saved.snapshots.push({id:snapshotId,content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:new Date().toISOString(),versionLabel:'Pinned record'});saved.entities.push(checkpoint,trace);saved.revision='1';expect(validateProject(saved).ok).toBe(true);return{saved,trace,checkpoint};
}
it('IC14a a supplied starting tick executes the same valid opening exception as shared presentation',async()=>{
 const {p,q,money,entry}=fixture(),direct=presentContent(p,initializeRuntimeState(p),{nodeId:entry.id,worldTick:'5'});expect(direct.ok).toBe(true);const trial=await startTrialVerified(p,{entryId:entry.id,worldTick:'5'},{});expect(trial.status).toBe('ready');if(direct.ok)expect(trial.state).toEqual(direct.state);expect(trial.state.variableValues[q.id]).toEqual({type:'integer',value:3});expect(trial.state.variableValues[money.id]).toEqual({type:'integer',value:12});
});
for(const [tick,status] of [[undefined,'unknown'],['10','error'],['-1','error']] as const)it(`IC14b absent/expired/outside tick ${tick} refuses the whole opening effect group`,async()=>{
 const {p,q,money,disclosure}=fixture(),before=structuredClone(p),trial=await startTrialVerified(p,{worldTick:tick},{});expect(trial.status).toBe(status);expect(trial.state.variableValues[q.id]).toEqual({type:'integer',value:0});expect(trial.state.variableValues[money.id]).toEqual({type:'integer',value:10});expect(trial.state.seenIds).not.toContain(disclosure.id);expect(p).toEqual(before);
});
it('IC14c flow opening tick survives complete-file restore and independent clone without repeating opening effects',async()=>{
 const {p,q,money}=fixture(),begun=await startTrialVerified(p,{worldTick:'5'},{}),trial=stepTrial(p,begun,{worldTick:'5'});expect(trial.status).toBe('terminal');const checkpointId=newId(),snapshotId=newId(),record=pinTrialRecord(trial,{checkpointId,snapshotId}),{saved,trace}=await saveRecord(p,record,checkpointId,snapshotId);expect(trace.data.initialWorldTick).toBe('5');const restored=(await inspectScenario(await exportScenario(saved),{worker:false})).project,replay=await replaySavedTraceVerified(restored,trace.id,{});expect(replay.status).toBe('terminal');expect(replay.initialWorldTick).toBe('5');expect(replay.state.variableValues[q.id]).toEqual({type:'integer',value:3});expect(replay.state.variableValues[money.id]).toEqual({type:'integer',value:12});
 const cloned=await cloneProject(restored),clonedReplay=await replaySavedTraceVerified(cloned.project,cloned.idMap[trace.id],{});expect(clonedReplay.status).toBe('terminal');expect(clonedReplay.initialWorldTick).toBe('5');expect(clonedReplay.state.variableValues[cloned.idMap[money.id]]).toEqual({type:'integer',value:12});expect(cloned.project.mainStart).toBe(p.mainStart);expect(restored.mainStart).toBe(p.mainStart);
});
it('IC14d chapter opening uses and replays the same captured tick after a complete-file restore',async()=>{
 const {p,q,money,scene,last}=fixture();let trial=await startChapterReading(p,{sceneIds:[scene.id,last.id],worldTick:'5'});trial=presentNextChapterScene(p,trial);expect(trial.status).toBe('ready');expect(trial.state.variableValues[q.id]).toEqual({type:'integer',value:3});trial=presentNextChapterScene(p,trial);expect(trial.status).toBe('terminal');const checkpointId=newId(),snapshotId=newId(),record=pinChapterReadingRecord(trial,{checkpointId,snapshotId}),{saved,trace,checkpoint}=await saveRecord(p,record,checkpointId,snapshotId);expect(trace.data.initialWorldTick).toBe('5');const restored=(await inspectScenario(await exportScenario(saved),{worker:false})).project,replay=await replayChapterReading(restored,restored.entities.find(e=>e.id===trace.id)!.data as any,restored.entities.find(e=>e.id===checkpoint.id)!.data as any,{});expect(replay.status).toBe('terminal');expect(replay.worldTick).toBe('5');expect(replay.state.variableValues[money.id]).toEqual({type:'integer',value:12});
});
it('IC14e a noninteger starting tick fails safely before any opening effect',async()=>{
 const {p,q,money}=fixture(),before=structuredClone(p),trial=await startTrialVerified(p,{worldTick:'2.5'},{});expect(trial.status).toBe('error');expect(trial.state.variableValues[q.id]).toEqual({type:'integer',value:0});expect(trial.state.variableValues[money.id]).toEqual({type:'integer',value:10});expect(p).toEqual(before);
});
