import { expect, it } from 'vitest';
import { createProject, createEntity, validateProject } from '../src/domain/model';
import { initializeRuntimeState } from '../src/domain/conditions';
import { createWorldSnapshot, previewWorldVersion } from '../src/domain/world';
import { presentContent } from '../src/domain/presentation';
it('IC13 a quest transition table from a verified fixed world rejects a forbidden disclosure effect group',async()=>{
 let world=createProject('Fixed quest world');const q=createEntity(world.projectId,'variable','Quest value',{key:'quest_state',valueType:'integer',initial:{type:'integer',value:0},allowed:{min:0,max:3}}),quest=createEntity(world.projectId,'quest','Shared quest',{stateVariableId:q.id,transitionRules:[{from:{type:'integer',value:0},to:{type:'integer',value:1}}]});world.entities.push(q,quest);world=await createWorldSnapshot(world,'Pinned quest');const snapshot=world.snapshots[0],registry={[snapshot.id]:snapshot.content};
 let p=(await previewWorldVersion(createProject('Work'),world,snapshot.id,[q.id,quest.id])).candidate;const scene=createEntity(p.projectId,'scene','Scene'),node=createEntity(p.projectId,'flow_node','Entry',{nodeType:'entry',sceneId:scene.id}),shadow=createEntity(p.projectId,'foreshadow','Shadow',{resolutionPolicy:'this_work'}),money=createEntity(p.projectId,'variable','Money',{key:'money',valueType:'integer',initial:{type:'integer',value:10},allowed:{min:0,max:20}}),gain=createEntity(p.projectId,'effect','Gain',{operation:'add',targetId:money.id,value:{type:'integer',value:2}}),forbidden=createEntity(p.projectId,'effect','Forbidden',{operation:'set',targetId:q.id,value:{type:'integer',value:3}}),disclosure=createEntity(p.projectId,'disclosure','Disclosure',{foreshadowId:shadow.id,anchor:{entityId:scene.id},role:'clue',stage:'hint',knowledgeEffects:[gain.id,forbidden.id]});p.entities.push(scene,node,shadow,money,gain,forbidden,disclosure);
 expect(validateProject(p,{worldSnapshots:registry}).ok).toBe(true);const state=initializeRuntimeState(p,p.projectId,snapshot.content.entities),before=structuredClone(state),result=presentContent(p,state,{sceneId:scene.id,referenceEntities:snapshot.content.entities});expect(result.ok).toBe(false);expect(state).toEqual(before);
});
