import { describe, expect, it } from 'vitest';
import { createProject, createEntity, emptyValidity, newId, validateProject } from '../src/domain/model';
import { initializeRuntimeState, applyEffectsAtomic } from '../src/domain/conditions';
import { startTrialVerified } from '../src/domain/runtimeVerified';
import { startTrial, stepTrial, restartTrial } from '../src/domain/runtime';
import { createWorldSnapshot, previewWorldVersion, worldStateCandidates, createWorldAssessment } from '../src/domain/world';
import { buildRelationGraph } from '../src/domain/relationGraph';
import { presentContent } from '../src/domain/presentation';
import type { Entity, ProjectData } from '../src/domain/types';
function add<K extends Entity['kind']>(p: ProjectData, kind: K, name: string, data: Partial<Entity<K>['data']> = {}): Entity<K> { const e = createEntity(p.projectId, kind, name, data) as Entity<K>; p.entities.push(e); return e; }
function fixture() { const p=createProject('Independent review'); const s1=add(p,'scene','first'),s2=add(p,'scene','last'); const a=add(p,'flow_node','entry',{nodeType:'entry',sceneId:s1.id,executionPolicy:'first_match'}), b=add(p,'flow_node','terminal',{nodeType:'terminal',sceneId:s2.id,terminalReason:'end'}); add(p,'flow_edge','advance',{fromId:a.id,toId:b.id,edgeType:'automatic',priority:0});return {p,s1,s2,a,b}; }
describe('Independent audit: expected original contracts',()=>{
 it('IR01 rejected state definitions do not initialize effective trial values',()=>{const {p}=fixture();const v=add(p,'variable','discarded state',{key:'discarded',valueType:'boolean',initial:{type:'boolean',value:true},allowed:{values:[false,true]}});v.status='rejected';expect(validateProject(p).ok).toBe(true);expect(initializeRuntimeState(p).variableValues[v.id]).toBeUndefined();});
 it('IR02 unresolved presentation outside the current chapter cannot block arrival',()=>{const {p,s1}=fixture();const c=add(p,'chapter','current',{sceneIds:[s1.id]}),other=add(p,'chapter','other');s1.data.chapterId=c.id;const f=add(p,'foreshadow','other clue',{resolutionPolicy:'this_work'});add(p,'disclosure','unresolved outside scope',{foreshadowId:f.id,anchor:{entityId:s1.id,positionStatus:'unresolved',positionReason:'awaiting relink'},role:'clue',stage:'hint',targetScope:{projectId:p.projectId,chapterId:other.id}});expect(validateProject(p).ok).toBe(true);expect(presentContent(p,initializeRuntimeState(p),{sceneId:s1.id}).ok).toBe(true);});
 it('RV01 scene_end resets, back/replay obligation remains separate',()=>{ const {p,a}=fixture();const v=add(p,'variable','scene value',{key:'scene_value',scope:'scene',valueType:'integer',initial:{type:'integer',value:0},allowed:{min:0,max:10},resetRules:[{on:'scene_end',value:{type:'integer',value:0}}]});expect(validateProject(p).ok).toBe(true);const state=initializeRuntimeState(p);state.variableValues[v.id]={type:'integer',value:5};const next=stepTrial(p,startTrial(p,{entryId:a.id,state}));expect(next.status).toBe('terminal');expect(next.state.variableValues[v.id]).toEqual({type:'integer',value:0});});
 it('RV01 explicit new_loop supersedes carryover',()=>{const {p}=fixture();const v=add(p,'variable','carried value',{key:'carried',scope:'across_runs',valueType:'integer',initial:{type:'integer',value:0},allowed:{min:0,max:10},resetRules:[{on:'new_loop',value:{type:'integer',value:2}}]});const trial=startTrial(p);trial.state.variableValues[v.id]={type:'integer',value:7};expect(restartTrial(p,trial,'next_run').state.variableValues[v.id]).toEqual({type:'integer',value:2});});
 it('RV02 free reason cannot authorize forbidden transition or accompanying money',()=>{const {p}=fixture();const v=add(p,'variable','quest',{key:'quest',valueType:'integer',initial:{type:'integer',value:0},allowed:{min:0,max:3},transitionRules:[{from:{type:'integer',value:0},to:{type:'integer',value:1}}]});const money=add(p,'variable','money',{key:'money',valueType:'integer',initial:{type:'integer',value:10},allowed:{min:0,max:100}});const good=add(p,'effect','money update',{operation:'add',targetId:money.id,value:{type:'integer',value:5}});const bad=add(p,'effect','forbidden',{operation:'set',targetId:v.id,value:{type:'integer',value:3},reason:'ordinary note'});const state=initializeRuntimeState(p);const result=applyEffectsAtomic(state,[good,bad],{state,variables:[v,money],entities:p.entities});expect(result.ok).toBe(false);expect(result.state).toEqual(state);});
 it('RV03 rejected world assertions are excluded from effective candidates and index',()=>{const p=createProject();const person=add(p,'character','person'),place=add(p,'place','discarded place');const rejected=add(p,'assertion','rejected location',{subjectId:person.id,predicate:'location',value:place.id,truthKind:'author_truth',validity:emptyValidity(),sourceIds:[]});rejected.status='rejected';for(const result of [worldStateCandidates(p,person.id,'location',{at:'0'}),createWorldAssessment(p,{at:'0'}).stateCandidates(person.id,'location')]){expect(result.definite).toEqual([]);expect(result.status).not.toBe('known');}});
 it('RV03 rejected trust is not an active effective relationship',()=>{const p=createProject();const a=add(p,'character','A'),b=add(p,'character','B');const id=newId();p.relations.push({id,projectId:p.projectId,revision:'0',fromId:a.id,toId:b.id,relationType:'trust',direction:'forward',validity:emptyValidity(),evidenceIds:[],status:'rejected',visibility:'private'});const graph=buildRelationGraph(p,{at:'0'});expect(graph.lines.some(line=>line.id===id&&line.assessment.value==='true')).toBe(false);});
 it('RV04 trial resolves adopted variable from the pinned registry',async()=>{let world=createProject('world');const v=add(world,'variable','world flag',{key:'world_flag',valueType:'boolean',initial:{type:'boolean',value:true},allowed:{values:[false,true]}});world=await createWorldSnapshot(world,'pinned');const {p,a}=fixture();const work=(await previewWorldVersion(p,world,world.snapshots[0].id,[v.id])).candidate;(work.entities.find(e=>e.id===a.id) as Entity<'flow_node'>).data.gate={op:'compare',variableId:v.id,comparator:'eq',value:{type:'boolean',value:true}};const worldSnapshots={[world.snapshots[0].id]:world.snapshots[0].content};expect(validateProject(work,{worldSnapshots}).ok).toBe(true);const trial=await startTrialVerified(work,{},worldSnapshots);expect(trial.status).toBe('ready');expect(trial.state.variableValues[v.id]).toEqual({type:'boolean',value:true});});
 it('RV10 another chapter disclosure is ignored consistently without effects',()=>{const {p,s1,a}=fixture();const c=add(p,'chapter','current',{sceneIds:[s1.id]}),other=add(p,'chapter','other');s1.data.chapterId=c.id;const v=add(p,'variable','disclosed',{key:'disclosed',valueType:'boolean',initial:{type:'boolean',value:false},allowed:{values:[false,true]}});const f=add(p,'foreshadow','other clue',{resolutionPolicy:'this_work'});const e=add(p,'effect','mark disclosure',{operation:'set',targetId:v.id,value:{type:'boolean',value:true}});add(p,'disclosure','other scope',{foreshadowId:f.id,anchor:{entityId:s1.id},role:'clue',stage:'hint',knowledgeEffects:[e.id],targetScope:{projectId:p.projectId,chapterId:other.id}});expect(validateProject(p).ok).toBe(true);const chapter=presentContent(p,initializeRuntimeState(p),{nodeId:a.id,sceneId:s1.id});expect(chapter.ok).toBe(true);expect(startTrial(p).state.variableValues[v.id]).toEqual({type:'boolean',value:false});});
});
