import { expect, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { createProject, createEntity, newId, validateProject } from '../src/domain/model';
import { startTrial, stepTrial, pinTrialRecord } from '../src/domain/runtime';
import { sha256, jsonBytes } from '../src/storage/json';
import { exportScenario } from '../src/storage/archive';
import { startChapterReading, presentNextChapterScene, pinChapterReadingRecord } from '../src/domain/presentation';
it('generates a valid successful baseline branch trace with no lifecycle declarations',async()=>{
 const p=createProject('Historical successful trace'),s1=createEntity(p.projectId,'scene','first'),s2=createEntity(p.projectId,'scene','last'),a=createEntity(p.projectId,'flow_node','entry',{nodeType:'entry',sceneId:s1.id,executionPolicy:'first_match'}),b=createEntity(p.projectId,'flow_node','terminal',{nodeType:'terminal',sceneId:s2.id,terminalReason:'end'}),e=createEntity(p.projectId,'flow_edge','next',{fromId:a.id,toId:b.id,edgeType:'automatic',priority:0}),v=createEntity(p.projectId,'variable','value',{key:'value',valueType:'integer',initial:{type:'integer',value:5},allowed:{min:0,max:10}});p.entities.push(s1,s2,a,b,e,v);
 const chapterProject=structuredClone(p);let chapter=await startChapterReading(chapterProject,{sceneIds:[s1.id,s2.id]});chapter=presentNextChapterScene(chapterProject,chapter);chapter=presentNextChapterScene(chapterProject,chapter);expect(chapter.status).toBe('terminal');const chapterCheckpointId=newId(),chapterSnapshotId=newId(),chapterRecord=pinChapterReadingRecord(chapter,{checkpointId:chapterCheckpointId,snapshotId:chapterSnapshotId});chapterProject.snapshots.push({id:chapterSnapshotId,content:chapterRecord.content,contentHash:await sha256(jsonBytes(chapterRecord.content)),createdAt:new Date().toISOString(),versionLabel:'Historical chapter fixture'});const chapterCheckpoint={...createEntity(p.projectId,'checkpoint','start',chapterRecord.checkpoint),id:chapterCheckpointId},chapterTrace=createEntity(p.projectId,'trace','chapters',chapterRecord.trace);chapterProject.entities.push(chapterCheckpoint,chapterTrace);chapterProject.revision='1';expect(validateProject(chapterProject).ok).toBe(true);writeFileSync('/tmp/shinariokanri-historical-chapter-trace-3099c9d.json',JSON.stringify({project:chapterProject,traceId:chapterTrace.id,checkpointId:chapterCheckpointId},null,2)+'\n');writeFileSync('/tmp/shinariokanri-historical-chapter-trace-3099c9d.scenario',await exportScenario(chapterProject));
 const trial=stepTrial(p,startTrial(p));expect(trial.status).toBe('terminal');const checkpointId=newId(),snapshotId=newId(),record=pinTrialRecord(trial,{checkpointId,snapshotId});p.snapshots.push({id:snapshotId,content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:new Date().toISOString(),versionLabel:'Historical fixture'});const checkpoint={...createEntity(p.projectId,'checkpoint','start',record.checkpoint),id:checkpointId},trace=createEntity(p.projectId,'trace','saved',record.trace);p.entities.push(checkpoint,trace);p.revision='1';expect(validateProject(p).ok).toBe(true);
 writeFileSync('/tmp/shinariokanri-historical-trace-3099c9d.json',JSON.stringify({project:p,traceId:trace.id},null,2)+'\n');writeFileSync('/tmp/shinariokanri-historical-trace-3099c9d.scenario',await exportScenario(p));
});
