import Dexie,{type Table} from 'dexie';
import {assertDocumentTarget,assertOperation,clone,createSyncOperation,sameValue,valueHash,SyncProtocolError,type SyncDocument,type SyncOperation,type SyncAck,type SyncConflict} from './protocol';
import {assertAck} from './validation';
import {threeWayMerge,type ConflictResolution} from './merge';
import {acknowledgeNativeDocuments,resolveCurrentNativeConflict,sameDocumentContent} from './nativeBridge';
export interface EditorImage {projectId:string;serverRevision:string;documents:SyncDocument[];contentHash:string}
export interface EditorWork {projectId:string;revision:number;base:EditorImage;documents:SyncDocument[];prepared?:{operation:SyncOperation;documents:SyncDocument[]};conflict?:SyncAck;postConflicts?:SyncConflict[];acks:SyncAck[];retained:SyncDocument[][];recovered?:EditorWork[]}
class EditorDatabase extends Dexie {works!:Table<EditorWork,string>;constructor(account:string){super(`scenario-editor-account-${encodeURIComponent(account)}`);this.version(1).stores({works:'projectId'});}}
/** A limited editor cache never contains a project header, author history, private fields or world registry. */
export class ScopedEditorStore {
 private db:EditorDatabase;
 constructor(readonly accountId:string){if(!accountId||accountId==='guest')throw new SyncProtocolError('AUTH_REQUIRED');this.db=new EditorDatabase(accountId);}
 async get(id:string){return clone(await this.db.works.get(id));}
 async list(){return clone(await this.db.works.toArray());}
 private async commit(before:EditorWork|undefined,next:EditorWork,ack?:SyncAck){const captured={...clone(next),base:clone(next.base),documents:clone(next.documents),...(next.prepared?{prepared:{operation:clone(next.prepared.operation),documents:clone(next.prepared.documents)}}:{})};await this.db.transaction('rw',this.db.works,async()=>{const current=await this.db.works.get(next.projectId);if(ack){const already=current?.acks.find(a=>a.operationId===ack.operationId);if(already){if(!sameValue(already,ack))throw new SyncProtocolError('OPERATION_REUSED');return;}}if(current?.revision!==before?.revision)throw new SyncProtocolError('REVISION_CHANGED');await this.db.works.put(captured);});}
 async receive(input:EditorImage){const image=clone(input),scope={accountId:this.accountId,projectId:image.projectId};if(!/^(0|[1-9]\d*)$/.test(image.serverRevision)||image.documents.length>100000||await valueHash(image.documents)!==image.contentHash)throw new SyncProtocolError('PROTOCOL_INVALID');const seen=new Set<string>();for(const d of image.documents){assertDocumentTarget(d,scope,d.id);if(seen.has(d.id)||d.fields.kind==='project'||d.fields.visibility!=='team')throw new SyncProtocolError('PROTOCOL_INVALID');seen.add(d.id);}const before=await this.get(image.projectId);if(before?.prepared||before?.conflict)throw new SyncProtocolError('REVISION_CHANGED');
  const old=new Map(before?.base.documents.map(d=>[d.id,d])),local=new Map(before?.documents.map(d=>[d.id,d])),documents=image.documents.map(remote=>{const edited=local.get(remote.id),base=old.get(remote.id);if(!edited||!base)return remote;const filter=(d:SyncDocument)=>({...d,fields:Object.fromEntries(Object.entries(d.fields).filter(([key])=>Object.hasOwn(remote.fields,key)))}),merged=threeWayMerge(filter(base),filter(edited),remote);if(merged.status==='conflict')throw new SyncProtocolError('REVISION_CHANGED');return merged.document;});const removed=before?.documents.filter(d=>!seen.has(d.id)||Object.keys(d.fields).some(k=>!Object.hasOwn(image.documents.find(r=>r.id===d.id)!.fields,k)))??[];
  await this.commit(before,{projectId:image.projectId,revision:(before?.revision??0)+1,base:image,documents,acks:before?.acks??[],retained:[...(before?.retained??[]),...(removed.length?[removed]:[])],recovered:before?.recovered??[]});}
 async saveField(projectId:string,id:string,field:string,value:unknown){const captured=clone(value),before=await this.get(projectId);if(!before)throw new SyncProtocolError('BASE_UNAVAILABLE');const next=clone(before),doc=next.documents.find(d=>d.id===id);if(!doc||!Object.hasOwn(doc.fields,field)||['kind','visibility','createdAt'].includes(field))throw new SyncProtocolError('FORBIDDEN');doc.fields[field]=captured as SyncDocument['fields'][string];assertDocumentTarget(doc,{accountId:this.accountId,projectId},doc.id);next.revision++;await this.commit(before,next);}
 async prepare(projectId:string){const before=await this.get(projectId);if(!before)throw new SyncProtocolError('BASE_UNAVAILABLE');if(before.conflict)throw new SyncProtocolError('REVISION_CHANGED');if(before.prepared)return before.prepared.operation;const old=new Map(before.base.documents.map(d=>[d.id,d])),targets=before.documents.filter(d=>!sameDocumentContent(old.get(d.id),d)).map(d=>({base:old.get(d.id)??null,local:d}));if(!targets.length)return null;const operation=await createSyncOperation({scope:{accountId:this.accountId,projectId},baseRevision:before.base.serverRevision,operationId:crypto.randomUUID(),targets,reason:'許可された項目の編集'});await this.commit(before,{...before,revision:before.revision+1,prepared:{operation,documents:clone(before.documents)}});return operation;}
 async acknowledge(input:SyncAck){const ack=clone(input),before=await this.get(ack.scope.projectId);if(!before||ack.scope.accountId!==this.accountId)throw new SyncProtocolError('FORBIDDEN');const prior=before.acks.find(a=>a.operationId===ack.operationId);if(prior){if(!sameValue(prior,ack))throw new SyncProtocolError('OPERATION_REUSED');return;}if(!before.prepared||!ack.confirmedDocuments)throw new SyncProtocolError('BASE_UNAVAILABLE');await assertAck(before.prepared.operation,ack);const next=clone(before);next.revision++;if(ack.status==='conflict'){next.conflict=ack;}else{const saved={operationId:ack.operationId,projectId:ack.scope.projectId,operation:before.prepared.operation,localRevision:String(before.revision),localDocuments:before.prepared.documents,outboxIds:[],createdAt:new Date().toISOString()},combined=acknowledgeNativeDocuments(saved,before.base,ack,before.documents);next.documents=combined.documents;next.base={projectId:ack.scope.projectId,serverRevision:ack.serverRevision,documents:ack.confirmedDocuments,contentHash:await valueHash(ack.confirmedDocuments)};if(combined.conflicts.length){next.conflict=ack;next.postConflicts=combined.conflicts;}else{delete next.prepared;delete next.conflict;delete next.postConflicts;}}next.acks.push(ack);await this.commit(before,next,ack);}
 async resolve(projectId:string,choices:Record<string,ConflictResolution>,expectedRevision:number){const picked=clone(choices),before=await this.get(projectId);if(!before?.prepared||!before.conflict||before.revision!==expectedRevision||!before.conflict.confirmedDocuments)throw new SyncProtocolError('REVISION_CHANGED');const remote=before.conflict.confirmedDocuments,saved={operationId:before.prepared.operation.operationId,projectId,prepared:{operationId:before.prepared.operation.operationId,projectId,operation:before.prepared.operation,localRevision:String(before.revision),localDocuments:before.prepared.documents,outboxIds:[],createdAt:new Date().toISOString()},ack:before.conflict,conflicts:before.postConflicts??before.conflict.conflicts,createdAt:new Date().toISOString()},targets=resolveCurrentNativeConflict(saved,picked,remote,before.documents);const operation=await createSyncOperation({scope:{accountId:this.accountId,projectId},baseRevision:before.conflict.serverRevision,operationId:crypto.randomUUID(),resolvesOperationId:before.prepared.operation.operationId,targets,reason:'共通元と二案を確認した限定編集の解決'});const docs=remote.map(d=>targets.find(t=>t.local.id===d.id)?.local??d);await this.commit(before,{...before,revision:before.revision+1,base:{projectId,serverRevision:before.conflict.serverRevision,documents:remote,contentHash:await valueHash(remote)},documents:docs,prepared:{operation,documents:docs},conflict:undefined,postConflicts:undefined});}
 async retainRecovery(input:EditorWork){const captured=clone(input),scope={accountId:this.accountId,projectId:captured.projectId};if(!captured.base||!Array.isArray(captured.documents)||!Array.isArray(captured.base.documents)||!Array.isArray(captured.acks)||!Array.isArray(captured.retained)||captured.documents.length>100000)throw new SyncProtocolError('PROTOCOL_INVALID');for(const image of [captured.base.documents,captured.documents,...captured.retained,captured.prepared?.documents??[]])for(const doc of image){assertDocumentTarget(doc,scope,doc.id);if(doc.fields.kind==='project'||doc.fields.visibility!=='team')throw new SyncProtocolError('FORBIDDEN');}if(captured.prepared){await assertOperation(captured.prepared.operation);if(!sameValue(scope,captured.prepared.operation.scope))throw new SyncProtocolError('FORBIDDEN');}const before=await this.get(captured.projectId),next=before??{projectId:captured.projectId,revision:0,base:{projectId:captured.projectId,serverRevision:'0',documents:[],contentHash:await valueHash([])},documents:[],acks:[],retained:[]};await this.commit(before,{...next,revision:next.revision+1,recovered:[...(next.recovered??[]),captured]});}
 async previewRecovery(projectId:string,index:number){const before=await this.get(projectId),saved=before?.recovered?.[index];if(!before||!saved||!before.base.documents.length||before.prepared||before.conflict)throw new SyncProtocolError('BASE_UNAVAILABLE');const source=new Map(saved.documents.map(d=>[d.id,d])),documents=before.documents.map(doc=>{const old=source.get(doc.id);if(!old)return doc;const next=clone(doc);for(const key of Object.keys(doc.fields))if(!['kind','visibility','createdAt'].includes(key)&&Object.hasOwn(old.fields,key))next.fields[key]=clone(old.fields[key]);return next;});const plan={projectId,index,revision:before.revision,baseHash:before.base.contentHash,documents};return {...plan,confirmationHash:await valueHash(plan)};}
 async adoptRecovery(input:Awaited<ReturnType<ScopedEditorStore['previewRecovery']>>){const plan=clone(input),{confirmationHash,...payload}=plan;if(await valueHash(payload)!==confirmationHash)throw new SyncProtocolError('PROTOCOL_INVALID');const before=await this.get(plan.projectId);if(!before||before.revision!==plan.revision||before.base.contentHash!==plan.baseHash)throw new SyncProtocolError('REVISION_CHANGED');const current=await this.previewRecovery(plan.projectId,plan.index);if(current.confirmationHash!==plan.confirmationHash)throw new SyncProtocolError('REVISION_CHANGED');await this.commit(before,{...before,revision:before.revision+1,documents:plan.documents});}
 close(){this.db.close();}
 async delete(){this.db.close();await this.db.delete();}
}
