import {assertOperation,clone,SyncProtocolError,type SyncAck,type SyncOperation,type SyncSession,type SyncTransport} from './protocol';
import {assertAck} from './validation';

export interface DedicatedSyncConfig {url:string;publishableKey:string;allowLocalHTTP?:boolean}
export interface AuthenticatedSession extends SyncSession {accessToken:string|null;expiresAt:number|null}
const error=(code:'AUTH_REQUIRED'|'FORBIDDEN'|'TRANSPORT_UNAVAILABLE'|'PROTOCOL_INVALID'|'REVISION_CHANGED')=>new SyncProtocolError(code);
export function validateDedicatedSyncConfig(input:DedicatedSyncConfig):DedicatedSyncConfig{
 const config=clone(input),url=new URL(config.url);if(url.username||url.password||url.search||url.hash||url.pathname!=='/'||!(url.protocol==='https:'||config.allowLocalHTTP&&url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))throw error('PROTOCOL_INVALID');
 if(typeof config.publishableKey!=='string'||config.publishableKey.length<16||config.publishableKey.length>4096||config.publishableKey.startsWith('sb_secret_'))throw error('PROTOCOL_INVALID');
 if(!config.publishableKey.startsWith('sb_publishable_')){try{const claim=JSON.parse(atob(config.publishableKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(claim.role!=='anon')throw Error();}catch{throw error('PROTOCOL_INVALID');}}
 return {...config,url:url.origin};
}
/** Tokens and passwords are held only in memory. No client may receive a service-role key. */
export class DedicatedSupabaseClient implements SyncTransport{
 readonly config:DedicatedSyncConfig;private session:AuthenticatedSession={accountId:null,authenticated:false,generation:crypto.randomUUID(),accessToken:null,expiresAt:null};
 private expirationTimer:ReturnType<typeof setTimeout>|undefined;private listeners=new Set<()=>void>();private fetcher:typeof fetch;
 constructor(config:DedicatedSyncConfig,fetcher:typeof fetch=(input,init)=>globalThis.fetch(input,init)){this.config=validateDedicatedSyncConfig(config);this.fetcher=fetcher;}
 getSession=():AuthenticatedSession=>{const value=clone(this.session);if(value.expiresAt!==null&&Date.now()>=value.expiresAt)value.authenticated=false;return value;};
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn);};
 private update(value:AuthenticatedSession){this.session=clone(value);clearTimeout(this.expirationTimer);if(value.expiresAt!==null){const generation=value.generation;this.expirationTimer=setTimeout(()=>{if(this.session.generation===generation)this.expire();},Math.max(0,value.expiresAt-Date.now()));}this.listeners.forEach(fn=>fn());}
 private current(expected?:SyncSession){const value=this.getSession();if(!value.authenticated||!value.accessToken)throw error('AUTH_REQUIRED');if(expected&&(expected.generation!==value.generation||expected.accountId!==value.accountId))throw new SyncProtocolError('ACCOUNT_CHANGED');return value;}
 async signIn(email:string,password:string,signal?:AbortSignal){const generation=this.session.generation,captured={email,password};const response=await this.fetcher(`${this.config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:this.config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(captured),signal});if(!response.ok)throw error(response.status===401||response.status===400?'AUTH_REQUIRED':'TRANSPORT_UNAVAILABLE');const raw=await response.json();if(this.session.generation!==generation)throw new SyncProtocolError('ACCOUNT_CHANGED');if(typeof raw.access_token!=='string'||typeof raw.user?.id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(raw.user.id)||!Number.isSafeInteger(raw.expires_in)||raw.expires_in<=0)throw error('PROTOCOL_INVALID');this.update({accountId:raw.user.id,authenticated:true,generation:crypto.randomUUID(),accessToken:raw.access_token,expiresAt:Date.now()+raw.expires_in*1000});return this.getSession();}
 async signOut(signal?:AbortSignal){const session=this.current();const response=await this.fetcher(`${this.config.url}/auth/v1/logout`,{method:'POST',headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`},signal});if(!response.ok&&response.status!==401)throw error('TRANSPORT_UNAVAILABLE');this.current(session);this.update({accountId:null,authenticated:false,generation:crypto.randomUUID(),accessToken:null,expiresAt:null});}
 /** Expiry/revocation is distinct from completed logout: local pending data remains available for reauthentication. */
 expire(){this.update({...this.session,authenticated:false,generation:crypto.randomUUID(),accessToken:null,expiresAt:null});}
 async request<T>(action:string,input:unknown,expected:SyncSession=this.getSession(),signal?:AbortSignal):Promise<T>{const captured=clone(input),session=this.current(expected),timeout=AbortSignal.timeout(30000),combined=signal?AbortSignal.any([signal,timeout]):timeout;
  const response=await this.fetcher(`${this.config.url}/functions/v1/scenario-sync`,{method:'POST',headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({specification:'scenario-sync-native/1.0.0',action,input:captured}),signal:combined});this.current(session);
  if(!response.ok){if(response.status===401){this.expire();throw error('AUTH_REQUIRED');}throw error(response.status===403?'FORBIDDEN':response.status===409?'REVISION_CHANGED':'TRANSPORT_UNAVAILABLE');}
  const length=Number(response.headers.get('Content-Length'));if(length>128*1024*1024)throw error('PROTOCOL_INVALID');const text=await response.text();this.current(session);if(new TextEncoder().encode(text).byteLength>128*1024*1024)throw error('PROTOCOL_INVALID');try{return JSON.parse(text) as T;}catch{throw error('PROTOCOL_INVALID');}
 }
 async send(input:SyncOperation,expected:SyncSession,signal?:AbortSignal):Promise<SyncAck>{const operation=clone(input);this.current(expected);await assertOperation(operation);this.current(expected);if(operation.scope.accountId!==expected.accountId)throw error('FORBIDDEN');const ack=await this.request<SyncAck>('apply',operation,expected,signal);await assertAck(operation,ack);if(!ack.confirmedDocuments)throw error('PROTOCOL_INVALID');this.current(expected);return clone(ack);}
 async downloadAsset(input:{projectId?:string;contentHash?:string;snapshotId?:string;publicAssetId?:string},expected:SyncSession=this.getSession(),signal?:AbortSignal):Promise<Uint8Array<ArrayBuffer>>{
  return this.download('download_asset',input,32*1024*1024,expected,signal);
 }
 async downloadArchive(input:{projectId:string;serverRevision?:string},expected:SyncSession=this.getSession(),signal?:AbortSignal){return this.download('download_archive',input,64*1024*1024,expected,signal);}
 private async download(action:string,input:unknown,limit:number,expected:SyncSession,signal?:AbortSignal):Promise<Uint8Array<ArrayBuffer>>{
  const captured=clone(input),session=this.current(expected),response=await this.fetcher(`${this.config.url}/functions/v1/scenario-sync`,{method:'POST',headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({specification:'scenario-sync-native/1.0.0',action,input:captured}),signal});this.current(session);if(!response.ok)throw error(response.status===401?'AUTH_REQUIRED':response.status===403?'FORBIDDEN':'TRANSPORT_UNAVAILABLE');if(Number(response.headers.get('Content-Length'))>limit)throw error('PROTOCOL_INVALID');const bytes=new Uint8Array(await response.arrayBuffer());this.current(session);if(bytes.byteLength>limit)throw error('PROTOCOL_INVALID');return bytes;
 }
 async publicSnapshots(signal?:AbortSignal,offset=0){if(!Number.isSafeInteger(offset)||offset<0||offset>100000)throw error('PROTOCOL_INVALID');const session=this.current(),response=await this.fetcher(`${this.config.url}/rest/v1/scenario_snapshots?select=id,public_project_id,content_hash,created_at,expires_at&order=created_at.desc&limit=30&offset=${offset}`,{headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`},signal});this.current(session);if(!response.ok)throw error(response.status===401?'AUTH_REQUIRED':response.status===403?'FORBIDDEN':'TRANSPORT_UNAVAILABLE');const data=await response.json() as {id:string;projection:unknown;content_hash:string;expires_at:string|null}[];this.current(session);return data;}
 async publicComments(snapshotId:string,signal?:AbortSignal,offset=0){if(!Number.isSafeInteger(offset)||offset<0||offset>100000)throw error('PROTOCOL_INVALID');if(!/^[a-f0-9-]{36}$/.test(snapshotId))throw error('PROTOCOL_INVALID');const session=this.current(),response=await this.fetcher(`${this.config.url}/rest/v1/scenario_comments?snapshot_id=eq.${snapshotId}&select=id,snapshot_id,public_entity_id,public_block_id,start_cp,end_cp,public_relation_id,public_version_id,body,created_at,resolved,review_stage&order=created_at,id&limit=60&offset=${offset}`,{headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`},signal});this.current(session);if(!response.ok)throw error('FORBIDDEN');const data=await response.json() as unknown[];this.current(session);return data;}
 async comment(input:{snapshot_id:string;public_entity_id?:string;public_block_id?:string;start_cp?:number;end_cp?:number;public_relation_id?:string;public_version_id?:string;body:string},signal?:AbortSignal){const captured=clone(input),session=this.current();if(captured.body.length<1||Array.from(captured.body).length>2000)throw error('PROTOCOL_INVALID');const response=await this.fetcher(`${this.config.url}/rest/v1/scenario_comments`,{method:'POST',headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(captured),signal});this.current(session);if(!response.ok)throw error(response.status===401?'AUTH_REQUIRED':'FORBIDDEN');const data:unknown=await response.json();this.current(session);return data;}
 async updateComment(id:string,input:{body?:string;resolved?:boolean;review_stage?:'open'|'fixed'|'verified'},signal?:AbortSignal){if(input.body!==undefined&&(!input.body.trim()||Array.from(input.body).length>2000)||input.review_stage!==undefined&&!['open','fixed','verified'].includes(input.review_stage))throw error('PROTOCOL_INVALID');return this.changeComment('PATCH',id,input,signal);}
 async deleteComment(id:string,signal?:AbortSignal){return this.changeComment('DELETE',id,undefined,signal);}
 private async changeComment(method:string,id:string,input:unknown,signal?:AbortSignal){if(!/^[a-f0-9-]{36}$/.test(id))throw error('PROTOCOL_INVALID');const session=this.current(),captured=clone(input),response=await this.fetcher(`${this.config.url}/rest/v1/scenario_comments?id=eq.${id}`,{method,headers:{apikey:this.config.publishableKey,Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json',Prefer:'return=representation'},...(input!==undefined?{body:JSON.stringify(captured)}:{}),signal});this.current(session);if(!response.ok)throw error(response.status===401?'AUTH_REQUIRED':'FORBIDDEN');const data=await response.json();this.current(session);if(!Array.isArray(data)||data.length!==1)throw error('FORBIDDEN');return data;}

}
