import 'fake-indexeddb/auto';
import {it,expect} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {createEntity,newId} from '../src/domain/model';
import {createWorldSnapshot} from '../src/domain/world';
import {productionCheckView,checkProductionRules} from '../src/domain/productionChecks';
import {startTrialVerified} from '../src/domain/runtimeVerified';
import {stepTrial} from '../src/domain/runtime';
import {captureRuntimeContent} from '../src/domain/runtimeVersions';
import type {ProjectData,ProjectContent,RuntimeContext,Entity} from '../src/domain/types';
const root='/tmp/shinariokanri-independent-rb07-11cffa7/independent/fixtures',input=()=>JSON.parse(readFileSync(root+'/world-route-production.json','utf8'))as{project:ProjectData;world:ProjectData;ids:Record<string,string>;registry:Record<string,ProjectContent>};
function voice(view:Awaited<ReturnType<typeof productionCheckView>>,context:RuntimeContext,frame:string){return checkProductionRules(view.project,{...view,context}).filter(x=>x.lineId===frame&&x.kind==='voice');}
it('CTX-R1 same verified world route false is excluded from candidates after real declared effect, without stub',async()=>{
 const {project:p,world,ids,registry}=input(),effect=createEntity(p.projectId,'effect','声条件を更新',{operation:'set',targetId:ids.flag,value:{type:'boolean',value:false}});effect.status='confirmed';p.entities.push(effect);(p.entities.find(e=>e.id===ids.edge)as Entity<'flow_edge'>).data.effectIds=[effect.id];let session=await startTrialVerified(p,{entryId:ids.entry},registry);session=stepTrial(p,session,{edgeId:ids.edge});expect(session.status).toBe('terminal');expect(session.state.provenance).toBe('full_play');expect(session.state.variableValues[ids.flag]).toEqual({type:'boolean',value:false});const view=await productionCheckView(p,registry,world.snapshots),context:RuntimeContext={state:session.state,entities:view.project.entities},checks=voice(view,context,ids.frame);expect(checks).toEqual([]);writeFileSync(root+'/CTX-R1.json',JSON.stringify({knownFlag:session.state.variableValues[ids.flag],provenance:session.state.provenance,checks},null,2)+'\n');
});
it('CTX-R2 older caption belongs to an inactive world epoch and never borrows the newer world path',async()=>{
 const {project:p,ids,registry}=input();let world=input().world;(world.entities.find(e=>e.id===ids.flag)as Entity<'variable'>).data.initial={type:'boolean',value:false};world=await createWorldSnapshot(world,'条件falseの次世界');const latest=world.snapshots.at(-1)!;registry[latest.id]=latest.content;p.worldReferences=[{projectId:world.projectId,immutableSnapshotId:latest.id,contentHash:latest.contentHash}];(p.entities.find(e=>e.id===ids.entry)as Entity<'flow_node'>).data.gate={op:'constant',value:true};let session=await startTrialVerified(p,{entryId:ids.entry},registry);session=stepTrial(p,session,{edgeId:ids.edge});expect(session.status).toBe('terminal');const view=await productionCheckView(p,registry,world.snapshots),checks=voice(view,{state:session.state,entities:view.project.entities},ids.frame);expect(view.verifiedVersionIds.has(ids.pin)).toBe(true);expect(view.worldContext.versionIds.has(ids.pin)).toBe(false);expect(checks).toHaveLength(1);expect(checks[0].value).toBe('unknown');writeFileSync(root+'/CTX-R2.json',JSON.stringify({knownNewFlag:session.state.variableValues[ids.flag],oldPin:ids.pin,newPin:latest.id,checks},null,2)+'\n');
});
it('CTX-R3 unverified sources and wrong state edition remain unknown, missing/corrupt world refuses',async()=>{
 const {project:p,world,ids,registry}=input(),session=await startTrialVerified(p,{entryId:ids.entry},registry),view=await productionCheckView(p,registry,world.snapshots),context:RuntimeContext={state:session.state,entities:view.project.entities};const raw=checkProductionRules(view.project,{context}).filter(x=>x.lineId===ids.frame&&x.kind==='voice');expect(raw).toHaveLength(1);expect(raw[0].value).toBe('unknown');const badContext:RuntimeContext={...context,state:{...context.state,contentVersionId:newId()}};expect(voice(view,badContext,ids.frame)[0].value).toBe('unknown');await expect(productionCheckView(p,{},world.snapshots)).rejects.toThrow();const broken=structuredClone(registry);broken[ids.pin].name='改ざん';await expect(productionCheckView(p,broken,world.snapshots)).rejects.toThrow();writeFileSync(root+'/CTX-R3.json',JSON.stringify({unverified:raw,wrongState:voice(view,badContext,ids.frame),missingAndCorruptRefused:true},null,2)+'\n');
});
it('CAP-R1 fixed work edition verification captures author bytes before its first await',async()=>{
 const {project:p,ids,registry}=input(),fixed=await createWorldSnapshot(p,'制作条件の作品固定版'),pin=fixed.snapshots.at(-1)!,source=await captureRuntimeContent(fixed,pin.id,{worldSnapshots:registry}),before=structuredClone(source);const pending=productionCheckView(source,registry,input().world.snapshots,pin.id);(source.entities.find(e=>e.id===ids.frame)as Entity<'storyboard_frame'>).data.caption![0].text='await後の別入力';const view=await pending;expect(view.project.entities.find(e=>e.id===ids.frame)).toEqual(before.entities.find(e=>e.id===ids.frame));writeFileSync(root+'/CAP-R1.json',JSON.stringify({fixedVersion:pin.id,capturedBeforeAwait:true,oldFrame:view.project.entities.find(e=>e.id===ids.frame)},null,2)+'\n');
});
