import 'fake-indexeddb/auto';
import {it,expect} from 'vitest';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createEntity,createProject,textToRichText,newId,validateProject} from '../src/domain/model';
import {createWorldSnapshot} from '../src/domain/world';
import {productionCheckView,checkProductionRules} from '../src/domain/productionChecks';
import {startTrialVerified} from '../src/domain/runtimeVerified';
import {stepTrial} from '../src/domain/runtime';
import {evaluateCondition} from '../src/domain/conditions';
import type {ProjectData,ProjectContent,RuntimeContext} from '../src/domain/types';
const root='/tmp/shinariokanri-independent-rb07-11cffa7/independent/fixtures';
it('R7D26 a selected actual full trace keeps the exact adopted fixed-world route condition for that same-world caption',async()=>{
 const path=root+'/world-route-production.json';let input:{project:ProjectData;world:ProjectData;ids:Record<string,string>;registry:Record<string,ProjectContent>};
 if(existsSync(path))input=JSON.parse(readFileSync(path,'utf8'));else{
  let world=createProject('経路条件付き声の固定世界');const actor=createEntity(world.projectId,'character','固定声の話者'),flag=createEntity(world.projectId,'variable','同じ固定世界の声条件',{key:'world_voice',scope:'across_runs',valueType:'boolean',initial:{type:'boolean',value:true}}),line=createEntity(world.projectId,'dialogue_line','世界の元台詞',{speakerId:actor.id,text:textToRichText('声の本文')}),rule=createEntity(world.projectId,'voice_rule','世界の状態に沿う声',{characterId:actor.id,firstPerson:'私',validity:{worldRange:null,routeCondition:{op:'compare',variableId:flag.id,comparator:'eq',value:{type:'boolean',value:true}},presentationAnchor:null}});[actor,flag,line,rule].forEach(e=>e.status='confirmed');world.entities.push(actor,flag,line,rule);world=await createWorldSnapshot(world,'声条件trueの世界固定版');const pin=world.snapshots.at(-1)!;
  const project=createProject('固定世界の同じ経路を読む作品'),frame=createEntity(project.projectId,'storyboard_frame','固定世界台詞の字幕',{anchor:{entityId:line.id,lineId:line.id,sourceVersionId:pin.id},caption:textToRichText('字幕で声を確認'),cueIds:[]}),entry=createEntity(project.projectId,'flow_node','条件trueの入口',{nodeType:'entry',executionPolicy:'first_match',gate:{op:'compare',variableId:flag.id,comparator:'eq',value:{type:'boolean',value:true}}}),terminal=createEntity(project.projectId,'flow_node','終端',{nodeType:'terminal',terminalReason:'完了'}),edge=createEntity(project.projectId,'flow_edge','内部進行',{fromId:entry.id,toId:terminal.id,edgeType:'automatic',priority:0});[frame,entry,terminal,edge].forEach(e=>e.status='confirmed');project.entities.push(frame,entry,terminal,edge);project.worldReferences=[{projectId:world.projectId,immutableSnapshotId:pin.id,contentHash:pin.contentHash}];input={project,world,ids:{flag:flag.id,line:line.id,rule:rule.id,frame:frame.id,entry:entry.id,terminal:terminal.id,edge:edge.id,pin:pin.id},registry:{[pin.id]:pin.content}};writeFileSync(path,JSON.stringify(input,null,2)+'\n');
 }
 const {project:p,ids,registry,world}=input;expect(validateProject(p,{worldSnapshots:registry}).ok).toBe(true);let session=await startTrialVerified(p,{entryId:ids.entry},registry);expect(session.status).toBe('ready');session=stepTrial(p,session,{edgeId:ids.edge});expect(session.status).toBe('terminal');expect(session.state.provenance).toBe('full_play');expect(session.state.variableValues[ids.flag]).toEqual({type:'boolean',value:true});const view=await productionCheckView(p,registry,world.snapshots),context:RuntimeContext={state:session.state,entities:view.project.entities,ruleContext:{projectId:p.projectId,sourceVersionId:session.state.contentVersionId}},rule=world.snapshots[0].content.entities.find(e=>e.id===ids.rule)!;if(rule.kind!=='voice_rule')throw Error('fixture');expect(evaluateCondition(rule.data.validity!.routeCondition!,context).value).toBe('true');const all=checkProductionRules(view.project,{...view,context}),checks=all.filter(x=>x.lineId===ids.frame&&x.kind==='voice'),sourceChecks=all.filter(x=>x.lineId===ids.line&&x.kind==='voice');writeFileSync(root+'/R7D26.json',JSON.stringify({checks,sourceChecks,sessionStatus:session.status,provenance:session.state.provenance,knownFlag:session.state.variableValues[ids.flag],directCondition:evaluateCondition(rule.data.validity!.routeCondition!,context),adoptedWorld:p.worldReferences[0],stateVersion:session.state.contentVersionId,sourcePin:ids.pin},null,2)+'\n');expect(sourceChecks[0].value).toBe('true');expect(checks).toHaveLength(1);expect(checks[0].value).toBe('true');
});
