import {expect,test,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {inspectScenario} from '../../src/storage/archive';

async function nav(page:Page,name:RegExp){await expect(page.locator('.app-shell')).toBeVisible();const menu=page.getByRole('button',{name:'メニューを開く',exact:true});if(await menu.isVisible())await menu.click();await page.locator('.sidebar').getByRole('button',{name}).first().click();}
async function backup(page:Page){await nav(page,/^作品・保存/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();const file=await pending;expect(await file.failure()).toBeNull();const bytes=new Uint8Array(await readFile((await file.path())!));return {bytes,prepared:await inspectScenario(bytes,{worker:false})};}
async function save(page:Page){await page.locator('.editor-footer').getByRole('button',{name:/^(保存する|保存を再試行)$/}).click();await expect(page.locator('.editor-save-state')).toContainText('端末内保存済み');}
async function eventEditor(page:Page,summary:string){await nav(page,/^資料/);await page.getByLabel('情報の種類',{exact:true}).selectOption('event');await page.locator('.entity-card').filter({hasText:summary}).click();}
async function durable(page:Page){return page.evaluate(async()=>{
 const db=await new Promise<IDBDatabase>((resolve,reject)=>{const q=indexedDB.open('scenario-manager-local-v1');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});
 try{return await new Promise<Record<string,unknown[]>>((resolve,reject)=>{const names=['projects','entities','relations','blocks','snapshots','commands','outbox','assets','restorePoints','worlds','recoveredPending','recordParts'],tx=db.transaction(names,'readonly'),rows:Record<string,unknown[]>={};for(const name of names){const q=tx.objectStore(name).getAll();q.onsuccess=()=>{rows[name]=q.result;};}tx.oncomplete=()=>resolve(rows);tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error);});}finally{db.close();}
});}

test('AT-B01: empty work saves name-only person and summary-only event; invalid input stays atomic; cold and empty new/clone keep text and IDs',async({page,browser},info)=>{
 test.setTimeout(180_000);
 const personName='名前だけの人物',summary='😀要約だけの出来事𠮷野の門が開く';
 await page.goto('./');await page.getByLabel('作品名',{exact:true}).fill('基本登録の通常操作');await page.getByRole('button',{name:'作品を作成',exact:true}).click();expect((await backup(page)).prepared.project.entities).toHaveLength(0);
 await nav(page,/^資料/);await page.getByRole('button',{name:'人物を追加',exact:true}).first().click();await page.getByRole('dialog').getByLabel('名前',{exact:true}).fill(personName);await page.getByRole('dialog').getByRole('button',{name:'編集を始める'}).click();await expect(page.locator('.editor-save-state')).toContainText('端末内保存済み');
 await nav(page,/^資料/);await page.getByLabel('情報の種類',{exact:true}).selectOption('event');await page.getByRole('button',{name:'出来事を追加',exact:true}).first().click();await page.getByRole('dialog').getByLabel('名前',{exact:true}).fill('');await page.getByRole('dialog').getByRole('button',{name:'編集を始める'}).click();
 const input=page.locator('[data-field="summary"] textarea[data-rich-text-editor]');await input.fill(summary);await save(page);
 const registered=await backup(page),person=registered.prepared.project.entities.find(e=>e.kind==='character')!,event=registered.prepared.project.entities.find(e=>e.kind==='event')!;expect(person.name).toBe(personName);expect(event.name).toBe('');expect(event.kind==='event'&&event.data.summary[0]!.text).toBe(summary);
 for(const query of [personName,summary]){await nav(page,/^検索/);await page.getByLabel('作品内を検索',{exact:true}).fill(query);await expect(page.locator('.entity-card')).toHaveCount(1);await page.locator('.entity-card').click();if(query===personName)await expect(page.locator('#entity-name')).toHaveValue(personName);else await expect(input).toHaveValue(summary);}
 await eventEditor(page,summary);const beforeBlank=await durable(page);await input.fill('　 ');await page.locator('.editor-footer').getByRole('button',{name:/^(保存する|保存を再試行)$/}).click();await expect(page.locator('.detail-panel').getByRole('alert')).toContainText('名称または要約');await expect(input).toHaveValue('　 ');expect(await durable(page)).toEqual(beforeBlank);await input.fill(summary);await save(page);
 await nav(page,/^資料/);await page.getByLabel('情報の種類',{exact:true}).selectOption('character');await page.locator('.entity-card').filter({has:page.getByRole('heading',{name:personName,exact:true})}).click();const beforePerson=await durable(page);await page.locator('#entity-name').fill('');await page.locator('.editor-footer').getByRole('button',{name:/^(保存する|保存を再試行)$/}).click();await expect(page.locator('.detail-panel').getByRole('alert')).toContainText('名称を入力');expect(await durable(page)).toEqual(beforePerson);
 await nav(page,/^構成/);await nav(page,/^資料/);await page.getByLabel('情報の種類',{exact:true}).selectOption('character');await page.locator('.entity-card').filter({has:page.getByRole('heading',{name:personName,exact:true})}).click();await expect(page.locator('#entity-name')).toHaveValue('');await page.locator('#entity-name').fill(personName);await save(page);
 await eventEditor(page,summary);const beforeReference=await durable(page),advanced=page.locator('details.advanced-details').filter({has:page.getByText('詳細データ・ルビ・本文リンクを編集',{exact:true})});await advanced.locator('summary').click();const raw=advanced.getByRole('textbox',{name:'詳細データ',exact:true}),data=JSON.parse(await raw.inputValue());data.locationId='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';await raw.fill(JSON.stringify(data,null,2));const invalid=await raw.inputValue();await page.locator('.editor-footer').getByRole('button',{name:/^(保存する|保存を再試行)$/}).click();await expect(page.locator('.detail-panel').getByRole('alert')).toContainText(/参照|場所/);await expect(raw).toHaveValue(invalid);expect(await durable(page)).toEqual(beforeReference);
 data.locationId=null;await raw.fill(JSON.stringify(data,null,2));const correctedData=JSON.parse(await raw.inputValue());await save(page);const beforeCold=await backup(page);expect(beforeCold.prepared.project.entities.find(e=>e.id===event.id)!.data).toEqual(correctedData);await page.reload();await expect(page.locator('.app-shell')).toBeVisible();const complete=await backup(page),cold=complete.prepared.project,coldEvent=cold.entities.find(e=>e.id===event.id)!;expect(cold).toEqual(beforeCold.prepared.project);expect(complete.prepared.recovery).toEqual(beforeCold.prepared.recovery);expect(cold.projectId).toBe(registered.prepared.project.projectId);expect(cold.entities.find(e=>e.id===person.id)!.data).toEqual(person.data);expect(coldEvent.data).toEqual(correctedData);
 for(const mode of ['new','clone'] as const){const context=await browser.newContext({viewport:{width:390,height:844}}),fresh=await context.newPage();try{
  await fresh.goto(page.url());await fresh.getByRole('button',{name:'保存ファイルを読み込む',exact:true}).click();await fresh.locator('input[type=file][accept*=".scenario"]').setInputFiles({name:'summary-only.scenario',mimeType:'application/zip',buffer:Buffer.from(complete.bytes)});await fresh.getByLabel('復元方法',{exact:true}).selectOption(mode);await fresh.getByLabel('復元方法と対象への影響を確認しました').check();await fresh.getByRole('button',{name:'この内容で復元する',exact:true}).click();await expect(fresh.locator('.app-shell')).toBeVisible();await fresh.reload();const restored=(await backup(fresh)).prepared.project,restoredEvent=restored.entities.find(e=>e.kind==='event')!;expect(restoredEvent.name).toBe('');expect(restoredEvent.kind==='event'&&restoredEvent.data.summary.map(b=>b.text)).toEqual(event.kind==='event'&&event.data.summary.map(b=>b.text));
  if(mode==='new')expect(restored).toEqual(cold);else{expect(restored.projectId).not.toBe(cold.projectId);expect(restoredEvent.id).not.toBe(event.id);expect(restoredEvent.kind==='event'&&restoredEvent.data.summary[0]!.id).not.toBe(coldEvent.kind==='event'&&coldEvent.data.summary[0]!.id);expect(restored.history).toHaveLength(cold.history.length+1);}
 }finally{await context.close();}}
 await info.attach('original-B01-normal-atomic-cold-complete',{body:Buffer.from(JSON.stringify({emptyProject:true,personId:person.id,eventId:event.id,eventNameEmpty:true,summaryCodePoints:Array.from(summary).length,invalidBlankEventAndPersonAndReferenceRejected:true,native12TablesUnchangedOnFailure:true,inputResumed:true,coldSameIDs:true,emptyNewAndClone:true,completeFileSha256:createHash('sha256').update(complete.bytes).digest('hex'),layer:'Linux production App/real IndexedDB; physical and actual Auth not_run'},null,2)),contentType:'application/json'});
});
