import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createEntity, createProject, textToRichText } from '../../src/domain/model';
import { exportScenario, inspectScenario } from '../../src/storage/archive';
async function navigate(page: Page, name: RegExp) { const menu = page.getByRole('button', { name: 'メニューを開く' }); if (await menu.isVisible()) await menu.click(); await page.locator('.sidebar').getByRole('button', { name }).first().click(); }
async function work(page: Page, tab: string) { await navigate(page, /^作品・保存/); await page.getByRole('tab', { name: tab, exact: true }).click(); }
async function seed(page: Page, bytes: Uint8Array) { await page.goto('./'); await page.getByRole('button', { name: '保存ファイルを読み込む', exact: true }).click(); await page.locator('input[type=file]').setInputFiles({ name: 'recovery.scenario', mimeType: 'application/zip', buffer: Buffer.from(bytes) }); await page.getByLabel('復元方法と対象への影響を確認しました').check(); await page.getByRole('button', { name: 'この内容で復元する', exact: true }).click(); await expect(page.locator('.sidebar')).toBeVisible(); }
async function backup(page: Page) { await work(page, '完全保存・復元'); const pending = page.waitForEvent('download'); await page.getByRole('button', { name: '完全保存ファイルを作成', exact: true }).click(); const download = await pending; return inspectScenario(new Uint8Array(await readFile((await download.path())!)), { worker: false }); }
async function oldHistory() { const bytes = new Uint8Array(await readFile('tests/fixtures/rb06-history.scenario')), prepared = await inspectScenario(bytes, { worker: false }), p = prepared.project, first = p.history[0], scene = first.after.entities[0]; return { bytes, p, operation: first.operationId, scene }; }

test('50件より古い版を通常検索し、単体復元と作品全体復元を区別して保存失敗・再入・cold再生する', async ({ page }) => {
  const f = await oldHistory(); await seed(page, f.bytes); await work(page, '変更履歴'); const panel = page.locator('.history-page'); expect(await panel.locator('.history-list > li').count()).toBeLessThanOrEqual(30); await panel.getByLabel('履歴を検索', { exact: true }).fill(f.operation); await panel.getByRole('button', { name: /原作品を保存 · 版 1/ }).click(); await panel.getByLabel('単体復元する対象', { exact: true }).selectOption(f.scene.id); await panel.getByRole('button', { name: 'この情報だけの復元を確認', exact: true }).click();
  await page.evaluate(() => { const original = IDBObjectStore.prototype.put; (window as any).__rb06Fail = true; IDBObjectStore.prototype.put = function (...args: Parameters<IDBObjectStore['put']>) { if ((window as any).__rb06Fail && this.name === 'projects') { (window as any).__rb06Fail = false; throw new DOMException('fixture full', 'QuotaExceededError'); } return original.apply(this, args); }; });
  await panel.getByRole('button', { name: 'この内容へ復元する', exact: true }).click(); await expect(panel.getByRole('alert')).toContainText('容量'); await expect(panel.getByRole('region', { name: '確認した復元差分' })).toContainText('原場面'); await navigate(page, /^資料/); await work(page, '変更履歴'); await expect(panel.getByRole('region', { name: '確認した復元差分' })).toBeVisible(); await panel.getByRole('button', { name: 'この内容へ復元する', exact: true }).click(); await expect(panel.getByRole('status').filter({ hasText: '保存した版を確認' })).toBeVisible();
  await page.reload(); await work(page, '変更履歴'); await expect(panel.getByLabel('履歴を検索', { exact: true })).toHaveValue(f.operation); await expect(panel.getByLabel('単体復元する対象', { exact: true })).toHaveValue(f.scene.id); let inspected = await backup(page); expect(inspected.project.name).toBe(f.p.name); expect(inspected.project.entities.find(e => e.id === f.scene.id)!.name).toBe('原場面'); expect(inspected.project.snapshots).toEqual(f.p.snapshots);
  await work(page, '変更履歴'); await panel.getByRole('button', { name: '作品全体の復元差分を確認', exact: true }).click(); await panel.getByRole('button', { name: '確認した作品全体へ復元', exact: true }).click(); await expect(panel.getByRole('status').filter({ hasText: '保存した版を確認' })).toBeVisible(); inspected = await backup(page); expect(inspected.project.name).toBe('復元元'); expect(inspected.project.history.length).toBe(f.p.history.length + 2); expect(inspected.project.snapshots).toEqual(f.p.snapshots); expect(inspected.recovery!.pending.length).toBeGreaterThanOrEqual(f.p.history.length);
});

test('別作品の全ID対応を画面移動・cold再起動から再開し、失敗後に原子統合して元履歴・段落を完全保存する', async ({ page }) => {
  const destination = createProject('統合先'), own = createEntity(destination.projectId, 'note', '残す元メモ', { body: textToRichText('保持する') }); destination.entities.push(own); await seed(page, await exportScenario(destination)); await work(page, '完全保存・復元'); const source = createProject('別の復元元'), scene = createEntity(source.projectId, 'scene', '取り込む場面', { body: textToRichText('別作品😀の段落') }); source.entities.push(scene);
  await page.locator('input[type=file]').setInputFiles({ name: 'other.scenario', mimeType: 'application/zip', buffer: Buffer.from(await exportScenario(source)) }); await page.getByLabel('復元方法', { exact: true }).selectOption('mapped_merge'); await page.getByLabel('復元する対象作品', { exact: true }).selectOption(destination.projectId); await page.getByRole('button', { name: '全IDへ新しい対応先を用意', exact: true }).click(); await page.getByRole('button', { name: '復元の影響を確認', exact: true }).click(); await page.locator('.import-preview details summary').first().click(); const selector = page.locator('select[aria-label$="の統合方法"]').first(); await selector.selectOption('existing'); await page.getByRole('button', { name: '復元の影響を確認', exact: true }).click(); await expect(page.getByLabel('復元方法と対象への影響を確認しました')).toBeEnabled();
  await navigate(page, /^資料/); await work(page, '完全保存・復元'); await expect(page.getByLabel('復元方法', { exact: true })).toHaveValue('mapped_merge'); await page.reload(); await work(page, '完全保存・復元'); await expect(page.getByText('元ファイルとID対応の入力を再開しました。対象版の影響を再確認してください。')).toBeVisible(); await expect(page.getByLabel('復元方法と対象への影響を確認しました')).not.toBeChecked(); await page.getByRole('button', { name: '復元の影響を確認', exact: true }).click(); await page.getByLabel('復元方法と対象への影響を確認しました').check();
  await page.evaluate(() => { const original = IDBObjectStore.prototype.put; (window as any).__rb06Fail = true; IDBObjectStore.prototype.put = function (...args: Parameters<IDBObjectStore['put']>) { if ((window as any).__rb06Fail && this.name === 'projects') { (window as any).__rb06Fail = false; throw new DOMException('fixture quota', 'QuotaExceededError'); } return original.apply(this, args); }; }); await page.getByRole('button', { name: 'この内容で復元する', exact: true }).click(); await expect(page.locator('.backup-page').getByRole('alert')).toContainText('容量'); await expect(page.getByLabel('復元方法', { exact: true })).toHaveValue('mapped_merge'); await page.getByRole('button', { name: 'この内容で復元する', exact: true }).click(); await expect(page.getByText('検査した作品を端末内に復元しました。保存した版を確認しました。')).toBeVisible();
  const restored = await backup(page); expect(restored.project.projectId).toBe(destination.projectId); expect(restored.project.name).toBe(destination.name); expect(restored.project.entities.find(e => e.id === own.id)).toBeTruthy(); const mapped = restored.project.entities.find(e => e.kind === 'scene')!; expect(mapped.id).not.toBe(scene.id); expect(mapped.kind === 'scene' && mapped.data.body[0].id).not.toBe(scene.data.body[0].id); expect(mapped.kind === 'scene' && mapped.data.body[0].text).toBe('別作品😀の段落'); await page.reload(); await work(page, '変更履歴'); await page.getByRole('button', { name: /専用ファイルをmapped_mergeで復元/ }).first().click(); await expect(page.getByRole('region', { name: '移行・読み込み前の復元点' })).toContainText('前の復元点');
});

test('復元保存待ちの後に選んだ資料と作品を保持し、新規復元だけを一覧へ追加する', async ({ page }) => {
  const original=createProject('復元後も続ける作品A');original.entities.push(createEntity(original.projectId,'note','続ける資料'));await seed(page,await exportScenario(original));await work(page,'完全保存・復元');
  const incoming=createProject('待機中に復元する作品C');await page.locator('input[type=file]').setInputFiles({name:'later.scenario',mimeType:'application/zip',buffer:Buffer.from(await exportScenario(incoming))});await page.getByLabel('復元方法と対象への影響を確認しました').check();
  await page.evaluate(()=>{const digest=crypto.subtle.digest.bind(crypto.subtle);let hold=true;crypto.subtle.digest=async(...args:Parameters<SubtleCrypto['digest']>)=>{if(hold){hold=false;(window as any).__rb06ImportHeld=true;await new Promise<void>(resolve=>{(window as any).__releaseRb06Import=resolve;});}return digest(...args);};});
  await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__rb06ImportHeld)).toBe(true);await navigate(page,/^資料/);await expect(page.locator('.workspace-heading h1')).toHaveText('資料');await page.evaluate(()=>(window as any).__releaseRb06Import());
  await expect.poll(()=>page.evaluate(async id=>{const databases=await indexedDB.databases();for(const item of databases){if(!item.name)continue;const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(item.name!);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{if(db.objectStoreNames.contains('projects')){const found=await new Promise<boolean>((resolve,reject)=>{const request=db.transaction('projects').objectStore('projects').get(id);request.onsuccess=()=>resolve(!!request.result);request.onerror=()=>reject(request.error);});if(found)return true;}}finally{db.close();}}return false;},incoming.projectId)).toBe(true);await expect(page.locator('.workspace-heading h1')).toHaveText('資料');await expect(page.locator('.project-switch strong')).toHaveText(original.name);await page.reload();await expect(page.locator('.project-switch strong')).toHaveText(original.name);await expect(page.locator('.workspace-heading h1')).toHaveText('資料');
});

test('native保存ack待ちに届いた後続ファイルを保持し、先の新規復元が確認画面を開き直さない',async({page})=>{
 const original=createProject('後続選択を続ける作品A');await seed(page,await exportScenario(original));await work(page,'完全保存・復元');const first=createProject('先に保存する作品C'),later=createProject('後から確認する作品D');
 await page.locator('input[type=file]').setInputFiles({name:'first.scenario',mimeType:'application/zip',buffer:Buffer.from(await exportScenario(first))});await page.getByLabel('復元方法と対象への影響を確認しました').check();
 await page.evaluate(id=>{const descriptor=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete')!,put=IDBObjectStore.prototype.put;let held:IDBTransaction|undefined;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='projects'&&(args[0] as any).projectId===id)held=this.transaction;return put.apply(this,args);};Object.defineProperty(IDBTransaction.prototype,'oncomplete',{...descriptor,set(handler){descriptor.set!.call(this,function(this:IDBTransaction,event:Event){if(this===held){(window as any).__rb06AckWaiting=true;(window as any).__rb06ReleaseAck=()=>handler.call(this,event);}else handler.call(this,event);});}});},first.projectId);
 await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__rb06AckWaiting)).toBe(true);
 const bytes=Array.from(await exportScenario(later));await page.locator('input[type=file]').evaluate((input,values)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(values)],'later.scenario',{type:'application/zip'}));(input as HTMLInputElement).files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));},bytes);await page.evaluate(()=>(window as any).__rb06ReleaseAck());
 await expect(page.locator('.project-switch strong')).toHaveText(original.name);await expect(page.locator('.import-preview h3')).toContainText(later.name);await page.reload();await work(page,'完全保存・復元');await expect(page.locator('.import-preview h3')).toContainText(later.name);await expect(page.getByLabel('復元方法と対象への影響を確認しました')).not.toBeChecked();
});
