import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
import {canonicalJson} from '../../src/storage/json';
import {createHttpContract,createProductionApp,type HttpContract} from './httpContract';
const account='a1000000-0000-4000-8000-000000000001',snapshotId='b1000000-0000-4000-8000-000000000001';
let endpoint='',contract:HttpContract|undefined,app:HttpContract|undefined;
test.afterEach(async()=>{await contract?.close();await app?.close();contract=undefined;app=undefined;});
const old={format:'scenario-projection',formatVersion:'1.0.0',title:'旧公開版',calendars:[],entities:[{id:'public-old-note',kind:'note',name:'旧公開名',status:'confirmed',data:{body:[{id:'public-old-block',kind:'paragraph',text:'😀旧版の引用'}]}}],relations:[],searchIndex:[{entityId:'public-old-note',kind:'note',name:'旧公開名',text:'😀旧版の引用',normalized:'😀旧版の引用'}]};
const projection={format:'scenario-projection',formatVersion:'1.0.0',title:'限定本文',calendars:[],entities:[{id:'public-note',kind:'note',name:'公開名',status:'confirmed',data:{body:[{id:'public-block',kind:'paragraph',text:'🔗参照',links:[{start:1,end:3,targetId:'public-old-note',sourceVersionId:'public-old',blockId:'public-old-block',targetStart:1,targetEnd:3}]}]}}],relations:[],searchIndex:[{entityId:'public-note',kind:'note',name:'公開名',text:'🔗参照',normalized:'🔗参照'}],versions:[{id:'public-old',projection:old}]},hash=createHash('sha256').update(canonicalJson(projection)).digest('hex');
async function login(page:Page){await page.getByRole('button',{name:'アカウント・専用同期',exact:true}).click();await page.getByLabel('専用Supabase URL',{exact:true}).fill(endpoint);await page.getByLabel('公開用APIキー',{exact:true}).fill('sb_publishable_contract_fixture');await page.getByRole('button',{name:'接続設定を保持',exact:true}).click();await page.getByLabel('メール',{exact:true}).fill('fixture@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-only');await page.getByRole('button',{name:'認証してアカウント領域を開く',exact:true}).click();await expect(page.getByRole('button',{name:'限定版の閲覧・指摘',exact:true})).toBeVisible();}
// Browser UI + real local HTTP fixture. This is not real Supabase Auth/Data API/Storage evidence.
test('approved fixed reference retains Unicode position, source return, comment version and cold cache without persisting Auth',async({page})=>{app=await createProductionApp();await page.addInitScript(()=>{(window as any).__coldDocumentNonce=crypto.randomUUID();});let posted:unknown;contract=await createHttpContract(async route=>{const request=route.request(),url=new URL(request.url()),body=request.postDataJSON() as {action:string;input:unknown}|null;let response:unknown=[];
 if(url.pathname.includes('/auth/v1/token'))response={access_token:'contract-memory-token',user:{id:account},expires_in:3600};else if(body?.action==='projects')response=[];else if(body?.action==='shared_snapshot')response={id:snapshotId,projection,contentHash:hash,createdAt:'2026-10-08T00:00:00Z',accessExpiresAt:new Date(Date.now()+60000).toISOString(),role:'reviewer'};else if(url.pathname.endsWith('scenario_snapshots'))response=[{id:snapshotId}];else if(url.pathname.endsWith('scenario_comments')&&request.method()==='POST'){posted=body;response=[{id:'c1000000-0000-4000-8000-000000000001'}];}await route.fulfill({json:response});});endpoint=contract.url;await page.goto(app.url);await login(page);await page.getByRole('button',{name:'限定版の閲覧・指摘',exact:true}).click();await page.getByLabel('受取った限定版ID').fill(snapshotId);await page.getByRole('button',{name:'指定した限定版を開く',exact:true}).click();await expect(page.getByRole('heading',{name:'限定本文',exact:true})).toBeVisible();await page.locator('#shared-content').getByRole('button',{name:'参照',exact:true}).click();await expect(page.locator('#shared-content mark')).toHaveText('旧版');await expect(page.locator('#shared-content')).toContainText('public-old');await page.getByRole('button',{name:'元の読み位置へ戻る',exact:true}).click();await expect(page.locator('#shared-content')).toContainText('🔗参照');await page.getByLabel('対象の公開段落',{exact:true}).selectOption('public-block');await page.getByLabel('開始位置',{exact:true}).fill('0');await page.getByLabel('終了位置',{exact:true}).fill('1');await page.getByLabel('指摘の本文').fill('Unicode位置の指摘');await page.getByRole('button',{name:'この版と位置へ指摘を保存'}).click();await expect.poll(()=>posted).toMatchObject({snapshot_id:snapshotId,public_version_id:'public-project',public_entity_id:'public-note',public_block_id:'public-block',start_cp:0,end_cp:1});expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('contract-memory-token');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);const onlineNonce=await page.evaluate(()=>(window as any).__coldDocumentNonce);expect(onlineNonce).toEqual(expect.any(String));await app.close();await contract.close();await page.reload();await expect.poll(async()=>{const nonce=await page.evaluate(()=>(window as any).__coldDocumentNonce);return typeof nonce==='string'&&nonce!==onlineNonce;}).toBe(true);await page.context().setOffline(true);await expect.poll(()=>page.evaluate(()=>navigator.onLine)).toBe(false);await page.getByRole('button',{name:'限定版の閲覧・指摘',exact:true}).click();await page.getByLabel('受取った限定版ID').fill(snapshotId);await page.getByRole('button',{name:'指定した限定版を開く',exact:true}).click();await expect(page.getByRole('heading',{name:'限定本文',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'この版と位置へ指摘を保存'})).toBeDisabled();});
test('revocation refuses a new snapshot and clears the cached displayed edition',async({page})=>{let revoked=false;contract=await createHttpContract(async route=>{const url=new URL(route.request().url()),body=route.request().postDataJSON() as {action?:string}|null;if(url.pathname.includes('/auth/v1/token'))return route.fulfill({json:{access_token:'contract-token',user:{id:account},expires_in:3600}});if(body?.action==='shared_snapshot')return route.fulfill(revoked?{status:403,json:{code:'FORBIDDEN'}}:{json:{id:snapshotId,projection,contentHash:hash,createdAt:'2026-10-08T00:00:00Z',accessExpiresAt:null,role:'reader'}});return route.fulfill({json:url.pathname.endsWith('scenario_snapshots')?[{id:snapshotId}]:[]});});endpoint=contract.url;await page.goto('');await login(page);await page.getByRole('button',{name:'限定版の閲覧・指摘',exact:true}).click();await page.getByLabel('受取った限定版ID').fill(snapshotId);await page.getByRole('button',{name:'指定した限定版を開く',exact:true}).click();await expect(page.getByRole('heading',{name:'限定本文',exact:true})).toBeVisible();revoked=true;await page.getByRole('button',{name:'指定した限定版を開く',exact:true}).click();await expect(page.getByRole('alert')).toContainText('FORBIDDEN');await expect(page.getByRole('heading',{name:'限定本文',exact:true})).toHaveCount(0);});

test('a requested fixed snapshot opens after a delayed metadata listing instead of being dropped by the initial busy lock',async({page})=>{let opens=0;contract=await createHttpContract(async route=>{const url=new URL(route.request().url()),body=route.request().postDataJSON() as {action?:string}|null;if(url.pathname.includes('/auth/v1/token'))return route.fulfill({json:{access_token:'contract-memory-token',user:{id:account},expires_in:3600}});if(body?.action==='shared_snapshot'){opens++;return route.fulfill({json:{id:snapshotId,projection,contentHash:hash,createdAt:'2026-10-08T00:00:00Z',accessExpiresAt:null,role:'reader'}});}if(url.pathname.endsWith('scenario_snapshots')){await new Promise(resolve=>setTimeout(resolve,350));return route.fulfill({json:[{id:snapshotId}]});}return route.fulfill({json:[]});});endpoint=contract.url;await page.goto('?shared='+snapshotId);await login(page);await expect(page.getByRole('heading',{name:'限定本文',exact:true})).toBeVisible();expect(opens).toBe(1);await page.locator('#shared-content').getByRole('button',{name:'参照',exact:true}).click();await expect(page.locator('#shared-content mark')).toHaveText('旧版');await page.getByRole('button',{name:'元の読み位置へ戻る',exact:true}).click();await expect(page.locator('#shared-content')).toContainText('🔗参照');});
