import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createEntity,createProject,textToRichText} from '../../src/domain/model';
import {exportScenario,inspectScenario} from '../../src/storage/archive';
import {sharedReviewFixture} from '../../src/testing/sharedReviewFixture';
import {createSharedCommentReview} from '../../src/domain/sharedReviews';
import {createHttpContract,type HttpContract} from './httpContract';
let contract:HttpContract|undefined;
test.afterEach(async()=>{await contract?.close();contract=undefined;});
async function nav(page:Page,name:RegExp){const menu=page.getByRole('button',{name:'メニューを開く'});if(await menu.isVisible())await menu.click();await page.locator('.sidebar').getByRole('button',{name}).first().click();}
async function seed(page:Page,bytes:Uint8Array,navigate=true){if(navigate)await page.goto('');await page.getByRole('button',{name:'保存ファイルを読み込む',exact:true}).click();await page.locator('input[type=file][accept*=".scenario"]').setInputFiles({name:'paging.scenario',mimeType:'application/zip',buffer:Buffer.from(bytes)});await page.getByLabel('復元方法と対象への影響を確認しました').check();await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await expect(page.locator('.sidebar')).toBeVisible();}
test('paged chapter tail keeps original move indices, selection and cold return position through a complete save',async({page})=>{
 const p=createProject('章の分割検査'),chapters=Array.from({length:11},(_,i)=>createEntity(p.projectId,'chapter',`章${i+1}`,{sceneIds:[]})),scenes=Array.from({length:65},(_,i)=>createEntity(p.projectId,'scene',`場面${i+1}`,{chapterId:chapters[0].id,body:textToRichText(`本文${i+1}`)}));chapters[0].data.sceneIds=scenes.map(s=>s.id);p.entities.push(...chapters,...scenes);
 await seed(page,await exportScenario(p));await nav(page,/^構成/);await page.getByRole('tab',{name:'章・本文',exact:true}).click();const list=page.locator('.chapter-list');expect(await list.locator('.chapter-section').count()).toBe(10);expect(await list.locator('.scene-row').count()).toBe(30);
 await page.getByRole('navigation',{name:'章1の場面のページ',exact:true}).getByRole('button',{name:'次のページ'}).click();await expect(list.getByRole('button',{name:'場面60を前へ',exact:true})).toBeEnabled();await list.getByRole('button',{name:'場面60を前へ',exact:true}).click();await expect(list.locator('.scene-open').filter({hasText:'場面60'}).locator('.scene-index')).toHaveText('59');await list.locator('.scene-open').filter({hasText:'場面60'}).click();await nav(page,/^資料/);await nav(page,/^構成/);await expect(list.locator('.scene-open').filter({hasText:'場面60'})).toBeVisible();await page.reload();await expect(list.locator('.scene-open').filter({hasText:'場面60'})).toBeVisible();
 await nav(page,/^作品・保存/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();const download=await pending,restored=await inspectScenario(new Uint8Array(await readFile((await download.path())!)),{worker:false}),chapter=restored.project.entities.find(e=>e.id===chapters[0].id)!;expect(chapter.kind).toBe('chapter');if(chapter.kind==='chapter'){expect(chapter.data.sceneIds).toHaveLength(65);expect(chapter.data.sceneIds[58]).toBe(scenes[59].id);expect(chapter.data.sceneIds[59]).toBe(scenes[58].id);}
});
test('paged branch and production searches reach tail items without creating all DOM records',async({page})=>{
 const p=createProject('分割した制作と分岐'),nodes=Array.from({length:65},(_,i)=>createEntity(p.projectId,'flow_node',`ノード${i+1}`,{nodeType:'terminal',terminalReason:'完了'})),graph=createEntity(p.projectId,'flow_graph','全ノード',{nodeIds:nodes.map(n=>n.id),entryIds:[nodes[0].id]}),tasks=Array.from({length:65},(_,i)=>createEntity(p.projectId,'production_task',`作業${i+1}`,{progress:'todo',stage:'writing',targetIds:[nodes[i].id]}));p.entities.push(graph,...nodes,...tasks);await seed(page,await exportScenario(p));await nav(page,/^構成/);await page.getByRole('tab',{name:'分岐',exact:true}).click();expect(await page.locator('.branch-node').count()).toBe(20);await page.getByRole('searchbox',{name:'分岐ノードを検索',exact:true}).fill('ノード65');await page.locator('.branch-node-heading').click();await expect(page.locator('.detail-heading')).toContainText('ノード65');await page.getByRole('tab',{name:'制作',exact:true}).click();expect(await page.locator('.task-card').count()).toBe(30);await page.getByRole('searchbox',{name:/のタスクを検索/}).fill('作業65');await page.locator('.task-open').click();await expect(page.locator('.detail-heading')).toContainText('作業65');await page.reload();await expect(page.locator('.task-card')).toHaveCount(1);await expect(page.locator('.task-open')).toContainText('作業65');
});
test('an actual failed atomic save retains input and exports only optional diagnostic metadata',async({page})=>{
 const p=createProject('秘密の作品名'),note=createEntity(p.projectId,'note','秘密の人物名',{body:textToRichText('秘密の本文')});p.entities.push(note);await seed(page,await exportScenario(p));await nav(page,/^資料/);await page.getByRole('button',{name:/^メモ/ }).click();await page.locator('.entity-card').click();const name=page.getByLabel('名前',{exact:true});await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('private stack auth token','QuotaExceededError');}return put.apply(this,args);};});await name.fill('保持する秘密の入力');await expect(page.locator('.detail-panel').getByRole('alert')).toContainText('容量');await expect(name).toHaveValue('保持する秘密の入力');await page.getByText('この作業の診断を確認・持出し',{exact:true}).click();await expect(page.getByRole('button',{name:'確認した診断をファイルに持出す',exact:true})).toBeEnabled();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'確認した診断をファイルに持出す',exact:true}).click();const file=await pending,raw=await readFile((await file.path())!,'utf8'),d=JSON.parse(raw);expect(d.records.some((r:{code:string;operationId:string;revision:string})=>r.code==='QUOTA_EXCEEDED'&&r.operationId&&r.revision)).toBe(true);for(const secret of ['秘密','本文','stack','auth token','access_token'])expect(raw).not.toContain(secret);expect(d.records[0].metadata.base).toBe('/shinariokanri/');
});
test('cancelling an in-flight command keeps the draft, revision, history and outbox until explicit retry',async({page})=>{
 const p=createProject('保存の取消'),note=createEntity(p.projectId,'note','元の名前',{body:textToRichText('元の本文')});p.entities.push(note);await seed(page,await exportScenario(p));await nav(page,/^資料/);await page.getByRole('button',{name:/^メモ/}).click();await page.locator('.entity-card').click();
 const durable=()=>page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('scenario-manager-local-v1');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise<Record<string,unknown[]>>((resolve,reject)=>{const names=['projects','commands','outbox','entities'],tx=db.transaction(names,'readonly'),result:Record<string,unknown[]>={};for(const name of names){const request=tx.objectStore(name).getAll();request.onsuccess=()=>{result[name]=request.result;};}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}finally{db.close();}});
 const before=await durable();await page.evaluate(()=>{const digest=crypto.subtle.digest.bind(crypto.subtle);let first=true;crypto.subtle.digest=async(...args:Parameters<SubtleCrypto['digest']>)=>{if(first){first=false;(window as any).__cancelHashWaiting=true;await new Promise<void>(resolve=>(window as any).__cancelHashRelease=resolve);}return digest(...args);};});
 const name=page.getByLabel('名前',{exact:true});await name.fill('取消して保持する名前');await page.waitForFunction(()=>(window as any).__cancelHashWaiting);await page.getByRole('button',{name:'現在の保存を中止して入力を保持',exact:true}).click();await page.evaluate(()=>(window as any).__cancelHashRelease());await expect(page.locator('.detail-panel').getByRole('alert')).toContainText('取り消し');await expect(name).toHaveValue('取消して保持する名前');await page.waitForTimeout(650);expect(await durable()).toEqual(before);
 await nav(page,/^構成/);await nav(page,/^資料/);await page.locator('.entity-card').click();await expect(name).toHaveValue('取消して保持する名前');await page.getByRole('button',{name:'保存する',exact:true}).click();await expect(page.locator('.detail-heading')).toContainText('取消して保持する名前');await expect.poll(durable).not.toEqual(before);await page.reload();await expect(page.locator('.entity-card')).toContainText('取消して保持する名前');
});

test('a handled authentication failure records only optional identifiers and never exports credentials or the remote message',async({page})=>{
 // A local HTTP fixture reaches service-worker fetches too. It is not real Auth evidence.
 contract=await createHttpContract(async route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204});return route.fulfill({status:401,json:{message:'private auth stack secret manuscript',access_token:'private-token'}});});const endpoint=contract.url;await page.goto('');await page.getByRole('button',{name:'アカウント・専用同期',exact:true}).click();await page.getByLabel('専用Supabase URL',{exact:true}).fill(endpoint);await page.getByLabel('公開用APIキー',{exact:true}).fill('sb_publishable_diagnostic_fixture');await page.getByRole('button',{name:'接続設定を保持',exact:true}).click();await page.getByLabel('メール',{exact:true}).fill('private-author@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('private-password');await page.getByRole('button',{name:'認証してアカウント領域を開く',exact:true}).click();await expect(page.getByRole('alert')).toContainText('AUTH_REQUIRED');await page.getByText('この作業の診断を確認・持出し',{exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'確認した診断をファイルに持出す',exact:true}).click();const file=await pending,raw=await readFile((await file.path())!,'utf8'),d=JSON.parse(raw);expect(d.records.some((r:{code:string;operationId:string})=>r.code==='AUTH_REQUIRED'&&r.operationId)).toBe(true);for(const secret of ['private','password','@','access_token','stack','manuscript','publishable'])expect(raw).not.toContain(secret);
});

test('AT-F29 normal author operation imports frozen shared quotation and task atomically, retains a failed preview, records both stages and reloads the old edition',async({page})=>{
 const f=await sharedReviewFixture(),account='a1000000-0000-4000-8000-000000000001';let reflected:unknown;contract=await createHttpContract(async route=>{const request=route.request();if(request.method()==='OPTIONS')return route.fulfill({status:204});const url=new URL(request.url()),body=request.postDataJSON() as {action?:string;review_stage?:string}|null;let response:unknown=[];if(url.pathname.includes('/auth/v1/token'))response={access_token:'memory-only-review-token',user:{id:account},expires_in:3600};else if(body?.action==='shares')response=[{id:f.comment.snapshot_id,sourceVersionId:f.pin.id,contentHash:f.envelope.projectionHash,withdrawnAt:null,expiresAt:null}];else if(body?.action==='members')response={membershipRevision:'1',members:[]};else if(body?.action==='review_source')response=f.envelope;else if(url.pathname.endsWith('scenario_comments')){if(request.method()==='PATCH'){reflected=body;response=[{...f.comment,review_stage:body?.review_stage,resolved:body?.review_stage!=='open'}];}else response=[f.comment];}await route.fulfill({json:response});});const endpoint=contract.url;
 await page.goto('');await page.getByRole('button',{name:'アカウント・専用同期',exact:true}).click();await page.getByLabel('専用Supabase URL',{exact:true}).fill(endpoint);await page.getByLabel('公開用APIキー',{exact:true}).fill('sb_publishable_shared_review_fixture');await page.getByRole('button',{name:'接続設定を保持',exact:true}).click();await page.getByLabel('メール',{exact:true}).fill('review@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-only');await page.getByRole('button',{name:'認証してアカウント領域を開く',exact:true}).click();await expect(page.getByRole('button',{name:'限定版の閲覧・指摘',exact:true})).toBeVisible();await seed(page,await exportScenario(f.p),false);
 await nav(page,/^作品・保存/);await page.getByRole('tab',{name:'同期・限定共有',exact:true}).click();const inbox=page.getByRole('region',{name:'共有指摘を制作へ取り込む'});await page.getByLabel('指摘を確認する共有版',{exact:true}).selectOption(f.comment.snapshot_id);await page.getByRole('button',{name:'共有版の指摘を取得',exact:true}).click();await page.getByRole('button',{name:'この指摘の元版と引用を確認',exact:true}).click();await expect(page.getByText('引用「😀版」',{exact:false})).toBeVisible();
 await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('quota','QuotaExceededError');}return put.apply(this,args);};});await page.getByRole('button',{name:'確認した指摘と引用を原子保存',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'選択と入力は保持'})).toBeVisible();await expect(page.getByRole('button',{name:'確認した指摘と引用を原子保存',exact:true})).toBeEnabled();await page.getByRole('button',{name:'確認した指摘と引用を原子保存',exact:true}).click();const actions=page.getByRole('region',{name:'指摘の修正と確認'});await expect(actions).toContainText('未処理');await expect(actions).toContainText('😀版');
 // Invalid JSON must not let a lifecycle action overwrite a retained draft.
 await page.getByText('詳細データ・ルビ・本文リンクを編集',{exact:true}).click();const reviewJson=page.getByRole('textbox',{name:'詳細データ',exact:true}),originalReview=await reviewJson.inputValue();await reviewJson.fill('{');await expect(actions.getByRole('button',{name:'修正済みとして保存',exact:true})).toBeDisabled();await reviewJson.fill(originalReview);await expect(actions.getByRole('button',{name:'修正済みとして保存',exact:true})).toBeEnabled();
 async function returnToReview(){await nav(page,/^検索/);await page.locator('.search-page .kind-select').selectOption('review');await page.locator('.entity-card').filter({hasText:'共有指摘'}).click();await expect(page.getByRole('region',{name:'指摘の修正と確認'})).toContainText('現在稿の位置 不明');}
 for(const deleteBlock of [false,true]){await nav(page,/^検索/);await page.locator('.search-page .kind-select').selectOption('dialogue_line');await page.locator('.entity-card').filter({hasText:'台詞L'}).click();await page.getByText('詳細データ・ルビ・本文リンクを編集',{exact:true}).click();const dataInput=page.getByRole('textbox',{name:'詳細データ',exact:true}),data=JSON.parse(await dataInput.inputValue());data.text=deleteBlock?[]:data.text.map((block:{text:string})=>({...block,text:'😀改訂された台詞'}));await dataInput.fill(JSON.stringify(data));await expect(page.locator('.editor-save-state')).toContainText('端末内保存済み');await returnToReview();await page.getByRole('button',{name:'指摘した元の固定版を開く',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('😀版本1の台詞L');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeHidden();}
 await actions.getByRole('button',{name:'修正済みとして保存',exact:true}).click();await expect(actions).toContainText('修正済み');await actions.getByRole('button',{name:'確認済みとして保存',exact:true}).click();await expect(actions).toContainText('確認済み');await actions.getByRole('button',{name:'共有側の修正済みを明示保存',exact:true}).click();await actions.getByRole('button',{name:'端末の確認状態を共有指摘へ反映',exact:true}).click();await expect.poll(()=>reflected).toMatchObject({review_stage:'verified'});
 await nav(page,/^作品・保存/);const pending=page.waitForEvent('download');await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();const archive=await inspectScenario(new Uint8Array(await readFile((await (await pending).path())!)),{worker:false}),review=archive.project.entities.find(e=>e.kind==='review'&&e.data.sharedSource?.comment===f.comment.id)!;expect(review.data).toMatchObject({stage:'verified',quotedText:'😀版',targetVersionId:f.pin.id});expect(archive.project.entities.some(e=>e.kind==='production_task'&&e.data.targetIds.includes(review.id))).toBe(true);
 await page.reload();await expect(page.getByRole('heading',{name:'再認証が必要です',exact:true})).toBeVisible();await page.getByRole('button',{name:'アカウント・専用同期',exact:true}).click();await page.getByLabel('メール',{exact:true}).fill('review@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill('fixture-only');await page.getByRole('button',{name:'認証してアカウント領域を開く',exact:true}).click();await expect(page.locator('.sidebar')).toBeVisible();await nav(page,/^検索/);await page.locator('.search-page .kind-select').selectOption('review');await page.locator('.entity-card').filter({hasText:'共有指摘'}).click();await expect(page.locator('.detail-heading')).toContainText('共有指摘');await expect(page.getByRole('region',{name:'指摘の修正と確認'})).toContainText('確認済み');await page.getByRole('button',{name:'指摘した元の固定版を開く',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('😀版本1の台詞L');
});

test('F29 public old-version deep link carries only public IDs and Unicode offsets without private identifiers',async({page})=>{
 const f=await sharedReviewFixture(),endpoint='https://dedicated.review.invalid',review=await createSharedCommentReview(f.p,f.envelope,f.comment,endpoint);f.p.entities.push(review);await seed(page,await exportScenario(f.p));await nav(page,/^検索/);await page.locator('.search-page .kind-select').selectOption('review');await page.locator('.entity-card').click();const link=page.getByRole('link',{name:'元の共有版と公開引用を開く',exact:true}),url=new URL((await link.getAttribute('href'))!);expect(url.searchParams.get('sharedBlock')).toBe(f.comment.public_block_id);expect(url.searchParams.get('sharedStart')).toBe('0');expect(url.searchParams.get('sharedEnd')).toBe('2');expect(url.href).not.toContain(f.line.id);expect(url.href).not.toContain(f.pin.id);
});

test('F37 normal state editor shows enum meaning candidates while keeping an unknown initial value through a complete file and reload',async({page})=>{
 const p=createProject('同義語と未知'),variable=createEntity(p.projectId,'variable','生死の状態',{key:'life',valueType:'enum',scope:'run',allowed:{values:['alive','dead']},initial:{type:'unknown',value:null,reason:'未設定'}});variable.status='confirmed';p.entities.push(variable);await seed(page,await exportScenario(p));await nav(page,/^検索/);await page.locator('.search-page .kind-select').selectOption('variable');await page.locator('.entity-card').click();await expect(page.getByRole('region',{name:'同義語・反対語の状態候補'})).toContainText('alive');await page.reload();await nav(page,/^検索/);await page.locator('.entity-card').click();await expect(page.getByRole('region',{name:'同義語・反対語の状態候補'})).toContainText('dead');await nav(page,/^作品/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();const restored=await inspectScenario(new Uint8Array(await readFile((await (await pending).path())!)),{worker:false});expect(restored.project.entities.find(e=>e.id===variable.id)?.data).toMatchObject({initial:{type:'unknown',value:null,reason:'未設定'},allowed:{values:['alive','dead']}});
});

test('real native IndexedDB cancels a worker while a full import transaction contains parts, then explicitly retries and cold-loads every body',async({page})=>{
 const p=createProject('原子分割の通常復元');for(let i=0;i<6;i++)p.entities.push(createEntity(p.projectId,'note',`分割本文${i}`,{body:textToRichText(String(i)+'A'.repeat(800000)+'😀')}));const archive=await exportScenario(p);await page.goto('');
 await page.evaluate(()=>{const post=Worker.prototype.postMessage;Worker.prototype.postMessage=function(...args:any[]){if(args[0]?.action==='pack'&&!(window as any).__partsAlreadyHeld){(window as any).__partsAlreadyHeld=true;(window as any).__partsWaiting=true;(window as any).__partsRelease=()=>post.apply(this,args as any);}else post.apply(this,args as any);};});
 await page.getByRole('button',{name:'保存ファイルを読み込む',exact:true}).click();await page.locator('input[type=file][accept*=".scenario"]').setInputFiles({name:'parts.scenario',mimeType:'application/zip',buffer:Buffer.from(archive)});await page.getByLabel('復元方法と対象への影響を確認しました').check();await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await page.waitForFunction(()=>(window as any).__partsWaiting);await page.getByRole('status').getByRole('button',{name:'中止',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:/取り消|中止/})).toBeVisible();
 const counts=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('scenario-manager-local-v1');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise<Record<string,number>>((resolve,reject)=>{const names=['projects','entities','commands','outbox','recordParts'],tx=db.transaction(names,'readonly'),counts:Record<string,number>={};for(const name of names){const request=tx.objectStore(name).count();request.onsuccess=()=>counts[name]=request.result;}tx.oncomplete=()=>resolve(counts);tx.onerror=()=>reject(tx.error);});}finally{db.close();}});expect(counts).toEqual({projects:0,entities:0,commands:0,outbox:0,recordParts:0});
 await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await page.locator('.app-shell').waitFor();await page.reload();await page.locator('.app-shell').waitFor();await nav(page,/^資料/);await page.getByRole('button',{name:/^メモ/}).click();await expect(page.locator('.entity-card')).toHaveCount(6);await nav(page,/^作品/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();const restored=await inspectScenario(new Uint8Array(await readFile((await (await pending).path())!)),{worker:false});for(const original of p.entities)expect(restored.project.entities.find(e=>e.id===original.id)?.data).toEqual(original.data);
});

test('active and queued chapter saves warn before departure until both atomic commands finish, then retain order after cold reread and complete export', async ({page}) => {
 const p = createProject('保存待ちの章を保持');
 const chapters = [createEntity(p.projectId,'chapter','第一章'),createEntity(p.projectId,'chapter','第二章')];
 const scenes = chapters.flatMap((chapter,index) => [0,1].map(position => createEntity(p.projectId,'scene',`章${index+1}場面${position+1}`,{chapterId:chapter.id,body:textToRichText(`待機中の本文😀 ${index}:${position}`)})));
 chapters.forEach((chapter,index) => {chapter.data.sceneIds = scenes.slice(index*2,index*2+2).map(scene=>scene.id);});
 p.entities.push(...chapters,...scenes);await seed(page,await exportScenario(p));await nav(page,/^構成/);await page.getByRole('tab',{name:'章・本文',exact:true}).click();
 expect(await page.locator('.detail-panel').count()).toBe(0);
 const warns = () => page.evaluate(() => {const event = new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;});
 expect(await warns()).toBe(false);
 await page.evaluate(() => {const digest = crypto.subtle.digest.bind(crypto.subtle);let first = true;crypto.subtle.digest = async (...args:Parameters<SubtleCrypto['digest']>) => {if(first){first=false;(window as any).__chapterHashWaiting=true;await new Promise<void>(resolve=>(window as any).__chapterHashRelease=resolve);}return digest(...args);};});
 await page.getByRole('button',{name:'章1場面2を前へ',exact:true}).click();await page.waitForFunction(()=>(window as any).__chapterHashWaiting);
 expect(await warns()).toBe(true);
 await page.getByRole('button',{name:'章2場面2を前へ',exact:true}).click();expect(await warns()).toBe(true);
 await page.evaluate(()=>(window as any).__chapterHashRelease());
 for(const name of ['章1場面2','章2場面2']) await expect(page.locator('.scene-open').filter({hasText:name}).locator('.scene-index')).toHaveText('1');
 await expect.poll(warns).toBe(false);await page.reload();
 for(const name of ['章1場面2','章2場面2']) await expect(page.locator('.scene-open').filter({hasText:name}).locator('.scene-index')).toHaveText('1');
 await nav(page,/^作品・保存/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();
 const download=await pending, restored=(await inspectScenario(new Uint8Array(await readFile((await download.path())!)),{worker:false})).project;
 expect(restored.history).toHaveLength(2);expect(restored.projectId).toBe(p.projectId);
 chapters.forEach((chapter,index) => {const actual=restored.entities.find(entity=>entity.id===chapter.id)!;expect(actual.kind).toBe('chapter');if(actual.kind==='chapter')expect(actual.data.sceneIds).toEqual([scenes[index*2+1].id,scenes[index*2].id]);});
 scenes.forEach(scene=>{const actual=restored.entities.find(entity=>entity.id===scene.id)!;expect(actual.kind).toBe('scene');if(actual.kind==='scene')expect(actual.data.body).toEqual(scene.data.body);});
 // This dispatch proves the handler contract in Linux browser engines. It is
 // separate from a physical device's native departure dialog verification.
});
