import { expect, test, type Page } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createEntity, createProject, emptyRuntimeState, emptyValidity, newId, validateProject } from '../../src/domain/model';
import type { Entity, ProjectData, RichText } from '../../src/domain/types';
import { exportScenario, inspectScenario, verifySnapshotHashes } from '../../src/storage/archive';
import { jsonBytes, sha256 } from '../../src/storage/json';

async function navigate(page: Page, name: '年表' | '検索' | '作品・保存') {
  const menu = page.getByRole('button', { name: 'メニューを開く', exact: true });
  if (await menu.isVisible()) await menu.click();
  await page.locator('.sidebar').getByRole('button', { name, exact: true }).click();
}
async function preserveArtifact(name: string, bytes: Uint8Array, contentType: string) {
  const path = test.info().outputPath(name);
  await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes);
  await test.info().attach(name, { path, contentType });
  return { path: name, bytes: bytes.byteLength, sha256: await sha256(bytes) };
}
async function restore(page: Page, project: ProjectData) {
  const validation = validateProject(project);
  expect(validation, validation.ok ? '' : JSON.stringify(validation.issues)).toMatchObject({ ok: true });
  await verifySnapshotHashes([project]);
  const input = await exportScenario(project);
  const fixture = await preserveArtifact('fixture-input.scenario', input, 'application/zip');
  const model = await preserveArtifact('fixture-input.json', jsonBytes(project), 'application/json');
  await preserveArtifact('fixture-input-manifest.json', jsonBytes({ capturedBeforeImport: true, projectId: project.projectId, test: test.info().title, engine: test.info().project.name, fixture, model }), 'application/json');
  await page.goto('./');
  await page.getByRole('button', { name: '保存ファイルを読み込む', exact: true }).click();
  await page.locator('input[type=file][accept*=".scenario"]').setInputFiles({ name: 'paged-editing.scenario', mimeType: 'application/zip', buffer: Buffer.from(input) });
  await expect(page.getByRole('heading', { name: '検査済みの作品' })).toBeVisible();
  await page.getByLabel('復元方法と対象への影響を確認しました').check();
  await page.getByRole('button', { name: 'この内容で復元する', exact: true }).click();
  await expect(page.locator('.app-shell')).toBeVisible();
}
async function open(page: Page, name: string) {
  await navigate(page, '検索');
  await page.getByLabel('作品内を検索', { exact: true }).fill(name);
  await page.locator('.entity-card').filter({ hasText: name }).first().click();
  return page.locator('.detail-panel');
}
async function completeSave(page: Page) {
  await navigate(page, '作品・保存');
  await page.getByRole('tab', { name: '完全保存・復元', exact: true }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '完全保存ファイルを作成', exact: true }).click();
  const result = await download;
  const bytes = new Uint8Array(await readFile((await result.path())!));
  const archive = await preserveArtifact('complete-save-output.scenario', bytes, 'application/zip');
  const restored = (await inspectScenario(bytes, { worker: false })).project;
  await verifySnapshotHashes([restored]);
  expect(validateProject(restored)).toMatchObject({ ok: true });
  const model = await preserveArtifact('complete-save-output.json', jsonBytes(restored), 'application/json');
  await preserveArtifact('complete-save-manifest.json', jsonBytes({ capturedAfterActualDownload: true, projectId: restored.projectId, test: test.info().title, engine: test.info().project.name, archive, model }), 'application/json');
  return restored;
}
async function saved(page: Page) {
  await expect(page.locator('.detail-panel .editor-save-state')).toContainText('端末内保存済み');
}
async function snapshot(project: ProjectData) {
  const { snapshots: _snapshots, history: _history, ...content } = structuredClone(project);
  const edition = { id: newId(), versionLabel: '元の固定版', createdAt: new Date().toISOString(), content, contentHash: await sha256(jsonBytes(content)) };
  project.snapshots.push(edition);
  return edition;
}

test('種類切替の確認をページ・行移動・詳細の往復で保持し、取消と明示適用を原子保存から再読込する', async ({ page }) => {
  const project = createProject('切替確認を持ってページを移動');
  const person = createEntity(project.projectId, 'character', '30件の別名を編集');
  person.data.aliases = Array.from({ length: 30 }, (_, i) => ({ id: newId(), text: `別名${i + 1}`, reading: '', validity: { worldRange: null, routeCondition: { op: 'visited', entityId: person.id, count: i + 1 }, presentationAnchor: null }, audienceHolderIds: [], isPublicDefault: true }));
  project.entities = [person];
  await restore(page, project);
  let editor = await open(page, person.name);
  await editor.getByRole('tab', { name: '詳細', exact: true }).click();
  let aliases = editor.locator('[data-field="aliases"]');
  let row = aliases.locator('.sd-array-item').first();
  await row.getByLabel('count', { exact: true }).fill('-');
  await row.getByLabel('経路条件の種類', { exact: true }).selectOption({ label: '常に真／偽' });
  await expect(row.getByRole('button', { name: '内容を確認して切り替える', exact: true })).toBeVisible();
  await aliases.getByRole('button', { name: '次の25件', exact: true }).click();
  await expect(aliases.locator('.sd-array-item')).toHaveCount(5);
  await expect(editor.getByRole('button', { name: '保存する', exact: true })).toBeDisabled();
  await aliases.getByRole('button', { name: '前の25件', exact: true }).click();
  await aliases.getByRole('button', { name: '別名と公開範囲 1を後へ', exact: true }).click();
  row = aliases.locator('.sd-array-item').nth(1);
  await expect(row.getByRole('button', { name: '内容を確認して切り替える', exact: true })).toBeVisible();
  await editor.getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  await page.getByRole('button', { name: '1件の未保存入力', exact: true }).click();
  await page.getByRole('dialog', { name: '未保存の入力', exact: true }).getByRole('button', { name: /入力へ戻る/ }).click();
  editor = page.locator('.detail-panel'); aliases = editor.locator('[data-field="aliases"]'); row = aliases.locator('.sd-array-item').nth(1);
  await expect(row.getByRole('button', { name: '内容を確認して切り替える', exact: true })).toBeVisible();
  await row.getByRole('button', { name: '切替を取り消す', exact: true }).click();
  await expect(row.getByLabel('count', { exact: true })).toHaveValue('-');
  await expect(row.getByLabel('ID', { exact: true })).toHaveValue(person.data.aliases![0].id);
  await expect(editor.getByRole('button', { name: '保存する', exact: true })).toBeDisabled();
  await row.getByLabel('経路条件の種類', { exact: true }).selectOption({ label: '常に真／偽' });
  await row.getByRole('button', { name: '内容を確認して切り替える', exact: true }).click();
  await row.getByRole('checkbox', { name: '値', exact: true }).check();
  await saved(page);
  await page.reload(); editor = await open(page, person.name); aliases = editor.locator('[data-field="aliases"]');
  expect(await aliases.locator('.sd-array-item').count()).toBe(25);
  await expect(aliases.locator('.sd-array-item').nth(1).getByLabel('経路条件の種類', { exact: true })).toHaveValue('0');
  const restored = await completeSave(page), actual = restored.entities.find((entity): entity is Entity<'character'> => entity.id === person.id && entity.kind === 'character')!;
  const expected = structuredClone(person.data.aliases!); [expected[0], expected[1]] = [expected[1]!, expected[0]!];
  expected[1]!.validity.routeCondition = { op: 'constant', value: true };
  expect(actual.data.aliases).toEqual(expected);
});

test('61件の記録辞書の末尾を旧版125状態から選び、隠れた不正入力と新キーを保持して保存・完全保存する', async ({ page }) => {
  const project = createProject('旧版の辞書を末尾まで編集');
  const variables = Array.from({ length: 125 }, (_, i) => ({ ...createEntity(project.projectId, 'variable', `状態${String(i + 1).padStart(3, '0')}`, { key: `old_${i}`, valueType: 'integer', initial: { type: 'integer', value: i }, allowed: { min: 0, max: 200 } }), id: `ca170001-0000-4000-8000-${(i + 1).toString(16).padStart(12, '0')}` }));
  project.entities = variables;
  const edition = await snapshot(project);
  const state = emptyRuntimeState(edition.id); state.provenance = 'partial';
  state.variableValues = Object.fromEntries(variables.slice(0, 61).map((variable, i) => [variable.id, { type: 'integer', value: i }]));
  const checkpoint = createEntity(project.projectId, 'checkpoint', '旧版61件の記録', { contentVersionId: edition.id, origin: 'partial', runtimeState: state });
  const decoys = variables.map((variable, i) => createEntity(project.projectId, 'variable', variable.name, { key: `new_${i}`, valueType: 'integer', initial: { type: 'integer', value: 0 }, allowed: { min: 0, max: 200 } }));
  project.entities = [...decoys, checkpoint];
  await restore(page, project);
  let editor = await open(page, checkpoint.name), runtime = editor.locator('[data-field="runtimeState"]');
  let dictionary = runtime.locator('.sd-record-rows').first();
  const pager = () => runtime.getByRole('navigation', { name: '状態値の項目のページ', exact: true });
  await pager().getByRole('button', { name: '次のページ', exact: true }).click();
  await pager().getByRole('button', { name: '次のページ', exact: true }).click();
  await expect(dictionary.locator(':scope > .sd-record-row')).toHaveCount(11);
  let row = dictionary.locator(':scope > .sd-record-row').first();
  await row.getByLabel('値', { exact: true }).fill('-');
  await row.getByLabel('項目51のキーを検索', { exact: true }).fill(variables[124]!.id);
  await row.getByLabel('項目51のキー', { exact: true }).selectOption(variables[124]!.id);
  await row.getByLabel('項目51のキーを検索', { exact: true }).fill('');
  const optionIds = await row.getByLabel('項目51のキー', { exact: true }).locator('option').evaluateAll(options => options.map(option => (option as HTMLOptionElement).value));
  expect(optionIds.length).toBeLessThanOrEqual(62);
  expect(optionIds).toContain(variables[124]!.id);
  expect(optionIds.some(id => decoys.some(variable => variable.id === id))).toBe(false);
  const newKey = () => dictionary.getByLabel('新しいキー', { exact: true });
  await dictionary.getByLabel('新しいキーを検索', { exact: true }).fill(variables[123]!.id);
  await newKey().selectOption(variables[123]!.id);
  await pager().getByRole('button', { name: '前のページ', exact: true }).click();
  await pager().getByRole('button', { name: '前のページ', exact: true }).click();
  await dictionary.locator(':scope > .sd-record-row').first().getByLabel('値', { exact: true }).fill('4');
  await expect(editor.getByRole('button', { name: '保存する', exact: true })).toBeDisabled();
  await editor.getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  editor = await open(page, checkpoint.name); runtime = editor.locator('[data-field="runtimeState"]'); dictionary = runtime.locator('.sd-record-rows').first();
  await expect(dictionary.getByLabel('項目1のキー', { exact: true })).toHaveValue(variables[0]!.id);
  await expect(newKey()).toHaveValue(variables[123]!.id);
  await newKey().selectOption('');
  await pager().getByRole('button', { name: '次のページ', exact: true }).click();
  await pager().getByRole('button', { name: '次のページ', exact: true }).click();
  row = dictionary.locator(':scope > .sd-record-row').first();
  await expect(row.getByLabel('項目51のキー', { exact: true })).toHaveValue(variables[124]!.id);
  await expect(row.getByLabel('値', { exact: true })).toHaveValue('-');
  await row.getByLabel('値', { exact: true }).fill('199');
  await saved(page);
  await page.reload(); editor = await open(page, checkpoint.name); runtime = editor.locator('[data-field="runtimeState"]'); dictionary = runtime.locator('.sd-record-rows').first();
  await expect(dictionary.getByLabel('項目51のキー', { exact: true })).toHaveValue(variables[124]!.id);
  await expect(dictionary.locator(':scope > .sd-record-row').first().getByLabel('値', { exact: true })).toHaveValue('199');
  const restored = await completeSave(page), actual = restored.entities.find((entity): entity is Entity<'checkpoint'> => entity.id === checkpoint.id && entity.kind === 'checkpoint')!;
  const expected = Object.fromEntries(Object.entries(state.variableValues).map(([id, value], i) => [i === 50 ? variables[124]!.id : id, i === 50 ? { type: 'integer', value: 199 } : i === 0 ? { type: 'integer', value: 4 } : value]));
  expect(actual.data.runtimeState.variableValues).toEqual(expected);
  expect(restored.snapshots).toEqual(project.snapshots);
  expect(restored.entities.filter(entity => entity.kind === 'variable')).toEqual(decoys);
});

test('125段落の末尾の固定版Unicode参照から戻り、分割の境界拒否と再リンクで旧版・対象位置を完全保存まで保つ', async ({ page }) => {
  const project = createProject('末尾の固定リンクを編集');
  const targets = Array.from({ length: 125 }, (_, i) => createEntity(project.projectId, 'character', `人物${String(i + 1).padStart(3, '0')}`, { body: [{ id: newId(), kind: 'paragraph', text: '😀昔の引用' }] }));
  project.entities = targets;
  const edition = await snapshot(project), oldTarget = targets[124]!;
  const fixedAnchor = { entityId: oldTarget.id, sourceVersionId: edition.id, blockId: oldTarget.data.body![0].id, start: 1, end: 3 };
  const blocks: RichText = Array.from({ length: 125 }, (_, i) => ({ id: newId(), kind: 'paragraph', text: i === 124 ? `${'😀'.repeat(10_000)}末尾語句` : `😀目印${i + 1}`, ...(i < 64 ? { links: [{ start: 1, end: 3, target: { entityId: targets[i]!.id } }] } : {}) }));
  blocks[124]!.links = [{ start: 10_000, end: 10_004, target: fixedAnchor }];
  blocks[123]!.text = '😀昔の';
  const scene = createEntity(project.projectId, 'scene', '125段落の参照元', { body: blocks });
  const decoy = createEntity(project.projectId, 'character', oldTarget.name, { body: [{ id: newId(), kind: 'paragraph', text: '現在稿だけの引用' }] });
  project.entities = [...targets.slice(0, 124), decoy, scene];
  await restore(page, project);
  let editor = await open(page, scene.name);
  await editor.getByRole('tab', { name: '本文', exact: true }).click();
  let annotations = editor.getByRole('region', { name: '本文のルビとリンク', exact: true });
  const markPager = annotations.getByRole('navigation', { name: '設定済みの注記のページ', exact: true });
  await markPager.getByRole('button', { name: '次のページ', exact: true }).click();
  await markPager.getByRole('button', { name: '次のページ', exact: true }).click();
  await annotations.locator('.condition-row').filter({ hasText: 'リンク：「末尾語句」' }).getByRole('button', { name: '対象を開く', exact: true }).click();
  const fixed = page.getByRole('dialog', { name: '固定版の参照先', exact: true });
  await expect(fixed.getByRole('heading', { name: oldTarget.name, exact: true })).toBeVisible();
  await expect(fixed.locator('.referenced-quote mark')).toHaveText('昔の');
  await fixed.getByRole('button', { name: '閉じる', exact: true }).click();
  editor = page.locator('.detail-panel'); annotations = editor.getByRole('region', { name: '本文のルビとリンク', exact: true });
  const start = blocks.slice(0, 124).reduce((sum, block) => sum + block.text.length + 1, 0) + 20_000;
  await expect.poll(() => editor.getByLabel('本文', { exact: true }).evaluate(node => ({ start: (node as HTMLTextAreaElement).selectionStart, text: (node as HTMLTextAreaElement).value.slice((node as HTMLTextAreaElement).selectionStart, (node as HTMLTextAreaElement).selectionEnd) }))).toEqual({ start, text: '末尾語句' });
  await annotations.getByLabel('注記する段落を検索', { exact: true }).fill(blocks[124]!.id);
  await annotations.getByLabel('注記する段落', { exact: true }).selectOption(blocks[124]!.id);
  expect(await annotations.getByLabel('注記する段落', { exact: true }).locator('option').count()).toBeLessThanOrEqual(62);
  for (const invalid of ['0', '-1', '10004', '10001.5', 'unknown']) {
    await annotations.getByLabel('分割位置', { exact: true }).fill(invalid);
    await expect(annotations.getByRole('button', { name: 'この位置で段落を分割', exact: true })).toBeDisabled();
  }
  await annotations.getByLabel('分割位置', { exact: true }).fill('10001');
  await annotations.getByRole('button', { name: 'この位置で段落を分割', exact: true }).click();
  await expect(annotations).toContainText('再リンク待ち');
  await annotations.getByRole('button', { name: '次の段落と結合', exact: true }).click();
  await annotations.getByLabel('リンクまたはルビを付ける語句', { exact: true }).fill('末尾語句');
  await expect(annotations.getByLabel('再リンク先', { exact: true })).toHaveValue(oldTarget.id);
  await expect(annotations.getByLabel('再リンク先', { exact: true })).toContainText(edition.id);
  await annotations.getByRole('button', { name: '選択した語句に再リンク', exact: true }).click();
  await saved(page);
  await annotations.getByLabel('注記する段落を検索', { exact: true }).fill(blocks[123]!.id);
  await annotations.getByLabel('注記する段落', { exact: true }).selectOption(blocks[123]!.id);
  await annotations.getByLabel('リンクまたはルビを付ける語句', { exact: true }).fill('昔の');
  await annotations.getByLabel('リンク先を検索', { exact: true }).fill(targets[0]!.id);
  await annotations.getByLabel('リンク先', { exact: true }).selectOption(targets[0]!.id);
  await annotations.getByRole('button', { name: 'リンクを付ける', exact: true }).click();
  await saved(page);
  await page.reload(); editor = await open(page, scene.name);
  const restored = await completeSave(page), actual = restored.entities.find((entity): entity is Entity<'scene'> => entity.id === scene.id && entity.kind === 'scene')!;
  const expected = structuredClone(blocks);
  expected[123]!.links = [{ start: 1, end: 3, target: { entityId: targets[0]!.id, blockId: targets[0]!.data.body![0]!.id, start: 1, end: 3 } }];
  expect(actual.data.body).toEqual(expected);
  expect(restored.snapshots).toEqual(project.snapshots);
  expect(restored.entities.some(entity => entity.id === oldTarget.id)).toBe(false);
  expect(restored.entities.find(entity => entity.id === decoy.id)).toEqual(decoy);
});

test('年表の125グループと125人物の後半を検索・並替・参照変更し、全ID順を再読込と完全保存まで保持する', async ({ page }) => {
  const project = createProject('年表の後半の人物参照を編集');
  const people = Array.from({ length: 126 }, (_, i) => createEntity(project.projectId, 'character', `人物${String(i + 1).padStart(3, '0')}`));
  const groups = Array.from({ length: 125 }, (_, i) => createEntity(project.projectId, 'group', `グループ${String(i + 1).padStart(3, '0')}`, { groupType: 'display', members: i === 0 ? people.slice(0, 125).map(person => person.id) : [] }));
  project.entities = [...groups, ...people];
  await restore(page, project); await navigate(page, '年表');
  await page.getByRole('button', { name: 'グループ・人物レーン', exact: true }).click();
  let dialog = page.getByRole('dialog', { name: 'グループ・人物レーンを編集', exact: true });
  await expect(dialog.locator('.timeline-group-editor-row')).toHaveCount(30);
  let pager = dialog.getByRole('navigation', { name: '年表のグループのページ', exact: true });
  for (let i = 0; i < 4; i++) await pager.getByRole('button', { name: '次のページ', exact: true }).click();
  await dialog.locator('.timeline-group-editor-row').filter({ hasText: groups[124]!.name }).getByRole('button', { name: '改名・階層・人物を編集', exact: true }).click();
  await dialog.getByRole('button', { name: '編集を中止', exact: true }).click();
  await expect(dialog.locator('.timeline-group-editor-row')).toHaveCount(5);
  await expect(dialog.locator('.timeline-group-editor-row').last()).toContainText(groups[124]!.name);
  await dialog.getByLabel('年表のグループを検索', { exact: true }).fill(groups[0]!.id);
  await dialog.getByRole('button', { name: '改名・階層・人物を編集', exact: true }).click();
  await dialog.getByLabel('年表のグループ名', { exact: true }).fill('末尾人物の順序を保存');
  const parent = dialog.getByLabel('年表の親グループ', { exact: true });
  expect(await parent.locator('option').count()).toBeLessThanOrEqual(62);
  expect(await parent.locator('option').evaluateAll(nodes => nodes.map(node => (node as HTMLOptionElement).value))).not.toContain(groups[0]!.id);
  await dialog.getByLabel('年表の親グループを検索', { exact: true }).fill(groups[124]!.id);
  await parent.selectOption(groups[124]!.id);
  await dialog.getByLabel('年表の親グループを検索', { exact: true }).fill('');
  await expect(parent).toHaveValue(groups[124]!.id);
  const members = dialog.locator('.timeline-member-list');
  await expect(members.locator(':scope > li')).toHaveCount(30);
  pager = dialog.getByRole('navigation', { name: '年表グループの人物のページ', exact: true });
  for (let i = 0; i < 4; i++) await pager.getByRole('button', { name: '次のページ', exact: true }).click();
  await dialog.getByRole('button', { name: '125番の人物を前へ', exact: true }).click();
  await members.locator('li').filter({ hasText: people[123]!.name }).getByRole('button', { name: '参照を外す', exact: true }).click();
  await dialog.getByLabel('グループへ参照を追加する人物', { exact: true }).selectOption(people[125]!.id);
  await expect(members).toContainText(people[125]!.name);
  await dialog.getByRole('button', { name: 'グループを保存', exact: true }).click();
  await expect(dialog.getByLabel('年表のグループ名', { exact: true })).toHaveCount(0);
  await dialog.getByRole('button', { name: '閉じる', exact: true }).click();
  await page.reload(); await navigate(page, '年表');
  await page.getByRole('button', { name: 'グループ・人物レーン', exact: true }).click();
  dialog = page.getByRole('dialog', { name: 'グループ・人物レーンを編集', exact: true });
  await expect(dialog.locator('.timeline-group-editor-row')).toHaveCount(1);
  await expect(dialog.locator('.timeline-group-editor-row')).toContainText('末尾人物の順序を保存');
  await dialog.getByRole('button', { name: '閉じる', exact: true }).click();
  const restored = await completeSave(page), actual = restored.entities.find((entity): entity is Entity<'group'> => entity.id === groups[0]!.id && entity.kind === 'group')!;
  expect(actual.data.parentId).toBe(groups[124]!.id);
  expect(actual.data.members).toEqual([...people.slice(0, 123), people[124]!, people[125]!].map(person => person.id));
  expect(restored.entities.filter(entity => entity.kind === 'character')).toEqual(people);
  expect(restored.entities.filter(entity => entity.kind === 'group' && entity.id !== groups[0]!.id)).toEqual(groups.slice(1));
});

test('125別名の後半を明示公開名として選び、検索変更でも選択IDを保持し原子保存と完全保存する', async ({ page }) => {
  const project = createProject('125別名の公開指定');
  const person = createEntity(project.projectId, 'character', '作者の登録名'); person.status = 'confirmed';
  person.data.aliases = Array.from({ length: 125 }, (_, i) => ({ id: newId(), text: `別名${String(i + 1).padStart(3, '0')}`, reading: '', validity: { worldRange: null, routeCondition: null, presentationAnchor: null }, audienceHolderIds: [], isPublicDefault: false }));
  const profile = createEntity(project.projectId, 'projection_profile', '明示公開名の投影', { audience: '閲覧者', includedIds: [person.id] });
  project.entities = [person, profile];
  await restore(page, project); await navigate(page, '年表');
  await page.getByRole('tab', { name: '世界・地図・履歴', exact: true }).click();
  await page.getByRole('tab', { name: '別名・正体・公開名', exact: true }).click();
  await page.getByLabel('別名を管理する対象', { exact: true }).selectOption(person.id);
  await page.getByLabel('公開名を指定する限定投影設定', { exact: true }).selectOption(profile.id);
  const alias = page.getByLabel('限定投影で公開する別名', { exact: true }), target = person.data.aliases[124]!;
  await expect(page.getByRole('button', { name: '限定投影へ公開名を指定', exact: true })).toBeDisabled();
  expect(await alias.locator('option').count()).toBeLessThanOrEqual(62);
  await page.getByLabel('限定投影で公開する別名を検索', { exact: true }).fill(target.id);
  await alias.selectOption(target.id);
  await page.getByLabel('限定投影で公開する別名を検索', { exact: true }).fill('別名001');
  await expect(alias).toHaveValue(target.id);
  expect(await alias.locator('option').count()).toBeLessThanOrEqual(62);
  await page.getByRole('button', { name: '限定投影へ公開名を指定', exact: true }).click();
  await page.getByRole('button', { name: '公開対象・家系・素材の設定を確認', exact: true }).click();
  await saved(page);
  await page.reload(); await open(page, profile.name); await saved(page);
  const restored = await completeSave(page), actual = restored.entities.find((entity): entity is Entity<'projection_profile'> => entity.id === profile.id && entity.kind === 'projection_profile')!;
  expect(actual.data.namePolicy).toEqual({ defaultPolicy: { mode: 'exclude' }, byEntityId: { [person.id]: { mode: 'alias', aliasId: target.id } } });
  expect(restored.entities.find(entity => entity.id === person.id)).toEqual(person);
});

test('125根拠の末尾を年表と関係表で開く・取消・交換し、同じ関係IDと全根拠順を完全保存する', async ({ page }) => {
  const project = createProject('大量の根拠を両方の画面で編集');
  const proofs = Array.from({ length: 126 }, (_, i) => createEntity(project.projectId, 'character', `根拠${String(i + 1).padStart(3, '0')}`));
  const events = [createEntity(project.projectId, 'event', '出発'), createEntity(project.projectId, 'event', '到着')];
  for (const entity of [...proofs, ...events]) entity.status = 'confirmed';
  const relation = { id: newId(), projectId: project.projectId, revision: '0', fromId: events[0]!.id, toId: events[1]!.id, relationType: 'causes', direction: 'forward' as const, validity: emptyValidity(), evidenceIds: proofs.slice(0, 125).map(entity => entity.id), status: 'confirmed' as const, visibility: 'private' as const };
  project.entities = [...events, ...proofs]; project.relations = [relation];
  await restore(page, project); await navigate(page, '年表');
  const openTimeline = async () => {
    await page.locator(`button[data-relation-id="${relation.id}"]`).click();
    return page.getByRole('dialog', { name: '年表の関係を編集', exact: true });
  };
  let modal = await openTimeline();
  await expect(modal.locator('.timeline-evidence-list > li')).toHaveCount(30);
  for (let i = 0; i < 4; i++) await modal.getByRole('navigation', { name: '年表関係の選択済み根拠のページ', exact: true }).getByRole('button', { name: '次のページ', exact: true }).click();
  await expect(modal.locator('.timeline-evidence-list > li')).toHaveCount(5);
  await modal.getByRole('button', { name: '根拠125を開く', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('根拠125');
  await page.locator('.detail-panel').getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  modal = await openTimeline(); await expect(modal.locator('.timeline-evidence-list > li')).toHaveCount(5);
  await modal.getByRole('button', { name: '根拠125を根拠から外す', exact: true }).click();
  await modal.getByRole('button', { name: '中止', exact: true }).click();
  modal = await openTimeline(); await expect(modal.getByRole('button', { name: '根拠125を開く', exact: true })).toBeVisible();
  await modal.getByRole('button', { name: '根拠125を根拠から外す', exact: true }).click();
  await modal.getByLabel('関係の根拠を検索', { exact: true }).fill(proofs[125]!.id);
  await modal.getByRole('button', { name: '根拠126を根拠に追加', exact: true }).click();
  await expect(modal.getByRole('button', { name: '根拠126を開く', exact: true })).toBeVisible();
  await modal.getByRole('button', { name: '関係を保存', exact: true }).click(); await expect(modal).toHaveCount(0);
  await page.getByRole('tab', { name: '関係表・図', exact: true }).click();
  const openRelation = async () => {
    await page.locator(`.world-relation-table article[data-relation-id="${relation.id}"] .world-relation-meaning`).click();
    return page.getByRole('dialog', { name: '意味付きの関係を編集', exact: true });
  };
  modal = await openRelation();
  await expect(modal.locator('.world-evidence ul > li')).toHaveCount(30);
  for (let i = 0; i < 4; i++) await modal.getByRole('navigation', { name: '選択済みの根拠のページ', exact: true }).getByRole('button', { name: '次のページ', exact: true }).click();
  await expect(modal.locator('.world-evidence ul > li')).toHaveCount(5);
  await modal.getByRole('button', { name: '根拠124を根拠から外す', exact: true }).click();
  await modal.getByLabel('根拠として追加する情報の候補を検索', { exact: true }).fill(proofs[124]!.id);
  await modal.getByLabel('根拠として追加する情報', { exact: true }).selectOption(proofs[124]!.id);
  await expect(modal.locator('.world-evidence')).toContainText('根拠125');
  await modal.getByRole('button', { name: '関係を保存', exact: true }).click(); await expect(modal).toHaveCount(0);
  await page.reload(); await navigate(page, '年表'); await page.getByRole('tab', { name: '関係表・図', exact: true }).click();
  modal = await openRelation(); await expect(modal.locator('.world-evidence ul > li')).toHaveCount(5);
  await expect(modal.locator('.world-evidence')).toContainText('根拠126'); await expect(modal.locator('.world-evidence')).toContainText('根拠125');
  await modal.getByRole('button', { name: '中止', exact: true }).click();
  const restored = await completeSave(page);
  expect(restored.relations).toHaveLength(1);
  const { revision: _revision, ...expectedRelation } = relation;
  expect(restored.relations[0]).toMatchObject({ ...expectedRelation, evidenceIds: [...proofs.slice(0, 123).map(entity => entity.id), proofs[125]!.id, proofs[124]!.id] });
  expect(restored.entities).toEqual(project.entities);
});

test('派生関係の126根拠を後半まで閲覧し、出所編集・保存・再読込でも作者の125参照を保つ', async ({ page }) => {
  const project = createProject('派生した関係の根拠を開く');
  const owner = createEntity(project.projectId, 'character', '所有者');
  const itemType = createEntity(project.projectId, 'item', '鍵の種類', { itemMode: 'type' });
  const item = createEntity(project.projectId, 'item', '鍵の個体', { itemMode: 'instance', typeId: itemType.id });
  const proofs = Array.from({ length: 125 }, (_, i) => createEntity(project.projectId, 'source', `所有根拠${String(i + 1).padStart(3, '0')}`, { sourceType: 'observation', locator: `本人観測${i + 1}`, redistributionAllowed: false }));
  const assertion = createEntity(project.projectId, 'assertion', '所有の記録', { subjectId: item.id, predicate: 'owner', value: { type: 'ref', value: owner.id }, truthKind: 'author_truth', sourceIds: proofs.map(entity => entity.id), validity: emptyValidity() });
  project.entities = [owner, itemType, item, ...proofs, assertion]; for (const entity of project.entities) entity.status = 'confirmed';
  await restore(page, project); await navigate(page, '年表'); await page.getByRole('tab', { name: '関係表・図', exact: true }).click();
  const edge = page.locator('.world-relation-table article').filter({ has: page.getByRole('button', { name: '記録 · owner', exact: false }) });
  await edge.getByRole('button', { name: owner.name, exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue(owner.name);
  await page.getByLabel('中心にする情報', { exact: true }).selectOption('');
  await edge.locator('.world-relation-meaning').click();
  const modal = page.getByRole('dialog', { name: '元情報からの関係', exact: true });
  await expect(modal.locator('ul > li')).toHaveCount(30);
  for (let i = 0; i < 4; i++) await modal.getByRole('navigation', { name: '元情報の関係の根拠のページ', exact: true }).getByRole('button', { name: '次のページ', exact: true }).click();
  await expect(modal.locator('ul > li')).toHaveCount(6);
  await modal.getByRole('button', { name: '所有根拠125', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('所有根拠125');
  await modal.getByRole('button', { name: '所有根拠124', exact: true }).click();
  await modal.getByRole('button', { name: '閉じる', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('所有根拠124');
  await page.locator('.detail-panel').getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('所有根拠125');
  await expect(page.getByLabel('中心にする情報', { exact: true })).toHaveValue('');
  await page.locator('.detail-panel').getByLabel('名前', { exact: true }).fill('確認した所有根拠125'); await saved(page);
  await page.locator('.detail-panel').getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue(owner.name);
  await expect(page.getByLabel('中心にする情報', { exact: true })).toHaveValue('');
  await edge.locator('.world-relation-meaning').click(); await expect(modal.locator('ul > li')).toHaveCount(6);
  await expect(modal.getByRole('button', { name: '確認した所有根拠125', exact: true })).toBeVisible();
  await modal.getByRole('button', { name: '元情報を編集', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue(assertion.name);
  await page.getByLabel('中心にする情報', { exact: true }).selectOption('');
  await page.getByLabel('関係を検索', { exact: true }).fill('確認した所有根拠125');
  await page.locator('.world-relation-table').getByRole('button', { name: '確認した所有根拠125', exact: true }).click();
  await expect(page.getByLabel('中心にする情報', { exact: true })).toHaveValue(proofs[124]!.id);
  await page.reload();
  const restored = await completeSave(page);
  expect(restored.entities.find(entity => entity.id === assertion.id)).toEqual(assertion);
  expect(restored.entities.find(entity => entity.id === proofs[124]!.id)).toMatchObject({ id: proofs[124]!.id, name: '確認した所有根拠125', data: proofs[124]!.data });
  expect(restored.entities.filter(entity => entity.id !== proofs[124]!.id)).toEqual(project.entities.filter(entity => entity.id !== proofs[124]!.id));
});

test('日時影響と世界確認の129根拠を分割して開き、取消・確定・再読込でも旧版のtickと根拠を動かさない', async ({ page }) => {
  const project = createProject('移動の影響から末尾の根拠を開く');
  const actor = createEntity(project.projectId, 'character', '移動する人物');
  const start = createEntity(project.projectId, 'place', '起点'), end = createEntity(project.projectId, 'place', '終点');
  const proofs = Array.from({ length: 125 }, (_, i) => createEntity(project.projectId, 'note', `移動根拠${String(i + 1).padStart(3, '0')}`));
  const route = createEntity(project.projectId, 'travel_route', '徒歩経路', { fromPlaceId: start.id, toPlaceId: end.id, method: '徒歩', minimumTicks: '200', maximumTicks: '400', evidence: proofs.map(entity => entity.id), validity: emptyValidity() });
  const first = createEntity(project.projectId, 'event', '起点での行動', { time: { mode: 'instant', calendarId: project.calendarId, at: '0' }, laneRole: 'participants', participants: [{ characterId: actor.id, role: 'actor' }], locationId: start.id });
  const second = createEntity(project.projectId, 'event', '終点での行動', { time: { mode: 'instant', calendarId: project.calendarId, at: '300' }, laneRole: 'participants', participants: [{ characterId: actor.id, role: 'actor' }], locationId: end.id });
  project.entities = [actor, start, end, ...proofs, route, first, second]; for (const entity of project.entities) entity.status = 'confirmed';
  await snapshot(project); await restore(page, project); await navigate(page, '年表');
  await page.locator('[aria-label="年表の表示"]').getByRole('button', { name: '出来事一覧', exact: true }).click();
  await page.locator(`button[data-event-id="${second.id}"]`).click();
  const openTime = async () => { await page.getByRole('button', { name: '選択した出来事の日時・制約', exact: true }).click(); return page.getByRole('dialog', { name: `日時・前後関係 · ${second.name}`, exact: true }); };
  let modal = await openTime();
  const preview = async () => {
    await modal.getByLabel('出来事の世界内tick', { exact: true }).fill('100');
    await modal.getByRole('button', { name: '変更前の影響を確認', exact: true }).click();
    await modal.getByText('年齢・所属・移動・関連情報への影響を確認', { exact: true }).click();
    return modal.locator('.world-check-candidate').filter({ hasText: '最低所要時間より短い候補' });
  };
  let candidate = await preview(); await expect(candidate.locator('[data-windowed-list="候補の根拠"] > button')).toHaveCount(30);
  for (let i = 0; i < 4; i++) await candidate.getByRole('navigation', { name: '候補の根拠のページ', exact: true }).getByRole('button', { name: '次のページ', exact: true }).click();
  await expect(candidate.locator('[data-windowed-list="候補の根拠"] > button')).toHaveCount(9);
  await candidate.getByRole('button', { name: '移動根拠125の根拠', exact: true }).click();
  await modal.getByRole('button', { name: '変更を中止', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('移動根拠125');
  await page.locator('.detail-panel').getByRole('button', { name: '詳細を閉じる', exact: true }).click();
  await page.locator(`button[data-event-id="${second.id}"]`).click(); modal = await openTime();
  await expect(modal.getByLabel('出来事の世界内tick', { exact: true })).toHaveValue('300');
  candidate = await preview(); await expect(candidate.locator('[data-windowed-list="候補の根拠"] > button')).toHaveCount(9);
  await modal.getByRole('button', { name: '差分を一括確定', exact: true }).click(); await expect(modal).toHaveCount(0);
  await page.getByRole('tab', { name: '世界・地図・履歴', exact: true }).click(); await page.getByRole('tab', { name: '世界時点の確認候補', exact: true }).click();
  candidate = page.locator('#world-tab-checks .world-check-candidate').filter({ hasText: '最低所要時間より短い候補' });
  await expect(candidate.locator('[data-windowed-list="候補の根拠"] > button')).toHaveCount(30);
  for (let i = 0; i < 4; i++) await candidate.getByRole('navigation', { name: '候補の根拠のページ', exact: true }).getByRole('button', { name: '次のページ', exact: true }).click();
  await candidate.getByRole('button', { name: '移動根拠125 · 根拠', exact: true }).click();
  await expect(page.locator('.detail-panel').getByLabel('名前', { exact: true })).toHaveValue('移動根拠125');
  await page.reload(); const restored = await completeSave(page);
  expect(restored.snapshots).toEqual(project.snapshots); expect(restored.mainStart).toBe(project.mainStart); expect(restored.calendars).toEqual(project.calendars);
  const expected = structuredClone(project.entities); const changed = expected.find(entity => entity.id === second.id)!;
  if (changed.kind !== 'event') throw new Error('Expected event'); changed.data.time = { mode: 'instant', calendarId: project.calendarId, at: '100' };
  const actual = restored.entities.find(entity => entity.id === second.id)!; const { revision: _revision, updatedAt: _updatedAt, ...expectedChanged } = changed; expect(actual).toMatchObject(expectedChanged);
  expect(Number(actual.revision)).toBeGreaterThan(Number(second.revision)); expect(Date.parse(actual.updatedAt)).toBeGreaterThanOrEqual(Date.parse(second.updatedAt));
  expect(restored.entities.filter(entity => entity.id !== second.id)).toEqual(project.entities.filter(entity => entity.id !== second.id));
});
