import {expect,it} from 'vitest';
import {createEntity,createProject,emptyRuntimeState,validateProject} from '../src/domain/model';
import {stateMeaningCandidates} from '../src/domain/stateMeaning';
import {applyEffectsAtomic,initializeRuntimeState} from '../src/domain/conditions';
it('AT-F37 suggests one enum for alive/dead while preserving unknown and refusing wrong types and forbidden integer bounds atomically',()=>{
 const p=createProject('状態の型'),alive=createEntity(p.projectId,'variable','生存状態',{key:'alive_state',valueType:'enum',allowed:{values:['存命','死亡']},initial:{type:'enum',value:'存命'}}),dead=createEntity(p.projectId,'variable','死亡',{key:'dead',valueType:'boolean',initial:{type:'unknown',value:null,reason:'未設定'}}),count=createEntity(p.projectId,'variable','所持数',{key:'count',valueType:'integer',allowed:{min:0,max:3},initial:{type:'integer',value:0}});p.entities.push(alive,dead,count);expect(validateProject(p).ok).toBe(true);expect(stateMeaningCandidates(p,alive).some(c=>c.relationship==='same_state'&&c.variableId===alive.id)).toBe(true);expect(stateMeaningCandidates(p,dead)).toEqual(expect.arrayContaining([expect.objectContaining({variableId:alive.id,value:{type:'enum',value:'死亡'},relationship:'same_state'})]));
 for(const e of p.entities)e.status='confirmed';const state=initializeRuntimeState(p),before=structuredClone(state);expect(state.variableValues[dead.id]).toMatchObject({type:'unknown',value:null});expect(applyEffectsAtomic(state,[{operation:'set',targetId:alive.id,value:{type:'enum',value:'死亡'}}],{state,entities:p.entities})).toMatchObject({ok:true,state:{variableValues:{[alive.id]:{type:'enum',value:'死亡'}}}});for(const value of [{type:'enum',value:'幽霊'},{type:'integer',value:1}]){const result=applyEffectsAtomic(state,[{operation:'set',targetId:alive.id,value},{operation:'set',targetId:count.id,value:{type:'integer',value:2}}] as any,{state,entities:p.entities});expect(result.ok).toBe(false);expect(state).toEqual(before);}expect(applyEffectsAtomic(state,[{operation:'set',targetId:count.id,value:{type:'integer',value:4}}] as any,{state,entities:p.entities}).ok).toBe(false);expect(state).toEqual(before);
 const rejected={...alive,status:'rejected' as const};expect(stateMeaningCandidates({...p,entities:[rejected,dead,count]},dead)).toEqual([]);expect(stateMeaningCandidates({...p,entities:[{...alive,data:{...alive.data,scope:'chapter'}},dead,count]},dead)).toEqual([]);expect(emptyRuntimeState(p.projectId).variableValues).toEqual({});
});
