import {authorDraftSummary,inputRecoveryBytes,parseInputRecovery,type InputRecovery} from './inputRecovery';
import {ScopedEditorPanel} from './ScopedEditorPanel';
import {ScopedEditorStore} from '../sync/editorStore';
import {SharedPortal} from './SharedPortal';
import {RemoteWorks,type RemoteWork} from './RemoteWorks';
import {useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import App from '../App';
import {ScenarioStore,scenarioStore} from '../storage';
import {DedicatedSupabaseClient,type DedicatedSyncConfig} from '../sync/supabaseClient';
import {authorBusy,ScenarioStoreProvider,purgeAuthorMemory} from './StoreContext';
import {SyncClientContext} from './SyncContext';
import {downloadBytes,safeFileName} from './components';
import {readWorkspaceDrafts,workspaceDraftKey,flushWorkspaceDrafts} from './workspaceDrafts';
import {valueHash} from '../sync/protocol';
const subscribeNone=()=>()=>{},guestSession={accountId:null,authenticated:false,generation:'guest'};
function storedConfig():DedicatedSyncConfig|null{try{const raw=localStorage.getItem('scenario-dedicated-sync:v1');return raw?JSON.parse(raw):null;}catch{return null;}}
function eraseLocalAccountInputs(account:string){const prefixes=[account+':','scenario-author-input:'+account+':','scenario-timeline:v1:'+account+':','scenario-world-map:v1:'+account+':','scenario-world-map-draft:v1:'+account+':','scenario-reader:'+account+':','scenario-hierarchy-open:v1:'+account+':','scenario-world:v1:'+account+':','scenario-reaction-draft:v1:'+account+':','scenario-link-candidate-suppressions:v1:'+encodeURIComponent(account+':'),'scenario-workspace-marks:v1:'+encodeURIComponent(account)+':','scenario-reuse-draft:v1:'+account+':','scenario-flow-hierarchy:'+account+':','scenario-history-selection:v1:'+account+':','scenario-reconfirmation-selection:'+account+':','scenario-chapter-reading:v1:'+account+':','scenario-list-position:v1:'+account+':','scenario-workspace-view:v1:'+encodeURIComponent(account)+':','scenario-relation-view:v1:'+encodeURIComponent(account)+':'];for(const key of Object.keys(localStorage))if(prefixes.some(p=>key.startsWith(p))||[workspaceDraftKey(account),`scenario-last-project:${account}`].includes(key))localStorage.removeItem(key);}
export function AccountWorkspace(){
 const [client,setClient]=useState<DedicatedSupabaseClient|null>(()=>{try{const config=storedConfig();return config?new DedicatedSupabaseClient(config):null;}catch{return null;}}),session=useSyncExternalStore(client?.subscribe??subscribeNone,()=>client?.getSession().generation??'guest'),actual=client?.getSession()??guestSession;
 const [account,setAccount]=useState<string|null>(()=>localStorage.getItem('scenario-last-account')),[store,setStore]=useState(()=>{const last=localStorage.getItem('scenario-last-account');return last?new ScenarioStore({accountId:last}):scenarioStore;}),[open,setOpen]=useState(false),[endpoint,setEndpoint]=useState(storedConfig()?.url??''),[key,setKey]=useState(storedConfig()?.publishableKey??''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmation,setConfirmation]=useState(''),[logoutReview,setLogoutReview]=useState<{fingerprint:string;rows:{id:string;name:string;pending:number}[];inputs:number}|null>(null);
 const lock=useRef(false),[online,setOnline]=useState(navigator.onLine),[area,setArea]=useState(new URL(location.href).searchParams.has('shared')?'shared':'author'),[access,setAccess]=useState<string|null>(null),[reload,setReload]=useState(0),[editorId,setEditorId]=useState(''),[inputRestore,setInputRestore]=useState<{file:InputRecovery;fingerprint:string;existingTools:Awaited<ReturnType<ScenarioStore['listAuthorToolDrafts']>>;existingWorkspace:Awaited<ReturnType<ScenarioStore['getWorkspaceInputs']>>}|null>(null);
 const controls=useRef<HTMLDivElement>(null),root=useRef<HTMLDivElement>(null),viewIntent=useRef({signature:'',epoch:0});
 const viewSignature=JSON.stringify([account,area,editorId,reload]);if(viewIntent.current.signature!==viewSignature)viewIntent.current={signature:viewSignature,epoch:viewIntent.current.epoch+1};const remoteEpoch=viewIntent.current.epoch;
 useLayoutEffect(()=>{const update=()=>root.current?.style.setProperty('--account-controls-height',`${controls.current?.getBoundingClientRect().height??0}px`);update();const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);if(controls.current)observer?.observe(controls.current);window.addEventListener('resize',update);return()=>{observer?.disconnect();window.removeEventListener('resize',update);};},[]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine),focus=()=>{if(navigator.onLine&&account&&!authorBusy(account)&&!store.pendingOperations)setReload(v=>v+1);};window.addEventListener('online',update);window.addEventListener('offline',update);window.addEventListener('focus',focus);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('focus',focus);};},[account,store]);
 useEffect(()=>{setAccess(null);if(!account||!online)return;if(!client||actual.accountId!==account||!actual.authenticated)return;let live=true;const expected=client.getSession();void client.request<RemoteWork[]>('projects',{},expected).then(works=>{if(!live)return;store.setAuthorAccess(Object.fromEntries(works.map(w=>[w.projectId,w.role])));setAccess(expected.generation);}).catch(cause=>{if(live)setError((cause as Error).message);});return()=>{live=false;};},[account,store,session,online,reload]);
 function enterAccount(id:string){if(account!==id){setAccount(id);setStore(new ScenarioStore({accountId:id}));}localStorage.setItem('scenario-last-account',id);setLogoutReview(null);}
 async function run(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await task();}catch(cause){setError((cause as Error).message||'ACCOUNT_ACTION_FAILED');}finally{lock.current=false;setBusy(false);}}
 async function fingerprint(){await flushWorkspaceDrafts(store);const works=await store.listProjects(),editorStore=new ScopedEditorStore(account!),editorWorks=await editorStore.list(),tools=await store.listAuthorToolDrafts(),rows=await Promise.all(works.map(async p=>({id:p.projectId,name:p.name,revision:p.revision,state:await store.getSaveState(p.projectId)}))),persistedWorkspace=await store.getWorkspaceInputs(),workspace=persistedWorkspace??readWorkspaceDrafts(account);editorStore.close();return {hash:await valueHash({editorWorks,rows,tools:authorDraftSummary(tools),workspace}),rows:rows.map(p=>({id:p.id,name:p.name,pending:p.state.pendingCount+p.state.recoveredPendingCount+p.state.pendingAssetCount})),tools,workspace,persistedWorkspace,editorWorks};}
 async function examineLogout(){const result=await fingerprint();setLogoutReview({fingerprint:result.hash,rows:result.rows,inputs:result.tools.length+Object.keys(result.workspace.drafts).length+Object.keys(result.workspace.settingsDrafts).length+Object.keys(result.workspace.alternativeDrafts).length+Object.keys(result.workspace.jsonBuffers).length});setConfirmation('');}
 async function backupInputs(){const state=await fingerprint(),bytes=await inputRecoveryBytes(account!,state.workspace,state.tools,state.editorWorks);downloadBytes(new Uint8Array(bytes),`scenario-unsaved-inputs-${Date.now()}.json`,'application/json');setNotice('入力・素材下書き・限定編集証跡を持出しました。作品本体は作品ごとの完全保存で保持してください。');}
 async function logout(){if(!client||!account||!logoutReview||confirmation!==account)throw Error('LOGOUT_REVIEW_REQUIRED');const fresh=await fingerprint();if(fresh.hash!==logoutReview.fingerprint){setLogoutReview(null);throw Error('ログアウト確認後に保存・入力が変わりました。更新された待ちと入力を再確認してください。');}if(authorBusy(account)||store.pendingOperations)throw Error('進行中の保存・検査があります。対象画面で完了を確認してから再確認してください。');if(client.getSession().authenticated)await client.signOut();else client.expire();const after=await fingerprint();if(after.hash!==logoutReview.fingerprint||authorBusy(account)||store.pendingOperations)throw Error('認証の失効中に入力・保存が進みました。キャッシュを保持しました。再認証して更新した入力を確認してください。');store.close();await store.deleteDatabase();await new ScopedEditorStore(account).delete();eraseLocalAccountInputs(account);localStorage.removeItem('scenario-last-account');purgeAuthorMemory(account);setAccount(null);setStore(scenarioStore);setLogoutReview(null);setConfirmation('');setNotice('このアカウントの認証と端末内作者キャッシュを消去しました。接続先の正本は保持されています。');}
 const connected=!!account&&(actual.authenticated&&actual.accountId===account||!online);
 return <SyncClientContext.Provider value={client}><div className="account-workspace" ref={root}><div className="account-controls" ref={controls}><div className="account-toolbar"><button className="button secondary small" onClick={()=>setOpen(!open)}>アカウント・専用同期</button><span>{account?`アカウント領域 ${account}`:'この端末の作品'}{account&&!actual.authenticated?' · 再認証待ち':''}</span>{account&&<button className="button subtle small" disabled={busy} onClick={()=>{setAccount(null);setStore(scenarioStore);setLogoutReview(null);setNotice('アカウント領域の保存待ち・入力を保持して端末内作品へ移動しました。ログアウトはアカウント欄から確認できます。');}}>端末内の作品を開く</button>}</div>
 {open&&<section className="settings-card" aria-label="アカウントと専用接続先"><h2>専用接続先とアカウント</h2><p>端末内の作品はログインせず使えます。アカウント領域への移動は完全保存の「新規／複製復元」で明示します。同名の作品を自動統合しません。</p><fieldset disabled={busy}><label>専用Supabase URL<input aria-label="専用Supabase URL" value={endpoint} onChange={e=>setEndpoint(e.target.value)}/></label><label>公開用APIキー<input aria-label="公開用APIキー" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="button secondary" disabled={!!actual.authenticated} onClick={()=>void run(async()=>{const next=new DedicatedSupabaseClient({url:endpoint,publishableKey:key,allowLocalHTTP:location.hostname==='localhost'||location.hostname==='127.0.0.1'});localStorage.setItem('scenario-dedicated-sync:v1',JSON.stringify(next.config));setClient(next);setNotice('専用接続設定を端末に保存しました。新規プロジェクト・課金・DB変更は実行していません。');})}>接続設定を保持</button><label>メール<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>パスワード<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary" disabled={!client||!!actual.authenticated} onClick={()=>void run(async()=>{const current=await client!.signIn(email,password);setPassword('');const id=current.accountId!;enterAccount(id);setNotice('認証したアカウントの領域を開きました。');})}>認証してアカウント領域を開く</button>{actual.authenticated&&<button className="button secondary" onClick={()=>{const id=actual.accountId!;enterAccount(id);}}>認証中の領域を開く</button>}</fieldset>
 {account&&<><button className="button secondary" disabled={busy} onClick={()=>void run(examineLogout)}>ログアウト前の保存待ち・入力を確認</button><button className="button secondary" disabled={busy} onClick={()=>void run(backupInputs)}>未保存入力をファイルに持出す</button><label>同じアカウントの入力を復元<input type="file" accept="application/json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(!file)return;void run(async()=>{if(file.size>64*1024*1024)throw Error('INPUT_BACKUP_LIMIT');const input=parseInputRecovery(new Uint8Array(await file.arrayBuffer()),account),before=await fingerprint();setInputRestore({file:input,fingerprint:before.hash,existingTools:before.tools,existingWorkspace:before.persistedWorkspace});setNotice('保存待ち・入力の現在版と持出し入力を確認してください。作品本体・権限・承認は変更しません。');});}}/></label>{inputRestore&&<div><p>復元する基底付きツール入力 {inputRestore.file.tools.length}件。現在の入力は持出してから、置換する入力を確認してください。限定編集の証跡 {inputRestore.file.editorWorks.length}件は再接続待ちとしてファイルに保持され、権限再確認後に限定編集画面で再開します。</p><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{const plan=inputRestore,fresh=await fingerprint();if(fresh.hash!==plan.fingerprint||authorBusy(account)||store.pendingOperations)throw Error('確認後に入力・保存待ちが変わりました。再確認してください。');await backupInputs();await store.restoreAuthorInputs({tools:plan.file.tools,workspace:plan.file.workspace},{tools:plan.existingTools,workspace:plan.existingWorkspace});let cacheFailed=false;try{localStorage.setItem(workspaceDraftKey(account),JSON.stringify(plan.file.workspace));for(const tool of plan.file.tools)localStorage.setItem(`scenario-author-input:${tool.key}`,JSON.stringify({key:tool.key,projectId:tool.projectId,baseRevision:tool.baseRevision,fields:tool.fields}));}catch{cacheFailed=true;}purgeAuthorMemory(account);setInputRestore(null);setReload(v=>v+1);setNotice('現在の入力を持出し、作品ごとの基底付き入力を一括復元しました。確認計画と承認は再実行してください。'+(cacheFailed?' 表示用キャッシュの保存はできませんでした。確定したIndexedDBの入力から再開します。':''));})}>現在入力を持出して確認した入力を復元</button></div>}{logoutReview&&<div><p>入力 {logoutReview.inputs}件。ログアウトでこの端末のアカウント作者キャッシュを消去します。同期、作品ごとの完全保存、入力持出しを行うか、残りを明示的に破棄してください。</p>{logoutReview.rows.map(row=><p key={row.id}>{row.name} · 保存待ち {row.pending}件<button className="button secondary small" disabled={busy} onClick={()=>void run(async()=>{downloadBytes(new Uint8Array(await store.exportProject(row.id)),`${safeFileName(row.name)}.scenario`,'application/octet-stream');setNotice('素材bytesを含む完全保存ファイルを作成しました。Files等で保存先を確認してください。');})}>作品を完全保存</button></p>)}<label>キャッシュ消去対象のアカウントID<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button danger" disabled={busy||confirmation!==account} onClick={()=>void run(logout)}>確認した残りを破棄してログアウト</button></div>}</>}{busy&&<p role="status">アカウント操作中…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>}
 {account&&<div className="section-tabs"><button onClick={()=>setArea('author')}>自分の作品</button><button onClick={()=>setArea('remote')}>接続先から取得</button><button onClick={()=>setArea('shared')}>限定版の閲覧・指摘</button></div>}</div><div inert={busy}>{account&&!connected?<section className="settings-card"><h2>再認証が必要です</h2><p>保存待ち・入力を保持しています。アカウント欄で再認証するか、入力と完全保存をファイルへ持ち出せます。</p></section>:<ScenarioStoreProvider key={account??'guest'} store={store}>{area==='editor'&&account?<ScopedEditorPanel key={`${editorId}:${reload}`} projectId={editorId}/>:area==='shared'&&account?<SharedPortal/>:area==='remote'&&account?<RemoteWorks onImported={()=>{if(viewIntent.current.epoch===remoteEpoch){setReload(v=>v+1);setArea('author');}}} onEdit={id=>{setEditorId(id);setArea('editor');}}/>:account&&online&&access!==actual.generation?<p role="status">現在の権限を確認しています。端末キャッシュと入力は保持しています。</p>:<App key={`${account??'guest'}:${reload}:${access??'offline'}`}/>}</ScenarioStoreProvider>}
 </div><span hidden>{session}</span></div></SyncClientContext.Provider>;
}
