import {useScenarioStore,useAuthorScope} from './StoreContext';
import { useEffect } from 'react';
import type { ProjectContent,ProjectData } from '../domain/types';
import { previewGameReceiptImport,confirmGameReceiptImport,parseGameReceipt } from '../domain/gameHandoff';
import { authorField,useAuthorField,useAuthorInput,flushAuthorDraft,acknowledgeAuthorDraft,AuthorDraftNotice } from './authorOperation';
import { PagedSelect } from './PagedSelect';
export function GameHandoffPanel({project,worldSnapshots,onSaveProject}:{project:ProjectData;worldSnapshots:Record<string,ProjectContent>;onSaveProject:(p:ProjectData,r:string)=>Promise<ProjectData>}){
  const scenarioStore=useScenarioStore();
 const key=useAuthorScope(`game-handoff:${project.projectId}`),[raw,setRaw]=useAuthorInput(key,'raw','',project.projectId,project.revision),[profile,setProfile]=useAuthorInput(key,'profile','',project.projectId,project.revision),[version,setVersion]=useAuthorInput(key,'version','',project.projectId,project.revision),[plan,setPlan]=useAuthorField<Awaited<ReturnType<typeof previewGameReceiptImport>>|null>(key,'plan',null),[busy,setBusy]=useAuthorField(key,'busy',false),[error,setError]=useAuthorField(key,'error',''),[saved,setSaved]=useAuthorField<string|null>(key,'saved',null);
 const [ack,setAck]=useAuthorField<string|null>(key,'pendingAck',null);
 function release(){setBusy(false);const next=authorField<File|null>(key,'queuedFile');if(next){setQueued(null);void read(next);}}
 useEffect(()=>{if(ack&&authorField(key,'pendingAck')===ack&&BigInt(project.revision)>=BigInt(ack)){setAck(null);release();}},[project.revision,ack]);
 async function read(file:File){if(authorField<boolean>(key,'busy')){setQueued(file);return;}setBusy(true);try{if(file.size>1024*1024)throw Error('受領証跡は1 MiB以下で選んでください。');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());parseGameReceipt(new TextEncoder().encode(text));setRaw(text);setPlan(null);setError('');await flushAuthorDraft(key);}catch(cause){setError((cause as Error).message);}finally{release();}}
 const [,setQueued]=useAuthorField<File|null>(key,'queuedFile',null);
 async function inspect(){if(authorField<boolean>(key,'busy'))return;setBusy(true);const captured=structuredClone(project),request={projectionProfileId:profile,...version?{targetVersionId:version}:{targetRevision:project.revision},worldSnapshots:structuredClone(worldSnapshots)},submitted=raw;try{await flushAuthorDraft(key);const assetBytes:Record<string,Uint8Array>={};for(const e of [...captured.entities,...captured.snapshots.flatMap(pin=>pin.content.entities),...Object.values(request.worldSnapshots).flatMap(world=>world.entities)])if(e.kind==='attachment'){const bytes=await scenarioStore.getAsset(e.data.contentHash);if(bytes)assetBytes[e.data.contentHash]=bytes;}const worldPins=Object.values(await scenarioStore.listWorldSnapshots()).flatMap(world=>world.snapshots);setPlan(await previewGameReceiptImport(captured,parseGameReceipt(new TextEncoder().encode(submitted)),{...request,worldPins,assetBytes}));setError('');}catch(cause){setError((cause as Error).message);}finally{release();}}
 async function save(){if(!plan||authorField<boolean>(key,'busy'))return;setBusy(true);try{const result=await onSaveProject(await confirmGameReceiptImport(project,plan),'受領hash・公開ID・実結果を照合したゲーム証跡を原子保存');acknowledgeAuthorDraft(key,result.revision);setAck(result.revision);setSaved(result.revision);setPlan(null);}catch(cause){setError((cause as Error).message);release();}}
 const edition=version?project.snapshots.find(pin=>pin.id===version)?.content:project;
 return <details className="settings-card game-handoff"><summary>ゲーム受領と実結果を取り込む</summary><p><a href={`${import.meta.env.BASE_URL}examples/browser-game/index.html`} target="_blank" rel="noopener noreferrer">独立ブラウザーゲーム受取例を開く</a>。汎用ランタイムJSONを受取例へ渡し、ゲーム側で保存したgame-receipt.jsonを戻します。</p><AuthorDraftNotice scope={key} revision={project.revision}/><fieldset disabled={busy}><PagedSelect label="受領対象の作品版" scope={`${key}:versions`} items={project.snapshots.map(pin=>({id:pin.id,label:pin.versionLabel}))} value={version} onChange={id=>{setVersion(id);setPlan(null);}} emptyLabel="現在稿"/><PagedSelect label="受渡しの公開範囲" scope={`${key}:profiles`} items={(edition?.entities??[]).filter(e=>e.kind==='projection_profile'&&!e.deletedAt).map(e=>({id:e.id,label:e.name}))} value={profile} onChange={id=>{setProfile(id);setPlan(null);}}/><label>ゲームの受領証跡<input type="file" accept=".json,application/json" aria-label="ゲームの受領証跡" onChange={event=>{const file=event.target.files?.[0];if(file)void read(file);}}/></label><label>受領証跡JSON<textarea aria-label="受領証跡JSON" value={raw} onChange={event=>{setRaw(event.target.value);setPlan(null);}}/></label><button disabled={!raw||!profile} onClick={()=>void inspect()}>受領hash・ID対応・実結果を検証</button>{plan&&<><p>対象revision {plan.baseRevision} · 実行証跡による分類 {plan.receipt.mode} · 管理元 {plan.receipt.receiverId} · 仕様 {plan.receipt.specification} · 結果 {plan.receipt.status}</p><p>受領hash {plan.receipt.packageHash}</p><button disabled={project.revision!==plan.baseRevision} onClick={()=>void save()}>検証したゲーム受領を保存</button></>}</fieldset>{saved&&<p role="status">ゲーム受領と実結果を正本のメモに保存し、現在の表示版を確認しました。</p>}{error&&<p role="alert">{error}</p>}</details>;
}
