import {useEffect} from 'react';
import type {ProjectData,Entity} from '../domain/types';
import {createEntity,textToRichText} from '../domain/model';
import {createWorldSnapshot} from '../domain/world';
import {resolveReuseContent} from '../domain/reuse';
import {adoptedRecord} from '../domain/adoption';
import {RichTextView,labelOf} from './Fields';
import {useAuthorField,authorField} from './authorOperation';
import {ListPager,useListWindow} from './ListWindow';
export function GameplayProductionLinks({project,onOpen,onSaveProject}:{project:ProjectData;onOpen:(id:string)=>void;onSaveProject?:(project:ProjectData,reason:string)=>Promise<ProjectData>}){
 const key=`gameplay-production:${project.projectId}`,[busy,setBusy]=useAuthorField(key,'busy',false),[error,setError]=useAuthorField(key,'error',''),[saved,setSaved]=useAuthorField<string|null>(key,'saved',null),rows=useListWindow({items:project.entities.filter(adoptedRecord).filter(entity=>['creative_brief','decision','gameplay_spec'].includes(entity.kind)),scope:key});
 let view=project;try{view=resolveReuseContent(project,project.snapshots);}catch{}
 useEffect(()=>{if(saved&&BigInt(project.revision)>=BigInt(saved)){setBusy(false);setSaved(null);}},[saved,project.revision]);
 async function review(entity:Entity<'gameplay_spec'>){if(!onSaveProject||authorField<boolean>(key,'busy'))return;setBusy(true);const captured=structuredClone(project),spec=structuredClone(entity),source=structuredClone(view.entities.find(entity=>entity.id===spec.data.sceneId));try{const candidate=await createWorldSnapshot(captured,'遊びと物語の差の確認対象版'),pin=candidate.snapshots.at(-1)!,record=createEntity(captured.projectId,'review',`${spec.name} · 遊びと物語の差の確認`,{target:spec.id,targetVersionId:pin.id,stage:'open',body:textToRichText(`物語: ${source?.kind==='scene'?[...source.data.summary??[],...source.data.body].map(block=>block.text).join('\n'):'対象場面未確認'}\nプレイ行動: ${spec.data.action.map(block=>block.text).join('\n')}\n必要機能: ${spec.data.mechanic??'未指定'}\n意図: ${spec.data.intentionalDifference??'未指定・確認が必要'}\n実装と執筆の工程状態を別々に確認する。`)});candidate.entities.push(record);const result=await onSaveProject(candidate,'遊びと物語の差を対象版付き確認候補へ保存');setSaved(result.revision);setError('');}catch(cause){setError((cause as Error).message);setBusy(false);}}
 return <div>{rows.items.map(entity=><article className="settings-card" key={entity.id}><button className="reference-link" onClick={()=>onOpen(entity.id)}>{labelOf(entity)}</button>{entity.kind==='creative_brief'?<><p>想定対象</p><RichTextView value={entity.data.targetAudience}/><p>届けたい体験・主題・作風・制作範囲</p>{[entity.data.experience,entity.data.theme,entity.data.tone,entity.data.scope].map((text,index)=><RichTextView key={index} value={text}/>)}{[...entity.data.deliverableIds??[],...entity.data.decisionIds??[]].map(id=><button key={id} onClick={()=>onOpen(id)}>成果物・判断 {labelOf(project.entities.find(entity=>entity.id===id))}</button>)}</>:entity.kind==='decision'?<><p>{entity.data.subject} · {entity.data.outcome} · 優先度 {entity.data.priority??'未指定'} · 対象版 {entity.data.targetVersionId}</p><RichTextView value={entity.data.reason}/></>:entity.kind==='gameplay_spec'?<><div className="gameplay-comparison"><section><h4>場面で提示する内容</h4><button onClick={()=>onOpen(entity.data.sceneId)}>{labelOf(view.entities.find(scene=>scene.id===entity.data.sceneId))}</button>{(()=>{const scene=view.entities.find(scene=>scene.id===entity.data.sceneId);return scene?.kind==='scene'?<RichTextView value={scene.data.summary??scene.data.body}/>:<p>対象場面未確認</p>;})()}</section><section><h4>プレイヤーが行う行動</h4><RichTextView value={entity.data.action}/><p>必要機能 {entity.data.mechanic??'未指定'} · 報酬 {entity.data.reward?JSON.stringify(entity.data.reward):'未指定'}</p>{entity.data.tutorial&&<><p>チュートリアル</p><RichTextView value={entity.data.tutorial}/></>}{entity.data.questId&&<button onClick={()=>onOpen(entity.data.questId!)}>対応クエスト</button>}</section></div><p>物語との意図した差 {entity.data.intentionalDifference??'未確認'}</p>{entity.data.taskIds?.map(id=>{const task=project.entities.find(entity=>entity.id===id);return <button key={id} onClick={()=>onOpen(id)}>{labelOf(task)} · {task?.kind==='production_task'?`${task.data.stage}/${task.data.progress}`:'対象作業未確認'}</button>;})}<button disabled={busy||!onSaveProject} onClick={()=>void review(entity)}>遊びと物語の差を確認候補へ保存</button></>:null}</article>)}<ListPager {...rows} label="企画・判断・プレイ行動"/>{error&&<p role="alert">{error}</p>}</div>;
}
