import { useState } from 'react';
import { ProductionReviewPanel } from './ProductionReviewPanel';
import { FlowHierarchy } from './FlowHierarchy';
import { ReactionBuilder } from './ReactionBuilder';
import type { ContentAnchor, Entity, EntityKind, ProjectData } from '../domain/types';
import { KIND_LABELS, getEntitiesByKind } from '../domain/model';
import { DATA_GROUPS } from './fieldSpecs';
import { dataOf, labelOf, describeCondition } from './Fields';
import { EmptyState, Icon, StatusBadge, fieldText, PROGRESS_LABELS } from './components';
import { timeLabel } from './Timeline';

export function EntityCards({ entities, project, selectedId, onSelect, emptyTitle = 'まだ情報がありません', onAdd }: { entities: Entity[]; project: ProjectData; selectedId: string | null; onSelect: (id: string) => void; emptyTitle?: string; onAdd?: () => void }) {
  const [page, setPage] = useState(0);
  const count = 60;
  const pageMax = Math.max(0, Math.ceil(entities.length / count) - 1);
  const currentPage = Math.min(page, pageMax);
  if (!entities.length) return <EmptyState title={emptyTitle} action={onAdd && <button type="button" className="button primary" onClick={onAdd}><Icon name="plus"/>追加する</button>}>名前だけの登録から、少しずつ内容を育てられます。</EmptyState>;
  return <><div className="entity-cards">{entities.slice(currentPage * count, (currentPage + 1) * count).map((e, i) => {
    const d = dataOf(e), desc = fieldText(d.summary) || fieldText(d.body) || fieldText(d.description) || fieldText(d.text) || fieldText(d.question);
    return <button type="button" key={e.id} className={`entity-card ${selectedId === e.id ? 'selected' : ''}`} onClick={() => onSelect(e.id)}><div className={`entity-avatar avatar-${e.kind}`}>{e.kind === 'character' ? Array.from(e.name)[0] || '人' : e.kind === 'scene' || e.kind === 'chapter' ? <span>{String(currentPage * count + i + 1).padStart(2, '0')}</span> : <Icon name={['variable', 'effect', 'assertion'].includes(e.kind) ? 'flag' : ['flow_graph', 'flow_node', 'flow_edge'].includes(e.kind) ? 'structure' : e.kind === 'event' ? 'timeline' : 'note'}/>}</div><div className="entity-card-copy"><div className="entity-card-heading"><h3>{labelOf(e)}</h3><StatusBadge status={e.status}/></div>{d.reading && <span className="reading-label">{d.reading}</span>}<p>{desc || '詳細はあとから補えます'}</p><div className="entity-card-meta"><span>{KIND_LABELS[e.kind]}</span>{e.kind === 'event' && <span>{timeLabel(d.time, project)}</span>}{e.kind === 'scene' && d.povId && <span>視点 · {labelOf(project.entities.find(v => v.id === d.povId))}</span>}{e.kind === 'chapter' && <span>{(d.sceneIds || []).length}場面</span>}{e.kind === 'variable' && <span>{d.key} · {d.initial?.type === 'unknown' ? '初期値未設定' : String(d.initial?.value)}</span>}{e.kind === 'flow_edge' && <span>{labelOf(project.entities.find(v => v.id === d.fromId))} → {typeof d.toId === 'string' ? labelOf(project.entities.find(v => v.id === d.toId)) : '未完成の行き先'}</span>}</div></div><span className="entity-card-arrow"><Icon name="arrow" size={18}/></span></button>;
  })}</div>{entities.length > count && <div className="pagination"><button className="button secondary small" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>前のページ</button><span>{currentPage + 1} / {pageMax + 1} · {entities.length}件</span><button className="button secondary small" disabled={currentPage === pageMax} onClick={() => setPage(currentPage + 1)}>次のページ</button></div>}</>;
}

export function KindPicker({ value, onChange, all = false }: { value: string; onChange: (kind: string) => void; all?: boolean }) {
  return <select className="kind-select" aria-label="情報の種類" value={value} onChange={e => onChange(e.target.value)}>{all && <option value="all">すべての種類</option>}{DATA_GROUPS.map(group => <optgroup key={group.label} label={group.label}>{group.kinds.map(kind => <option key={kind} value={kind}>{KIND_LABELS[kind as EntityKind]}</option>)}</optgroup>)}</select>;
}

export function ChapterList({ project, selectedId, onSelect, onAdd, onSave }: { project: ProjectData; selectedId: string | null; onSelect: (id: string) => void; onAdd: (kind: EntityKind, data?: Record<string, unknown>) => void; onSave: (entity: Entity) => Promise<Entity> }) {
  const chapters = getEntitiesByKind(project, 'chapter');
  const scenes = getEntitiesByKind(project, 'scene');
  const linked = new Set(chapters.flatMap(c => c.data.sceneIds));
  const [moveError, setMoveError] = useState('');
  if (!chapters.length && !scenes.length) return <EmptyState icon="structure" title="最初の章を書き始めましょう" action={<button className="button primary" onClick={() => onAdd('chapter')}><Icon name="plus"/>章を追加</button>}>場面と世界内の出来事を結び、本文を同じ場所で管理できます。</EmptyState>;
  return <div className="chapter-list">{moveError && <div className="error-notice" role="alert">{moveError}</div>}{chapters.map((chapter, chapterIndex) => <section className="chapter-section" key={chapter.id}><div className="chapter-heading"><button type="button" className="chapter-title" onClick={() => onSelect(chapter.id)}><span className="chapter-number">{String(chapterIndex + 1).padStart(2, '0')}</span><span><h3>{labelOf(chapter)}</h3><small>{chapter.data.sceneIds.length}場面 · {fieldText(chapter.data.summary) || '章の要約を追加できます'}</small></span></button><button className="button subtle small" onClick={() => onAdd('scene', { chapterId: chapter.id })}><Icon name="plus" size={16}/>場面</button></div><div className="scene-rows">{chapter.data.sceneIds.map((id, i) => { const scene = scenes.find(s => s.id === id); if (!scene) return <p className="field-error" key={id}>参照先の場面が見つかりません。</p>; return <div className={`scene-row ${selectedId === id ? 'selected' : ''}`} key={id}><button type="button" className="scene-open" onClick={() => onSelect(id)}><span className="scene-index">{i + 1}</span><span><strong>{labelOf(scene)}</strong><small>{fieldText(scene.data.summary) || (scene.data.body.length ? `${fieldText(scene.data.body).length}文字の本文` : '本文未入力')}</small></span><StatusBadge status={scene.status}/></button><div className="scene-move"><button type="button" className="icon-button small" aria-label={`${labelOf(scene)}を前へ`} disabled={i === 0} onClick={async () => { const ids = [...chapter.data.sceneIds]; [ids[i - 1], ids[i]] = [ids[i], ids[i - 1]]; try { await onSave({ ...chapter, data: { ...chapter.data, sceneIds: ids } }); setMoveError(''); } catch (e) { setMoveError((e as Error).message); } }}>↑</button><button type="button" className="icon-button small" aria-label={`${labelOf(scene)}を後へ`} disabled={i === chapter.data.sceneIds.length - 1} onClick={async () => { const ids = [...chapter.data.sceneIds]; [ids[i + 1], ids[i]] = [ids[i], ids[i + 1]]; try { await onSave({ ...chapter, data: { ...chapter.data, sceneIds: ids } }); setMoveError(''); } catch (e) { setMoveError((e as Error).message); } }}>↓</button></div></div>; })}{!chapter.data.sceneIds.length && <p className="chapter-empty">章の場面はまだありません。</p>}</div></section>)}{scenes.some(s => !linked.has(s.id)) && <section className="chapter-section"><div className="section-heading"><h3>章に未配置の場面</h3></div><EntityCards entities={scenes.filter(s => !linked.has(s.id))} project={project} selectedId={selectedId} onSelect={onSelect}/></section>}</div>;
}

export function BranchList({ project, selectedId, onSelect, onAdd, onSaveProject, onOpenTarget }: { project: ProjectData; selectedId: string | null; onSelect: (id: string) => void; onAdd: (kind: EntityKind, data?: Record<string, unknown>) => void; onSaveProject?: (project: ProjectData, reason: string) => Promise<ProjectData>; onOpenTarget?: (anchor: ContentAnchor) => void }) {
  const [hierarchical, setHierarchical] = useState(false);
  const nodes = getEntitiesByKind(project, 'flow_node');
  const edges = getEntitiesByKind(project, 'flow_edge');
  const graphs = getEntitiesByKind(project, 'flow_graph');
  if (hierarchical) return <><button className="button secondary" onClick={() => setHierarchical(false)}>分岐の一覧へ戻る</button><FlowHierarchy project={project} selectedId={selectedId} onSelect={onSelect} onOpenTarget={onOpenTarget}/></>;
  return <div className="branch-view">{onSaveProject && <ReactionBuilder key={project.projectId} project={project} onSaveProject={onSaveProject} onOpen={onSelect}/>}<button className="button secondary" onClick={() => setHierarchical(true)}>章・場面・会話へ掘り下げる</button><div className="branch-summary"><span>{nodes.length}ノード</span><span>{edges.length}接続</span><span>{edges.filter(e => typeof e.data.toId !== 'string').length}未完成</span><button className="button subtle small" onClick={() => onAdd('flow_graph')}><Icon name="plus" size={16}/>分岐グループ</button></div>{graphs.map(graph => <button className="graph-summary-card" key={graph.id} onClick={() => onSelect(graph.id)}><Icon name="structure"/><strong>{labelOf(graph)}</strong><span>{graph.data.nodeIds.length}ノード / {graph.data.entryIds.length}入口</span><Icon name="arrow" size={16}/></button>)}{nodes.length === 0 ? <EmptyState icon="structure" title="物語の道をつなぎましょう" action={<button className="button primary" onClick={() => onAdd('flow_node')}><Icon name="plus"/>ノードを追加</button>}>入口・選択・自動進行・終端を分けて登録できます。</EmptyState> : <div className="branch-node-list">{nodes.map(node => <section className={`branch-node ${selectedId === node.id ? 'selected' : ''}`} key={node.id}><button className="branch-node-heading" onClick={() => onSelect(node.id)}><span className={`node-type node-${node.data.nodeType}`}>{{ entry: '入口', scene: '場面', choice: '選択', automatic: '自動', call: '呼出し', exit: '出口', terminal: '終端' }[node.data.nodeType]}</span><strong>{labelOf(node)}</strong><Icon name="arrow" size={16}/></button>{node.data.sceneId && <button className="text-button branch-scene-link" onClick={() => onSelect(node.data.sceneId!)}><Icon name="note" size={16}/>{labelOf(project.entities.find(e => e.id === node.data.sceneId))}</button>}{edges.filter(edge => edge.data.fromId === node.id).map(edge => <button className="branch-edge" key={edge.id} onClick={() => onSelect(edge.id)}><span className="branch-line">↳</span><span><strong>{edge.data.label || edge.name || '次へ'}</strong><small>{describeCondition(edge.data.condition, project)}</small></span><span className="edge-destination">{typeof edge.data.toId === 'string' ? labelOf(project.entities.find(e => e.id === edge.data.toId)) : '行き先未定'} →</span></button>)}{node.data.nodeType === 'terminal' ? <p className="terminal-reason">{node.data.terminalReason || '終了理由が未入力です'}</p> : <button className="text-button add-branch" onClick={() => onAdd('flow_edge', { fromId: node.id })}><Icon name="plus" size={16}/>接続・選択肢を追加</button>}</section>)}</div>}</div>;
}

export function ProductionBoard({ project, onSelect, onAdd, onSave, onOpenTarget, onSaveProject }: { project: ProjectData; onSelect: (id: string) => void; onAdd: () => void; onSave: (entity: Entity) => Promise<Entity>; onOpenTarget?: (anchor: ContentAnchor) => void; onSaveProject?: (project: ProjectData, reason: string) => Promise<ProjectData> }) {
  const tasks = getEntitiesByKind(project, 'production_task');
  const [error, setError] = useState('');
  const sceneIds = new Set(tasks.flatMap(t => t.data.targetIds.filter(id => project.entities.find(e => e.id === id)?.kind === 'scene')));
  if (!tasks.length) return <><ProductionReviewPanel project={project} onOpen={onSelect} onOpenTarget={onOpenTarget} onSaveProject={onSaveProject}/><EmptyState icon="work" title="制作の進み具合を管理しましょう" action={<button className="button primary" onClick={onAdd}><Icon name="plus"/>制作タスクを追加</button>}>執筆・レビュー・実装・翻訳・収録を別の工程として追えます。</EmptyState></>;
  return <><ProductionReviewPanel project={project} onOpen={onSelect} onOpenTarget={onOpenTarget} onSaveProject={onSaveProject}/><div className="production-stats"><div><strong>{tasks.length}</strong><span>制作タスク</span></div><div><strong>{tasks.filter(t => t.data.progress === 'done').length}</strong><span>完了したタスク</span></div><div><strong>{sceneIds.size}</strong><span>固有の対象場面</span></div></div>{error && <div className="error-notice" role="alert">{error}</div>}<div className="production-board">{Object.entries(PROGRESS_LABELS).map(([progress, label]) => <section className="production-column" key={progress}><h3><span className={`progress-dot progress-${progress}`}/>{label}<span className="count-pill">{tasks.filter(t => t.data.progress === progress).length}</span></h3>{tasks.filter(t => t.data.progress === progress).map(task => <article className="task-card" key={task.id}><button className="task-open" onClick={() => onSelect(task.id)}><span className="eyebrow">{{ writing: '執筆', review: 'レビュー', implementation: '実装', translation: '翻訳', recording: '収録', verification: '確認', publication: '公開' }[task.data.stage]}</span><h4>{labelOf(task)}</h4>{task.data.deadline && <small><Icon name="clock" size={14}/>{task.data.deadline.date}</small>}<p>{task.data.targetIds.map(id => labelOf(project.entities.find(e => e.id === id))).join('、') || '対象未設定'}</p>{task.data.dependsOn?.length ? <span className="dependency-label">{task.data.dependsOn.length}件の先行タスク</span> : null}</button><select aria-label={`${labelOf(task)}の進捗`} value={task.data.progress} onChange={async e => { try { await onSave({ ...task, data: { ...task.data, progress: e.target.value as any } }); setError(''); } catch (err) { setError((err as Error).message); } }}>{Object.entries(PROGRESS_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></article>)}</section>)}</div></>;
}

export { Relationships } from './Relationships';
