import { useEffect } from 'react';
import type { Entity, ProjectData } from '../domain/types';
import { previewMediaRevision, confirmMediaRevision, previewConsultationImport, confirmConsultationImport } from '../domain/productionPlanning';
import { useAuthorField, useAuthorInput, flushAuthorDraft, authorField, acknowledgeAuthorDraft, AuthorDraftNotice } from './authorOperation';
import { PagedSelect } from './PagedSelect';
import { RichTextView, labelOf } from './Fields';
import { textToRichText } from '../domain/model';
import {scenarioStore} from '../storage';
export function MediaRevisionTools({project,entity,onSaveProject,onOpen,disabled}:{project:ProjectData;entity:Entity<'media_variant'>;onSaveProject:(p:ProjectData,r:string)=>Promise<ProjectData>;onOpen:(id:string)=>void;disabled:boolean}){
 const key=`media-revision:${project.projectId}:${entity.id}`,[body,setBody]=useAuthorInput(key,'body',()=>entity.data.body?.map(b=>b.text).join('\n')??'',project.projectId,project.revision),[plan,setPlan]=useAuthorField<Awaited<ReturnType<typeof previewMediaRevision>>|null>(key,'plan',null),[busy,setBusy]=useAuthorField(key,'busy',false),[error,setError]=useAuthorField(key,'error',''),[saved,setSaved]=useAuthorField<{revision:string;id:string}|null>(key,'saved',null);
 useEffect(()=>{if(saved&&BigInt(project.revision)>=BigInt(saved.revision))setBusy(false);},[saved,project.revision]);
 async function preview(){if(disabled||authorField<boolean>(key,'busy'))return;setBusy(true);const captured=structuredClone(project),id=entity.id,submitted=textToRichText(body);try{await flushAuthorDraft(key);const worlds=await scenarioStore.listWorldSnapshots(),worldSnapshots=Object.fromEntries(Object.values(worlds).flatMap(world=>world.snapshots.map(pin=>[pin.id,pin.content])));setPlan(await previewMediaRevision(captured,id,submitted,{worldSnapshots}));setError('');}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 async function save(){if(!plan||disabled||authorField<boolean>(key,'busy'))return;setBusy(true);try{const result=await onSaveProject(await confirmMediaRevision(project,plan),'旧媒体を保持して改訂候補を原子保存');acknowledgeAuthorDraft(key,result.revision);setSaved({revision:result.revision,id:plan.newId});setPlan(null);}catch(cause){setError((cause as Error).message);setBusy(false);}}
 return <details className="settings-card"><summary>媒体の旧公開版と改訂候補を比較</summary><p>旧媒体の本文と元公開版を保持し、作者が入力した本文を別の改訂候補へ保存します。確認先と予定日は媒体の通常欄で指定できます。</p><AuthorDraftNotice scope={key} revision={project.revision}/><fieldset disabled={disabled||busy}><label>媒体の改訂候補本文<textarea aria-label="媒体の改訂候補本文" value={body} onChange={e=>{setBody(e.target.value);setPlan(null);}}/></label><button onClick={()=>void preview()}>媒体の改訂差分を確認</button>{plan&&<><p>基底revision {plan.baseRevision} · 旧元版 {plan.old.data.baseSnapshotId} · 元hash {plan.baseHash}</p><h4>旧媒体本文</h4><RichTextView value={plan.old.data.body??[]}/><h4>改訂候補本文</h4><RichTextView value={(plan.candidate.entities.find((e):e is Entity<'media_variant'>=>e.id===plan.newId&&e.kind==='media_variant')?.data.body??[])}/><p>設定・制作対象の旧元版と現在版を保持。旧 {plan.old.data.sourceIds?.length??0}対象 · 新元版revision {project.revision}</p>{plan.differences.map(diff=><details key={diff.id}><summary>{diff.before?.name??diff.after?.name??diff.id} · 元設定の改訂差</summary><p>旧公開版</p><pre>{JSON.stringify(diff.before,null,2)}</pre><p>確認時の現稿</p><pre>{JSON.stringify(diff.after,null,2)}</pre></details>)}<button disabled={project.revision!==plan.baseRevision} onClick={()=>void save()}>旧媒体を保持して改訂候補を保存</button></>}</fieldset>{saved&&<button className="reference-link" onClick={()=>onOpen(saved.id)}>保存した媒体改訂候補を開く</button>}{error&&<p role="alert">{error}</p>}</details>;
}
export function ConsultationImportPanel({project,onSaveProject}:{project:ProjectData;onSaveProject:(p:ProjectData,r:string)=>Promise<ProjectData>}){
 const key=`consultation-import:${project.projectId}`,[text,setText]=useAuthorInput(key,'text','',project.projectId,project.revision),[source,setSource]=useAuthorInput(key,'source','',project.projectId,project.revision),[version,setVersion]=useAuthorInput(key,'version',project.projectId,project.projectId,project.revision),[target,setTarget]=useAuthorInput(key,'target','',project.projectId,project.revision),[plan,setPlan]=useAuthorField<Awaited<ReturnType<typeof previewConsultationImport>>|null>(key,'plan',null),[busy,setBusy]=useAuthorField(key,'busy',false),[error,setError]=useAuthorField(key,'error',''),[saved,setSaved]=useAuthorField<string|null>(key,'saved',null);
 const [,setQueued]=useAuthorField<File|null>(key,'queuedFile',null);
 function release(){setBusy(false);const next=authorField<File|null>(key,'queuedFile');if(next){setQueued(null);void read(next);}}
 useEffect(()=>{if(saved&&BigInt(project.revision)>=BigInt(saved))release();},[saved,project.revision]);
 const edition=version===project.projectId?project:project.snapshots.find(s=>s.id===version)?.content;
 async function read(file:File){if(authorField<boolean>(key,'busy')){setQueued(file);return;}setBusy(true);try{if(file.size>1024*1024)throw Error('提案は1 MiB以下で選んでください。');const submitted=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());setText(submitted);setPlan(null);setError('');await flushAuthorDraft(key);}catch(cause){setError((cause as Error).message);}finally{release();}}
 async function preview(){if(authorField<boolean>(key,'busy'))return;setBusy(true);const captured=structuredClone(project),request={text,source,versionId:version,targetId:target||undefined};try{await flushAuthorDraft(key);setPlan(await previewConsultationImport(captured,request));setError('');}catch(cause){setError((cause as Error).message);}finally{release();}}
 async function save(){if(!plan||authorField<boolean>(key,'busy'))return;setBusy(true);try{const result=await onSaveProject(await confirmConsultationImport(project,plan),'出所・相談対象版付き作者別案として提案を保存');acknowledgeAuthorDraft(key,result.revision);setSaved(result.revision);setPlan(null);}catch(cause){setError((cause as Error).message);release();}}
 return <details className="settings-card consultation-import"><summary>相談Markdownから作者別案を取り込む</summary><p>出所と相談対象版を指定し、提案を別案へ保存します。構成の作者別案で比較し、選んだ変更を採用できます。</p><AuthorDraftNotice scope={key} revision={project.revision}/><fieldset disabled={busy}><label>提案の出所<input aria-label="提案の出所" value={source} onChange={e=>{setSource(e.target.value);setPlan(null);}}/></label><PagedSelect label="提案の相談対象版" scope={`${key}:versions`} items={[{id:project.projectId,label:'現在稿'},...project.snapshots.map(s=>({id:s.id,label:s.versionLabel}))]} value={version} onChange={id=>{setVersion(id);setTarget('');setPlan(null);}}/><PagedSelect label="提案を比較する本文対象" scope={`${key}:targets`} items={(edition?.entities??[]).filter(e=>!e.deletedAt&&['scene','dialogue_line','chapter','note'].includes(e.kind)).map(e=>({id:e.id,label:labelOf(e)}))} value={target} onChange={id=>{setTarget(id);setPlan(null);}} emptyLabel="提案メモだけを別案へ保存"/><label>提案Markdown<textarea aria-label="提案Markdown" value={text} onChange={e=>{setText(e.target.value);setPlan(null);}}/></label><label>提案MDを選ぶ<input type="file" accept=".md,text/markdown,text/plain" aria-label="提案MDを選ぶ" onChange={e=>{const file=e.target.files?.[0];if(file)void read(file);}}/></label><button onClick={()=>void preview()}>提案の別案差分を確認</button>{plan&&<><p>確認revision {plan.baseRevision} · 出所 {source} · 相談対象 {plan.versionId}</p><button disabled={plan.baseRevision!==project.revision} onClick={()=>void save()}>提案を作者別案として保存</button></>}</fieldset>{saved&&<p role="status">作者別案へ保存しました。構成→作者別案から比較と選択採用へ進めます。</p>}{error&&<p role="alert">{error}</p>}</details>;
}
