import type { ContentAnchor, Entity, ProjectData, RuntimeState } from '../domain/types';
import { adoptedRecord } from '../domain/adoption';
import { assessPresentationClaims, type NarrativeOccurrence } from '../domain/narrative';
import { labelOf } from './Fields';
import { ListPager, useListWindow } from './ListWindow';
import {WindowedList} from './WindowedList';
const KINDS = { author_truth: '作者の真実', testimony: '証言', belief: '人物の信念', hypothesis: '仮説' };
const STATUS = { candidate: '確認候補', unknown: '未確認', intentional: '意図した発言', passed_for_checked_scope: 'この提示時点で確認' };
export function NarrativeClaims({ project, state, occurrences = [], referenceEntities = [], onOpenTarget }: { project: ProjectData; state: RuntimeState; occurrences?: NarrativeOccurrence[]; referenceEntities?: Entity[]; onOpenTarget: (anchor: ContentAnchor) => void }) {
  const entities = [...project.entities, ...referenceEntities], assessments = assessPresentationClaims(project, occurrences, referenceEntities).map(item => ({ ...item, id: `${item.occurrenceIndex}:${item.lineId}:${item.assertionId}` }));
  const page = useListWindow({ items: assessments, scope: `${project.projectId}:narrative-claims:${state.contentVersionId}` });
  const presentations = occurrences.map((occurrence, index) => ({ ...occurrence, id: `${index}`, index })).filter(occurrence => occurrence.conditions.length);
  const presentationPage = useListWindow({ items: presentations, scope: `${project.projectId}:narrative-presentations:${state.contentVersionId}` });
  const legacyLines = !occurrences.length ? entities.filter((entity): entity is Entity<'dialogue_line'> => entity.kind === 'dialogue_line' && adoptedRecord(entity) && state.seenIds.includes(entity.id) && !!entity.data.claimAssertionIds?.length) : [];
  if (!assessments.length && !legacyLines.length && !presentations.length) return null;
  return <section aria-label="発言と提示時点の認識"><h3>発言・真実・信念と提示</h3><p className="field-hint">章順または経路の条件を同じ効果前状態で観測し、確定した効果を本文順に発言まで照合します。読者の理解は認定しません。</p>
    {!!presentations.length && <div><h4>読み手への提示記録</h4><ListPager {...presentationPage} label="読み手への提示記録"/>{presentationPage.items.map(occurrence => <details key={occurrence.id}><summary>提示 {occurrence.index + 1} · {labelOf(entities.find(entity => entity.id === (occurrence.target.nodeId ?? occurrence.target.sceneId)))} · {occurrence.state.provenance === 'full_play' ? '宣言入口からの経路' : '途中・仮値を含む提示'}</summary>{<WindowedList items={occurrence.conditions.map(result=>({...result,id:result.targetId}))} scope={`${project.projectId}:${state.contentVersionId}:${occurrence.index}:conditions`} label="提示条件の観測" render={result => { const disclosure = entities.find((entity): entity is Entity<'disclosure'> => entity.kind === 'disclosure' && entity.id === result.targetId), shown = result.value === 'true' && occurrence.state.seenIds.includes(result.targetId); return <p key={result.targetId}>{shown ? '実際に提示' : result.value === 'false' ? '条件不成立で提示せず' : '提示は未確認'} · {disclosure?.data.stage} · <button className="text-button" onClick={() => onOpenTarget(disclosure?.data.anchor ?? { entityId: result.targetId })}>{labelOf(disclosure)}</button> · {disclosure?.data.role === 'payoff' ? '回収' : '手掛かり'}{result.reasons.join('、')}</p>; }}/>}<p>人物の取得記録: 効果前 {occurrence.observationState?.assertions.filter(assertion => assertion.holderId && assertion.truth === 'true').length ?? '未確認'}件 → 提示後 {occurrence.state.assertions.filter(assertion => assertion.holderId && assertion.truth === 'true').length}件。本文の提示だけで取得・理解とは認定しません。</p></details>)}</div>}
    <ListPager {...page} label="提示時点の発言"/>
    {page.items.map(item => {
      const line = entities.find((entity): entity is Entity<'dialogue_line'> => entity.kind === 'dialogue_line' && entity.id === item.lineId);
      return <details key={item.id}><summary>提示 {item.occurrenceIndex + 1} · {labelOf(line)} · {STATUS[item.status]} · {item.knowledge === 'acquired' ? '取得済み' : item.knowledge === 'not_acquired' ? '未取得' : '取得は未確認'}</summary><p>{item.message}</p><p>{labelOf(entities.find(entity => entity.id === item.speakerId))} · <button className="text-button" onClick={() => onOpenTarget({ entityId: item.lineId })}>台詞へ戻る</button> · <button className="text-button" onClick={() => onOpenTarget({ entityId: item.positionId })}>提示箇所へ戻る</button></p>
        <WindowedList items={item.counterpartIds.map(id=>({id}))} scope={`${project.projectId}:${item.id}:counterparts`} label="照合する真実・証言・信念" render={({id}) => { const claim = entities.find((entity): entity is Entity<'assertion'> => entity.kind === 'assertion' && entity.id === id); if (!claim) return null; return <div key={id}><button className="text-button" onClick={() => onOpenTarget({ entityId: id })}>{KINDS[claim.data.truthKind]} · {labelOf(claim)} · {claim.status === 'confirmed' ? '採用確定' : '仮・要確認'}</button>{claim.data.holderId && ` · ${labelOf(entities.find(entity => entity.id === claim.data.holderId))}`} · {typeof claim.data.value === 'string' ? claim.data.value : claim.data.value.type === 'unknown' ? `未定：${claim.data.value.reason}` : String(claim.data.value.value)}{claim.data.evidenceLocation && <button className="text-button" onClick={() => onOpenTarget(claim.data.evidenceLocation!)}>根拠位置</button>}<WindowedList items={(claim.data.sourceIds??[]).map(id=>({id}))} scope={`${project.projectId}:${item.id}:${claim.id}:sources`} label="発言の出所" render={({id:sourceId})=><button key={sourceId} className="text-button" onClick={() => onOpenTarget({ entityId: sourceId })}>出所 · {labelOf(entities.find(entity => entity.id === sourceId))}</button>}/></div>; }}/>
      </details>;
    })}
    <WindowedList items={legacyLines} scope={`${project.projectId}:${state.contentVersionId}:legacy-claims`} label="提示時点が未確認の台詞" render={line => <details key={line.id}><summary>{labelOf(line)} · 提示時点は未確認</summary><p>提示前の観測記録がありません。現在の取得記録だけで、過去に知っていたとは認定しません。</p><p>{state.assertions.some(assertion => assertion.holderId === line.data.speakerId && assertion.truth === 'true') ? '現在の取得記録あり' : '人物の取得記録なし・発言を確認する候補'}</p><button className="text-button" onClick={() => onOpenTarget({ entityId: line.id })}>台詞と出所へ戻る</button></details>}/>
  </section>;
}
