import type { ContentAnchor, Entity, ProjectData, RuntimeState } from '../domain/types';
import { adoptedRecord } from '../domain/adoption';
import { labelOf } from './Fields';

/** Authored claims and committed presentations are separate evidence. */
export function NarrativeClaims({ project, state, onOpenTarget }: { project: ProjectData; state: RuntimeState; onOpenTarget: (anchor: ContentAnchor) => void }) {
  const lines = project.entities.filter((entity): entity is Entity<'dialogue_line'> => entity.kind === 'dialogue_line' && adoptedRecord(entity) && state.seenIds.includes(entity.id) && !!entity.data.claimAssertionIds?.length);
  const assertions = project.entities.filter((entity): entity is Entity<'assertion'> => entity.kind === 'assertion' && adoptedRecord(entity));
  const kinds = { author_truth: '作者の真実', testimony: '証言', belief: '人物の信念', hypothesis: '仮説' };
  if (!lines.length) return null;
  return <section><h3>発言・真実・信念と提示</h3><p className="field-hint">この経路で提示した台詞を比較します。提示は読者の理解の認定には使いません。</p>{lines.slice(0, 60).map(line => <details key={line.id}><summary>{labelOf(line)} · {{ statement: '発言', lie: '嘘', misunderstanding: '誤解', quotation: '引用' }[line.data.assertionIntent ?? 'statement']}</summary><p>{line.data.assertionReason || '発言の意図の根拠は未記入'}</p><button className="text-button" onClick={() => onOpenTarget({ entityId: line.id })}>台詞と提示箇所へ戻る</button>{(line.data.claimAssertionIds ?? []).map(id => { const claim = assertions.find(assertion => assertion.id === id); if (!claim) return <p key={id}>採用中の主張が見つかりません。</p>; const counterparts = assertions.filter(other => other.data.subjectId === claim.data.subjectId && other.data.predicate === claim.data.predicate); return <div key={id}>{counterparts.map(other => <p key={other.id}><button className="text-button" onClick={() => onOpenTarget({ entityId: other.id })}>{kinds[other.data.truthKind]} · {labelOf(other)} · {other.status === 'confirmed' ? '採用確定' : '仮・要確認'}</button>{other.data.holderId && ` · ${labelOf(project.entities.find(entity => entity.id === other.data.holderId))}`} · {typeof other.data.value === 'string' ? other.data.value : other.data.value.type === 'unknown' ? `未定：${other.data.value.reason}` : String(other.data.value.value)}{other.data.evidenceLocation && <button className="text-button" onClick={() => onOpenTarget(other.data.evidenceLocation!)}>根拠位置</button>}{other.data.sourceIds?.map(sourceId => <button key={sourceId} className="text-button" onClick={() => onOpenTarget({ entityId: sourceId })}>出所 · {labelOf(project.entities.find(entity => entity.id === sourceId))}</button>)}</p>)}</div>; })}</details>)}</section>;
}
