import { useEffect } from 'react';
import { productionWorkload, productionTraceWorkload, estimateProduction } from '../domain/productionPlanning';
import type { Entity, ProjectData } from '../domain/types';
import { adoptedRecord } from '../domain/adoption';
import { useAuthorField, useAuthorInput, flushAuthorDraft, authorField, acknowledgeAuthorDraft, AuthorDraftNotice } from './authorOperation';
import { PagedSelect } from './PagedSelect';
import { ListPager, useListWindow } from './ListWindow';
import { labelOf } from './Fields';
import {GameplayProductionLinks} from './GameplayProductionLinks';
import {scenarioStore} from '../storage';
import {ProductionDependencies} from './ProductionDependencies';
export function ProductionPlanningPanel({project,onOpen,onSaveProject}:{project:ProjectData;onOpen:(id:string)=>void;onSaveProject?:(p:ProjectData,reason:string)=>Promise<ProjectData>}){
 const key=`production-planning:${project.projectId}`,[traceId,setTrace]=useAuthorInput(key,'trace','',project.projectId,project.revision),[taskId,setTask]=useAuthorInput(key,'task','',project.projectId,project.revision),[speed,setSpeed]=useAuthorInput(key,'speed','',project.projectId,project.revision),[assumptions,setAssumptions]=useAuthorInput(key,'assumptions','',project.projectId,project.revision),[busy,setBusy]=useAuthorField(key,'busy',false),[error,setError]=useAuthorField(key,'error',''),[plan,setPlan]=useAuthorField<{revision:string;task:Entity<'production_task'>}|null>(key,'plan',null),[saved,setSaved]=useAuthorField<string|null>(key,'saved',null);
 const trace=project.entities.find(e=>e.id===traceId&&e.kind==='trace'),[route,setRoute]=useAuthorField<Awaited<ReturnType<typeof productionTraceWorkload>>|null>(key,'route',null),[routeError,setRouteError]=useAuthorField(key,'routeError','');
 useEffect(()=>{let alive=true;setRoute(null);setRouteError('');if(traceId){const captured=structuredClone(project);void scenarioStore.listWorldSnapshots().then(worlds=>productionTraceWorkload(captured,traceId,Object.fromEntries(Object.values(worlds).flatMap(world=>world.snapshots.map(pin=>[pin.id,pin.content]))))).then(result=>{if(alive)setRoute(result);}).catch(cause=>{if(alive)setRouteError((cause as Error).message);});}return()=>{alive=false;};},[project.revision,project.projectId,traceId]);
 let workload:ReturnType<typeof productionWorkload>|undefined,problem='';try{workload=productionWorkload(project);}catch(cause){problem=(cause as Error).message;}
 const rows=useListWindow({items:workload?.rows.map(row=>({...row,id:row.task.id}))??[],scope:`${key}:rows`});
 useEffect(()=>{if(saved&&BigInt(project.revision)>=BigInt(saved)){setSaved(null);setBusy(false);setPlan(null);}},[project.revision,saved]);
 async function preview(){if(authorField<boolean>(key,'busy'))return;setBusy(true);const captured=structuredClone(project),selectedTask=taskId,input={speed:Number(speed),unit:'作業日',assumptions:assumptions.split('\n'),source:'作者が入力した速度と制作対象の固有件数'};try{await flushAuthorDraft(key);const task=captured.entities.find((e):e is Entity<'production_task'>=>e.id===selectedTask&&e.kind==='production_task'&&adoptedRecord(e));if(!task)throw Error('制作対象のタスクを選んでください。');setPlan({revision:captured.revision,task:{...task,data:{...task.data,estimate:estimateProduction(captured,task,input)}}});setError('');}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 async function save(){if(!plan||authorField<boolean>(key,'busy')||!onSaveProject)return;if(plan.revision!==project.revision){setError('確認後に作品が更新されました。入力を保持して再確認してください。');return;}setBusy(true);try{const result=await onSaveProject({...project,entities:project.entities.map(e=>e.id===plan.task.id?plan.task:e)},'速度・仮定・不明数付き制作見積を保存');acknowledgeAuthorDraft(key,result.revision);setSaved(result.revision);}catch(cause){setError((cause as Error).message);setBusy(false);}}
 return <section className="settings-card production-planning"><h3>企画・判断・プレイ行動と制作量</h3><GameplayProductionLinks project={project} onOpen={onOpen} onSaveProject={onSaveProject}/>{workload&&<p>固有場面 {workload.uniqueScenes} · 固有台詞 {workload.uniqueLines} · 固有素材 {workload.uniqueAssets} · 再利用先 {workload.reuseSites} · 選択経路の提示量 {route?.workload.routeOccurrences??(traceId?'確認中':'未選択')} · 経路参照不明 {route?.workload.unknownRouteReferences??'未確認'}</p>}<PagedSelect label="制作量を比較する経路" scope={`${key}:traces`} items={project.entities.filter(e=>e.kind==='trace'&&adoptedRecord(e)).map(e=>({id:e.id,label:labelOf(e)}))} value={traceId} onChange={setTrace}/>{trace&&<p>対象版 {trace.kind==='trace'?trace.data.contentVersionId:''}。部分開始・仮値・未探索を通し確認へ換算しません。</p>}<ProductionDependencies tasks={rows.items.map(row=>row.task)} onOpen={onOpen}/>{rows.items.map(row=><article key={row.id}><button className="text-button" onClick={()=>onOpen(row.id)}>{labelOf(row.task)}</button><p>{row.task.data.stage} · {row.task.data.progress} · {row.blocked?'先行条件または詰まりあり':'先行条件を照合'} · 制作期限 {row.task.data.deadline?.date??'未指定'} / {row.task.data.deadline?.timeZone??'時域未指定'}</p>{row.deadlineConflict&&<p role="alert">先行作業の期限が後、または時域が異なります。現実の日付を再確認してください。</p>}{row.task.data.blockingReason&&<p>{row.task.data.blockingReason}</p>}{row.dependencies.map(dep=><button key={dep.id} className="text-button" onClick={()=>onOpen(dep.id)}>先行 {dep.status}</button>)}{row.estimate&&<p>見積 {row.estimate.value??`${row.estimate.range?.min}〜${row.estimate.range?.max}`} {row.estimate.unit} · 速度 {row.estimate.speed??'未指定'} · 不明 {row.estimate.unknownCount} · 仮定 {row.estimate.assumptions.join(' / ')}</p>}</article>)}<ListPager {...rows} label="制作計画"/><AuthorDraftNotice scope={key} revision={project.revision}/><fieldset disabled={busy}><PagedSelect label="見積する制作タスク" scope={`${key}:tasks`} items={(workload?.rows??[]).map(row=>({id:row.task.id,label:labelOf(row.task)}))} value={taskId} onChange={id=>{setTask(id);setPlan(null);}}/><label>一作業日の固有件数<input aria-label="一作業日の固有件数" value={speed} onChange={e=>{setSpeed(e.target.value);setPlan(null);}}/></label><label>見積の仮定<textarea aria-label="見積の仮定" value={assumptions} onChange={e=>{setAssumptions(e.target.value);setPlan(null);}}/></label><button onClick={()=>void preview()}>制作見積を確認</button>{plan&&<><p>確認版 {plan.revision} · {plan.task.data.estimate?.value}作業日 · 不明 {plan.task.data.estimate?.unknownCount}件</p><button disabled={plan.revision!==project.revision} onClick={()=>void save()}>確認した制作見積を保存</button></>}</fieldset>{route&&<p>経路の対象版 {route.sourceVersionId} / {route.sourceRevision} · 開始由来 {route.origin} · 外部 {route.externalMode}</p>}{(error||problem||routeError)&&<p role="alert">{error||problem||routeError}</p>}</section>;
}
