import {recordDiagnostic} from '../diagnostics';
import {useAuthorField,authorField} from './authorOperation';
import {useState} from 'react';
import {useScenarioStore,useAuthorScope} from './StoreContext';
import {useSyncClient} from './SyncContext';
import {inspectConfirmedArchive} from '../sync/archiveTransfer';
import {downloadBytes,safeFileName} from './components';
import type {ConfirmedSyncBase} from '../sync/nativeBridge';
import type {ProjectData} from '../domain/types';
import {ListPager,useListWindow} from './ListWindow';
export interface RemoteWork {projectId:string;serverRevision:string;role:'owner'|'editor';name:string|null}
export function RemoteWorks({onImported,onEdit}:{onImported:()=>void;onEdit:(id:string)=>void}){
 const store=useScenarioStore(),client=useSyncClient(),scope=useAuthorScope('remote-works'),[works,setWorks]=useState<RemoteWork[]>([]),[busy,setBusy]=useAuthorField(scope,'busy',false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[controller,setController]=useState<AbortController|null>(null),view=useListWindow({items:works.map(w=>({...w,id:w.projectId})),scope:'remote-owned-works',size:30});
 async function run(task:(signal:AbortSignal)=>Promise<void>){if(authorField<boolean>(scope,'busy'))return;const abort=new AbortController(),operationId=crypto.randomUUID();setController(abort);setBusy(true);setError('');try{await task(abort.signal);}catch(cause){recordDiagnostic(cause,{accountId:store.accountId,operationId});setError((cause as Error).message);}finally{setBusy(false);setController(null);}}
 async function restore(w:RemoteWork,signal:AbortSignal){if(!client||!store.accountId||w.role!=='owner')throw Error('FORBIDDEN');const session=client.getSession();if(await store.getProject(w.projectId))throw Error('このIDは端末内にあります。作品の同期画面から確定版を取得してください。');setNotice('完全保存と確定版を取得中…');const bytes=await client.downloadArchive({projectId:w.projectId,serverRevision:w.serverRevision},session,signal),confirmed=await client.request<{project:ProjectData;documents:ConfirmedSyncBase['documents'];contentHash:string;serverRevision:string}>('pull',{projectId:w.projectId},session,signal);if(confirmed.serverRevision!==w.serverRevision)throw Error('REVISION_CHANGED');setNotice('履歴・旧固定版・素材bytes・世界依存・hashを検証中…');const prepared=await inspectConfirmedArchive(bytes,w.projectId,confirmed.documents,signal);if(signal.aborted)throw Error('CANCELLED');const result=await store.importScenario(prepared,{mode:'new',signal});try{const outbox=await store.listOutbox(w.projectId);await store.bindConfirmedProject({...confirmed,projectId:w.projectId,localRevision:result.project.revision,outboxIds:outbox.map(o=>o.operationId)});}catch(cause){downloadBytes(bytes,`${safeFileName(prepared.project.name)}.scenario`,'application/octet-stream');throw Error(`復元データを保持しましたが、接続基底は未確定です: ${(cause as Error).message}`);}setNotice('作品・履歴・固定世界・旧公開版・素材bytesを復元し、同じサーバー確定版へ接続しました。旧送信証跡は再接続待ちとして保持しています。');onImported();}
 return <section className="settings-card"><h2>接続先から作品を取得</h2><button className="button secondary" disabled={busy||!client||!store.accountId} onClick={()=>void run(async signal=>{setWorks(await client!.request('projects',{},client!.getSession(),signal));})}>許可された作品を確認</button>{view.items.map(w=><p key={w.projectId}>{w.name??'編集を許可された作品'} · {w.projectId} · 確定版 {w.serverRevision}{w.role==='owner'?<button disabled={busy} onClick={()=>void run(signal=>restore(w,signal))}>完全保存から新規復元</button>:<button disabled={busy} onClick={()=>onEdit(w.projectId)}>許可項目を編集</button>}</p>)}<ListPager {...view} label="接続先の作品"/>{busy&&<p role="status">取得・復元中…<button onClick={()=>controller?.abort()}>中止</button></p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}</section>;
}
