import type {ContentAnchor,Entity,ProjectData} from '../domain/types';
import {createEntity} from '../domain/model';
import {commentStage,reviewLatestPosition,type SharedComment,type SharedReviewStage} from '../domain/sharedReviews';
import {useSyncClient} from './SyncContext';
import {useAuthorScope,useScenarioStore} from './StoreContext';
import {authorField,useAuthorField} from './authorOperation';
export const REVIEW_STAGE_LABELS:Record<SharedReviewStage,string>={open:'未処理',fixed:'修正済み',verified:'確認済み'};
export function sharedReviewUrl(review:Entity<'review'>){const source=review.data.sharedSource;if(!source)return undefined;const url=new URL(import.meta.env.BASE_URL,location.origin);url.searchParams.set('shared',source.sharedSnapshot);url.searchParams.set('sharedConnection',source.connection);url.searchParams.set('sharedVersion',source.publicVersion);if(source.publicEntity)url.searchParams.set('sharedEntity',source.publicEntity);if(source.publicRelation)url.searchParams.set('sharedRelation',source.publicRelation);if(source.publicBlock){url.searchParams.set('sharedBlock',source.publicBlock);url.searchParams.set('sharedStart',String(source.startCp));url.searchParams.set('sharedEnd',String(source.endCp));}return url.href;}
export function ReviewActions({project,review,disabled,onSaveProject,onApplied,onBusy,onOpenTarget,onOpen}:{project:ProjectData;review:Entity<'review'>;disabled:boolean;onSaveProject:(p:ProjectData,reason:string)=>Promise<ProjectData>;onApplied:(review:Entity<'review'>)=>void;onBusy:(busy:boolean)=>void;onOpenTarget?:(anchor:ContentAnchor)=>void;onOpen:(id:string)=>void}){
 const client=useSyncClient(),store=useScenarioStore(),scope=useAuthorScope(`review-actions:${project.projectId}:${review.id}`),[busy,setBusy]=useAuthorField(scope,'busy',false),[error,setError]=useAuthorField(scope,'error',''),[notice,setNotice]=useAuthorField(scope,'notice','');
 const source=review.data.sharedSource,url=sharedReviewUrl(review),tasks=project.entities.filter(e=>e.kind==='production_task'&&!e.deletedAt&&e.data.targetIds.includes(review.id)),next:SharedReviewStage=review.data.stage==='open'?'fixed':'verified';
 async function run(task:()=>Promise<void>){if(authorField<boolean>(scope,'busy')||disabled)return;setBusy(true);onBusy(true);setError('');try{await task();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);onBusy(false);}}
 async function stage(value:SharedReviewStage){const updated={...review,data:{...review.data,stage:value}},saved=await onSaveProject({...project,entities:project.entities.map(e=>e.id===review.id?updated:e)},`指摘を${REVIEW_STAGE_LABELS[value]}として明示保存`),record=saved.entities.find((e):e is Entity<'review'>=>e.id===review.id&&e.kind==='review');if(!record)throw Error('SAVE_NOT_CONFIRMED');onApplied(record);setNotice(`端末の指摘を${REVIEW_STAGE_LABELS[value]}にしました。共有版へは下の明示操作で反映できます。`);}
 async function reflect(value:SharedReviewStage=review.data.stage){if(!source||!client||client.config.url!==source.connection||client.getSession().accountId!==store.accountId)throw Error('REVIEW_CONNECTION_UNKNOWN');const rows=await client.updateComment(source.comment,{review_stage:value}) as SharedComment[],actual=rows[0];if(actual.id!==source.comment||actual.snapshot_id!==source.sharedSnapshot||commentStage(actual)!==value)throw Error('REVIEW_ACK_UNKNOWN');setNotice('専用接続先が指摘の状態を確定しました。本文・対象版・引用は変更していません。');}
 return <section aria-label="指摘の修正と確認"><h3>指摘の修正と確認</h3><p>{REVIEW_STAGE_LABELS[review.data.stage]} · 元の固定版 {review.data.targetVersionId} · 現在稿の位置 {reviewLatestPosition(project,review)==='known'?'確認できる':'不明'}</p><blockquote>{review.data.quotedText??source?.quotedText??''}</blockquote><fieldset disabled={disabled||busy}><button className="button secondary" onClick={()=>{const target=review.data.target;if(typeof target==='string'){onOpenTarget?.({entityId:target,sourceVersionId:review.data.targetVersionId});}else onOpenTarget?.({...target,sourceVersionId:target.sourceVersionId??review.data.targetVersionId});}}>指摘した元の固定版を開く</button>{url&&<a href={url} target="_blank" rel="noopener noreferrer">元の共有版と公開引用を開く</a>}{review.data.stage!=='verified'&&<button className="button primary" onClick={()=>void run(()=>stage(next))}>{REVIEW_STAGE_LABELS[next]}として保存</button>}{review.data.stage!=='open'&&<button className="button secondary" onClick={()=>void run(()=>stage('open'))}>未処理へ戻す</button>}{source&&review.data.stage==='verified'&&<button className="button secondary" disabled={!client||!navigator.onLine} onClick={()=>void run(()=>reflect('fixed'))}>共有側の修正済みを明示保存</button>}{source&&<button className="button secondary" disabled={!client||!navigator.onLine} onClick={()=>void run(()=>reflect())}>端末の確認状態を共有指摘へ反映</button>}{tasks.length?<button className="button secondary" onClick={()=>onOpen(tasks[0]!.id)}>対応する制作タスクを開く（{tasks.length}件）</button>:<button className="button secondary" onClick={()=>void run(async()=>{const task=createEntity(project.projectId,'production_task',`${review.name}への対応`,{targetIds:[review.id],stage:'review',progress:'todo'}),saved=await onSaveProject({...project,entities:[...project.entities,task]},'指摘と結び付いた制作タスクを保存');if(!saved.entities.some(e=>e.id===task.id))throw Error('SAVE_NOT_CONFIRMED');onOpen(task.id);})}>この指摘の制作タスクを作る</button>}</fieldset>{busy&&<p role="status">確認状態を保存中…</p>}{error&&<p role="alert">{error} · 指摘と引用は保持しています。</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
