import { useEffect, useMemo, useRef, useState } from 'react';
import type { CalendarDefinition, Entity, ID, ProjectData, Relation, Tick, TimeSpec } from '../domain/types';
import { emptyValidity, newId, RELATION_LABELS, RELATION_TYPES } from '../domain/model';
import { compareTicks, formatCalendarTick, formatRelativeTick, isTick, MAX_TICK, parseTick, type TimeResolution } from '../domain/time';
import { applyTimeEditPreview, calendarAxisTicks, calendarDisplayUnits, characterTimeSummary, displayUnitTicks, resolveEventTimes, shiftAllEventTimes, undoTimeEdit, type CalendarDisplayUnit, type TimeEditChange, type TimeEditPreview } from '../domain/timeEditing';
import { buildTimelineLanes, buildTimelineLayout, timelineWindow } from '../domain/timelineLayout';
import { EmptyState, Icon, Modal, StatusBadge, fieldText } from './components';
import { labelOf } from './Fields';
import { PreviewTable, TickInput, TimelinePagination, TimelineTimeEditor, TIMELINE_PAGE_SIZE as PAGE_SIZE, type TimelineSave } from './TimelineEditors';
import { TimelineLaneEditor, TimelineRelationEditor } from './TimelineDialogs';
import { assessWorldValidity, assertionValueLabel, compatibleLocations, createWorldAssessment, WORLD_PREDICATES } from '../domain/world';
import { checkpointContext } from './WorldFields';
import { WorldTimeImpactPreview } from './WorldTimeImpactPreview';
import './Timeline.css';

const PARTICIPANT_ROLES = { actor: '行動', witness: '目撃', mentioned: '言及', informed: '伝聞・情報取得', custom: 'その他' };
const LIFE_STATES = { alive: '存命', dead: '死亡後', unborn: '未誕生', uncertain: '生涯の時期が不確定', unknown: '存命状態不明' };

export function timeLabel(value: unknown, project: ProjectData): string {
  if (!value || typeof value !== 'object') return '日時未定';
  const time = value as TimeSpec;
  const calendar = 'calendarId' in time ? project.calendars.find(candidate => candidate.id === time.calendarId) : undefined;
  const label = (tick: Tick) => { try { return calendar ? formatCalendarTick(tick, calendar) : `${tick} tick（暦の対応未定）`; } catch { return `${tick} tick`; } };
  if (time.mode === 'instant') return label(time.at);
  if (time.mode === 'interval') return `${label(time.start)} 〜 ${label(time.end)}（終了を含まない）`;
  if (time.mode === 'uncertain') return `${label(time.earliest)} 〜 ${label(time.latest)} · ${time.precision}`;
  if (time.mode === 'relative') return `${labelOf(project.entities.find(entity => entity.id === time.anchorEventId))}の${time.anchorPoint === 'start' ? '開始' : '終了'}から ${time.minOffset}〜${time.maxOffset} tick`;
  return `日時未定${time.mode === 'unknown' && time.reason ? ` · ${time.reason}` : ''}`;
}

interface LocalTimelineView { center: Tick; unit: CalendarDisplayUnit; zoom: number; span: string | null; collapsed: ID[]; scrollTop: number; scrollLeft: number; calendarId: string; customTicks: Tick; customName: string; selectedId?: ID | null }
function validSpan(value: unknown): value is string { return typeof value === 'string' && /^[1-9][0-9]{0,38}$/.test(value) && BigInt(value) <= MAX_TICK * 2n; }
function initialView(project: ProjectData): LocalTimelineView {
  const defaults: LocalTimelineView = { center: project.mainStart, unit: 'tick', zoom: 1, span: null, collapsed: [], scrollTop: 0, scrollLeft: 0, calendarId: project.calendarId, customTicks: '1', customName: '独自単位' };
  try {
    const saved = JSON.parse(localStorage.getItem(`scenario-timeline:v1:${project.projectId}`) ?? 'null') as Partial<LocalTimelineView> | null;
    if (!saved || !isTick(saved.center) || !['tick', 'hour', 'day', 'month', 'year', 'custom'].includes(saved.unit ?? '')) return defaults;
    return { ...defaults, center: saved.center, unit: saved.unit!, zoom: typeof saved.zoom === 'number' && saved.zoom >= .001 && saved.zoom <= 20 ? saved.zoom : 1, span: validSpan(saved.span) ? saved.span : null, collapsed: Array.isArray(saved.collapsed) ? saved.collapsed.filter((id): id is ID => typeof id === 'string') : [], scrollTop: typeof saved.scrollTop === 'number' && Number.isFinite(saved.scrollTop) ? Math.max(0, saved.scrollTop) : 0, scrollLeft: typeof saved.scrollLeft === 'number' && Number.isFinite(saved.scrollLeft) ? Math.max(0, saved.scrollLeft) : 0, selectedId: typeof saved.selectedId === 'string' ? saved.selectedId : null, calendarId: project.calendars.some(calendar => calendar.id === saved.calendarId) ? saved.calendarId! : project.calendarId, customTicks: isTick(saved.customTicks) && parseTick(saved.customTicks) > 0n ? saved.customTicks : '1', customName: typeof saved.customName === 'string' ? saved.customName.slice(0, 128) : defaults.customName };
  } catch { return defaults; }
}

export interface TimelineProps {
  project: ProjectData; selectedId: ID | null; onSelect: (id: ID) => void; onAdd: () => void; onSaveProject?: TimelineSave; onOpenRelation?: (id: ID) => void;
  referenceEntities?: Entity[]; referenceRelations?: Relation[]; referenceCalendars?: CalendarDefinition[]; adoptedReferenceIds?: ID[]; placeFilterId?: ID | null;
  worldTick?: Tick | null; checkpointId?: ID; onViewPointChange?: (at: Tick | null, checkpointId: ID) => void;
  onShowMap?: (placeId: ID, eventId?: ID) => void; onShowRelationships?: (entityId: ID, at?: Tick | null) => void; onShowWorldHistory?: (entityId: ID, at?: Tick | null) => void;
}
export function Timeline({ project, selectedId: externalSelectedId, onSelect, onAdd, onSaveProject, onOpenRelation, referenceEntities = [], referenceRelations = [], referenceCalendars = [], adoptedReferenceIds, placeFilterId, worldTick, checkpointId = '', onViewPointChange, onShowMap, onShowRelationships, onShowWorldHistory }: TimelineProps) {
  const [initial] = useState(() => initialView(project));
  const [localSelectedId, setLocalSelectedId] = useState<ID | null>(initial.selectedId ?? null), selectedId = externalSelectedId ?? localSelectedId;
  useEffect(() => { if (externalSelectedId) setLocalSelectedId(externalSelectedId); }, [externalSelectedId]);
  const [unit, setUnit] = useState<CalendarDisplayUnit>(initial.unit), [zoom, setZoom] = useState(initial.zoom), [fittedSpan, setFittedSpan] = useState<string | null>(initial.span), [center, setCenter] = useState<Tick>(initial.center), [calendarId, setCalendarId] = useState(initial.calendarId);
  const [customTicks, setCustomTicks] = useState<Tick>(initial.customTicks), [customName, setCustomName] = useState(initial.customName), [listPage, setListPage] = useState(0), [unknownPage, setUnknownPage] = useState(0), [relationPage, setRelationPage] = useState(0), [localTick, setLocalTick] = useState<Tick | null>(worldTick !== undefined ? worldTick : initial.center);
  const [jump, setJump] = useState(''), [jumpError, setJumpError] = useState(''), [collapsed, setCollapsed] = useState<ID[]>(initial.collapsed), [mode, setMode] = useState<'timeline' | 'list'>('timeline'), [query, setQuery] = useState('');
  const [viewport, setViewport] = useState({ top: initial.scrollTop, left: initial.scrollLeft, height: 590 }), [relationFilter, setRelationFilter] = useState('all'), [relatedOnly, setRelatedOnly] = useState(false), [linking, setLinking] = useState(false), [linkSource, setLinkSource] = useState<ID | null>(null);
  const [editingRelation, setEditingRelation] = useState<Relation | null>(null), [editingTime, setEditingTime] = useState<ID | null>(null), [laneEditor, setLaneEditor] = useState(false), [mainStartEditor, setMainStartEditor] = useState(false), [mainStartDraft, setMainStartDraft] = useState(project.mainStart), [mainStartValid, setMainStartValid] = useState(true);
  const [shiftEditor, setShiftEditor] = useState(false), [shiftOffset, setShiftOffset] = useState('0'), [shiftPreview, setShiftPreview] = useState<TimeEditPreview | null>(null), [lastChanges, setLastChanges] = useState<TimeEditChange[] | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const canvas = useRef<HTMLDivElement>(null), restored = useRef(false), pendingReveal = useRef<ID | null>(null), previousSelection = useRef<ID | null>(initial.selectedId === selectedId ? selectedId : null);
  const active = useMemo(() => { const local = project.entities.filter(entity => !entity.deletedAt), ids = new Set(project.entities.map(entity => entity.id)); return [...local, ...referenceEntities.filter(entity => !entity.deletedAt && !ids.has(entity.id))]; }, [project.entities, referenceEntities]);
  const entityIndex = useMemo(() => new Map(active.map(entity => [entity.id, entity])), [active]);
  const localEvents = useMemo(() => project.entities.filter((entity): entity is Entity<'event'> => entity.kind === 'event' && !entity.deletedAt), [project.entities]);
  const referenceEvents = useMemo(() => active.filter((entity): entity is Entity<'event'> => entity.kind === 'event' && entity.projectId !== project.projectId), [active, project.projectId]);
  const allEvents = useMemo(() => [...localEvents, ...referenceEvents], [localEvents, referenceEvents]);
  const events = useMemo(() => allEvents.filter(event => !placeFilterId || !!event.data.locationId && compatibleLocations(event.data.locationId, placeFilterId, entityIndex)), [allEvents, placeFilterId, entityIndex]);
  const times = useMemo(() => resolveEventTimes([...localEvents, ...referenceEvents]), [localEvents, referenceEvents]);
  const viewProject = useMemo(() => { const ids = new Set(project.calendars.map(calendar => calendar.id)), relationIds = new Set(project.relations.map(relation => relation.id)); return { ...project, entities: active, relations: [...project.relations, ...referenceRelations.filter(relation => !relationIds.has(relation.id))], calendars: [...project.calendars, ...referenceCalendars.filter(calendar => !ids.has(calendar.id))] }; }, [project, active, referenceRelations, referenceCalendars]);
  const calendar = viewProject.calendars.find(candidate => candidate.id === calendarId) ?? viewProject.calendars.find(candidate => candidate.id === project.calendarId) ?? viewProject.calendars[0];
  const choices = calendarDisplayUnits(calendar), effectiveUnit = choices.find(choice => choice.key === unit)?.available ? unit : 'tick';
  const unitTick = effectiveUnit === 'custom' && (!isTick(customTicks) || parseTick(customTicks) <= 0n) ? 1n : displayUnitTicks(center, calendar, effectiveUnit, customTicks);
  const rawSpan = fittedSpan ? BigInt(fittedSpan) : unitTick * BigInt(Math.max(4, Math.round((effectiveUnit === 'month' || effectiveUnit === 'year' ? 12 : 120) / zoom)));
  const span = rawSpan > MAX_TICK * 2n ? MAX_TICK * 2n : rawSpan < 4n ? 4n : rawSpan, rawOrigin = parseTick(center) - span / 2n;
  const origin = rawOrigin < -MAX_TICK ? -MAX_TICK : rawOrigin + span > MAX_TICK ? MAX_TICK - span : rawOrigin, end = origin + span;
  const lanes = useMemo(() => { const ids = new Set(events.map(event => event.id)), adopted = adoptedReferenceIds === undefined ? undefined : new Set(adoptedReferenceIds); return buildTimelineLanes({ ...viewProject, entities: viewProject.entities.filter(entity => entity.kind === 'event' ? ids.has(entity.id) : !adopted || entity.projectId === project.projectId || !['character', 'group'].includes(entity.kind) || adopted.has(entity.id) || entity.kind === 'group' && (entity.data.members ?? []).some(id => adopted.has(id))) }, collapsed); }, [viewProject.entities, events, collapsed, adoptedReferenceIds, project.projectId]);
  const displayTimes = useMemo(() => new Map([...times].filter(([, time]) => time.status !== 'resolved' || time.calendarId === calendar.id)), [times, calendar.id]);
  const layout = useMemo(() => buildTimelineLayout(lanes, displayTimes, origin.toString(), end.toString()), [lanes, displayTimes, origin, end]);
  const windowRows = useMemo(() => timelineWindow(layout, viewport.top, viewport.height), [layout, viewport.top, viewport.height]);
  const sortedEvents = useMemo(() => [...events].sort((a, b) => { const x = times.get(a.id), y = times.get(b.id); return x?.status === 'resolved' && y?.status === 'resolved' ? compareTicks(x.earliest, y.earliest) || a.name.localeCompare(b.name) : x?.status === 'resolved' ? -1 : y?.status === 'resolved' ? 1 : a.name.localeCompare(b.name); }), [events, times]);
  const filteredEvents = useMemo(() => sortedEvents.filter(event => !query || `${event.name} ${fieldText(event.data.summary)} ${event.id}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [sortedEvents, query]);
  const unknown = useMemo(() => events.filter(event => { const time = times.get(event.id); return time?.status !== 'resolved' || time.calendarId !== calendar.id; }), [events, times, calendar.id]);
  const eventTypes = RELATION_TYPES.filter(type => type.fromKinds.includes('event') && type.toKinds.includes('event'));
  const percent = (tick: Tick) => Number((parseTick(tick) - origin) * 100_000n / span) / 1000;
  const axisTicks = useMemo(() => calendarAxisTicks(origin.toString(), end.toString(), calendar, effectiveUnit, isTick(customTicks) && parseTick(customTicks) > 0n ? customTicks : '1'), [origin, end, calendar, effectiveUnit, customTicks]);
  const safeListPage = Math.min(listPage, Math.max(0, Math.ceil(filteredEvents.length / PAGE_SIZE) - 1)), safeUnknownPage = Math.min(unknownPage, Math.max(0, Math.ceil(unknown.length / PAGE_SIZE) - 1));
  const selected = selectedId ? entityIndex.get(selectedId) : undefined, selectedTick = worldTick !== undefined ? worldTick : localTick;
  const context = useMemo(() => checkpointContext(viewProject, checkpointId), [viewProject, checkpointId]), point = useMemo(() => ({ at: selectedTick, context }), [selectedTick, context]), worldAssessment = useMemo(() => createWorldAssessment(viewProject, point), [viewProject, point]);
  const selectedPeople = selected?.kind === 'event' ? [...new Set((selected.data.participants ?? []).map(participant => participant.characterId))].flatMap(id => { const person = entityIndex.get(id); return person?.kind === 'character' ? [person] : []; }) : selected?.kind === 'character' ? [selected] : [];
  const eventRelations = useMemo(() => viewProject.relations.filter(relation => !relation.deletedAt && entityIndex.get(relation.fromId)?.kind === 'event' && entityIndex.get(relation.toId)?.kind === 'event' && assessWorldValidity(relation.validity, point).value !== 'false' && (relationFilter === 'all' || relation.relationType === relationFilter) && (!relatedOnly || relation.fromId === selectedId || relation.toId === selectedId)), [viewProject.relations, entityIndex, relationFilter, relatedOnly, selectedId, point]);
  const safeRelationPage = Math.min(relationPage, Math.max(0, Math.ceil(eventRelations.length / PAGE_SIZE) - 1));

  useEffect(() => {
    const node = canvas.current; if (!node || mode !== 'timeline') return;
    node.scrollTop = restored.current ? viewport.top : initial.scrollTop;
    node.scrollLeft = restored.current ? viewport.left : initial.scrollLeft;
    restored.current = true;
    const update = () => setViewport({ top: node.scrollTop, left: node.scrollLeft, height: node.clientHeight || 590 });
    update(); const observer = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(update) : undefined; observer?.observe(node);
    window.addEventListener('resize', update); return () => { observer?.disconnect(); window.removeEventListener('resize', update); };
  }, [mode, events.length > 0]);
  useEffect(() => { try { localStorage.setItem(`scenario-timeline:v1:${project.projectId}`, JSON.stringify({ center, unit, zoom, span: fittedSpan, collapsed, scrollTop: viewport.top, scrollLeft: viewport.left, calendarId, customTicks, customName, selectedId })); } catch { /* A blocked preference store does not block editing. */ } }, [project.projectId, center, unit, zoom, fittedSpan, collapsed, viewport.top, viewport.left, calendarId, customTicks, customName, selectedId]);
  useEffect(() => {
    const node = canvas.current; if (!node) return;
    const point = pendingReveal.current ? layout.positions.get(pendingReveal.current)?.[0] : undefined, lane = pendingReveal.current ? layout.rows.find(row => row.lane.characterId === pendingReveal.current || row.lane.groupId === pendingReveal.current) : undefined;
    if (point || lane) { node.scrollTop = Math.max(0, (point?.y ?? lane!.top) - 100); pendingReveal.current = null; setViewport(previous => ({ ...previous, top: node.scrollTop })); }
    else if (viewport.top > layout.height) { node.scrollTop = Math.max(0, layout.height - viewport.height); setViewport(previous => ({ ...previous, top: node.scrollTop })); }
  }, [layout, mode]);
  useEffect(() => { if (worldTick && isTick(worldTick) && calendar.id === project.calendarId) setCenter(worldTick); }, [worldTick]);
  useEffect(() => {
    if (previousSelection.current === selectedId) return; previousSelection.current = selectedId;
    if (!selectedId) return;
    const time = times.get(selectedId); if (time?.status === 'resolved') { setCalendarId(time.calendarId); setCenter(time.earliest); setLocalTick(time.calendarId === project.calendarId ? time.earliest : null); }
    if (mode === 'timeline') reveal(selectedId); else { setQuery(''); setListPage(Math.max(0, Math.floor(sortedEvents.findIndex(event => event.id === selectedId) / PAGE_SIZE))); }
  }, [selectedId]);
  const moveCenter = (tick: Tick, sourceCalendarId = calendar.id) => { setCenter(tick); const at = sourceCalendarId === project.calendarId ? tick : null; setLocalTick(at); onViewPointChange?.(at, checkpointId); };
  const collapse = (id: ID) => setCollapsed(previous => previous.includes(id) ? previous.filter(candidate => candidate !== id) : [...previous, id]);
  const navigatePeriod = (direction: bigint) => { const next = parseTick(center) + span * direction; moveCenter((next > MAX_TICK ? MAX_TICK : next < -MAX_TICK ? -MAX_TICK : next).toString()); };
  const fit = () => {
    const known = events.flatMap(event => times.get(event.id) ?? []).filter((time): time is Extract<TimeResolution, { status: 'resolved' }> => time.status === 'resolved' && time.calendarId === calendar.id);
    if (!known.length) { setCalendarId(project.calendarId); moveCenter(project.mainStart, project.calendarId); return; }
    let minimum = parseTick(known[0].earliest), maximum = parseTick(known[0].endLatest);
    for (const time of known) { const start = parseTick(time.earliest), stop = parseTick(time.endLatest); if (start < minimum) minimum = start; if (stop > maximum) maximum = stop; }
    moveCenter(((minimum + maximum) / 2n).toString()); const distance = maximum - minimum; setFittedSpan((distance + distance / 5n + 4n > MAX_TICK * 2n ? MAX_TICK * 2n : distance + distance / 5n + 4n).toString());
  };
  const reveal = (id: ID) => {
    const time = times.get(id); if (time?.status === 'resolved') { setCalendarId(time.calendarId); moveCenter(time.earliest, time.calendarId); }
    const event = entityIndex.get(id); if (!event || !['event', 'character', 'group'].includes(event.kind)) return;
    const participantIds = new Set(event.kind === 'event' ? (event.data.participants ?? []).map(participant => participant.characterId) : event.kind === 'character' ? [event.id] : []), expand = new Set<ID>();
    for (const group of active) if (group.kind === 'group' && (group.data.members ?? []).some(member => participantIds.has(member))) {
      let current: Entity | undefined = group;
      while (current?.kind === 'group' && !expand.has(current.id)) { expand.add(current.id); current = current.data.parentId ? entityIndex.get(current.data.parentId) : undefined; }
    }
    setCollapsed(previous => previous.filter(groupId => !expand.has(groupId))); pendingReveal.current = id; setMode('timeline');
    const point = layout.positions.get(id)?.[0]; if (point && canvas.current) { canvas.current.scrollTop = Math.max(0, point.y - 100); setViewport(previous => ({ ...previous, top: canvas.current!.scrollTop })); pendingReveal.current = null; }
  };
  const newRelation = (fromId = '', toId = ''): Relation => ({ id: newId(), projectId: project.projectId, revision: '0', fromId, toId, relationType: 'causes', direction: 'forward', validity: emptyValidity(), evidenceIds: [], status: 'provisional', visibility: 'private' });
  const chooseEvent = (id: ID) => {
    if (!linking) { setLocalSelectedId(id); const time = times.get(id), at = time?.status === 'resolved' && time.calendarId === project.calendarId ? time.earliest : null; setLocalTick(at); onViewPointChange?.(at, checkpointId); onSelect(id); return; }
    if (!linkSource) { setLinkSource(id); setNotice(`始点「${labelOf(entityIndex.get(id))}」を選択しました。終点を選んでください。`); return; }
    if (linkSource === id) { setError('終点には別の出来事を選んでください。'); return; }
    setEditingRelation(newRelation(linkSource, id)); setLinking(false); setLinkSource(null); setError('');
  };
  const openRelation = (relation: Relation) => { if (relation.projectId !== project.projectId) onSelect(relation.id); else if (onOpenRelation) onOpenRelation(relation.id); else if (onSaveProject) setEditingRelation(structuredClone(relation)); };
  const arrowTop = Math.max(50, viewport.top - 100), arrowHeight = viewport.height + 200;

  return <section className="timeline-section rb03-timeline"><div className="view-switch" aria-label="年表の表示"><button type="button" className={mode === 'timeline' ? 'active' : ''} onClick={() => setMode('timeline')}><Icon name="timeline" size={17}/>年表</button><button type="button" className={mode === 'list' ? 'active' : ''} onClick={() => setMode('list')}><Icon name="note" size={17}/>出来事一覧</button></div>
    <div className="timeline-controls"><div className="control-group"><label>表示する暦<select aria-label="年表の暦" value={calendar.id} onChange={event => { setCalendarId(event.target.value); if (unit === 'hour' && viewProject.calendars.find(candidate => candidate.id === event.target.value)?.kind !== 'gregorian') setUnit('tick'); setFittedSpan(null); }}>{viewProject.calendars.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label><label>表示単位<select aria-label="年表の表示単位" value={effectiveUnit} onChange={event => { setUnit(event.target.value as CalendarDisplayUnit); setFittedSpan(null); }}>{choices.map(choice => <option key={choice.key} value={choice.key} disabled={!choice.available} title={choice.reason}>{choice.label}{choice.reason ? `（${choice.reason}）` : ''}</option>)}</select></label><div className="zoom-controls"><button type="button" className="icon-button" aria-label="年表を縮小" disabled={fittedSpan ? span >= MAX_TICK * 2n : zoom <= .001} onClick={() => { if (fittedSpan) setFittedSpan((span * 2n > MAX_TICK * 2n ? MAX_TICK * 2n : span * 2n).toString()); else setZoom(Math.max(.001, zoom / 2)); }}>−</button><span>{fittedSpan ? '全体幅' : zoom < 1 ? `${zoom.toFixed(3)}倍` : `${zoom}倍`}</span><button type="button" className="icon-button" aria-label="年表を拡大" disabled={fittedSpan ? span <= 4n : zoom >= 20} onClick={() => { if (fittedSpan) setFittedSpan((span / 2n).toString()); else setZoom(Math.min(20, zoom * 2)); }}>＋</button></div></div><div className="control-group"><button type="button" className="button subtle small" onClick={fit}>全体へ戻る</button><button type="button" className="button subtle small" onClick={() => { setCalendarId(project.calendarId); moveCenter(project.mainStart, project.calendarId); }}>本編開始へ</button>{selectedId && <button type="button" className="button subtle small" onClick={() => reveal(selectedId)}>選択対象へ</button>}</div></div>
    {effectiveUnit === 'custom' && <div className="timeline-custom-unit"><label>独自単位名<input aria-label="独自表示単位名" value={customName} onChange={event => setCustomName(event.target.value)}/></label><label>1単位のtick数<input aria-label="独自表示単位のtick数" value={customTicks} onChange={event => { setCustomTicks(event.target.value); setFittedSpan(null); }}/></label>{(!isTick(customTicks) || parseTick(customTicks) <= 0n) && <span className="field-error" role="alert">正の整数tickを入力してください。</span>}</div>}
    <div className="timeline-context"><span><span className="legend-dot"/>{calendar.name}</span><span>本編開始 {project.mainStart} tick</span><span>表示 {origin.toString()} 〜 {end.toString()} tick</span><span>中心の本編基準 {formatRelativeTick(center, project.mainStart, unitTick.toString())} {effectiveUnit === 'custom' ? customName : choices.find(choice => choice.key === effectiveUnit)?.label}</span></div>
    {onSaveProject && <div className="timeline-edit-controls"><button type="button" className="button secondary small" onClick={() => setLaneEditor(true)}>グループ・人物レーン</button><button type="button" className="button secondary small" disabled={selected?.kind !== 'event' || selected.projectId !== project.projectId} onClick={() => { if (selected?.kind === 'event') setEditingTime(selected.id); }}>選択した出来事の日時・制約</button><button type="button" className="button secondary small" onClick={() => { setMainStartDraft(project.mainStart); setMainStartValid(true); setMainStartEditor(true); }}>本編開始の基準を変更</button><button type="button" className="button secondary small" onClick={() => { setShiftPreview(null); setShiftEditor(true); }}>全出来事の日時を移動</button><button type="button" className="button secondary small" disabled={busy || !lastChanges} onClick={async () => { if (!lastChanges) return; setBusy(true); setError(''); try { await onSaveProject(undoTimeEdit(project, lastChanges), '日時と承認済み連動先の変更を一括取消'); setLastChanges(null); setNotice('日時の変更をすべて取り消しました。'); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}>前回の日時変更を一括取消</button></div>}
    {placeFilterId && <p className="field-hint" role="status">場所で絞り込み中：{labelOf(entityIndex.get(placeFilterId))} · {events.length} / {allEvents.length}件{onShowMap && <button type="button" className="button secondary small" onClick={() => onShowMap(placeFilterId, selected?.kind === 'event' ? selected.id : undefined)}>この場所の地図へ</button>}</p>}
    {selected?.kind === 'event' && <div className="timeline-edit-controls">{selected.projectId !== project.projectId && <><span className="field-hint">共通世界の固定版です。日時は元情報の改訂から変更します。</span><button type="button" className="button secondary small" onClick={() => onSelect(selected.id)}>固定版の出来事を開く</button></>}{selected.data.locationId && onShowMap && <button type="button" className="button secondary small" onClick={() => onShowMap(selected.data.locationId!, selected.id)}>出来事の場所を地図で開く</button>}{onShowRelationships && <button type="button" className="button secondary small" onClick={() => onShowRelationships(selected.id, selectedTick)}>この出来事の関係図へ</button>}</div>}
    {notice && <p className="field-hint" role="status">{notice}</p>}{error && <div className="error-notice" role="alert">{error}</div>}
    {events.length === 0 ? <EmptyState icon="timeline" title="物語の時間を並べましょう" action={<button type="button" className="button primary" onClick={onAdd}><Icon name="plus"/>出来事を追加</button>}>日時が未定でも、要約から出来事を残せます。</EmptyState> : mode === 'list' ? <><div className="timeline-list-search"><input type="search" aria-label="出来事一覧を検索" placeholder="出来事の名前・要約・IDで検索" value={query} onChange={event => { setQuery(event.target.value); setListPage(0); }}/><span>{filteredEvents.length}件</span></div><div className="event-table"><div className="table-labels"><span>出来事</span><span>世界内日時</span></div>{filteredEvents.slice(safeListPage * PAGE_SIZE, (safeListPage + 1) * PAGE_SIZE).map(event => <button key={event.id} data-event-id={event.id} className={`event-table-row ${selectedId === event.id ? 'selected' : ''}`} type="button" onClick={() => chooseEvent(event.id)}><span><strong>{event.name || fieldText(event.data.summary).slice(0, 40)}</strong><small>{event.data.participants?.map(participant => `${labelOf(entityIndex.get(participant.characterId))}（${PARTICIPANT_ROLES[participant.role]}）`).join('、') || '参加人物未設定'}</small></span><span>{timeLabel(event.data.time, viewProject)}<StatusBadge status={event.status}/></span></button>)}</div><TimelinePagination page={safeListPage} total={filteredEvents.length} onChange={setListPage}/></> : <>
      <div className="timeline-canvas" ref={canvas} tabIndex={0} aria-label="世界内年表。左右と上下にスクロールできます。人物名と時間ラベルは固定されます。" onScroll={event => { const node = event.currentTarget; setViewport({ top: node.scrollTop, left: node.scrollLeft, height: node.clientHeight }); }}><div className="timeline-grid" style={{ height: `${layout.height}px` }}><div className="timeline-axis"><div className="lane-label axis-label">人物・グループ</div><div className="axis-ticks">{axisTicks.map(value => <span key={value} style={{ left: `${percent(value)}%` }} title={`${value} tick`}>{effectiveUnit === 'tick' ? value : effectiveUnit === 'custom' ? `${parseTick(value) / parseTick(isTick(customTicks) && parseTick(customTicks) > 0n ? customTicks : '1')} ${customName}` : formatCalendarTick(value, calendar)}</span>)}</div></div>
        {windowRows.map(({ row, boxes }) => { const lane = row.lane;
          if (lane.kind === 'group') return <div className="timeline-group" key={lane.id} data-lane-id={lane.id} style={{ top: row.top, height: row.height }}><button type="button" className="lane-label group-label" onClick={() => collapse(lane.id)} aria-expanded={!collapsed.includes(lane.id)} title={lane.name}><span>{collapsed.includes(lane.id) ? '▸' : '▾'}</span><span style={{ paddingLeft: `${lane.depth * 8}px` }}>{lane.name}</span></button></div>;
          const group = lane.groupId ? entityIndex.get(lane.groupId) : undefined;
          return <div key={lane.id} data-lane-id={lane.id} className={`timeline-lane ${lane.kind === 'common' ? 'common-lane' : ''}`} style={{ top: row.top, height: row.height }}><div className="lane-label" title={lane.name} style={{ minHeight: 88 }}><span>{lane.kind === 'common' && <span className="common-label">共通</span>}{lane.characterId ? <button type="button" className="timeline-person-label" onClick={() => onSelect(lane.characterId!)}>{lane.name}</button> : lane.name}</span>{group && <small>{labelOf(group)}</small>}<small>{row.boxes.length}件{lane.depth > 1 ? ` · 階層${lane.depth}` : ''}</small></div><div className="lane-track">{calendar.id === project.calendarId && percent(project.mainStart) >= 0 && percent(project.mainStart) <= 100 && <span className="main-start-line" style={{ left: `${percent(project.mainStart)}%` }} aria-label="本編開始"/>}{boxes.map(box => { const event = entityIndex.get(box.eventId); if (event?.kind !== 'event') return null; const roles = lane.characterId ? (event.data.participants ?? []).filter(participant => participant.characterId === lane.characterId).map(participant => PARTICIPANT_ROLES[participant.role]).join('・') : '';
            return <button type="button" key={event.id} data-event-id={event.id} className={`timeline-event event-${event.data.time.mode} ${selectedId === event.id ? 'selected' : ''} ${linkSource === event.id ? 'link-source' : ''}`} style={{ left: `${box.left}%`, width: `${box.width}%`, top: `${box.slot * 60 + 12}px` }} onClick={() => chooseEvent(event.id)} title={`${event.name} · ${timeLabel(event.data.time, viewProject)}${roles ? ` · ${roles}` : ''}`}><span className="event-shape"/>{event.name || fieldText(event.data.summary).slice(0, 24)}<small>{event.projectId !== project.projectId && '固定世界版 · '}{event.data.time.mode === 'interval' ? '期間' : event.data.time.mode === 'uncertain' ? '不確定な範囲' : event.data.time.mode === 'relative' ? '相対日時' : '瞬間'}{roles && ` · ${roles}`}</small></button>;
          })}</div></div>;
        })}
        <svg className="timeline-arrows" viewBox={`0 ${arrowTop} 1000 ${arrowHeight}`} preserveAspectRatio="none" style={{ top: arrowTop, height: arrowHeight }} aria-label="出来事間の意味付き矢印"><defs><marker id={`timeline-arrow-${project.projectId}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="var(--accent)"/></marker></defs>{eventRelations.map(relation => {
          const from = layout.positions.get(relation.fromId)?.[0], to = layout.positions.get(relation.toId)?.[0];
          if (!from || !to || Math.max(from.y, to.y) < arrowTop || Math.min(from.y, to.y) > arrowTop + arrowHeight) return null;
          const ax = from.x * 10, bx = to.x * 10, curve = Math.max(40, Math.abs(bx - ax) / 3), d = `M ${ax} ${from.y} C ${ax + curve} ${from.y - 22}, ${bx - curve} ${to.y - 22}, ${bx} ${to.y}`;
          const name = `${labelOf(entityIndex.get(relation.fromId))} ${relation.direction === 'symmetric' ? '↔' : '→'} ${labelOf(entityIndex.get(relation.toId))} · ${RELATION_LABELS[relation.relationType] ?? relation.relationType}`;
          return <g key={relation.id} data-relation-id={relation.id} role="button" tabIndex={0} aria-label={`${name}の関係を編集`} onClick={() => openRelation(relation)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openRelation(relation); } }}><title>{name}</title><path className="timeline-arrow-hit" d={d} fill="none" stroke="transparent" strokeWidth="24"/><path d={d} fill="none" stroke="var(--accent)" strokeWidth="2" markerEnd={`url(#timeline-arrow-${project.projectId})`} markerStart={relation.direction === 'symmetric' ? `url(#timeline-arrow-${project.projectId})` : undefined}/><text x={(ax + bx) / 2} y={(from.y + to.y) / 2 - 14} textAnchor="middle">{RELATION_LABELS[relation.relationType] ?? relation.relationType}</text></g>;
        })}</svg>
      </div></div><div className="timeline-bottom"><div className="timeline-legend"><span><i className="legend-instant"/>瞬間</span><span><i className="legend-interval"/>期間</span><span><i className="legend-uncertain"/>不確定な範囲</span><span>相対日時は基準から解決して表示</span></div><span>{layout.visibleEventIds.size} / {events.length}件 · レーン上の表示 {layout.displayedBoxes}件</span></div>
    </>}
    <div className="timeline-navigation"><button type="button" className="button secondary small" onClick={() => navigatePeriod(-1n)}><Icon name="back" size={16}/>前の期間</button><form onSubmit={event => { event.preventDefault(); if (isTick(jump)) { moveCenter(jump); setJumpError(''); } else setJumpError('38桁以内の整数tickを入力してください。'); }}><input aria-label="移動先の世界内tick" placeholder="tickへ移動" value={jump} onChange={event => setJump(event.target.value)}/><button className="button secondary small" type="submit">移動</button></form><button type="button" className="button secondary small" onClick={() => navigatePeriod(1n)}>次の期間<Icon name="arrow" size={16}/></button></div>{jumpError && <p className="field-error" role="alert">{jumpError}</p>}
    <details className="timeline-calendar-jump"><summary>暦の日付へ移動する</summary><CalendarJump calendar={calendar} onJump={moveCenter}/></details>
    <section className="timeline-relations"><div className="section-heading"><h3>出来事間の関係</h3><span className="count-pill">{eventRelations.length}</span></div><div className="timeline-relation-controls"><select aria-label="年表の関係を種類で絞り込む" value={relationFilter} onChange={event => { setRelationFilter(event.target.value); setRelationPage(0); }}><option value="all">すべての出来事間の関係</option>{eventTypes.map(type => <option key={type.key} value={type.key}>{type.label}</option>)}</select><label className="timeline-check"><input type="checkbox" checked={relatedOnly} onChange={event => { setRelatedOnly(event.target.checked); setRelationPage(0); }}/>選択した出来事に関係する線</label>{onSaveProject && <><button type="button" className="button secondary small" aria-pressed={linking} onClick={() => { setLinking(previous => !previous); setLinkSource(null); setNotice(''); }}>{linking ? 'タップで結ぶ操作を中止' : '始点 → 終点をタップで結ぶ'}</button><button type="button" className="button secondary small" onClick={() => setEditingRelation(newRelation(selected?.kind === 'event' ? selected.id : ''))}>一覧から関係を追加</button></>}</div>{linking && <p className="field-hint" role="status">{linkSource ? '終点の出来事をタップしてください。' : '始点の出来事をタップしてください。'}出来事一覧からも選べます。</p>}
      {eventRelations.slice(safeRelationPage * PAGE_SIZE, (safeRelationPage + 1) * PAGE_SIZE).map(relation => <div className="timeline-relation-row" key={relation.id}><button type="button" className="button subtle small" onClick={() => { reveal(relation.fromId); onSelect(relation.fromId); }}>{labelOf(entityIndex.get(relation.fromId))}</button><button type="button" className="button secondary small" data-relation-id={relation.id} onClick={() => openRelation(relation)}>{RELATION_LABELS[relation.relationType] ?? relation.relationType} {relation.direction === 'symmetric' ? '↔' : '→'}</button><button type="button" className="button subtle small" onClick={() => { reveal(relation.toId); onSelect(relation.toId); }}>{labelOf(entityIndex.get(relation.toId))}</button></div>)}<TimelinePagination page={safeRelationPage} total={eventRelations.length} onChange={setRelationPage}/>
    </section>
    {selectedPeople.length > 0 && <section className="timeline-life"><div className="section-heading"><h3>選択時点の人物</h3><span>{selectedTick ? formatCalendarTick(selectedTick, calendar) : '世界時点未選択・暦の対応未定'}</span></div>{selectedPeople.map(person => {
      const summary = selectedTick ? characterTimeSummary(person, selectedTick, calendar, [...localEvents, ...referenceEvents], times) : { age: '年齢不明', state: 'unknown' as const }, membership = worldAssessment.stateCandidates(person.id, WORLD_PREDICATES.membership), appearances = worldAssessment.stateCandidates(person.id, WORLD_PREDICATES.appearance);
      return <article key={person.id}><button type="button" className="button subtle small" onClick={() => onSelect(person.id)}>{labelOf(person)}</button><strong>{summary.age} · {LIFE_STATES[summary.state]}</strong>{'reason' in summary && summary.reason && <p>{summary.reason}</p>}<p>所属：{membership.candidates.length ? membership.candidates.map(candidate => `${assertionValueLabel(candidate.assertion.data.value, entityIndex)}${candidate.assessment.value === 'unknown' ? '（時期・経路未確認）' : ''}`).join('、') : 'この時点の所属期間は未登録'}</p>{appearances.candidates.filter(candidate => selected?.kind !== 'event' || (candidate.assertion.data.sourceIds ?? []).includes(selected.id)).map(candidate => <p key={candidate.assertion.id}>{assertionValueLabel(candidate.assertion.data.value, entityIndex)} · {candidate.assertion.data.reason || '理由未登録'}{candidate.assessment.value === 'unknown' && '（時期・経路未確認）'}</p>)}{onShowRelationships && <button type="button" className="button secondary small" onClick={() => onShowRelationships(person.id, selectedTick)}>この人物の関係図へ</button>}{onShowWorldHistory && <button type="button" className="button secondary small" onClick={() => onShowWorldHistory(person.id, selectedTick)}>誕生・死亡・所属・例外の履歴を編集</button>}</article>;
    })}</section>}
    {unknown.length > 0 && <section className="undated-section"><div className="section-heading"><h3>日時未定・未解決・別の暦</h3><span className="count-pill">{unknown.length}</span></div><div className="compact-cards">{unknown.slice(safeUnknownPage * PAGE_SIZE, (safeUnknownPage + 1) * PAGE_SIZE).map(event => { const time = times.get(event.id); return <button type="button" key={event.id} data-event-id={event.id} className="compact-card" onClick={() => chooseEvent(event.id)}><Icon name="clock"/><span><strong>{labelOf(event)}</strong><small>{time?.status !== 'resolved' ? time?.reason : `別の暦：${timeLabel(event.data.time, viewProject)}`}</small></span><Icon name="arrow" size={16}/></button>; })}</div><TimelinePagination page={safeUnknownPage} total={unknown.length} onChange={setUnknownPage}/></section>}
    {editingTime && onSaveProject && entityIndex.get(editingTime)?.kind === 'event' && <TimelineTimeEditor project={project} referenceProject={viewProject} point={point} event={entityIndex.get(editingTime) as Entity<'event'>} onClose={() => setEditingTime(null)} onSave={onSaveProject} onApplied={changes => { setLastChanges(changes); setNotice('日時と承認した連動先を一括保存しました。取消ボタンですべて戻せます。'); }}/>} {editingRelation && onSaveProject && <TimelineRelationEditor project={project} referenceProject={viewProject} relation={editingRelation} onSave={onSaveProject} onClose={() => setEditingRelation(null)} onSelect={id => { setEditingRelation(null); onSelect(id); }}/>} {laneEditor && onSaveProject && <TimelineLaneEditor project={project} onSave={onSaveProject} onClose={() => setLaneEditor(false)} collapsed={collapsed} onCollapse={collapse}/>}
    {mainStartEditor && onSaveProject && <Modal title="本編開始の基準を変更" onClose={() => { if (!busy) setMainStartEditor(false); }}><fieldset disabled={busy} className="world-save-fields"><p className="field-hint">本編の基準点を変更します。出来事の絶対日時は保持され、相対表示だけ更新されます。</p><TickInput label="本編開始の世界内tick" value={mainStartDraft} calendar={viewProject.calendars.find(item => item.id === project.calendarId)!} onChange={setMainStartDraft} onValid={setMainStartValid}/>{error && <p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setMainStartEditor(false)}>中止</button><button type="button" className="button primary" disabled={busy || !mainStartValid || !isTick(mainStartDraft)} onClick={async () => { setBusy(true); setError(''); try { await onSaveProject({ ...project, mainStart: mainStartDraft }, '本編開始の基準点だけ変更'); setMainStartEditor(false); setNotice('本編の基準を保存しました。'); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}>本編の基準を保存</button></div></fieldset></Modal>}
    {shiftEditor && onSaveProject && <Modal title="全出来事の日時を移動" onClose={() => { if (!busy) setShiftEditor(false); }} wide><fieldset disabled={busy} className="world-save-fields"><p className="field-hint">確定・期間・不確定日時を同じ時間差で移動します。相対日時は基準に追随します。本編開始の基準点は保持します。</p><div className="form-field"><label>移動する時間差（tick）</label><input aria-label="全出来事を移動するtick差" value={shiftOffset} onChange={event => { setShiftOffset(event.target.value); setShiftPreview(null); }}/></div><button type="button" className="button secondary" disabled={busy || !isTick(shiftOffset)} onClick={() => { try { setShiftPreview(shiftAllEventTimes(project, shiftOffset, referenceEvents)); setError(''); } catch (cause) { setError((cause as Error).message); } }}>全出来事の変更前後を確認</button>{shiftPreview && <><PreviewTable preview={shiftPreview} project={viewProject}/><WorldTimeImpactPreview preview={shiftPreview} project={viewProject} point={point}/></>} {error && <p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setShiftEditor(false)}>中止</button><button type="button" className="button primary" disabled={busy || !shiftPreview?.canApply} onClick={async () => { if (!shiftPreview) return; setBusy(true); setError(''); try { await onSaveProject(applyTimeEditPreview(project, shiftPreview), '全出来事の日時を差分確認して一括移動'); setLastChanges(shiftPreview.changes); setShiftEditor(false); setNotice('全出来事の日時を移動しました。取消ボタンで戻せます。'); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}>確認した日時を一括移動</button></div></fieldset></Modal>}
  </section>;
}

function CalendarJump({ calendar, onJump }: { calendar: ProjectData['calendars'][number]; onJump: (tick: Tick) => void }) {
  const [tick, setTick] = useState('0'), [valid, setValid] = useState(true);
  return <form onSubmit={event => { event.preventDefault(); if (valid && isTick(tick)) onJump(tick); }}><TickInput label="移動先の世界内日時" value={tick} calendar={calendar} onChange={setTick} onValid={setValid}/><button className="button secondary small" type="submit" disabled={!valid || !isTick(tick)}>この日時へ移動</button></form>;
}
