import { useEffect, useMemo, useRef, useState } from 'react';
import type { Condition, Entity, ID, ProjectData, RuntimeContext, Tick, TimeSpec, Validity } from '../domain/types';
import { emptyValidity } from '../domain/model';
import { compareTicks, isTick, MAX_TICK, parseTick } from '../domain/time';
import { assessWorldValidity, type WorldPoint } from '../domain/world';
import { ConditionEditor, RefSelect } from './Fields';
import { EntityChoice, TickInput } from './TimelineEditors';
import { PagedSelect } from './PagedSelect';

export function ValidityEditor({ value, project, onChange, onValid, scope }: { value: Validity | null | undefined; project: ProjectData; scope: string; onChange: (value: Validity) => void; onValid?: (valid: boolean) => void }) {
  const validity = value ?? emptyValidity(), range = validity.worldRange;
  const calendar = project.calendars.find(item => item.id === project.calendarId);
  const parts = useRef<Record<string, boolean>>({}), rangeRef = useRef(range); rangeRef.current = range;
  const validRange = (next: Validity['worldRange']) => !next || (next.start === null || isTick(next.start)) && (next.end === null || isTick(next.end)) && (!next.start || !next.end || compareTicks(next.start, next.end) < 0);
  const ordered = validRange(range);
  const partsValid = (next: Validity['worldRange']) => Object.entries(parts.current).every(([key, valid]) => (key === 'start' || key === 'end') && (!next || next[key] === null) || valid);
  const report = (key: string, valid: boolean) => { parts.current = { ...parts.current, [key]: valid }; onValid?.(partsValid(rangeRef.current) && validRange(rangeRef.current)); };
  const setRange = (next: Validity['worldRange']) => { rangeRef.current = next; onChange({ ...validity, worldRange: next }); onValid?.(validRange(next) && partsValid(next)); };
  return <div className="world-validity"><label className="checkbox-label"><input type="checkbox" checked={!!range} onChange={event => setRange(event.target.checked ? { start: null, end: null } : null)}/>世界内の期間を指定する</label>{range && <><p className="field-hint">開始を含み、終了を含まない期間です。開始または終了を空欄にするとその側の限界を指定しません。</p>{(['start', 'end'] as const).map(key => <div key={key}><label className="checkbox-label"><input type="checkbox" checked={range[key] !== null} onChange={event => { report(key, true); setRange({ ...range, [key]: event.target.checked ? '0' : null }); }}/>{key === 'start' ? '開始時点を指定' : '終了時点を指定'}</label>{range[key] !== null && calendar && <TickInput label={key === 'start' ? '有効期間の開始' : '有効期間の終了'} value={range[key]!} calendar={calendar} onChange={tick => setRange({ ...range, [key]: tick })} onValid={valid => report(key, valid)}/>}</div>)}{!ordered && <p className="field-error" role="alert">終了は開始より後にしてください。</p>}</>}
    <div className="form-field"><label>有効になる経路・状態</label><ConditionEditor project={project} scope={`${scope}:condition`} value={validity.routeCondition} onChange={condition => onChange({ ...validity, routeCondition: condition as Condition | null })} onValid={valid => report('condition', valid)}/></div>
    <details className="advanced-details"><summary>提示位置の範囲</summary><RefSelect label="有効になる提示位置" project={project} value={validity.presentationAnchor?.entityId} kinds={['scene', 'dialogue_line', 'flow_node', 'chapter']} onChange={id => onChange({ ...validity, presentationAnchor: id ? { ...(validity.presentationAnchor ?? {}), entityId: id } : null })}/>{validity.presentationAnchor && <p className="field-hint">登録された本文内の位置は保持されます。本文の位置を細かく直すときは元の情報を開いてください。</p>}</details>
  </div>;
}

export function checkpointContext(project: ProjectData, id: ID): RuntimeContext | undefined {
  const checkpoint = project.entities.find((entity): entity is Entity<'checkpoint'> => entity.id === id && !entity.deletedAt && entity.kind === 'checkpoint');
  return checkpoint ? { state: checkpoint.data.runtimeState, entities: project.entities, variables: project.entities.filter((entity): entity is Entity<'variable'> => entity.kind === 'variable' && !entity.deletedAt) } : undefined;
}
export function WorldPointFields({ project, at, checkpointId, onAtChange, onCheckpointChange }: { project: ProjectData; at: Tick | null; checkpointId: ID; onAtChange: (at: Tick | null) => void; onCheckpointChange: (id: ID) => void }) {
  const [current, setRaw] = useState(at ?? ''); useEffect(() => setRaw(at ?? ''), [at]);
  const valid = current === '' || isTick(current), checkpoints = useMemo(() => project.entities.filter((entity): entity is Entity<'checkpoint'> => !entity.deletedAt && entity.kind === 'checkpoint'), [project.entities]);
  return <div className="world-point-fields"><div className="form-field"><label>世界時点（tick）<input aria-label="世界時点（tick）" inputMode="numeric" value={current} onChange={event => { const next = event.target.value; setRaw(next); if (next === '' || isTick(next)) onAtChange(next || null); }}/></label>{!valid && <p className="field-error">世界時刻は38桁までの整数です。</p>}</div><RefSelect label="経路・状態の記録" project={{ ...project, entities: checkpoints }} kinds={['checkpoint']} value={checkpointId} onChange={id => onCheckpointChange(id ?? '')}/><p className="field-hint">経路の記録を選ぶと、その記録の状態値を使います。未選択の条件は未確認として表示します。</p></div>;
}
export function ValidityBadge({ value, point }: { value: Validity | null | undefined; point: WorldPoint }) { const result = assessWorldValidity(value, point); return <span title={result.reasons.join(' ')} className={`world-certainty world-certainty-${result.value}`}>{result.value === 'true' ? '有効' : result.value === 'false' ? '範囲外' : '時点・経路が未確認'}</span>; }

export function DurationInput({ label, value, ticksPerDay, onChange, onValid }: { label: string; value: Tick; ticksPerDay: Tick; onChange: (value: Tick) => void; onValid?: (valid: boolean) => void }) {
  const [unit, setUnit] = useState<'tick' | 'day'>('tick'), width = unit === 'day' ? parseTick(ticksPerDay) : 1n;
  const valid = isTick(value) && parseTick(value) >= 0n, divisible = isTick(value) && parseTick(value) % parseTick(ticksPerDay) === 0n;
  return <label>{label}<div className="world-inline-actions"><input aria-label={label} inputMode="numeric" value={isTick(value) && parseTick(value) % width === 0n ? (parseTick(value) / width).toString() : value} onChange={event => { const raw = event.target.value, converted = isTick(raw) ? (parseTick(raw) * width).toString() : raw; onChange(converted); onValid?.(isTick(converted) && parseTick(converted) >= 0n); }}/><select aria-label={`${label}の単位`} value={unit} onChange={event => setUnit(event.target.value as 'tick' | 'day')}><option value="tick">tick</option><option value="day" disabled={!divisible}>日（{ticksPerDay} tick）</option></select></div>{!valid && <span className="field-error" role="alert">所要時間は0以上、38桁までの整数tickです。</span>}</label>;
}

export function WorldTimeFields({ value, project, label, onChange, onValid }: { value: TimeSpec; project: ProjectData; label: string; onChange: (time: TimeSpec) => void; onValid?: (valid: boolean) => void }) {
  const calendar = project.calendars.find(item => item.id === ('calendarId' in value ? value.calendarId : project.calendarId)) ?? project.calendars[0], parts = useRef<Record<string, boolean>>({}), latest = useRef(value); latest.current = value;
  const isValid = (time: TimeSpec) => time.mode === 'unknown' || time.mode === 'instant' && isTick(time.at) || time.mode === 'interval' && isTick(time.start) && isTick(time.end) && compareTicks(time.start, time.end) < 0 || time.mode === 'uncertain' && isTick(time.earliest) && isTick(time.latest) && compareTicks(time.earliest, time.latest) <= 0 || time.mode === 'relative' && !!time.anchorEventId && isTick(time.minOffset) && isTick(time.maxOffset) && compareTicks(time.minOffset, time.maxOffset) <= 0;
  const update = (time: TimeSpec) => { latest.current = time; onChange(time); onValid?.(isValid(time) && Object.values(parts.current).every(Boolean)); };
  const report = (key: string, valid: boolean) => { parts.current = { ...parts.current, [key]: valid }; onValid?.(isValid(latest.current) && Object.values(parts.current).every(Boolean)); };
  const absolute = (key: 'at' | 'start' | 'end' | 'earliest' | 'latest', suffix: string) => <TickInput key={`${key}:${calendar.id}`} label={`${label}の${suffix}`} value={(value as unknown as Record<string, Tick>)[key]} calendar={calendar} onChange={tick => update({ ...value, [key]: tick } as TimeSpec)} onValid={valid => report(key, valid)}/>;
  return <div><label>{label}の日時の種類<select aria-label={`${label}の日時の種類`} value={value.mode} onChange={event => { const mode = event.target.value as TimeSpec['mode']; parts.current = {}; update(mode === 'instant' ? { mode, at: project.mainStart, calendarId: calendar.id } : mode === 'interval' ? { mode, start: project.mainStart, end: parseTick(project.mainStart) < MAX_TICK ? (parseTick(project.mainStart) + 1n).toString() : MAX_TICK.toString(), calendarId: calendar.id } : mode === 'uncertain' ? { mode, earliest: project.mainStart, latest: project.mainStart, precision: '概算', calendarId: calendar.id } : mode === 'relative' ? { mode, anchorEventId: '', anchorPoint: 'start', minOffset: '0', maxOffset: '0' } : { mode, reason: '日時未登録' }); }}><option value="instant">確定した時点</option><option value="interval">期間</option><option value="uncertain">不確かな範囲</option><option value="relative">出来事からの相対日時</option><option value="unknown">日時未定</option></select></label>{'calendarId' in value && <PagedSelect label={`${label}の暦`} scope={`${project.projectId}:${label}:time-calendar`} value={value.calendarId} onChange={id => update({ ...value, calendarId: id })} items={project.calendars.map(item => ({ id: item.id, label: item.name }))}/>}{value.mode === 'instant' && absolute('at', '世界内日時')}{value.mode === 'interval' && <>{absolute('start', '開始日時')}{absolute('end', '終了日時')}</>}{value.mode === 'uncertain' && <>{absolute('earliest', '最も早い日時')}{absolute('latest', '最も遅い日時')}<label>精度・理由<input aria-label={`${label}の精度・理由`} value={value.precision} onChange={event => update({ ...value, precision: event.target.value })}/></label></>}{value.mode === 'relative' && <><EntityChoice label={`${label}の基準となる出来事`} entities={project.entities.filter(entity => entity.kind === 'event')} value={value.anchorEventId} onChange={anchorEventId => update({ ...value, anchorEventId })}/><label>基準<select aria-label={`${label}の基準位置`} value={value.anchorPoint} onChange={event => update({ ...value, anchorPoint: event.target.value as 'start' | 'end' })}><option value="start">出来事の開始</option><option value="end">出来事の終了</option></select></label>{(['minOffset', 'maxOffset'] as const).map(key => <label key={key}>{key === 'minOffset' ? '最小の時間差tick' : '最大の時間差tick'}<input aria-label={`${label}の${key}`} value={value[key]} onChange={event => update({ ...value, [key]: event.target.value })}/></label>)}</>}{value.mode === 'unknown' && <label>未定の理由<textarea aria-label={`${label}の未定の理由`} value={value.reason} onChange={event => update({ ...value, reason: event.target.value })}/></label>}{!isValid(value) && <p className="field-error" role="alert">日時の整数tick、開始と終了の順序、相対日時の基準を確認してください。</p>}</div>;
}
