import { WindowedList } from './WindowedList';
import { useMemo, useState } from 'react';
import type { ID, ProjectData } from '../domain/types';
import type { TimeEditPreview } from '../domain/timeEditing';
import { worldTimeConsequences, type LifeTimeSample } from '../domain/worldTimeImpact';
import type { WorldPoint } from '../domain/world';
import { labelOf } from './Fields';
import { TIMELINE_PAGE_SIZE, TimelinePagination } from './TimelineEditors';

const lifeLabels = { alive: '存命', dead: '死亡後', unborn: '未誕生', uncertain: '時期不確定', unknown: '存命状態不明' };
function samples(values: LifeTimeSample[]) { return values.length ? values.map(value => `${value.at} tick：${value.life.age}・${lifeLabels[value.life.state]}、所属 ${value.memberships.join(' / ') || '未登録'}${value.uncertainMembership ? '（未確認を含む）' : ''}`).join(' ／ ') : '日時未解決'; }
export function WorldTimeImpactPreview({ preview, project, point = {}, onOpen }: { preview: TimeEditPreview; project: ProjectData; point?: WorldPoint; onOpen?: (id: ID) => void }) {
  const [opened, setOpened] = useState(false), [page, setPage] = useState(0), [linkedPage, setLinkedPage] = useState(0), localIds = useMemo(() => new Set(preview.candidate.entities.map(entity => entity.id)), [preview.candidate.entities]);
  const report = useMemo(() => opened ? worldTimeConsequences(project, { ...preview.candidate, calendars: project.calendars, entities: [...preview.candidate.entities, ...project.entities.filter(entity => !localIds.has(entity.id))] }, preview.impacts, point) : undefined, [opened, project, preview, localIds, point]);
  const index = useMemo(() => new Map(project.entities.map(entity => [entity.id, entity])), [project.entities]), total = (report?.lives.length ?? 0) + (report?.newCandidates.length ?? 0) + (report?.resolvedCandidates.length ?? 0), safePage = Math.min(page, Math.max(0, Math.ceil(total / TIMELINE_PAGE_SIZE) - 1));
  const safeLinkedPage = Math.min(linkedPage, Math.max(0, Math.ceil((report?.linkedIds.length ?? 0) / TIMELINE_PAGE_SIZE) - 1));
  const entries = report ? [...report.lives.map((life, i) => ({ key: `life:${i}`, content: <article className="timeline-impact"><h4>{labelOf(index.get(life.characterId))} · {labelOf(index.get(life.eventId))}</h4><p>変更前の開始・終了候補：{samples(life.before)}</p><p>変更後の開始・終了候補：{samples(life.after)}</p></article> })), ...report.newCandidates.map(candidate => ({ key: `new:${candidate.id}`, content: <article className="world-check-candidate"><strong>変更後の確認候補 · {candidate.certainty === 'intentional' ? '理由を登録した例外' : candidate.certainty === 'supported' ? '登録情報からの候補' : '未確認'}</strong><p>{candidate.reason}</p>{onOpen && <WindowedList items={candidate.evidenceIds.map(id => ({ id }))} scope={`${project.projectId}:${candidate.id}:time-impact-evidence`} label="候補の根拠" searchText={({ id }) => labelOf(index.get(id))} className="world-inline-actions" render={({ id }) => <button key={id} type="button" className="button subtle small" onClick={() => onOpen(id)}>{labelOf(index.get(id))}の根拠</button>}/> }</article> })), ...report.resolvedCandidates.map(candidate => ({ key: `resolved:${candidate.id}`, content: <article className="timeline-impact"><strong>この変更では検出しなくなった候補</strong><p>{candidate.reason}</p><p className="field-hint">世界全体で問題がないと確定するものではありません。</p></article> }))] : [];
  return <details className="advanced-details" onToggle={event => setOpened(event.currentTarget.open)}><summary>年齢・所属・移動・関連情報への影響を確認</summary>{report && <><p>{report.lives.length}件の人物表示、{report.newCandidates.length}件の変更後の確認候補、{report.resolvedCandidates.length}件の検出しなくなった候補があります。</p>{!report.complete && <p className="error-notice">比較上限に達しています。全件を確認済みにはしていません。</p>}{entries.slice(safePage * TIMELINE_PAGE_SIZE, (safePage + 1) * TIMELINE_PAGE_SIZE).map(entry => <div key={entry.key}>{entry.content}</div>)}<TimelinePagination page={safePage} total={total} onChange={setPage}/><p>同じ出来事を参照する情報：{report.linkedIds.length}件</p>{onOpen && report.linkedIds.slice(safeLinkedPage * TIMELINE_PAGE_SIZE, (safeLinkedPage + 1) * TIMELINE_PAGE_SIZE).map(id => <button type="button" key={id} className="button subtle small" onClick={() => onOpen(id)}>{labelOf(index.get(id))}を確認</button>)}{onOpen && <TimelinePagination page={safeLinkedPage} total={report.linkedIds.length} onChange={setLinkedPage}/>}<p>保存済みの{report.fixedSnapshotIds.length}件の確定版は変更前の日時・暦を保持します。</p></>}</details>;
}
