import {expect,test,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createEntity,createProject,emptyValidity,newId} from '../../src/domain/model';
import {exportScenario,inspectScenario} from '../../src/storage/archive';

async function nav(page:Page,name:RegExp){await page.locator('.app-shell').waitFor();const menu=page.getByRole('button',{name:'メニューを開く',exact:true});if(await menu.isVisible())await menu.click();await page.locator('.sidebar').getByRole('button',{name}).first().click();}
async function graph(page:Page){await nav(page,/^年表/);await page.getByRole('tab',{name:'関係表・図',exact:true}).click();await page.getByRole('button',{name:'関係図',exact:true}).click();}
async function completeImage(page:Page){await nav(page,/^作品/);await page.getByRole('tab',{name:'完全保存・復元',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完全保存ファイルを作成',exact:true}).click();return (await inspectScenario(new Uint8Array(await readFile((await (await pending).path())!)),{worker:false})).project;}

test('graph movement keeps connected lines, device layout and live semantic edits consistent through cold reload',async({page})=>{
 const p=createProject('配置と意味を分ける'),a=createEntity(p.projectId,'character','配置A'),b=createEntity(p.projectId,'character','配置B');a.status=b.status='confirmed';p.entities.push(a,b);p.relations.push({id:newId(),projectId:p.projectId,revision:'0',fromId:a.id,toId:b.id,relationType:'trust',direction:'forward',validity:emptyValidity(),evidenceIds:[],status:'confirmed',visibility:'private'});
 const key=createEntity(p.projectId,'variable','鍵あり',{key:'key',valueType:'boolean',scope:'run',initial:{type:'boolean',value:false},allowed:{values:[false,true]}}),clock=createEntity(p.projectId,'variable','時刻',{key:'clock',valueType:'enum',scope:'run',initial:{type:'enum',value:'昼'},allowed:{values:['昼','夜']}});
 const entry=createEntity(p.projectId,'flow_node','括弧付き条件の入口',{nodeType:'automatic',executionPolicy:'first_match',gate:{op:'all',children:[{op:'compare',variableId:key.id,comparator:'eq',value:{type:'boolean',value:true}},{op:'any',children:[{op:'compare',variableId:clock.id,comparator:'eq',value:{type:'enum',value:'昼'}},{op:'compare',variableId:clock.id,comparator:'eq',value:{type:'enum',value:'夜'}}]}]}}),end=createEntity(p.projectId,'flow_node','条件の終端',{nodeType:'terminal',terminalReason:'条件を満たして完了'}),edge=createEntity(p.projectId,'flow_edge','条件の進行',{fromId:entry.id,toId:end.id,edgeType:'automatic',priority:0,condition:{op:'constant',value:true}}),flow=createEntity(p.projectId,'flow_graph','括弧付き条件の図',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});
 for(const entity of [key,clock,entry,end,edge,flow]){entity.status='confirmed';p.entities.push(entity);}
 await page.setViewportSize({width:1440,height:1000});await page.goto('');await page.getByRole('button',{name:'保存ファイルを読み込む',exact:true}).click();await page.locator('input[type=file][accept*=".scenario"]').setInputFiles({name:'graph.scenario',mimeType:'application/zip',buffer:Buffer.from(await exportScenario(p))});await page.getByLabel('復元方法と対象への影響を確認しました').check();await page.getByRole('button',{name:'この内容で復元する',exact:true}).click();await expect(page.locator('.app-shell')).toBeVisible();
 const before=await completeImage(page);await graph(page);
 const node=page.getByRole('button',{name:'配置Aを選択。矢印キーで配置を移動、Enterで詳細',exact:true}),other=page.getByRole('button',{name:'配置Bを選択。矢印キーで配置を移動、Enterで詳細',exact:true}),line=page.getByRole('button',{name:'配置Aから配置Bへ、信頼、関係を編集',exact:true});
 const x=Number(await node.locator('text').getAttribute('x')),otherX=await other.locator('text').getAttribute('x');await node.press('ArrowRight');await node.press('ArrowRight');await expect(node.locator('text')).toHaveAttribute('x',String(x+40));await expect(line.locator('line').first()).toHaveAttribute('x1',String(x+40));await expect(other.locator('text')).toHaveAttribute('x',otherX!);await expect(page.getByLabel('選択した項目の横位置',{exact:true})).toHaveValue(String(x+40));
 const box=(await node.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+32,box.y+box.height/2,{steps:4});await page.mouse.up();await expect.poll(async()=>Number(await node.locator('text').getAttribute('x'))).toBeGreaterThan(x+40);await expect(line.locator('line').first()).toHaveAttribute('x1',(await node.locator('text').getAttribute('x'))!);await page.getByLabel('選択した項目の横位置',{exact:true}).fill(String(x+40));await page.getByRole('button',{name:'座標を適用',exact:true}).click();await expect(node.locator('text')).toHaveAttribute('x',String(x+40));
 await page.reload();await graph(page);await expect(node.locator('text')).toHaveAttribute('x',String(x+40));await page.setViewportSize({width:390,height:844});await expect(node.locator('text')).toHaveAttribute('x',String(x));await node.click();await page.getByRole('button',{name:'選択項目を→へ移動',exact:true}).click();await expect(node.locator('text')).toHaveAttribute('x',String(x+20));await expect(line.locator('line').first()).toHaveAttribute('x1',String(x+20));await page.setViewportSize({width:1440,height:1000});await expect(node.locator('text')).toHaveAttribute('x',String(x+40));
 expect(await completeImage(page)).toEqual(before);await graph(page);await node.press('Enter');await expect(page.locator('.detail-heading')).toContainText('配置A');await page.getByRole('button',{name:'詳細を閉じる',exact:true}).click();await line.press('Enter');const dialog=page.getByRole('dialog',{name:'意味付きの関係を編集',exact:true});await dialog.getByLabel('関係の種類',{exact:true}).selectOption('related');await dialog.getByRole('combobox',{name:'関係の始点',exact:true}).selectOption(a.id);await dialog.getByRole('combobox',{name:'関係の終点',exact:true}).selectOption(b.id);await dialog.getByLabel('関係の向き',{exact:true}).selectOption('symmetric');await dialog.getByRole('button',{name:'関係を保存',exact:true}).click();await expect(dialog).toBeHidden();
 const updated=page.getByRole('button',{name:'配置Aから配置Bへ、関連、関係を編集',exact:true});await expect(updated).toBeVisible();await expect(line).toHaveCount(0);await expect(updated.locator('line').nth(1)).toHaveAttribute('marker-start','url(#world-relation-arrow)');
 await page.setViewportSize({width:320,height:844});await page.getByRole('button',{name:'関係表',exact:true}).click();const reference=page.locator('.world-relation-meaning strong').filter({hasText:'参照 · data.gate.children[1].children[0].variableId'});await expect(reference).toHaveText('参照 · data.gate.children[1].children[0].variableId');await expect(reference).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
 await page.evaluate(()=>document.documentElement.style.fontSize='200%');await expect(reference).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.evaluate(()=>document.documentElement.style.removeProperty('font-size'));await page.setViewportSize({width:1440,height:1000});await page.reload();await graph(page);await expect(updated).toBeVisible();await expect(node.locator('text')).toHaveAttribute('x',String(x+40));const after=await completeImage(page);expect(after.relations).toHaveLength(1);expect(after.relations[0]).toMatchObject({id:p.relations[0].id,fromId:a.id,toId:b.id,relationType:'related',direction:'symmetric'});expect(after.entities).toEqual(before.entities);
});
