import 'fake-indexeddb/auto';
import {it,expect,afterEach} from 'vitest';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createProject,createEntity,textToRichText,newId,validateProject} from '../src/domain/model';
import {createWorldSnapshot} from '../src/domain/world';
import {exportProject} from '../src/domain/exports';
import {receiveGamePackage,appendGameAction,buildGameReceipt,verifyGameReceipt,previewGameReceiptImport,confirmGameReceiptImport,verifyStoredGameEvidence} from '../src/domain/gameHandoff';
import {productionTraceWorkload,productionWorkload,estimateProduction,previewMediaRevision,confirmMediaRevision,previewConsultationImport,confirmConsultationImport} from '../src/domain/productionPlanning';
import {startTrial,stepTrial,pinTrialRecord} from '../src/domain/runtime';
import {startChapterReading,presentNextChapterScene,pinChapterReadingRecord} from '../src/domain/presentation';
import {canonicalJson,jsonBytes,sha256} from '../src/storage/json';
import {ScenarioStore} from '../src/storage/store';
import {inspectScenario} from '../src/storage/archive';
import type {ProjectData,Entity,PublicTextFields} from '../src/domain/types';
const root='/tmp/shinariokanri-independent-rb08-b59fddc/independent/fixtures';
type Fixture={project:ProjectData;ids:Record<string,string>};
const stores:ScenarioStore[]=[];function open(){const s=new ScenarioStore({databaseName:'independent-rb08-'+newId()});stores.push(s);return s;}afterEach(async()=>{for(const s of stores.splice(0))await s.deleteDatabase();});
function fixture():Fixture{
 const path=root+'/production-handoff.json';if(existsSync(path))return JSON.parse(readFileSync(path,'utf8'));
 const p=createProject('SECRET_R8_AUTHOR作品'),a=createEntity(p.projectId,'character','SECRET_R8_私的話者'),ch=createEntity(p.projectId,'chapter','独立の章',{summary:textToRichText('😀独立の章')}),s=createEntity(p.projectId,'scene','独立入口場面',{body:textToRichText('😀入口の物語'),authorNotes:textToRichText('SECRET_R8_AUTHORメモ')}),endScene=createEntity(p.projectId,'scene','独立結末場面',{body:textToRichText('結末の物語')}),line=createEntity(p.projectId,'dialogue_line','独立の原台詞',{speakerId:a.id,text:textToRichText('😀鍵を開く。')}),v=createEntity(p.projectId,'variable','SECRET_R8_内部状態',{key:'counter',valueType:'integer',scope:'across_runs',initial:{type:'integer',value:0},allowed:{min:0,max:100}}),c=createEntity(p.projectId,'external_contract','SECRET_R8_外部',{key:'battle',owner:'game',inputType:'boolean',outputType:'boolean',missingPolicy:'block',version:'1.0.0',stubValues:[{type:'boolean',value:true},{type:'boolean',value:false}]}),effect=createEntity(p.projectId,'effect','独立の更新',{operation:'add',targetId:v.id,value:{type:'integer',value:1}}),entry=createEntity(p.projectId,'flow_node','独立入口',{nodeType:'entry',sceneId:s.id,executionPolicy:'first_match',gate:{op:'external',contractId:c.id}}),terminal=createEntity(p.projectId,'flow_node','独立終端',{nodeType:'terminal',sceneId:endScene.id,terminalReason:'確認した終端'}),edge=createEntity(p.projectId,'flow_edge','独立の道',{fromId:entry.id,toId:terminal.id,edgeType:'automatic',effectIds:[effect.id]}),graph=createEntity(p.projectId,'flow_graph','独立graph',{nodeIds:[entry.id,terminal.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[terminal.id]}),task=createEntity(p.projectId,'production_task','独立の実装作業',{targetIds:[s.id,endScene.id],stage:'implementation',progress:'todo',deadline:{date:'2026-11-01',timeZone:'UTC'}});
 s.data.chapterId=endScene.data.chapterId=ch.id;s.data.dialogueLineIds=[line.id];ch.data.sceneIds=[s.id,endScene.id];p.entities.push(a,ch,s,endScene,line,v,c,effect,entry,terminal,edge,graph,task);p.entities.forEach(e=>e.status='confirmed');
 const texts:Record<string,PublicTextFields>={},blockSources:Record<string,string>={};for(const e of p.entities){const data=e.data as unknown as Record<string,unknown>,fields:Record<string,unknown>={};for(const field of ['body','text','summary','description','question','label','terminalReason','reason','key','predicate','cueType','language','canonical','displayName'])if(data[field]!=null){const approved=structuredClone(data[field]);if(Array.isArray(approved))for(const block of approved)if(block&&typeof block==='object'&&typeof block.id==='string'&&typeof block.text==='string'){const old=block.id;block.id=newId();blockSources[block.id]=old;}fields[field]=approved;}texts[e.id]=fields;}
 const policy=createEntity(p.projectId,'projection_profile','独立公開確認',{audience:'reader',publicTitle:'独立の公開作品',publicVersionLabel:'独立確認版',includedIds:p.entities.map(e=>e.id),allowedKinds:[...new Set(p.entities.map(e=>e.kind))],idPolicy:'preserve',namePolicy:{defaultPolicy:{mode:'replace',replacement:'確認した公開情報'}},publicTexts:texts,blockSources});policy.status='confirmed';p.entities.push(policy);
 const f={project:p,ids:{actor:a.id,chapter:ch.id,scene:s.id,endScene:endScene.id,line:line.id,variable:v.id,contract:c.id,effect:effect.id,entry:entry.id,terminal:terminal.id,edge:edge.id,graph:graph.id,task:task.id,policy:policy.id}};writeFileSync(path,JSON.stringify(f,null,2)+'\n');return JSON.parse(readFileSync(path,'utf8'));
}
async function pkg(){const f=fixture(),output=await exportProject(f.project,{profile:'runtime_json',projectionProfileId:f.ids.policy,targetRevision:f.project.revision});if(!output.ok)throw Error(JSON.stringify(output.issues));const wire=JSON.parse(output.artifact.content),accepted=await receiveGamePackage(wire);return {...f,pkg:accepted};}
function proof(name:string,value:unknown){writeFileSync(root+'/'+name+'.json',JSON.stringify(value,null,2)+'\n');}
it('R8V01 independent own fixture satisfies strict structural contracts and retains all authored content',()=>{const f=fixture();expect(validateProject(f.project)).toMatchObject({ok:true});expect(f.project.entities.find(e=>e.id===f.ids.scene)?.data).toMatchObject({authorNotes:[expect.objectContaining({text:'SECRET_R8_AUTHORメモ'})]});});
it('R8D01 buildGameReceipt captures requests before its first await, later caller progress is a separate operation',async()=>{const f=await pkg(),win=await appendGameAction(f.pkg,[],f.ids.contract,'win'),submitted={entryId:f.ids.entry,actions:[win],requests:[] as object[]},pending=buildGameReceipt(f.pkg,submitted);submitted.requests.push({});const receipt=await pending;proof('R8D01',{receipt,submittedAfterCall:submitted});expect(receipt.requests).toEqual([]);expect(receipt.status).toBe('ready');expect(receipt.finalState).toMatchObject({variableValues:{[f.ids.variable]:{type:'integer',value:0}}});});
it('R8D02 verifyGameReceipt captures valid received bytes before awaiting package verification',async()=>{const f=await pkg(),stub=await appendGameAction(f.pkg,[],f.ids.contract,'stub',0),receipt=await buildGameReceipt(f.pkg,{entryId:f.ids.entry,actions:[stub],requests:[]});const pending=verifyGameReceipt(f.pkg,receipt);receipt.mode='actual';const checked=await pending;proof('R8D02',{checked,callerMode:receipt.mode});expect(checked.mode).toBe('stub');});
it('R8D03 durable save rejects rehashed final state that cannot replay from the original received package',async()=>{const f=await pkg(),win=await appendGameAction(f.pkg,[],f.ids.contract,'win'),receipt=await buildGameReceipt(f.pkg,{entryId:f.ids.entry,actions:[win],requests:[{}]}),db=open(),base=(await db.saveProject(f.project,{reason:'独立の元作品'})).project,plan=await previewGameReceiptImport(base,receipt,{projectionProfileId:f.ids.policy,targetRevision:base.revision}),candidate=await confirmGameReceiptImport(base,plan),note=candidate.entities.find(e=>e.id===plan.noteId);if(note?.kind!=='note'||!note.data.handoffReceipt)throw Error('fixture note');const bad=JSON.parse(note.data.handoffReceipt.rawJson);bad.finalState.variableValues[f.ids.variable]={type:'integer',value:99};const {receiptHash:_old,...payload}=bad;bad.receiptHash=await sha256(jsonBytes(payload));note.data.handoffReceipt.receiptHash=bad.receiptHash;note.data.handoffReceipt.rawJson=canonicalJson(bad);await expect(verifyGameReceipt(f.pkg,bad)).rejects.toThrow('最終結果');const issues=await verifyStoredGameEvidence(candidate).then(()=>[]).catch(e=>[e.message]);let refused=false;try{await db.saveProject(candidate,{reason:'偽造を拒否する'});}catch{refused=true;}const after=await db.getProject(base.projectId);proof('R8D03',{directReplayRejected:true,durableIssues:issues,refused,afterRevision:after?.revision,beforeRevision:base.revision});expect(refused).toBe(true);expect(after).toEqual(base);});
it('R8D04 complete native chapter route reports its actual full origin, independent of empty flow steps',async()=>{const f=fixture();let session=await startChapterReading(f.project,{chapterIds:[f.ids.chapter]});while(session.status==='ready')session=presentNextChapterScene(f.project,session);expect(session.status).toBe('terminal');expect(session.state.provenance).toBe('full_play');const checkpointId=newId(),snapshotId=newId(),record=pinChapterReadingRecord(session,{checkpointId,snapshotId},f.project),pin={id:snapshotId,versionLabel:'章の記録版',content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:new Date().toISOString()},cp=createEntity(f.project.projectId,'checkpoint','章の開始',record.checkpoint),trace=createEntity(f.project.projectId,'trace','章の全体',record.trace);cp.id=checkpointId;cp.status=trace.status='confirmed';f.project.snapshots.push(pin);f.project.entities.push(cp,trace);const result=await productionTraceWorkload(f.project,trace.id);proof('R8D04',{result,checkpointOrigin:record.checkpoint.runtimeState?.provenance,terminalOrigin:session.state.provenance,flowSteps:record.trace.steps.length});expect(result.origin).toBe('full_play');expect(result.workload.routeOccurrences).toBe(2);});
it('R8D05 normal internal route is not labeled external stub',async()=>{const f=fixture(),entry=f.project.entities.find(e=>e.id===f.ids.entry);if(entry?.kind!=='flow_node')throw Error('fixture');entry.data.gate={op:'constant',value:true};let session=startTrial(f.project,{entryId:f.ids.entry});session=stepTrial(f.project,session,{});expect(session.status).toBe('terminal');const cpId=newId(),snapId=newId(),record=await pinTrialRecord(session,{checkpointId:cpId,snapshotId:snapId},f.project),cp=createEntity(f.project.projectId,'checkpoint','内部開始',record.checkpoint),trace=createEntity(f.project.projectId,'trace','内部経路',record.trace);cp.id=cpId;cp.status=trace.status='confirmed';f.project.entities.push(cp,trace);f.project.snapshots.push({id:snapId,versionLabel:'内部経路版',createdAt:new Date().toISOString(),content:record.content,contentHash:await sha256(jsonBytes(record.content))});expect(record.trace.externalMode??null).toBe(null);const result=await productionTraceWorkload(f.project,trace.id);proof('R8D05',{result,storedExternalMode:record.trace.externalMode??null});expect(result.externalMode??null).toBe(null);});
it('R8V02 actual/stub/mixed are computed from verified game mechanics; wrong owner and rehashed results reject',async()=>{const f=await pkg(),stub=await appendGameAction(f.pkg,[],f.ids.contract,'stub',0),win=await appendGameAction(f.pkg,[stub],f.ids.contract,'win'),mixed=await buildGameReceipt(f.pkg,{entryId:f.ids.entry,actions:[stub,win],requests:[{}]});expect(mixed.mode).toBe('mixed');const bad=structuredClone(mixed);bad.actions[1].score=999;const {hash:_h,...event}=bad.actions[1];bad.actions[1].hash=await sha256(jsonBytes(event));const {receiptHash:_r,...body}=bad;bad.receiptHash=await sha256(jsonBytes(body));await expect(verifyGameReceipt(f.pkg,bad)).rejects.toThrow('実結果');const foreign=structuredClone(f.pkg);const c=foreign.runtimeProject.entities.find(e=>e.id===f.ids.contract);if(c?.kind!=='external_contract')throw Error('contract');c.data.owner='scenario';await expect(appendGameAction(foreign,[],f.ids.contract,'win')).rejects.toThrow('ゲーム管理');});
it('R8V03 all six purpose profiles preserve confirmed scope, exclude author names/notes, carry actual output evidence',async()=>{const f=fixture(),results=[];for(const profile of ['reader','runtime_json','localization','production','consultation','playable_preview']as const){const result=await exportProject(f.project,{profile,projectionProfileId:f.ids.policy,targetRevision:f.project.revision});proof('profile-'+profile,result.ok?{ok:true,preview:result.preview,filename:result.artifact.filename,content:result.artifact.content}:result);expect(result.ok,profile).toBe(true);if(result.ok){expect(result.artifact.content).not.toContain('SECRET_R8_');results.push({profile,filename:result.artifact.filename,preview:result.preview});}}proof('R8V03',{results});});
it('R8V04 consultation is immutable canonical data until selected adoption, stale approval rejects, archive restores sealed alternative',async()=>{const f=fixture(),old=await createWorldSnapshot(f.project,'相談の旧版'),pin=old.snapshots.at(-1)!,before=canonicalJson(old.entities),input={text:'# 独立相談の提案\n😀別の本文',source:'手動で持ち出した独立相談MD',versionId:pin.id,targetId:f.ids.scene},pending=previewConsultationImport(old,input);input.text='後の別提案';old.revision='7';const plan=await pending;expect(plan.baseRevision).toBe('0');await expect(confirmConsultationImport(old,plan)).rejects.toThrow('REVISION_CONFLICT');old.revision='0';const candidate=await confirmConsultationImport(old,plan);expect(canonicalJson(candidate.entities)).toBe(before);const db=open(),saved=(await db.saveProject(candidate,{reason:'別案だけ保存'})).project,inspection=await inspectScenario(await db.exportProject(saved.projectId),{worker:false}),clone=(await open().importScenario(inspection,{mode:'clone'})).project;expect(clone.authorAlternatives).toHaveLength(1);expect(clone.entities.find(e=>e.kind==='scene'&&e.name==='独立入口場面')?.data).toMatchObject({body:[expect.objectContaining({text:'😀入口の物語'})]});proof('R8V04',{planBaseRevision:plan.baseRevision,sealedHash:plan.alternative.versions.at(-1)?.contentHash,cloneAlternativeCount:clone.authorAlternatives?.length});});
