import 'fake-indexeddb/auto';
import {it,expect} from 'vitest';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createEntity,newId,validateProject} from '../src/domain/model';
import {ScenarioStore} from '../src/storage/store';
import {inspectScenario,worldSnapshotContents} from '../src/storage/archive';
import type {ProjectData,ProjectContent,Relation} from '../src/domain/types';
const root='/tmp/shinariokanri-independent-rb07-28eccca/independent/fixtures';
it('R7D25 a relation fixed presentation anchor retains its historical world in complete save without previous active-world adoption',async()=>{
 const path=root+'/world-relation-production.json';let input:{project:ProjectData;ids:Record<string,string>;world:ProjectData;registry:Record<string,ProjectContent>};
 if(existsSync(path))input=JSON.parse(readFileSync(path,'utf8'));else{input=JSON.parse(readFileSync(root+'/world-new-current-production.json','utf8'));const p=input.project,x=createEntity(p.projectId,'character','作品の関係元'),y=createEntity(p.projectId,'character','作品の関係先');x.status=y.status='confirmed';p.entities=[x,y];const relation:Relation={id:newId(),projectId:p.projectId,revision:'0',fromId:x.id,toId:y.id,relationType:'trust',direction:'forward',validity:{worldRange:null,routeCondition:null,presentationAnchor:{entityId:input.ids.line,sourceVersionId:input.ids.old}},evidenceIds:[],status:'confirmed',visibility:'private'};p.relations.push(relation);input.ids.relation=relation.id;writeFileSync(path,JSON.stringify(input,null,2)+'\n');}
 const source=JSON.parse(readFileSync(root+'/world-production.json','utf8'))as{worldA:ProjectData;worldB:ProjectData};const {project:p,ids,registry}=input;expect(validateProject(p,{worldSnapshots:registry}).ok).toBe(true);const db=new ScenarioStore({databaseName:'historical-relation-world-'+newId()});try{
  await db.saveProject(source.worldB,{reason:'世界原稿保存'});await db.saveProject(source.worldA,{reason:'別作品の旧Bを登録',worldPin:{world:source.worldB,snapshotId:ids.old}});const saved=(await db.saveProject(p,{reason:'新B採用・関係の提示位置だけ旧B',worldPin:{world:source.worldB,snapshotId:ids.newest}})).project;expect((await db.getProject(saved.projectId))!.relations).toEqual(saved.relations);writeFileSync(root+'/R7D25-before.json',JSON.stringify({saved,worldPinIds:Object.keys(await db.listWorldSnapshots())},null,2)+'\n');const archiveBytes=await db.exportProject(saved.projectId);writeFileSync(root+'/R7D25-complete.scenario',archiveBytes);const prepared=await inspectScenario(archiveBytes,{worker:false});writeFileSync(root+'/R7D25-after.json',JSON.stringify({archivedWorldPinIds:Object.keys(worldSnapshotContents(prepared.worlds)),oldRequiredPin:ids.old,archivedRelation:prepared.project.relations[0],sourceSavedRevision:saved.revision},null,2)+'\n');expect(worldSnapshotContents(prepared.worlds)[ids.old]).toBeDefined();for(const mode of ['new','clone']as const){const target=new ScenarioStore({databaseName:'relation-world-restore-'+newId()});try{const restored=(await target.importScenario(prepared,{mode})).project,worlds=worldSnapshotContents(await target.listWorldSnapshots());expect(validateProject(restored,{worldSnapshots:worlds}).ok).toBe(true);expect(restored.relations[0].validity?.presentationAnchor?.sourceVersionId).toBe(ids.old);expect(worlds[ids.old]).toBeDefined();writeFileSync(root+'/R7D25-'+mode+'.json',JSON.stringify({valid:true,worldPinIds:Object.keys(worlds),relation:restored.relations[0]},null,2)+'\n');}finally{await target.deleteDatabase();}}
 }finally{await db.deleteDatabase();}
});
