import 'fake-indexeddb/auto';
import {it,expect,afterEach} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {exportProject} from '../src/domain/exports';
import {createEntity,newId} from '../src/domain/model';
import {createWorldSnapshot} from '../src/domain/world';
import {receiveGamePackage,appendGameAction,buildGameReceipt,verifyGameReceipt,previewGameReceiptImport,confirmGameReceiptImport,verifyStoredGameEvidence} from '../src/domain/gameHandoff';
import {rebuildGameExecution} from '../src/domain/gameEvidence';
import {ScenarioStore} from '../src/storage/store';
import {inspectScenario} from '../src/storage/archive';
import {jsonBytes,sha256,canonicalJson} from '../src/storage/json';
const root='/tmp/shinariokanri-independent-rb08-bf0f6b0/independent/fixtures',stores:ScenarioStore[]=[];function db(){const x=new ScenarioStore({databaseName:'independent-game-'+newId()});stores.push(x);return x;}afterEach(async()=>{for(const x of stores.splice(0))await x.deleteDatabase();});function proof(name:string,v:unknown){writeFileSync(root+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');}
async function fixture(){const f=JSON.parse(readFileSync(root+'/production-handoff.json','utf8')),output=await exportProject(f.project,{profile:'runtime_json',projectionProfileId:f.ids.policy,targetRevision:f.project.revision});if(!output.ok)throw Error('fixture export');const pkg=await receiveGamePackage(JSON.parse(output.artifact.content)),action=await appendGameAction(pkg,[],f.ids.contract,'win'),receipt=await buildGameReceipt(pkg,{entryId:f.ids.entry,actions:[action],requests:[{}]}),plan=await previewGameReceiptImport(f.project,receipt,{projectionProfileId:f.ids.policy,targetRevision:f.project.revision}),candidate=await confirmGameReceiptImport(f.project,plan),note=candidate.entities.find(e=>e.id===plan.noteId);if(note?.kind!=='note'||!note.data.handoffReceipt)throw Error('fixture note');return{...f,pkg,receipt,plan,candidate,note};}
it('R8V10 valid actual evidence keeps exact receiver wire across atomic save, fake IDB reload, archive empty/new/clone and later draft revision',async()=>{const f=await fixture(),store=db(),saved=(await store.saveProject(f.candidate,{reason:'受領を保存'})).project;expect(await store.getProject(saved.projectId)).toEqual(saved);await expect(verifyStoredGameEvidence(saved)).resolves.toBeUndefined();const assetFree=await store.exportProject(saved.projectId),archive=await inspectScenario(assetFree,{worker:false}),restored=(await db().importScenario(archive,{mode:'new'})).project,clone=(await db().importScenario(archive,{mode:'clone'})).project;for(const p of [restored,clone]){const note=p.entities.find(e=>e.kind==='note'&&e.data.handoffReceipt);expect(note?.kind==='note'&&note.data.handoffReceipt?.rawJson).toBe(canonicalJson(f.receipt));await expect(verifyStoredGameEvidence(p)).resolves.toBeUndefined();}const revised=structuredClone(saved),current=revised.entities.find(e=>e.id===f.ids.variable);if(current?.kind!=='variable')throw Error('variable');current.data.initial={type:'integer',value:9};const later=(await store.saveProject(revised,{reason:'現稿の状態変更後も旧受領を保持'})).project;await expect(verifyStoredGameEvidence(later)).resolves.toBeUndefined();proof('R8V10',{originalReceipt:f.receipt,savedRevision:saved.revision,laterRevision:later.revision,cloneProjectId:clone.projectId,restoredNoteCount:restored.entities.filter(e=>e.kind==='note').length,wirePreserved:true});});
it('R8V11 unknown receiver, foreign work edition and hand-entered actual classification reject atomically',async()=>{const f=await fixture(),store=db(),base=(await store.saveProject(f.project,{reason:'基底'})).project;const wrong=structuredClone(f.receipt);(wrong as any).receiverId='another-receiver';await expect(verifyGameReceipt(f.pkg,wrong)).rejects.toThrow('仕様');const stub=await appendGameAction(f.pkg,[],f.ids.contract,'stub',0),wire=await buildGameReceipt(f.pkg,{entryId:f.ids.entry,actions:[stub],requests:[{}]});expect(wire.mode).toBe('stub');const fake=structuredClone(wire);fake.mode='actual';const {receiptHash:_old,...body}=fake;fake.receiptHash=await sha256(jsonBytes(body));await expect(verifyGameReceipt(f.pkg,fake)).rejects.toThrow('stub/actual/mixed');const foreignPlan=await previewGameReceiptImport(base,f.receipt,{projectionProfileId:f.ids.policy,targetRevision:base.revision}),candidate=await confirmGameReceiptImport(base,foreignPlan),note=candidate.entities.find(e=>e.kind==='note'&&e.data.handoffReceipt);if(note?.kind!=='note'||!note.data.handoffReceipt)throw Error('note');note.data.handoffReceipt.sourceVersionId=newId();await expect(store.saveProject(candidate,{reason:'別作品版を拒否'})).rejects.toThrow('sourceVersionId');expect(await store.getProject(base.projectId)).toEqual(base);proof('R8V11',{receiverRefused:true,manualActualRefused:true,foreignEditionRefused:true,existingRevision:base.revision});});
it('R8D08 historical receipt images are captured before async verification, later caller mutation cannot replace the submitted snapshot receipt',async()=>{const f=await fixture(),p=await createWorldSnapshot(f.candidate,'受領の履歴画像'),original=structuredClone(p);await expect(verifyStoredGameEvidence(original)).resolves.toBeUndefined();const later=p.snapshots.at(-1)!.content.entities.find(e=>e.kind==='note'&&e.data.handoffReceipt);if(later?.kind!=='note'||!later.data.handoffReceipt)throw Error('history fixture');const pending=verifyStoredGameEvidence(p);later.data.handoffReceipt.mode='stub';try{await pending;proof('R8D08',{capturedValid:true,callerLaterMode:later.data.handoffReceipt.mode});}catch(e){proof('R8D08',{capturedValid:false,error:(e as Error).message,callerLaterMode:later.data.handoffReceipt.mode,original});throw e;}expect(later.data.handoffReceipt.mode).toBe('stub');});
it('R8D09 rebuilding verified execution captures evidence metadata before its first await',async()=>{const f=await fixture(),evidence=f.note.data.handoffReceipt!;const control=await rebuildGameExecution(f.candidate,structuredClone(evidence),{});expect(control.runtimeProjectHash).toBe(f.receipt.runtimeProjectHash);const pending=rebuildGameExecution(f.candidate,evidence,{});evidence.sourceRevision='99';try{const captured=await pending;expect(captured.runtimeProjectHash).toBe(f.receipt.runtimeProjectHash);proof('R8D09',{controlHash:control.runtimeProjectHash,capturedHash:captured.runtimeProjectHash,callerRevision:evidence.sourceRevision});}catch(e){proof('R8D09',{controlHash:control.runtimeProjectHash,error:(e as Error).message,callerRevision:evidence.sourceRevision});throw e;}});

it('R8D10 durable game evidence rejects a fabricated reception package hash even when action and receipt hashes are resealed consistently',async()=>{const f=await fixture(),store=db(),base=(await store.saveProject(f.project,{reason:'package hashの保存基底'})).project,plan=await previewGameReceiptImport(base,f.receipt,{projectionProfileId:f.ids.policy,targetRevision:base.revision}),candidate=await confirmGameReceiptImport(base,plan),note=candidate.entities.find(e=>e.id===plan.noteId);if(note?.kind!=='note'||!note.data.handoffReceipt)throw Error('fixture note');const bad=JSON.parse(note.data.handoffReceipt.rawJson);bad.packageHash='f'.repeat(64);let previous=bad.packageHash;for(const action of bad.actions){action.previousHash=previous;const {hash:_hash,...payload}=action;action.hash=await sha256(jsonBytes(payload));previous=action.hash;}const {receiptHash:_receipt,...payload}=bad;bad.receiptHash=await sha256(jsonBytes(payload));note.data.handoffReceipt.packageHash=bad.packageHash;note.data.handoffReceipt.receiptHash=bad.receiptHash;note.data.handoffReceipt.rawJson=canonicalJson(bad);await expect(verifyGameReceipt(f.pkg,bad)).rejects.toThrow('hash');let refused=false,error='';try{await store.saveProject(candidate,{reason:'架空の受領hashを拒否'});}catch(e){refused=true;error=(e as Error).message;}proof('R8D10',{originalPackageHash:f.receipt.packageHash,forgedReceipt:bad,refused,error,baseRevision:base.revision,afterRevision:(await store.getProject(base.projectId))?.revision});expect(refused).toBe(true);expect(await store.getProject(base.projectId)).toEqual(base);});
