import json,hashlib,subprocess,datetime
from pathlib import Path
r=Path('/tmp/shinariokanri-independent-rb07-39079f4');old=Path('/tmp/shinariokanri-independent-rb07-297f19a');repo=Path('/workspace/shinariokanri-rb07');c='39079f4066676d80b7098cf87e5719fc865c0564';tree='a6d0ecbd8164cb3d6cf70abaa8fbe064296fd25f';base='b310800c98bc9a89b93182ad721380a0be99d2d3'
sha=lambda b:hashlib.sha256(b).hexdigest();read=lambda name:json.loads((r/name).read_text())
def write(name,data):(r/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
def gitdata(commit,name):return subprocess.check_output(['git','show',commit+':'+name],cwd=repo)
previous=json.loads((old/'INDEPENDENT_REVIEW.json').read_text());oldbind=json.loads((old/'SOURCE_COMMIT_BINDING.json').read_text());oldsha=sha((old/'INDEPENDENT_REVIEW.json').read_bytes());assert oldsha=='d93c363b9ffa8b88b92e3cc2659cace3f3821c0f1f3931bb6638ba1994071cab';oldartifacts=json.loads((old/'ARTIFACT_BINDING.json').read_text())['artifacts'];assert all(sha((old/x['file']).read_bytes())==x['sha256']for x in oldartifacts)
m=read('source-manifest.json');files=[];oldsrc={x['file']:x['sha256']for x in oldbind['files']};changed=[]
for row in m['files']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name));files.append({'file':name,'sha256':h,'manifestMatches':True,'commitMatches':True})
 if oldsrc.get(name)!=h:changed.append(name)
assert len(files)==169
norm=[]
for row in oldbind['originalContracts']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name))==sha(gitdata(base,name));norm.append({**row,'baseMatches':True,'commitMatches':True,'originalHashMatches':True})
legacy=[]
for row in oldbind['legacyFixtureInputs']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256']==sha(gitdata(c,name));legacy.append({**row,'notExecutedInThisRB07Review':True})
inputs=[]
for row in oldbind['independentInputs']:
 name=row['file'];h=sha((r/name).read_bytes());assert h==row['sha256'];item={'file':name,'sha256':h,'sameBytesAs297':True,'regenerated':False}
 if name.startswith('tests/'):assert h==sha(gitdata(c,name));item['commitMatches']=True
 inputs.append(item)
name='independent/fixtures/world-relation-production.json';inputs.append({'file':name,'sha256':sha((r/name).read_bytes()),'newIndependentBoundary':True,'generatedOnceIn390':True,'changes':'Exact newest-world input with frame removed, two confirmed work-local characters and a confirmed trust Relation whose presentationAnchor alone cites oldB. World registry/descriptors unchanged.'})
write('SOURCE_COMMIT_BINDING.json',{'commit':c,'tree':tree,'base':base,'sourceFileCount':169,'all169Match':True,'files':files,'changedSourceFrom297':changed,'originalContracts':norm,'legacyFixtureInputs':legacy,'independentInputs':inputs,'historical297ReportSha256':oldsha,'historical75ArtifactsUnchanged':True})
assert 'Tests  25 passed (25)'in(r/'independent/domain-reinspection.log').read_text();assert 'Tests  1 failed (1)'in(r/'independent/domain-relation-world.log').read_text();assert 'Tests  1 failed (1)'in(r/'independent/domain-ui-relation-download.log').read_text()
ui=[]
for name in ['browser-production','browser-fixed','browser-speaker','browser-reuse','browser-world','browser-local-rule']:ui+=read('independent/'+name+'.json')['results']
assert len(ui)==13 and all(x['status']=='passed'for x in ui);assert read('independent/production-browser.json')['stats']['expected']==3
native=read('independent/fixtures/R7D25-after.json');download=read('independent/fixtures/R7U14-archive-observation.json');assert native['oldRequiredPin']not in native['archivedWorldPinIds'];assert download['expectedOldPin']not in download['archivedWorldPinIds']
finding={'id':'R7D25/R7U14','classification':'typed_Relation_immutable_world_citation_missing_from_complete_archive','requirements':['REQ-B09','REQ-B16','REQ-F09','REQ-N19'],'acceptance':['AT-B09','AT-B16','AT-F09','AT-N19'],'review':'RV16/RV19','given':'Older worldB pin is registered through another work. This work first adopts only newerB and has confirmed local characters+trust Relation. Relation.validity.presentationAnchor explicitly cites oldB line and snapshot; no caption or previous active-oldB history can mask the citation. Valid project and atomic save/reload succeed.','when':'Complete archive, both direct store API and normal App cold backup download, then inspect file and restore into empty new/clone.','expected':'Retain the relation historical world pin and its stored expectedHash; preserve the current newer world separately and resolve the exact old presentation source after restore.','actual':{'component':native,'normalDownloadedArchive':download,'normalBrowser':read('independent/browser-relation-world.json')['results'],'note':'Normal complete download announces success and inspect accepts the archive, but old pin is missing. Download alone is not a full-save success. Empty restoration assertion stops at missing old pin.'},'cause':{'file':'src/storage/archive.ts','sha256':next(x['sha256']for x in files if x['file']=='src/storage/archive.ts'),'detail':'referencedWorlds additions detect only Entity.kind/data and collectReferences, while Relation has relationType and needs collectRelationReferences. The valid old pin registry is pruned from the complete file.'},'evidence':['tests/independent-rb07-relation-world-citation.test.ts','tests/independent-rb07-ui-relation-download.test.ts','independent/domain-relation-world.log','independent/domain-ui-relation-download.log','independent/relation-world-run1/test.ts','independent/relation-world-run1/raw.log','independent/fixtures/world-relation-production.json','independent/fixtures/R7D25-after.json','independent/fixtures/R7D25-complete.scenario','independent/browser-relation-world.json','independent/fixtures/R7U14-relation-world-complete.scenario','independent/fixtures/R7U14-archive-observation.json'],'status':'failed_correct_expected_outcome_retained'}
prior1b=json.loads((Path('/tmp/shinariokanri-independent-rb07-1b7b508')/'INDEPENDENT_REVIEW.json').read_text())
report={'target':{'commit':c,'tree':tree,'base':base,'source169AllMatch':True,'frozenAt':m['frozenAt'],'verifiedAt':datetime.datetime.now(datetime.timezone.utc).isoformat()},'purpose':'Limited independent RB07 RV18/19 and related complete-save review. Full104/116/24/6/RB07 not graded.','results':{'components':{'passed':24,'failed':0,'fixtureValidityPassed':1,'notAcceptance':True,'log':'independent/domain-reinspection.log'},'normalApp':{'passed':13,'failed':0,'cases':ui,'classification':'Actual App/native IndexedDB/Chromium151, same frozen positive inputs, controlled save/failure/ack/cold boundaries and verified current-vs-fixed source navigation'},'production':{**prior1b['results']['production'],'buildInfo':read('dist/build-info.json'),'classification':'Unchanged repository production E2E, Chromium151, dedicated5353'},'additionalRelationComponent':{'passed':0,'failed':1,'id':'R7D25','log':'independent/domain-relation-world.log'},'additionalRelationNormalAppArtifact':{'passed':0,'failed':1,'id':'R7U14','classification':'Actual App download succeeds; separately inspected actual file is missing the required pin, so combined complete-save positive assertion fails. No download-only acceptance pass.','logs':['independent/browser-relation-world.log','independent/domain-ui-relation-download.log']}},'findings':[finding],'resolvedFindings':previous['resolvedFindings']+[{'id':'R7D24/R7U13','historicalCommit':previous['target']['commit'],'historicalReportSha256':oldsha,'status':'passed_same_frozen_bytes_correct_expectation','actual':'Current work terminology root opens its actual work editor; old-world voice/source remain explicitly pinned.'}],'descriptorContract':previous['descriptorContract'],'environment':{**previous['environment'],'ports':'Vite5351/preview5353 stopped'},'originalContracts':previous['originalContracts'],'harnessHistory':'R7D25 first failed source/raw preserved separately; instrumentation adds file/world ID proof without changing the positive expectation or input. R7U14 file downloaded by actual App is independently inspected, not graded from the success notice. Older setup errors/history are immutable in previous archives.','historicalNegativeEvidence':previous['historicalNegativeEvidence']+[{'directory':str(old),'reportSha256':oldsha,'artifactCount':len(oldartifacts),'allArtifactsUnchanged':True}],'unexecuted':previous['unexecuted'],'productRepositoryWrites':False,'evidenceBinding':'SOURCE_COMMIT_BINDING169src/15originaldocs/4legacyhashonly/sameinputs; ARTIFACT_BINDING includes actual complete files, reviewer source/raw/results/dist with trailing whitespace retained.'}
write('INDEPENDENT_REVIEW.json',report);(r/'INDEPENDENT_REVIEW.md').write_text(f'''RB07候補 `{c}` / tree `{tree}` を同じ正期待で独立再検査した。24部品＋fixture妥当性1件、13通常App群、production3件は成功。旧字幕とローカル用語規則はそれぞれ正しい版の本文／根拠へ戻り、Entity側の旧世界引用は新規／複製復元で保持した。\n\n新R7D25/R7U14は失敗した。別作品で登録済みの旧B世界へRelation.validity.presentationAnchorだけが固定参照する作品（現行採用は新B、旧採用履歴なし）で、原子保存・cold reloadと通常完全保存downloadは成功するが、ファイルには旧Bが含まれない。直接storeと実Appが取得した.scenarioの両方をinspectして欠落を確認した。complete表示やdownloadだけを合格に数えない。Entityだけを拾うreferencedWorldsがcollectRelationReferencesを収集していない。元入力・正期待・失敗源/raw・実ファイルは保持した。\n\n169srcと原15資料、旧4fixture（hashのみ）、11固定入力、ログ／ファイル／distをSHA結合し、297の75成果物と全歴史的負例を保持。隔離build-info unknown/dirty=trueをclean releaseへ換算しない。104/116/24/6・全RB07・実端末/Files/録音/支援技術/全性能/長時間/実Auth/APIは未判定。repo製品・証拠・commitは編集していない。\n''')
paths={r/'source-manifest.json',r/'SOURCE_COMMIT_BINDING.json',r/'INDEPENDENT_REVIEW.json',r/'INDEPENDENT_REVIEW.md',r/'write-final-review.py',r/'independent-playwright.config.ts'};paths.update(f for f in(r/'independent').rglob('*')if f.is_file());paths.update(r.glob('tests/independent*.test.ts'));paths.update(f for f in r.glob('independent-app*')if f.is_file());paths.update(f for f in(r/'dist').rglob('*')if f.is_file());a=[{'file':str(f.relative_to(r)),'sha256':sha(f.read_bytes()),'bytes':len(f.read_bytes())}for f in sorted(paths)];write('ARTIFACT_BINDING.json',{'commit':c,'tree':tree,'artifactCount':len(a),'artifacts':a,'source169AllMatch':True,'rawLogsTrailingWhitespacePreserved':True,'notEntirePlanPass':True});assert all(sha((r/x['file']).read_bytes())==x['sha256']for x in a)
print(json.dumps({'commit':c,'tree':tree,'components':24,'normalApp':13,'production':3,'newRelationComponentFailed':1,'newRelationNormalDownloadContentFailed':1,'artifactCount':len(a),'reportSha256':sha((r/'INDEPENDENT_REVIEW.json').read_bytes())},ensure_ascii=False))
