import React from 'react';import{createRoot}from'react-dom/client';import Dexie from'dexie';import App from'./src/App';import{scenarioStore}from'./src/storage/store';import{inspectScenario}from'./src/storage/archive';import{replaySavedTraceVerified}from'./src/domain/runtimeVerified';import{sha256}from'./src/storage/json';import'./src/styles.css';
const w=window as any;
const bytes=new Uint8Array(await(await fetch('./docs/quality/current-review/evidence/legacy/3099c9d-flow-trace.scenario')).arrayBuffer()),source=(await inspectScenario(bytes)).project;
if(!localStorage.getItem('independent-v1-installed')){
 const old=new Dexie('scenario-manager-local-v1');old.version(1).stores({projects:'projectId,name',entities:'[projectId+id],projectId,[projectId+kind]',relations:'[projectId+id],projectId,[projectId+fromId],[projectId+toId]',blocks:'[projectId+id],projectId,[projectId+entityId]',snapshots:'[projectId+id],projectId',commands:'operationId,projectId,[projectId+revision]',outbox:'operationId,projectId,accountId',assets:'contentHash',views:'[projectId+id],projectId',viewStates:'key,projectId',syncMetadata:'projectId',acks:'operationId,projectId',restorePoints:'id,projectId,createdAt',worlds:'id',importLogs:'operationId,projectId'});await old.open();const {entities,relations,snapshots,history,views,...header}=source;
 const asset=new Uint8Array([137,80,78,71,13,10,26,10]),hash=await sha256(asset);
 await old.transaction('rw',old.tables,async()=>{await old.table('projects').put({...header,entityIds:entities.map(e=>e.id),relationIds:relations.map(e=>e.id),snapshotIds:snapshots.map(e=>e.id),historyIds:history.map(e=>e.operationId),viewIds:views.map(e=>e.id)});await old.table('entities').bulkPut(entities.map(record=>({id:record.id,projectId:source.projectId,kind:record.kind,record})));if(relations.length)await old.table('relations').bulkPut(relations);await old.table('snapshots').bulkPut(snapshots.map(s=>({...s,projectId:source.projectId})));if(history.length)await old.table('commands').bulkPut(history.map(record=>({operationId:record.operationId,projectId:source.projectId,revision:record.revision,record})));if(views.length)await old.table('views').bulkPut(views.map(v=>({...v,projectId:source.projectId})));await old.table('assets').put({contentHash:hash,mediaType:'image/png',path:`assets/${hash}.png`,bytes:asset});await old.table('syncMetadata').put({projectId:source.projectId,serverRevision:source.revision,state:'synced'});});
 w.preUpgrade={version:old.verno,tables:old.tables.map(t=>t.name),projectId:source.projectId,assetHash:hash};localStorage.setItem('independent-v1-before',JSON.stringify(w.preUpgrade));old.close();localStorage.setItem('independent-v1-installed','true');
}
localStorage.setItem('scenario-last-project',source.projectId);
w.controls={source,before:JSON.parse(localStorage.getItem('independent-v1-before')!),read:()=>scenarioStore.getProject(source.projectId),replay:async()=>{const p=(await scenarioStore.getProject(source.projectId))!;return replaySavedTraceVerified(p,p.entities.find(e=>e.kind==='trace')!.id);},asset:()=>scenarioStore.getAsset(JSON.parse(localStorage.getItem('independent-v1-before')!).assetHash),after:async()=>{const db=new Dexie('scenario-manager-local-v1');await db.open();const d={version:db.verno,tables:db.tables.map(t=>t.name)};db.close();return d;}};
createRoot(document.getElementById('root')!).render(<App/>);
