import{it,expect}from'vitest';
import{mkdirSync,writeFileSync}from'node:fs';
import{createProject,createEntity,newId,validateProject}from'../src/domain/model';
import{startTrial,stepTrial,setTrialStubValues,checkTrialForeshadows,trialNarrativeOccurrences}from'../src/domain/runtime';
import{startChapterReading,presentNextChapterScene,checkChapterForeshadows,chapterNarrativeOccurrences}from'../src/domain/presentation';
import{assessPresentationClaims}from'../src/domain/narrative';
import{applyEffectsAtomic,initializeRuntimeState}from'../src/domain/conditions';
import type{Entity,EntityKind,ProjectData}from'../src/domain/types';
const dir='/tmp/shinariokanri-independent-rb05-narrative-f51f6b9/independent/fixtures';
function record(id:string,data:unknown){mkdirSync(dir,{recursive:true});writeFileSync(dir+'/'+id+'.json',JSON.stringify(data,null,2)+'\n');}
function add<K extends EntityKind>(p:ProjectData,kind:K,name:string,data:Partial<Entity<K>['data']>={}){const e=createEntity(p.projectId,kind,name,data);p.entities.push(e);return e;}
function flow(p:ProjectData,scenes:Entity<'scene'>[]){const entry=add(p,'flow_node','入口',{nodeType:'entry'}),nodes=scenes.map(s=>add(p,'flow_node',s.name,{nodeType:'scene',sceneId:s.id})),end=add(p,'flow_node','終端',{nodeType:'terminal',terminalReason:'本編の終端'}),all=[entry,...nodes,end],edges=all.slice(0,-1).map((n,i)=>add(p,'flow_edge','進む'+i,{fromId:n.id,toId:all[i+1].id})),graph=add(p,'flow_graph','本編',{nodeIds:all.map(n=>n.id),edgeIds:edges.map(e=>e.id),entryIds:[entry.id],exitIds:[end.id]});return{entry,nodes,end,edges,graph};}
function run(p:ProjectData,f:ReturnType<typeof flow>){let s=startTrial(p,{entryId:f.entry.id});for(const e of f.edges)s=stepTrial(p,s,{edgeId:e.id});return s;}
it('NP01 later stub provenance keeps presented-payoff missing information unknown',()=>{
 const p=createProject(),missing=add(p,'scene','未提示手掛かり',{body:[{id:newId(),kind:'paragraph',text:'未提示'}]}),scene=add(p,'scene','先に真相',{body:[{id:newId(),kind:'paragraph',text:'真相'}]}),v=add(p,'variable','仮値',{key:'stub',valueType:'integer',initial:{type:'integer',value:0},scope:'across_runs',allowed:{min:0,max:10}}),f=flow(p,[scene]),q=add(p,'foreshadow','必須情報Q',{resolutionPolicy:'this_work'}),clue=add(p,'disclosure','必須手掛かり',{foreshadowId:q.id,role:'clue',anchor:{entityId:missing.id,blockId:missing.data.body[0].id}}),payoff=add(p,'disclosure','先行回収',{foreshadowId:q.id,role:'payoff',stage:'reveal',anchor:{entityId:scene.id,blockId:scene.data.body[0].id}});q.data.clueIds=[clue.id];q.data.payoffIds=[payoff.id];q.data.requiredInfo=[clue.id];let s=startTrial(p,{entryId:f.entry.id});s=setTrialStubValues(p,s,{variables:{[v.id]:{type:'integer',value:1}}});for(const e of f.edges)s=stepTrial(p,s,{edgeId:e.id});const findings=checkTrialForeshadows(p,s);record('NP01',{project:p,validation:validateProject(p),session:s,findings});expect(validateProject(p).ok).toBe(true);expect(s.status).toBe('terminal');expect(s.startState.provenance).toBe('full_play');expect(s.state.provenance).toBe('stub');expect(findings.filter(x=>x.targetId===q.id).map(x=>x.status)).toEqual(['unknown']);
});
function knowledgeFixture(earlierScene=false,refForms=false){
 const p=createProject(),holder=add(p,'character','人物C'),subject=add(p,'character','世界の対象'),place=add(p,'place','参照値の場所'),source=add(p,'source','取得の出所',{sourceType:'observation',locator:'独立 fixture の提示時取得記録'}),acquireScene=add(p,'scene','先に知識を得る',{body:[{id:newId(),kind:'paragraph',text:'😀取得の本文'}]}),speakScene=earlierScene?add(p,'scene','知識を使う場面',{body:[]}):acquireScene;
 const truth=add(p,'assertion','作者真実',{subjectId:subject.id,predicate:'secret',value:refForms?place.id:{type:'boolean',value:true},truthKind:'author_truth'}),belief=add(p,'assertion','Cの取得する信念',{subjectId:subject.id,predicate:'secret',value:refForms?{type:'ref',value:place.id}:{type:'boolean',value:true},truthKind:'belief',holderId:holder.id,sourceIds:[source.id],evidenceLocation:{entityId:acquireScene.id,blockId:acquireScene.data.body[0].id,start:0,end:1}}),effect=add(p,'effect','Cが取得',{operation:'assert',targetId:belief.id,value:{type:'boolean',value:true}}),q=add(p,'foreshadow','知識取得の提示',{resolutionPolicy:'intentional_open'}),d=add(p,'disclosure','知識を渡す',{foreshadowId:q.id,anchor:{entityId:acquireScene.id,blockId:acquireScene.data.body[0].id,start:0,end:1},role:'clue',knowledgeEffects:[effect.id]}),line=add(p,'dialogue_line','Cの発言',{text:[{id:newId(),kind:'paragraph',text:'取得した情報を断言'}],speakerId:holder.id,claimAssertionIds:[truth.id],assertionIntent:'statement'});q.data.clueIds=[d.id];speakScene.data.dialogueLineIds=[line.id];for(const e of p.entities)e.status='confirmed';const f=flow(p,earlierScene?[acquireScene,speakScene]:[speakScene]);return{p,holder,belief,truth,line,f};
}
it('NP02 an earlier body disclosure can supply knowledge to a later dialogue in the same presentation',()=>{
 const r=knowledgeFixture(),s=run(r.p,r.f),assessments=assessPresentationClaims(r.p,trialNarrativeOccurrences(s));record('NP02',{project:r.p,validation:validateProject(r.p),session:s,assessments});expect(validateProject(r.p).ok).toBe(true);expect(s.status).toBe('terminal');expect(s.state.assertions.some(a=>a.assertionId===r.belief.id&&a.truth==='true')).toBe(true);expect(assessments.find(a=>a.lineId===r.line.id)?.knowledge).toBe('acquired');
});
it('NP03 a line-position Unicode deadline rejects a payoff later in that same line',()=>{
 const p=createProject(),line=add(p,'dialogue_line','期限と回収',{text:[{id:newId(),kind:'paragraph',text:'😀abc'}]}),scene=add(p,'scene','一場面',{body:[],dialogueLineIds:[line.id]}),f=flow(p,[scene]),q=add(p,'foreshadow','遅れた回収Q',{resolutionPolicy:'this_work',presentationDeadline:{entityId:line.id,lineId:line.id,start:1,end:2}}),payoff=add(p,'disclosure','期限より後の回収',{foreshadowId:q.id,role:'payoff',stage:'reveal',anchor:{entityId:line.id,lineId:line.id,start:3,end:4}});q.data.payoffIds=[payoff.id];const s=run(p,f),findings=checkTrialForeshadows(p,s);record('NP03',{project:p,validation:validateProject(p),session:s,findings});expect(validateProject(p).ok).toBe(true);expect(s.status).toBe('terminal');expect(findings.some(x=>x.targetId===q.id&&x.status==='candidate'&&/指定提示位置/.test(x.message))).toBe(true);
});
it('NP04 the direct ID and typed-ref forms of the same assertion value describe the same acquired information',()=>{
 const r=knowledgeFixture(true,true),s=run(r.p,r.f),assessments=assessPresentationClaims(r.p,trialNarrativeOccurrences(s));record('NP04',{project:r.p,validation:validateProject(r.p),session:s,assessments});expect(validateProject(r.p).ok).toBe(true);expect(s.status).toBe('terminal');expect(assessments.find(a=>a.lineId===r.line.id)?.knowledge).toBe('acquired');
});
it('NP05 terminal unrecovered information is evaluated for both chapter and flow occurrence order',async()=>{
 const p=createProject(),scene=add(p,'scene','手掛かりだけ',{body:[{id:newId(),kind:'paragraph',text:'提示する手掛かり'}]}),absent=add(p,'scene','回収しない場面',{body:[{id:newId(),kind:'paragraph',text:'提示されない回収'}]}),f=flow(p,[scene]),q=add(p,'foreshadow','今作で回収するQ',{resolutionPolicy:'this_work'}),clue=add(p,'disclosure','手掛かりC',{foreshadowId:q.id,role:'clue',anchor:{entityId:scene.id,blockId:scene.data.body[0].id}}),payoff=add(p,'disclosure','回収P',{foreshadowId:q.id,role:'payoff',anchor:{entityId:absent.id,blockId:absent.data.body[0].id}});q.data.clueIds=[clue.id];q.data.payoffIds=[payoff.id];const flowReading=run(p,f),flowFindings=checkTrialForeshadows(p,flowReading),chapter=presentNextChapterScene(p,await startChapterReading(p,{sceneIds:[scene.id]})),chapterFindings=checkChapterForeshadows(chapter);record('NP05',{project:p,validation:validateProject(p),flowReading,flowFindings,chapter,chapterFindings});expect(validateProject(p).ok).toBe(true);expect(flowFindings.some(x=>x.targetId===q.id&&x.status==='candidate')).toBe(true);expect(chapterFindings.some(x=>x.targetId===q.id&&x.status==='unknown')).toBe(true);
});
it('NP06 earlier-scene acquisition remains known at later-scene speech in both flow and chapter',async()=>{
 const r=knowledgeFixture(true),s=run(r.p,r.f),flowAssessments=assessPresentationClaims(r.p,trialNarrativeOccurrences(s));let chapter=await startChapterReading(r.p,{sceneIds:r.f.nodes.map(n=>n.data.sceneId!)});while(chapter.status==='ready')chapter=presentNextChapterScene(r.p,chapter);const chapterAssessments=assessPresentationClaims(chapter.content,chapterNarrativeOccurrences(chapter));record('NP06',{project:r.p,validation:validateProject(r.p),session:s,flowAssessments,chapter,chapterAssessments});expect(validateProject(r.p).ok).toBe(true);expect(flowAssessments.find(a=>a.lineId===r.line.id)?.knowledge).toBe('acquired');expect(chapterAssessments.find(a=>a.lineId===r.line.id)?.knowledge).toBe('acquired');
});
it('NP07 an unresolved explicit presentation deadline remains unknown at the terminal',()=>{
 const p=createProject(),scene=add(p,'scene','期限のある場面',{body:[{id:newId(),kind:'paragraph',text:'期限を再リンクする本文'}]}),f=flow(p,[scene]),q=add(p,'foreshadow','再リンク待ちの期限',{resolutionPolicy:'this_work',presentationDeadline:{entityId:scene.id,blockId:scene.data.body[0].id,positionStatus:'unresolved',positionReason:'元の文字範囲が本文改稿で特定できない'}}),s=run(p,f),findings=checkTrialForeshadows(p,s);record('NP07',{project:p,validation:validateProject(p),session:s,findings});expect(validateProject(p).ok).toBe(true);expect(s.status).toBe('terminal');expect(findings.filter(x=>x.targetId===q.id).map(x=>x.status)).toEqual(['unknown']);
});
it('NP08 a legacy occurrence without a pre-effect observation cannot borrow a later acquisition for earlier speech',()=>{
 const r=knowledgeFixture(),scene=r.p.entities.find((e):e is Entity<'scene'>=>e.kind==='scene'&&e.id===r.f.nodes[0].data.sceneId)!,late=add(r.p,'dialogue_line','発言の後で知識を得る',{text:[{id:newId(),kind:'paragraph',text:'ここで初めて取得'}]});late.status='confirmed';scene.data.body=[];scene.data.dialogueLineIds=[r.line.id,late.id];const anchor={entityId:late.id,lineId:late.id,blockId:late.data.text[0].id,start:0,end:1};r.belief.data.evidenceLocation=anchor;const d=r.p.entities.find((e):e is Entity<'disclosure'>=>e.kind==='disclosure')!;d.data.anchor=anchor;const s=run(r.p,r.f),occurrences=trialNarrativeOccurrences(s),normal=assessPresentationClaims(r.p,occurrences),legacy=assessPresentationClaims(r.p,occurrences.map(({observationState:_observationState,...occurrence})=>occurrence));record('NP08',{project:r.p,validation:validateProject(r.p),session:s,normal,legacy,legacyOccurrences:occurrences.map(({observationState:_observationState,...occurrence})=>occurrence)});expect(validateProject(r.p).ok).toBe(true);expect(s.status).toBe('terminal');expect(normal.find(x=>x.lineId===r.line.id)?.knowledge).toBe('not_acquired');expect(legacy.find(x=>x.lineId===r.line.id)?.knowledge).toBe('unknown');
});
for(const [suffix,mode]of[['a','missing-source'],['b','expired'],['c','rejected-source']]as const)it(`NP09${suffix} invalid acquisition ${mode} rolls back the entire group`,()=>{
 const r=knowledgeFixture(),money=add(r.p,'variable','金額',{key:'money',valueType:'integer',initial:{type:'integer',value:0},scope:'across_runs',allowed:{min:0,max:10}}),pay=add(r.p,'effect','先に金額を増やす',{operation:'add',targetId:money.id,value:{type:'integer',value:1}}),acquire=r.p.entities.find((e):e is Entity<'effect'>=>e.kind==='effect'&&e.data.operation==='assert')!;if(mode==='missing-source')r.belief.data.sourceIds=[];if(mode==='rejected-source')r.p.entities.find(e=>e.id===r.belief.data.sourceIds![0])!.status='rejected';if(mode==='expired')r.belief.data.validity={worldRange:{start:'0',end:'2'},routeCondition:null,presentationAnchor:null};const state=initializeRuntimeState(r.p),anchor=r.belief.data.evidenceLocation!;state.seenIds=[anchor.entityId,anchor.blockId!];const before=structuredClone(state),result=applyEffectsAtomic(state,[pay,acquire],{state,entities:r.p.entities,ruleContext:{projectId:r.p.projectId,worldTick:'2'}});record('NP09'+suffix,{project:r.p,validation:validateProject(r.p),before,result,originalState:state});expect(validateProject(r.p).ok).toBe(true);expect(result.ok).toBe(false);expect(result.state).toEqual(before);expect(state).toEqual(before);expect(result.state.variableValues[money.id]).toEqual({type:'integer',value:0});expect(result.state.assertions).toEqual([]);
});
it('NP10 author truth and source metadata alone do not give knowledge; an intentional lie stays separate',()=>{
 const r=knowledgeFixture();for(const e of r.p.entities)if(e.kind==='disclosure')e.data.knowledgeEffects=[];const s=run(r.p,r.f),normal=assessPresentationClaims(r.p,trialNarrativeOccurrences(s));r.line.data.assertionIntent='lie';r.line.data.assertionReason='相手に真相を渡さないため';const intentional=assessPresentationClaims(r.p,trialNarrativeOccurrences(s));record('NP10',{project:r.p,validation:validateProject(r.p),session:s,normal,intentional});expect(validateProject(r.p).ok).toBe(true);expect(s.state.assertions).toEqual([]);expect(normal.find(x=>x.lineId===r.line.id)).toMatchObject({knowledge:'not_acquired',status:'candidate'});expect(intentional.find(x=>x.lineId===r.line.id)).toMatchObject({knowledge:'not_acquired',status:'intentional'});
});
it('NP03b a whole-block deadline is not satisfied by a payoff in a later block of the same presentation',()=>{
 const p=createProject(),scene=add(p,'scene','同一提示の別段落',{body:[{id:newId(),kind:'paragraph',text:'ここが期限'},{id:newId(),kind:'paragraph',text:'期限後の回収'}]}),f=flow(p,[scene]),q=add(p,'foreshadow','段落期限Q',{resolutionPolicy:'this_work',presentationDeadline:{entityId:scene.id,blockId:scene.data.body[0].id}}),payoff=add(p,'disclosure','後の段落で回収',{foreshadowId:q.id,role:'payoff',stage:'reveal',anchor:{entityId:scene.id,blockId:scene.data.body[1].id}});q.data.payoffIds=[payoff.id];const s=run(p,f),findings=checkTrialForeshadows(p,s);record('NP03b',{project:p,validation:validateProject(p),session:s,findings});expect(validateProject(p).ok).toBe(true);expect(s.status).toBe('terminal');expect(findings.some(x=>x.targetId===q.id&&x.status==='candidate'&&/指定提示位置/.test(x.message))).toBe(true);
});
it('NP07b a shown payoff cannot certify an unresolved deadline earlier in the same line',()=>{
 const p=createProject(),line=add(p,'dialogue_line','期限位置が不明',{text:[{id:newId(),kind:'paragraph',text:'😀abc'}]}),scene=add(p,'scene','曖昧な期限',{body:[],dialogueLineIds:[line.id]}),f=flow(p,[scene]),q=add(p,'foreshadow','期限内か未確認Q',{resolutionPolicy:'this_work',presentationDeadline:{entityId:line.id,lineId:line.id,positionStatus:'unresolved',positionReason:'改稿後に期限の文字位置を再選択する'}}),payoff=add(p,'disclosure','真相は提示された',{foreshadowId:q.id,role:'payoff',stage:'reveal',anchor:{entityId:line.id,lineId:line.id,start:3,end:4}});q.data.payoffIds=[payoff.id];const s=run(p,f),findings=checkTrialForeshadows(p,s);record('NP07b',{project:p,validation:validateProject(p),session:s,findings});expect(validateProject(p).ok).toBe(true);expect(s.status).toBe('terminal');expect(findings.some(x=>x.targetId===q.id&&x.status==='unknown')).toBe(true);
});
