import 'fake-indexeddb/auto';
import { it, expect } from 'vitest';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { createProject, createEntity, newId, validateProject, emptyValidity } from '../src/domain/model';
import type { Entity, EntityKind, ProjectData } from '../src/domain/types';
import { prepareReuse } from '../src/domain/reuse';
import { startChapterReading, presentNextChapterScene } from '../src/domain/presentation';
import { startTrialVerified, replaySavedTraceVerified } from '../src/domain/runtimeVerified';
import { preparePartialCheckpoint, previewCheckpointMigration, confirmedCheckpointMigration } from '../src/domain/checkpoints';
import { sha256, jsonBytes } from '../src/storage/json';
import { validateProjectIntegrity } from '../src/domain/projectRecordValidation';
import { exportScenario, inspectScenario } from '../src/storage/archive';
import { ScenarioStore, cloneProject } from '../src/storage/store';
import { startTrial, stepTrial, pinTrialRecord } from '../src/domain/runtime';
const out='/tmp/shinariokanri-independent-rb05-narrative-f51f6b9/independent/fixtures';
function save(id:string,data:unknown){mkdirSync(out,{recursive:true});writeFileSync(`${out}/${id}.json`,JSON.stringify(data,null,2)+'\n');}
function add<K extends EntityKind>(p:ProjectData,kind:K,data:Partial<Entity<K>['data']>={},name:string=kind):Entity<K>{const entity=createEntity(p.projectId,kind,name,data);p.entities.push(entity);return entity;}
async function fixedReuse(){
 let p=createProject('有限例外付き固定共通場面');const fixed=newId(),evidence=add(p,'source',{locator:'確定根拠'});evidence.status='confirmed';
 const other=add(p,'variable',{key:'other',initial:{type:'boolean',value:true}}),v=add(p,'variable',{key:'borrowed',initial:{type:'boolean',value:true},exclusions:[{variableId:other.id,value:{type:'boolean',value:true},otherValue:{type:'boolean',value:true},reason:'限定期間に確定根拠があるときのみ同時採用',exceptions:[{reason:'固定元の限定期間',evidenceIds:[evidence.id],targetScope:{projectId:p.projectId,targetSnapshotId:fixed},validity:{...emptyValidity(),worldRange:{start:'0',end:'10'}}}]}]});
 const source=add(p,'scene',{body:[{id:newId(),kind:'paragraph',text:'限定期間内の固定本文',links:[{start:0,end:2,target:{entityId:v.id}}]}]},'固定共通元'),use=add(p,'scene',{},'使用先'),chapter=add(p,'chapter',{sceneIds:[use.id]},'使用先章');use.data.chapterId=chapter.id;
 const entry=add(p,'flow_node',{nodeType:'entry',sceneId:use.id}),end=add(p,'flow_node',{nodeType:'terminal',terminalReason:'正規終了'}),edge=add(p,'flow_edge',{fromId:entry.id,toId:end.id});add(p,'flow_graph',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});
 const{snapshots:_s,history:_h,authorAlternatives:_a,...content}=structuredClone(p);p.snapshots.push({id:fixed,content,contentHash:await sha256(jsonBytes(content)),createdAt:'2026-10-08T08:00:00Z',versionLabel:'元版'});v.data.initial={type:'boolean',value:false};v.data.exclusions=[];
 p=(await prepareReuse(p,{ownerId:use.id,sourceId:source.id,snapshotId:fixed,mode:'reference'})).candidate;return{p,use,chapter,entry,fixed};
}

async function stubBase(){
 const p=createProject('型付き個別状態+stubの独立境界'),money=add(p,'variable',{key:'money',valueType:'integer',initial:{type:'integer',value:2},scope:'across_runs',allowed:{min:0,max:100}}),untouched=add(p,'variable',{key:'untouched',valueType:'integer',initial:{type:'integer',value:4},scope:'across_runs',allowed:{min:0,max:100}}),contract=add(p,'external_contract',{key:'item_gate',owner:'game'}),type=add(p,'item',{itemMode:'type'}),item=add(p,'item',{itemMode:'instance',typeId:type.id}),entry=add(p,'flow_node',{nodeType:'entry'}),end=add(p,'flow_node',{nodeType:'terminal',terminalReason:'宣言終端'}),edge=add(p,'flow_edge',{fromId:entry.id,toId:end.id});add(p,'flow_graph',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});
 const base=structuredClone(startTrial(p).state);base.variableValues[money.id]={type:'integer',value:7};base.variableValues[untouched.id]={type:'integer',value:12};base.loopNumber=3;base.provenance='partial';base.itemInstances=[{instanceId:item.id,typeId:type.id,quantity:1,ownerId:null,locationId:null,consumed:false}];
 const initial=startTrial(p,{entryId:entry.id,state:base,worldTick:'5',stub:{variables:{[money.id]:{type:'integer',value:8}},external:{[contract.id]:{type:'boolean',value:true}}}}),ended=stepTrial(p,initial,{edgeId:edge.id}),ids={checkpointId:newId(),snapshotId:newId()},record=pinTrialRecord(ended,ids),cp={...createEntity(p.projectId,'checkpoint','部分開始+stub',record.checkpoint),id:ids.checkpointId},trace=add(p,'trace',record.trace);p.entities.push(cp);p.snapshots.push({id:ids.snapshotId,content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:'2026-10-08T08:30:00Z',versionLabel:'型付き個別開始'});expect(ended.status).toBe('terminal');expect(validateProject(p).ok).toBe(true);return{p,cp,trace,money,untouched,contract,item,type,base,ended};
}
it('EN14 independently preserves partial base, external stub, inventory and clock through atomic restart/native/clone',async()=>{
 const f=await stubBase(),databaseName='independent-stub-base-'+newId(),store=new ScenarioStore({databaseName});let cold:ScenarioStore|undefined;
 try{await store.saveProject(f.p,{reason:'個別開始+初期stubの原子保存'});store.close();cold=new ScenarioStore({databaseName});const loaded=(await cold.getProject(f.p.projectId))!,bytes=await exportScenario(loaded),restored=(await inspectScenario(bytes,{worker:false})).project,clone=await cloneProject(restored),results=[];
 for(const target of[loaded,restored,clone.project]){const map=target===clone.project?clone.idMap:undefined,key=(id:string)=>map?.[id]??id,trace=target.entities.find((e):e is Entity<'trace'>=>e.id===key(f.trace.id)&&e.kind==='trace')!,replay=await replaySavedTraceVerified(target,trace.id);results.push({status:replay.status,startProvenance:replay.startState.provenance,baseProvenance:trace.data.initialStubBaseState!.provenance,baseMoney:trace.data.initialStubBaseState!.variableValues[key(f.money.id)],baseUntouched:trace.data.initialStubBaseState!.variableValues[key(f.untouched.id)],startMoney:replay.startState.variableValues[key(f.money.id)],external:replay.startExternalValues[key(f.contract.id)],itemRetained:replay.startState.itemInstances.some(x=>x.instanceId===key(f.item.id)&&x.typeId===key(f.type.id)),clock:replay.initialWorldTick,loop:replay.startState.loopNumber});}
 save('EN14',{project:f.p,loaded,restored,clone,archiveBytes:bytes.byteLength,results});expect(results).toEqual(Array.from({length:3},()=>({status:'terminal',startProvenance:'stub',baseProvenance:'partial',baseMoney:{type:'integer',value:7},baseUntouched:{type:'integer',value:12},startMoney:{type:'integer',value:8},external:{type:'boolean',value:true},itemRetained:true,clock:'5',loop:3})));
 }finally{cold?.close();await store.deleteDatabase();}
});
it('EN15 known clocks, half-open limits and ambiguous old clocks preserve safe target execution',async()=>{
 const f=await fixedReuse(),cp=await preparePartialCheckpoint(f.p,{entryId:f.entry.id,worldTick:'5'});f.p.entities.push(cp.checkpoint);f.p.snapshots.push(...cp.snapshots);const plan=await previewCheckpointMigration(f.p,cp.checkpoint.id,{entryId:f.entry.id}),approved=await confirmedCheckpointMigration(f.p,plan,'migrate');f.p.entities.push(approved.checkpoint);f.p.snapshots.push(...approved.snapshots);const replay=await startTrialVerified(f.p,{checkpointId:approved.checkpoint.id,contentVersionId:approved.checkpoint.data.contentVersionId}),unknownFlow=await startTrialVerified(f.p,{entryId:f.entry.id}),unknownChapter=await startChapterReading(f.p,{sceneIds:[f.use.id]}),boundaries=[];
 for(const tick of['0','9','10']){const flow=await startTrialVerified(f.p,{entryId:f.entry.id,worldTick:tick});let chapterStatus='',error='';try{chapterStatus=(await startChapterReading(f.p,{sceneIds:[f.use.id],worldTick:tick})).status;}catch(e){error=(e as Error).message;}boundaries.push({tick,flow:flow.status,chapterStatus,error});}
 const forged=structuredClone(plan);forged.targetWorldTick='6';let forgedError='',expiredError='';try{await confirmedCheckpointMigration(f.p,forged,'migrate');}catch(e){forgedError=(e as Error).message;}try{await previewCheckpointMigration(f.p,cp.checkpoint.id,{entryId:f.entry.id,worldTick:'10'});}catch(e){expiredError=(e as Error).message;}
 delete cp.checkpoint.data.worldTick;for(const tick of['5','6'])add(f.p,'trace',{contentVersionId:cp.checkpoint.data.contentVersionId,startCheckpointId:cp.checkpoint.id,initialWorldTick:tick});let ambiguousError='';try{await previewCheckpointMigration(f.p,cp.checkpoint.id,{entryId:f.entry.id});}catch(e){ambiguousError=(e as Error).message;}
 save('EN15',{project:f.p,plan,approved,replay,unknownFlow,unknownChapter,boundaries,forgedError,expiredError,ambiguousError});expect(approved.checkpoint.data.worldTick).toBe('5');expect(replay.status).toBe('ready');expect(unknownFlow.status).toBe('unknown');expect(unknownChapter.status).toBe('unknown');expect(boundaries.map(x=>x.flow)).toEqual(['ready','ready','error']);expect(boundaries.slice(0,2).map(x=>x.chapterStatus)).toEqual(['ready','ready']);expect(boundaries[2].error).toMatch(/相互排他/);expect(forgedError).toMatch(/変更/);expect(expiredError).toMatch(/相互排他/);expect(ambiguousError).toMatch(/複数/);
});
it('EN16 explicit chapter selection does not append an unselected orphan or expand an empty chosen set',async()=>{
 const f=await fixedReuse(),one=await startChapterReading(f.p,{chapterIds:[f.chapter.id],worldTick:'5'}),empty=await startChapterReading(f.p,{chapterIds:[],worldTick:'5'}),all=await startChapterReading(f.p,{worldTick:'5'}),scene=await startChapterReading(f.p,{sceneIds:[f.use.id],worldTick:'5'});save('EN16',{project:f.p,validation:validateProject(f.p),one,empty,all,scene});expect(scene.sceneIds).toEqual([f.use.id]);expect(presentNextChapterScene(f.p,scene).status).toBe('terminal');expect(one.sceneIds).toEqual([f.use.id]);expect(empty.sceneIds).toEqual([]);expect(all.sceneIds.length).toBe(2);
});
it('EN17 ordinary flow clock contradictions are rejected at durable/native boundaries as well as replay',async()=>{
 const p=createProject('仮値なしの開始時点矛盾'),entry=add(p,'flow_node',{nodeType:'entry'}),end=add(p,'flow_node',{nodeType:'terminal',terminalReason:'終端'}),edge=add(p,'flow_edge',{fromId:entry.id,toId:end.id});add(p,'flow_graph',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});const ended=stepTrial(p,startTrial(p,{worldTick:'5'}),{edgeId:edge.id}),ids={checkpointId:newId(),snapshotId:newId()},record=pinTrialRecord(ended,ids),cp={...createEntity(p.projectId,'checkpoint','時点5',record.checkpoint),id:ids.checkpointId},trace=add(p,'trace',record.trace);p.entities.push(cp);p.snapshots.push({id:ids.snapshotId,content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:'2026-10-08T08:30:00Z',versionLabel:'時点5'});expect((await replaySavedTraceVerified(p,trace.id)).status).toBe('terminal');trace.data.initialWorldTick='6';const replay=await replaySavedTraceVerified(p,trace.id),issues=await validateProjectIntegrity(p);let accepted=false,error='';try{await inspectScenario(await exportScenario(p),{worker:false});accepted=true;}catch(e){error=(e as Error).message;}save('EN17',{project:p,validation:validateProject(p),replay,issues,accepted,error});expect(replay.status).toBe('error');expect(issues.length).toBeGreaterThan(0);expect(accepted).toBe(false);
});
it('EN18 altered untouched base state, wrong base edition and external stub contradictions stop replay and restore',async()=>{
 const f=await stubBase(),cases=[];
 for(const mode of['base-value','base-edition','external-input','external-captured']as const){const p=structuredClone(f.p),trace=p.entities.find((e):e is Entity<'trace'>=>e.id===f.trace.id&&e.kind==='trace')!;if(mode==='base-value')trace.data.initialStubBaseState!.variableValues[f.untouched.id]={type:'integer',value:13};if(mode==='base-edition')trace.data.initialStubBaseState!.contentVersionId=p.projectId;if(mode==='external-input')trace.data.initialStubValues!.external![f.contract.id]={type:'boolean',value:false};if(mode==='external-captured')trace.data.initialExternalValues![f.contract.id]={type:'boolean',value:false};const replay=await replaySavedTraceVerified(p,trace.id),issues=await validateProjectIntegrity(p);let accepted=false,error='';try{await inspectScenario(await exportScenario(p),{worker:false});accepted=true;}catch(e){error=(e as Error).message;}cases.push({mode,status:replay.status,issues,accepted,error});}
 save('EN18',{project:f.p,cases});expect(cases.every(x=>x.status==='error'&&x.issues.length>0&&!x.accepted)).toBe(true);
});
