import 'fake-indexeddb/auto';
import { it, expect } from 'vitest';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { createProject, createEntity, newId, validateProject, emptyValidity } from '../src/domain/model';
import type { Entity, EntityKind, ProjectData } from '../src/domain/types';
import { prepareReuse } from '../src/domain/reuse';
import { startChapterReading, presentNextChapterScene } from '../src/domain/presentation';
import { startTrialVerified, replaySavedTraceVerified } from '../src/domain/runtimeVerified';
import { preparePartialCheckpoint, previewCheckpointMigration, confirmedCheckpointMigration } from '../src/domain/checkpoints';
import { sha256, jsonBytes } from '../src/storage/json';
import { validateProjectIntegrity } from '../src/domain/projectRecordValidation';
import { exportScenario, inspectScenario } from '../src/storage/archive';
import { startTrial, stepTrial, backTrial, pinTrialRecord, declaredEntrypoints } from '../src/domain/runtime';
import { ScenarioStore, cloneProject } from '../src/storage/store';
const out='/tmp/shinariokanri-independent-rb05-narrative-7812804/independent/fixtures';
function save(id:string,data:unknown){mkdirSync(out,{recursive:true});writeFileSync(`${out}/${id}.json`,JSON.stringify(data,null,2)+'\n');}
function add<K extends EntityKind>(p:ProjectData,kind:K,data:Partial<Entity<K>['data']>={},name:string=kind):Entity<K>{const entity=createEntity(p.projectId,kind,name,data);p.entities.push(entity);return entity;}
async function fixedReuse(scope:'graph'|'chapter'){
 let p=createProject('有限例外付き固定共通場面');const fixed=newId(),evidence=add(p,'source',{locator:'確定根拠'});evidence.status='confirmed';
 const other=add(p,'variable',{key:'other',initial:{type:'boolean',value:true}}),v=add(p,'variable',{key:'borrowed',initial:{type:'boolean',value:true},exclusions:[{variableId:other.id,value:{type:'boolean',value:true},otherValue:{type:'boolean',value:true},reason:'限定期間に確定根拠があるときのみ同時採用',exceptions:[{reason:'固定元の限定期間',evidenceIds:[evidence.id],targetScope:{projectId:p.projectId,targetSnapshotId:fixed},validity:{...emptyValidity(),worldRange:{start:'0',end:'10'}}}]}]});
 const source=add(p,'scene',{body:[{id:newId(),kind:'paragraph',text:'限定期間内の固定本文',links:[{start:0,end:2,target:{entityId:v.id}}]}]},'固定共通元'),use=add(p,'scene',{},'使用先'),chapter=add(p,'chapter',{sceneIds:[use.id]},'使用先章');use.data.chapterId=chapter.id;
 const entry=add(p,'flow_node',{nodeType:'entry',sceneId:use.id}),end=add(p,'flow_node',{nodeType:'terminal',terminalReason:'正規終了'}),edge=add(p,'flow_edge',{fromId:entry.id,toId:end.id});const graph=add(p,'flow_graph',{nodeIds:[entry.id,end.id],edgeIds:[edge.id],entryIds:[entry.id],exitIds:[end.id]});v.data.exclusions![0].exceptions![0].targetScope[scope==='graph'?'graphId':'chapterId']=scope==='graph'?graph.id:chapter.id;
 const{snapshots:_s,history:_h,authorAlternatives:_a,...content}=structuredClone(p);p.snapshots.push({id:fixed,content,contentHash:await sha256(jsonBytes(content)),createdAt:'2026-10-08T08:00:00Z',versionLabel:'元版'});v.data.initial={type:'boolean',value:false};v.data.exclusions=[];
 const original=await startTrialVerified(p,{contentVersionId:fixed,entryId:entry.id,worldTick:'5'});p=(await prepareReuse(p,{ownerId:use.id,sourceId:source.id,snapshotId:fixed,mode:'reference'})).candidate;return{p,use,chapter,entry,fixed,original,source,graph};
}


for(const scope of ['graph','chapter']as const)it(`CTX-${scope}-extended protects use-site limits, clock, immutable restoration and migration`,async()=>{
 const f=await fixedReuse(scope),base=structuredClone(f.p),restored=(await inspectScenario(await exportScenario(f.p),{worker:false})).project,clone=await cloneProject(restored),preserved=[];
 for(const p of[restored,clone.project]){const map=p===clone.project?clone.idMap:undefined,key=(id:string)=>map?.[id]??id;const run=await startTrialVerified(p,{entryId:key(f.entry.id),worldTick:'5'});let chapterStatus='';if(scope==='chapter')chapterStatus=(await startChapterReading(p,{chapterIds:[key(f.chapter.id)],worldTick:'5'})).status;preserved.push({valid:validateProject(p).ok,status:run.status,chapterStatus});}
 const cp=await preparePartialCheckpoint(f.p,{entryId:f.entry.id,worldTick:'5'});f.p.entities.push(cp.checkpoint);f.p.snapshots.push(...cp.snapshots);const preview=await previewCheckpointMigration(f.p,cp.checkpoint.id,{entryId:f.entry.id}),migration=await confirmedCheckpointMigration(f.p,preview,'migrate');
 const otherScene=add(f.p,'scene',{},'範囲外場面'),otherChapter=add(f.p,'chapter',{sceneIds:[otherScene.id]},'範囲外章');otherScene.data.chapterId=otherChapter.id;const otherEntry=add(f.p,'flow_node',{nodeType:'entry',sceneId:otherScene.id}),otherEnd=add(f.p,'flow_node',{nodeType:'terminal',terminalReason:'別の終了'}),otherEdge=add(f.p,'flow_edge',{fromId:otherEntry.id,toId:otherEnd.id});add(f.p,'flow_graph',{nodeIds:[otherEntry.id,otherEnd.id],edgeIds:[otherEdge.id],entryIds:[otherEntry.id],exitIds:[otherEnd.id]});
 const rebound=(await prepareReuse(f.p,{ownerId:otherScene.id,sourceId:f.source.id,snapshotId:f.fixed,mode:'reference'})).candidate,denied=await startTrialVerified(rebound,{entryId:otherEntry.id,worldTick:'5'}),expired=await startTrialVerified(base,{entryId:f.entry.id,worldTick:'10'}),unknown=await startTrialVerified(base,{entryId:f.entry.id});
 save(`CTX-${scope}-extended`,{project:base,restored,clone,preserved,migration,rebound,denied,expired,unknown});expect(preserved).toEqual(Array.from({length:2},()=>({valid:true,status:'ready',chapterStatus:scope==='chapter'?'ready':''})));expect(migration.checkpoint.data.worldTick).toBe('5');expect(migration.checkpoint.data.runtimeState.provenance).toBe('partial');expect(denied.status).toBe('error');expect(denied.issues.some(x=>x.code==='TRANSITION_BLOCKED')).toBe(true);expect(expired.status).toBe('error');expect(unknown.status).toBe('unknown');
});

async function fixedChild(){
 let p=createProject('独立 固定子graphの原子実行'),evidence=add(p,'source',{locator:'内部graph専用の採用済み根拠'},'子範囲の根拠');evidence.status='confirmed';
 const v=add(p,'variable',{key:'child_transition',valueType:'integer',initial:{type:'integer',value:0},scope:'across_runs',allowed:{min:0,max:3},transitionRules:[{from:{type:'integer',value:0},to:{type:'integer',value:1}}]},'子内の限定値'),money=add(p,'variable',{key:'child_money',valueType:'integer',initial:{type:'integer',value:4},scope:'across_runs',allowed:{min:0,max:100}},'子内の金額'),item=add(p,'item',{itemMode:'type'},'子内の物品');
 const childEntry=add(p,'flow_node',{nodeType:'entry'},'固定子の入口'),childExit=add(p,'flow_node',{nodeType:'exit'},'固定子の出口'),childEdge=add(p,'flow_edge',{fromId:childEntry.id,toId:childExit.id,label:'子内の遷移'},'子内の遷移'),child=add(p,'flow_graph',{nodeIds:[childEntry.id,childExit.id],edgeIds:[childEdge.id],entryIds:[childEntry.id],exitIds:[childExit.id]},'固定子graph');
 const gain=add(p,'effect',{operation:'add',targetId:money.id,value:{type:'integer',value:5}},'子内+5'),grant=add(p,'effect',{operation:'grant',targetId:item.id,value:{type:'integer',value:1}},'子内取得'),effect=add(p,'effect',{operation:'set',targetId:v.id,value:{type:'integer',value:2},exceptionDetails:{reason:'この固定子graph内の期間限定遷移',evidenceIds:[evidence.id],targetScope:{projectId:p.projectId,graphId:child.id},validity:{...emptyValidity(),worldRange:{start:'0',end:'10'}}}},'子内0→2の限定許可');childEdge.data.effectIds=[gain.id,grant.id,effect.id];
 const source=add(p,'flow_node',{nodeType:'call',childGraphId:child.id},'固定呼出元'),entry=add(p,'flow_node',{nodeType:'entry'},'呼出元入口'),use=add(p,'flow_node',{},'固定呼出し使用先'),end=add(p,'flow_node',{nodeType:'terminal',terminalReason:'子graphから正規復帰'},'呼出元終端'),enter=add(p,'flow_edge',{fromId:entry.id,toId:use.id,label:'固定callへ'},'固定callへ'),leave=add(p,'flow_edge',{fromId:use.id,toId:end.id,edgeType:'call_return',label:'固定callから戻る'},'固定callから戻る');add(p,'flow_graph',{nodeIds:[entry.id,use.id,end.id],edgeIds:[enter.id,leave.id],entryIds:[entry.id],exitIds:[end.id]},'呼出元graph');
 p=(await prepareReuse(p,{ownerId:use.id,sourceId:source.id,mode:'reference'})).candidate;return{p,evidence,v,money,item,childEntry,childExit,childEdge,child,source,entry,use,end,enter,leave};
}
it('CTX-child-independent keeps real virtual child scope and rejects expired/unknown effects as an entire group',async()=>{
 const f=await fixedChild();expect(validateProject(f.p).ok).toBe(true);const native=(await inspectScenario(await exportScenario(f.p),{worker:false})).project;let run=await startTrialVerified(native,{entryId:f.entry.id,worldTick:'5'});const use=native.entities.find((e):e is Entity<'flow_node'>=>e.id===f.use.id&&e.kind==='flow_node')!,bindings=use.data.reuse!.bindings!;
 run=stepTrial(native,run,{edgeId:f.enter.id,worldTick:'5'});run=stepTrial(native,run,{worldTick:'5'});expect(run.status).toBe('ready');expect(run.nodeId).toBe(bindings[f.childEntry.id]);expect(run.state.callStack[0].graphId).toBe(bindings[f.child.id]);const before=structuredClone(run.state),expired=stepTrial(native,run,{edgeId:bindings[f.childEdge.id],worldTick:'10'}),unknown=stepTrial(native,run,{edgeId:bindings[f.childEdge.id]});
 expect(expired.status).toBe('error');expect(expired.state).toEqual(before);expect(unknown.status).toBe('unknown');expect(unknown.state).toEqual(before);run=stepTrial(native,run,{edgeId:bindings[f.childEdge.id],worldTick:'5'});expect(run.status).toBe('ready');expect(run.nodeId).toBe(bindings[f.childExit.id]);expect(run.state.variableValues[bindings[f.v.id]]).toEqual({type:'integer',value:2});expect(run.state.variableValues[bindings[f.money.id]]).toEqual({type:'integer',value:9});expect(run.state.itemInstances.some(x=>x.typeId===bindings[f.item.id]&&x.quantity===1)).toBe(true);const back=backTrial(run);expect(back.state).toEqual(before);run=stepTrial(native,run,{worldTick:'5'});expect(run.status).toBe('terminal');
 const ids={checkpointId:newId(),snapshotId:newId()},record=pinTrialRecord(run,ids),cp={...createEntity(native.projectId,'checkpoint','固定子の旧開始',record.checkpoint),id:ids.checkpointId},trace=add(native,'trace',record.trace,'固定子graphの保存経路');native.entities.push(cp);native.snapshots.push({id:ids.snapshotId,content:record.content,contentHash:await sha256(jsonBytes(record.content)),createdAt:'2026-10-08T09:20:00Z',versionLabel:'固定子の証跡'});
 const databaseName='independent-ctx-child-'+newId(),store=new ScenarioStore({databaseName});let cold:ScenarioStore|undefined;const results=[];
 try{await store.saveProject(native,{reason:'固定子graph原子保存'});store.close();cold=new ScenarioStore({databaseName});const loaded=(await cold.getProject(native.projectId))!,restored=(await inspectScenario(await exportScenario(loaded),{worker:false})).project,clone=await cloneProject(restored);
 for(const p of[loaded,restored,clone.project]){const map=p===clone.project?clone.idMap:undefined,session=await replaySavedTraceVerified(p,map?.[trace.id]??trace.id),owner=p.entities.find((e):e is Entity<'flow_node'>=>e.id===(map?.[f.use.id]??f.use.id)&&e.kind==='flow_node')!,b=owner.data.reuse!.bindings!,vKey=b[map?.[f.v.id]??f.v.id],mKey=b[map?.[f.money.id]??f.money.id];results.push({status:session.status,provenance:session.startState.provenance,externalMode:p.entities.find((e):e is Entity<'trace'>=>e.id===(map?.[trace.id]??trace.id)&&e.kind==='trace')!.data.externalMode,clock:session.initialWorldTick,depth:session.state.callStack.length,limited:session.state.variableValues[vKey],money:session.state.variableValues[mKey],borrowedRecordsCopied:p.entities.some(e=>e.id===b[map?.[f.childEntry.id]??f.childEntry.id]),virtualEntrypointCount:declaredEntrypoints(p).filter(id=>id===b[map?.[f.childEntry.id]??f.childEntry.id]).length});}
 save('CTX-child-independent',{project:f.p,native,loaded,restored,clone,run,expired,unknown,results,ids:{v:f.v.id,money:f.money.id,item:f.item.id,entry:f.entry.id,use:f.use.id,childEntry:f.childEntry.id,childExit:f.childExit.id,childEdge:f.childEdge.id,enter:f.enter.id,leave:f.leave.id,trace:trace.id}});expect(results).toEqual(Array.from({length:3},()=>({status:'terminal',provenance:'full_play',externalMode:null,clock:'5',depth:0,limited:{type:'integer',value:2},money:{type:'integer',value:9},borrowedRecordsCopied:false,virtualEntrypointCount:0})));
 }finally{cold?.close();await store.deleteDatabase();}
});
