import'fake-indexeddb/auto';import{it,expect}from'vitest';import{readFileSync,writeFileSync}from'node:fs';import{ScenarioStore}from'../src/storage/store';import{inspectScenario}from'../src/storage/archive';import{createProject,createEntity,newId,textToRichText}from'../src/domain/model';import{collectImportIds}from'../src/storage/importMapping';import{projectWithRecoveryHistory}from'../src/storage/recovery';
it('R6I14 explicitly mapped74 old commands retain original provenance and arbitrary unit restore across duplicate revision numbers',async()=>{
 const source=await inspectScenario(new Uint8Array(readFileSync('tests/fixtures/rb06-history.scenario')),{worker:false}),db=new ScenarioStore({databaseName:'independent-imported-history-'+newId()}),empty=new ScenarioStore({databaseName:'independent-imported-history-empty-'+newId()});
 try{const p=createProject('異なる作品の履歴統合先'),note=createEntity(p.projectId,'note','統合先の固有メモ',{body:textToRichText('残す元の本文')});p.entities.push(note);const target=(await db.saveProject(p,{reason:'統合先を保存'})).project;
 const ids=collectImportIds(projectWithRecoveryHistory(source.project,source.recovery)),idMap=Object.fromEntries(ids.map(item=>[item.id,item.role==='project'?target.projectId:newId()]));let q=await db.previewImport(source,{mode:'mapped_merge',targetProjectId:target.projectId,idMap});const resolutions=Object.fromEntries(q.conflicts.map(x=>[x.id,'existing' as const]));q=await db.previewImport(source,{mode:'mapped_merge',targetProjectId:target.projectId,idMap,resolutions});
 const imported=await db.importScenario(source,{mode:'mapped_merge',targetProjectId:target.projectId,idMap,resolutions,baseRevision:target.revision,confirmationHash:q.confirmationHash}),loaded=(await db.getProject(target.projectId))!,first=source.project.history[0],operation=idMap[first.operationId],scene=idMap[first.after.entities[0].id],history=await db.historyPage(target.projectId,{query:operation});expect(history.total).toBe(1);expect(loaded.history).toHaveLength(source.project.history.length+2);expect(loaded.history.find(x=>x.operationId===operation)?.importOrigin).toMatchObject({sourceProjectId:source.project.projectId,sourceOperationId:first.operationId});
 await expect(db.getProjectAtRevision(target.projectId,'1')).rejects.toMatchObject({code:'RESTORE_CONFLICT'});
 const restored=(await db.restoreEntity(target.projectId,operation,scene,'after',loaded.revision)).project;expect(restored.name).toBe(target.name);expect(restored.entities.find(x=>x.id===note.id)?.data).toEqual(note.data);expect(restored.entities.find(x=>x.id===scene)?.name).toBe(first.after.entities[0].name);expect(restored.snapshots).toEqual(loaded.snapshots);
 const bytes=await db.exportProject(target.projectId),round=await inspectScenario(bytes,{worker:false});await empty.importScenario(round,{mode:'new'});expect(await empty.getProject(target.projectId)).toEqual(restored);const retained=await empty.listRecoveredPending(target.projectId);expect(retained.slice(0,source.recovery!.pending.length).map(x=>x.operation.origin!.operationId)).toEqual(source.recovery!.pending.map(x=>x.operation.origin?.operationId??x.operationId));writeFileSync('independent/fixtures/R6I14.json',JSON.stringify({sourceFixture:'tests/fixtures/rb06-history.scenario',idMap,history,imported,restored,recovery:round.recovery},null,2)+'\n');
 }finally{await db.deleteDatabase();await empty.deleteDatabase();}
},30000);
