import { prepareReuse,resolveReuseContent } from '../domain/reuse';
import { reconcileDeliverables } from '../domain/production';
import 'fake-indexeddb/auto';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createEntity, createProject, newId, textToRichText, validateProject } from '../domain/model';
import { dialogueContentHash, pendingSourceHashes } from '../domain/production';
import { previewDialogueChange, confirmDialogueChange, previewSourceApproval, confirmSourceApproval } from '../domain/productionWorkflow';
import { prepareAsset } from '../domain/attachments';
import { previewMaterial, confirmMaterial, materialAvailability } from '../domain/materials';
import { createWorldSnapshot } from '../domain/world';
import { checkProductionRules, verifyProductionSources, productionCheckView } from '../domain/productionChecks';
import { exportProject } from '../domain/exports';
import { readFileSync } from 'node:fs';
import { ScenarioStore } from './store';
import { inspectScenario, exportScenario,worldSnapshotContents } from './archive';
import type { ProjectData } from '../domain/types';
import { mkdirSync, writeFileSync } from 'node:fs';
const stores: ScenarioStore[] = [];
const open = (fault?:()=>void) => { const store = new ScenarioStore({ databaseName:`rb07-${newId()}`, faultInjector:stage=>{if(stage==='before-commit')fault?.();} });stores.push(store);return store; };
afterEach(async()=>{for(const store of stores.splice(0))await store.deleteDatabase();});
async function fixture() {
 const p=createProject('台詞・資料の対応確認'), speaker=createEntity(p.projectId,'character','改名前の話者'), blockId=newId();
 const line=createEntity(p.projectId,'dialogue_line','原台詞L1',{speakerId:speaker.id,text:[{id:blockId,kind:'paragraph',text:'😀赤い扉へ帰る',ruby:[{start:1,end:3,text:'あかい'}],links:[{start:5,end:7,target:{entityId:speaker.id}}]}]});
 const cue=createEntity(p.projectId,'cue','右側の音声',{anchor:{entityId:line.id,lineId:line.id,blockId,start:5,end:7},cueType:'sound',mediaTime:123,waitMs:456});line.data.cueIds=[cue.id];
 const scene=createEntity(p.projectId,'scene','原場面',{dialogueLineIds:[line.id]});p.entities.push(speaker,line,cue,scene);p.entities.forEach(e=>e.status='confirmed');
 const hash=await dialogueContentHash(p,line),loc=createEntity(p.projectId,'localization','翻訳L1',{sourceLineId:line.id,language:'en',sourceHash:hash,text:textToRichText('Return to the red door.'),stage:'reviewed'}),recording=createEntity(p.projectId,'recording','収録L1',{sourceLineId:line.id,language:'ja',sourceHash:hash,stage:'reviewed'});loc.status=recording.status='confirmed';p.entities.push(loc,recording);
 return {p,line,cue,scene,speaker,blockId,loc,recording};
}
describe('RB07 authored production workflow and complete recovery',()=>{
 it('splits Unicode text with ruby, links and positional cue once; atomically retains old IDs, deliverables and immutable editions through empty/clone roundtrips',async()=>{
  const f=await fixture();let fail=false;const db=open(()=>{if(fail)throw new DOMException('production quota','QuotaExceededError');});
  let original=(await db.saveProject(await createWorldSnapshot(f.p,'変更前の公開版'),{reason:'元の台詞を保存'})).project;
  const plan=await previewDialogueChange(original,{mode:'split',sourceIds:[f.line.id],blockId:f.blockId,offset:4,reason:'音声の収録単位を分ける'});const candidate=await confirmDialogueChange(original,plan);
  expect(validateProject(candidate).ok).toBe(true);const parts=plan.newLineIds.map(id=>candidate.entities.find(e=>e.id===id)!);expect(parts.map(e=>e.kind==='dialogue_line'&&e.data.text[0].text)).toEqual(['😀赤い扉','へ帰る']);
  expect(parts.map(e=>e.kind==='dialogue_line'&&e.data.cueIds)).toEqual([[],[f.cue.id]]);const right=parts[1];if(right.kind!=='dialogue_line')throw new Error('fixture');expect(right.data.text[0].links![0]).toMatchObject({start:1,end:3});
  expect(candidate.entities.find(e=>e.id===f.cue.id)).toMatchObject({data:{anchor:{entityId:right.id,lineId:right.id,blockId:right.data.text[0].id,start:1,end:3}}});
  fail=true;await expect(db.saveProject(candidate,{reason:'分割'})).rejects.toMatchObject({code:'QUOTA_EXCEEDED'});expect(await db.getProject(original.projectId)).toEqual(original);fail=false;
  const saved=(await db.saveProject(candidate,{reason:'分割と対応を保存'})).project;expect(saved.entities.find(e=>e.id===f.line.id)).toMatchObject({status:'rejected',data:{replacedByLineIds:plan.newLineIds}});for(const id of [f.loc.id,f.recording.id])expect(saved.entities.find(e=>e.id===id)).toMatchObject({data:{sourceLineId:f.line.id,stage:'needs_review'}});
  expect(saved.snapshots).toEqual(original.snapshots);const backup=await db.exportProject(saved.projectId),prepared=await inspectScenario(backup,{worker:false});const destination=open();expect((await destination.importScenario(prepared,{mode:'new'})).project).toEqual(saved);
  const clone=(await open().importScenario(prepared,{mode:'clone'})).project;expect(validateProject(clone).ok).toBe(true);const lineage=clone.entities.find(e=>e.kind==='dialogue_line'&&e.data.lineage);expect(lineage?.kind==='dialogue_line'&&lineage.data.lineage?.segments[0].source.entityId).not.toBe(f.line.id);
  const dir='/tmp/shinariokanri-rb07-fixtures';mkdirSync(dir,{recursive:true});writeFileSync(`${dir}/production-ui.scenario`,await exportScenario(original));writeFileSync(`${dir}/production-ui.json`,JSON.stringify({project:original,...Object.fromEntries(['line','cue','scene','speaker','loc','recording'].map(key=>[key,(f as any)[key].id])),blockId:f.blockId},null,2));
 });
 it('rejects ruby/link interior cuts, empty boundary splits, duplicate/ordered-incompatible merges and changed confirmations without saving',async()=>{
  const f=await fixture();for(const offset of [0,2,6,7,-1,NaN])await expect(previewDialogueChange(f.p,{mode:'split',sourceIds:[f.line.id],blockId:f.blockId,offset,reason:'検査'})).rejects.toThrow();
  const second=createEntity(f.p.projectId,'dialogue_line','台詞L2',{text:textToRichText('続く'),speakerId:f.speaker.id});f.p.entities.push(second);f.scene.data.dialogueLineIds=[second.id,f.line.id];
  await expect(previewDialogueChange(f.p,{mode:'merge',sourceIds:[f.line.id,second.id],reason:'統合'})).rejects.toThrow('隣接');await expect(previewDialogueChange(f.p,{mode:'merge',sourceIds:[f.line.id,f.line.id],reason:'統合'})).rejects.toThrow('重複');
  const plan=await previewDialogueChange(f.p,{mode:'split',sourceIds:[f.line.id],blockId:f.blockId,offset:4,reason:'分割'});await expect(confirmDialogueChange({...f.p,revision:'1'},plan)).rejects.toThrow('確認後');plan.candidate.name='改ざん';await expect(confirmDialogueChange(f.p,plan)).rejects.toThrow('確認後');
 });
 it('merges adjacent same-speaker lines into fresh IDs and blocks, keeps intents/reasons, relocates precise anchors and leaves existing audio mappings for review',async()=>{
  const f=await fixture();const second=createEntity(f.p.projectId,'dialogue_line','原台詞L2',{text:textToRichText('次の一言'),speakerId:f.speaker.id,assertionReason:'第二の根拠'});second.status='confirmed';f.line.data.assertionReason='第一の根拠';f.p.entities.push(second);f.scene.data.dialogueLineIds=[f.line.id,second.id];
  const plan=await previewDialogueChange(f.p,{mode:'merge',sourceIds:[f.line.id,second.id],reason:'同じ収録単位'}),candidate=await confirmDialogueChange(f.p,plan),merged=candidate.entities.find(e=>e.id===plan.newLineIds[0]);expect(validateProject(candidate).ok).toBe(true);expect(merged).toMatchObject({data:{assertionReason:'第一の根拠\n第二の根拠',originLineIds:[f.line.id,second.id]}});expect(candidate.entities.find(e=>e.id===f.scene.id)).toMatchObject({data:{dialogueLineIds:plan.newLineIds}});
  const db=open(),saved=(await db.saveProject(candidate,{reason:'統合'})).project;expect(saved.entities.find(e=>e.id===f.recording.id)).toMatchObject({data:{stage:'needs_review',sourceLineId:f.line.id}});
 });
 it('keeps hashes for renaming/reorder, requires fresh explicit approval after text/ruby/speaker/cue/restore changes and refuses stale/hash-tampered approval',async()=>{
  const f=await fixture(),db=open();let p=(await db.saveProject(f.p,{reason:'原文'})).project;const source=()=>p.entities.find(e=>e.id===f.line.id)!;
  p=(await db.saveProject({...p,entities:p.entities.map(e=>e.id===f.speaker.id?{...e,name:'改名後'}:e).reverse()},{reason:'改名と並替え'})).project;expect((await pendingSourceHashes(p)).every(row=>!row.stale)).toBe(true);expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'reviewed'}});
  const oldOperation=p.history[0].operationId;const edited:ProjectData=structuredClone({...p,history:[]});edited.history=p.history;const line=edited.entities.find(e=>e.id===f.line.id)!;if(line.kind!=='dialogue_line')throw new Error('fixture');line.data.text[0].text='😀青い扉へ帰る';p=(await db.saveProject(edited,{reason:'本文修正'})).project;
  const plan=await previewSourceApproval(p,f.loc.id);expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'needs_review'}});await expect(confirmSourceApproval({...p,revision:'999'},plan)).rejects.toThrow('確認後');await expect(confirmSourceApproval(p,{...plan,sourceHash:'0'.repeat(64)})).rejects.toThrow('確認後');p=(await db.saveProject(await confirmSourceApproval(p,plan),{reason:'原文を確認'})).project;expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'reviewed',sourceHash:plan.sourceHash}});
  p=(await db.restoreEntity(p.projectId,oldOperation,f.line.id,'after',p.revision)).project;expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'needs_review'}});expect(source().id).toBe(f.line.id);
 });
 it('saves accessed real time, source provenance, attachment bytes and ms cues separately; missing metadata remains missing and material replacement keeps pinned versions',async()=>{
  const f=await fixture(),db=open(),oldBytes=new Uint8Array([137,80,78,71,13,10,26,10,0]),nextBytes=new Uint8Array([137,80,78,71,13,10,26,10,1]);const asset=await prepareAsset(oldBytes,'旧仮素材.png');let plan=await previewMaterial(f.p,asset);let p=await confirmMaterial(f.p,plan);const source=createEntity(p.projectId,'source','採取した書籍資料',{sourceType:'book',locator:'ISBN 9780000000000 p.12',accessedAt:'2026-10-08T09:00:00Z',excerptLocation:'第2章 p.12',interpretation:textToRichText('作者の解釈'),attachmentId:plan.newAttachmentId,redistributionAllowed:false});source.status='confirmed';p.entities.push(source);p.entities.find(e=>e.id===f.cue.id)!.data= {...f.cue.data,attachmentId:plan.newAttachmentId};p=(await db.saveProject(await createWorldSnapshot(p,'旧素材公開'),{reason:'原資料と素材',assets:[asset]})).project;
  expect(materialAvailability(p,await db.availableAssetHashes()).every(row=>row.bytes==='available')).toBe(true);expect(materialAvailability(p,new Set())[0].bytes).toBe('missing');const oldSnapshot=p.snapshots[0];const replacement=await prepareAsset(nextBytes,'完成差替え.png');plan=await previewMaterial(p,replacement,plan.newAttachmentId,[f.cue.id]);p=(await db.saveProject(await confirmMaterial(p,plan),{reason:'指定演出だけ差替え',assets:[replacement]})).project;expect(p.snapshots[0]).toEqual(oldSnapshot);expect(p.entities.find(e=>e.id===source.id)).toMatchObject({data:{attachmentId:oldSnapshot.content.entities.find(e=>e.kind==='attachment')!.id,accessedAt:'2026-10-08T09:00:00Z'}});expect(p.entities.find(e=>e.id===f.cue.id)).toMatchObject({data:{mediaTime:123,waitMs:456,attachmentId:plan.newAttachmentId}});expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'needs_review'}});
  const imported=await inspectScenario(await db.exportProject(p.projectId),{worker:false});expect(imported.assets).toHaveLength(2);expect(imported.project.entities.find(e=>e.id===source.id)).toEqual(p.entities.find(e=>e.id===source.id));
 });
 it('keeps production input and material bytes across reopening; rejects damaged drafts and oversized/active attachments without touching saved author data',async()=>{
  const f=await fixture(),name=`rb07-draft-${newId()}`,db=new ScenarioStore({databaseName:name});stores.push(db);const original=(await db.saveProject(f.p,{reason:'正本'})).project,asset=await prepareAsset(new TextEncoder().encode('資料本文'),'資料.txt','text/plain');await db.saveAuthorToolDraft({key:'production-fixture',projectId:f.p.projectId,baseRevision:original.revision,fields:{reason:'未保存の入力',fileName:asset.displayName},asset:{bytes:asset.bytes,contentHash:asset.contentHash}});db.close();const cold=new ScenarioStore({databaseName:name});stores.push(cold);expect((await cold.getAuthorToolDraft('production-fixture'))!.asset!.bytes).toEqual(asset.bytes);expect(await cold.getProject(f.p.projectId)).toEqual(original);await expect(cold.saveAuthorToolDraft({key:'bad',projectId:f.p.projectId,baseRevision:'1',fields:{},asset:{bytes:asset.bytes,contentHash:'0'.repeat(64)}})).rejects.toMatchObject({code:'HASH_MISMATCH'});
  for(const bytes of [new TextEncoder().encode('<svg onload="alert(1)"></svg>'),new TextEncoder().encode('<html><script>1</script></html>'),new Uint8Array([77,90,1])])await expect(prepareAsset(bytes,'unsafe.bin','application/octet-stream')).rejects.toThrow();await expect(prepareAsset(new Uint8Array(32*1024*1024+1),'large.png')).rejects.toThrow('32 MiB');
 });
 it('copies a line into independent IDs without moving the scene or old deliverables, and refuses a raw reviewed-stage change with a stale source hash',async()=>{
  const f=await fixture(),db=open();let p=(await db.saveProject(f.p,{reason:'元台詞'})).project;const plan=await previewDialogueChange(p,{mode:'copy',sourceIds:[f.line.id],reason:'別場面用の独立複製'}),candidate=await confirmDialogueChange(p,plan);expect(candidate.entities.find(e=>e.id===f.scene.id)).toEqual(p.entities.find(e=>e.id===f.scene.id));expect(candidate.entities.find(e=>e.id===f.line.id)).toEqual(p.entities.find(e=>e.id===f.line.id));const copied=candidate.entities.find(e=>e.id===plan.newLineIds[0]);expect(copied?.kind).toBe('dialogue_line');if(copied?.kind!=='dialogue_line')throw Error('fixture');expect(copied.data.text[0].id).not.toBe(f.blockId);expect(copied.data.cueIds![0]).not.toBe(f.cue.id);expect(candidate.entities.find(e=>e.id===copied.data.cueIds![0])).toMatchObject({data:{anchor:{lineId:copied.id,blockId:copied.data.text[0].id},mediaTime:123,waitMs:456}});p=(await db.saveProject(candidate,{reason:'複製'})).project;expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'reviewed'}});
  const edited=structuredClone(p);const source=edited.entities.find(e=>e.id===f.line.id)!;if(source.kind!=='dialogue_line')throw Error('fixture');source.data.text[0].text='😀青い扉へ帰る';p=(await db.saveProject(edited,{reason:'原文変更'})).project;const raw=structuredClone(p),translation=raw.entities.find(e=>e.id===f.loc.id)!;if(translation.kind!=='localization')throw Error('fixture');translation.data.stage='reviewed';p=(await db.saveProject(raw,{reason:'旧hashの手動段階変更'})).project;expect(p.entities.find(e=>e.id===f.loc.id)).toMatchObject({data:{stage:'needs_review'}});
 });
 it('observes literal Unicode reading/spelling in source, translation and caption; rejected, expired, unknown and old-edition rules never become an approval',async()=>{
  const f=await fixture(),term=createEntity(f.p.projectId,'terminology','赤い扉の表記',{canonical:'赤い扉',reading:'あかいとびら',variants:['赤き扉'],validity:{worldRange:{start:'10',end:'20'},routeCondition:null,presentationAnchor:null}});term.status='confirmed';f.loc.data.text=textToRichText('😀赤き扉');const frame=createEntity(f.p.projectId,'storyboard_frame','字幕',{anchor:{entityId:f.line.id,lineId:f.line.id},caption:textToRichText('😀赤い扉')});frame.status='confirmed';f.p.entities.push(term,frame);expect(checkProductionRules(f.p,{at:'9'})).toEqual([]);expect(checkProductionRules(f.p,{at:'20'})).toEqual([]);expect(checkProductionRules(f.p).some(row=>row.value==='unknown')).toBe(true);const current=checkProductionRules(f.p,{at:'10'});expect(current.find(row=>row.lineId===f.loc.id&&row.kind==='spelling')?.anchor).toMatchObject({start:1,end:4});expect(current.find(row=>row.lineId===frame.id&&row.kind==='reading')).toBeTruthy();term.status='rejected';expect(checkProductionRules(f.p,{at:'10'})).toEqual([]);term.status='confirmed';term.data.validity={worldRange:null,routeCondition:null,presentationAnchor:{entityId:f.line.id,sourceVersionId:newId()}};expect(checkProductionRules(f.p,{at:'10'}).every(row=>row.value==='unknown')).toBe(true);
 });
 it('binds a newly uploaded source attachment inside the confirmed diff and verifies actual media signatures without treating metadata as bytes',async()=>{
  const f=await fixture(),source=createEntity(f.p.projectId,'source','動画資料',{accessedAt:'2026-10-08T11:00:00Z'});source.status='confirmed';f.p.entities.push(source);for(const [file,type] of [['fixture-blue.mp4','video/mp4'],['fixture-tone.wav','audio/wav']] as const){const asset=await prepareAsset(new Uint8Array(readFileSync(`tests/fixtures/media/${file}`)),file);expect(asset.mediaType).toBe(type);const plan=await previewMaterial(f.p,asset,undefined,[],source.id);expect(plan.candidate.entities.find(e=>e.id===source.id)).toMatchObject({data:{attachmentId:plan.newAttachmentId}});expect((await confirmMaterial(f.p,plan)).entities.find(e=>e.id===source.id)).toEqual(plan.candidate.entities.find(e=>e.id===source.id));await expect(confirmMaterial({...f.p,revision:'99'},plan)).rejects.toThrow('確認後');}
 });
 it('exports only task-assigned deliverables and their material dependencies, keeps stable public IDs and never exposes the private assignee ID',async()=>{
  const f=await fixture(),other=createEntity(f.p.projectId,'dialogue_line','担当外',{text:textToRichText('担当外の原文')}),task=createEntity(f.p.projectId,'production_task','担当作業',{targetIds:[f.loc.id],assigneeId:'fa326622-a8cc-4e7d-9abd-47913eb1c0a2'});other.status=task.status='confirmed';f.p.entities.push(other,task);const profile=createEntity(f.p.projectId,'projection_profile','翻訳公開',{audience:'public',publicTitle:'担当翻訳',allowedKinds:['character','dialogue_line','localization','recording','cue','attachment','terminology'],idPolicy:'preserve',includedIds:f.p.entities.map(e=>e.id),namePolicy:{defaultPolicy:{mode:'replace',replacement:'公開項目'}},publicTexts:{[f.cue.id]:{cueType:'sound'},[f.recording.id]:{language:'ja'},[f.line.id]:{text:f.line.data.text},[f.loc.id]:{text:f.loc.data.text,language:'en'},[other.id]:{text:other.data.text}}});f.p.entities.push(profile);const result=await exportProject(f.p,{profile:'localization',projectionProfileId:profile.id,targetRevision:f.p.revision,assigneeId:'fa326622-a8cc-4e7d-9abd-47913eb1c0a2'});if(!result.ok)throw Error(JSON.stringify(result.issues));expect(result.ok).toBe(true);const payload=JSON.parse(result.artifacts.find(a=>a.filename==='localization.json')!.content);expect(payload.lines).toHaveLength(1);expect(payload.lines[0].lineId).toBe(f.line.id);expect(payload.lines[0].translations.map((t:any)=>t.id)).toEqual([f.loc.id]);expect(payload.lines[0].recordings).toEqual([]);expect(JSON.stringify(payload)).not.toContain('fa326622-a8cc-4e7d-9abd-47913eb1c0a2');expect((await exportProject(f.p,{profile:'localization',projectionProfileId:profile.id,targetRevision:f.p.revision,assigneeId:'missing'})).ok).toBe(false);
 });
 it('keeps the historical source of an independent copied line when its original later merges, and propagates a material cue change to storyboard/task review atomically',async()=>{
  const f=await fixture(),copy=await previewDialogueChange(f.p,{mode:'copy',sourceIds:[f.line.id],reason:'独立複製'});let p=await confirmDialogueChange(f.p,copy);const copied=p.entities.find(e=>e.id===copy.newLineIds[0])!;if(copied.kind!=='dialogue_line')throw Error('fixture');const historic=structuredClone(copied.data.lineage);const second=createEntity(p.projectId,'dialogue_line','後続台詞',{speakerId:f.speaker.id,text:textToRichText('後続')});second.status='confirmed';p.entities.push(second);const scene=p.entities.find(e=>e.id===f.scene.id)!;if(scene.kind!=='scene')throw Error('fixture');scene.data.dialogueLineIds=[f.line.id,second.id];const merged=await confirmDialogueChange(p,await previewDialogueChange(p,{mode:'merge',sourceIds:[f.line.id,second.id],reason:'元だけ統合'}));expect(merged.entities.find(e=>e.id===copied.id)).toMatchObject({data:{lineage:historic}});
  const db=open(),asset=await prepareAsset(new Uint8Array([137,80,78,71,13,10,26,10]),'first.png'),material=await previewMaterial(f.p,asset);let base=await confirmMaterial(f.p,material);const cue=base.entities.find(e=>e.id===f.cue.id)!;if(cue.kind!=='cue')throw Error('fixture');cue.data.attachmentId=material.newAttachmentId;const frame=createEntity(base.projectId,'storyboard_frame','影響を受けるコマ',{anchor:{entityId:f.line.id},cueIds:[f.cue.id]}),task=createEntity(base.projectId,'production_task','完成したコマ作業',{targetIds:[frame.id],progress:'done'});frame.status=task.status='confirmed';base.entities.push(frame,task);base=(await db.saveProject(base,{reason:'旧素材と依存',assets:[asset]})).project;const replacement=await prepareAsset(new Uint8Array([137,80,78,71,13,10,26,10,1]),'new.png'),plan=await previewMaterial(base,replacement,material.newAttachmentId,[f.cue.id]),saved=(await db.saveProject(await confirmMaterial(base,plan),{reason:'演出から確認待ちを伝播',assets:[replacement]})).project;expect(saved.entities.find(e=>e.id===frame.id)?.status).toBe('needs_review');expect(saved.entities.find(e=>e.id===task.id)).toMatchObject({data:{progress:'needs_review'}});
 });
 it('captures material/source approval input before the first hash await instead of approving later mutable revisions, names, bytes or replacement arrays',async()=>{
  const f=await fixture(),asset=await prepareAsset(new Uint8Array([137,80,78,71,13,10,26,10]),'capture.png'),original=structuredClone(f.p),digest=crypto.subtle.digest.bind(crypto.subtle);let release!:()=>void,held=false;const spy=vi.spyOn(crypto.subtle,'digest').mockImplementation(async(...args)=>{if(!held){held=true;await new Promise<void>(resolve=>{release=resolve;});}return digest(...args);});
  try{const ids:string[]=[],pending=previewMaterial(f.p,asset,undefined,ids);f.p.revision='9';f.p.name='後発名';ids.push(f.cue.id);asset.bytes[0]=0;release();const plan=await pending;expect(plan.baseRevision).toBe('0');expect(plan.candidate.name).toBe(original.name);expect(plan.replacementIds).toEqual([]);expect(plan.asset.bytes[0]).toBe(137);await expect(confirmMaterial(f.p,plan)).rejects.toThrow('確認後');}finally{spy.mockRestore();}
  f.p=original;held=false;const second=vi.spyOn(crypto.subtle,'digest').mockImplementation(async(...args)=>{if(!held){held=true;await new Promise<void>(resolve=>{release=resolve;});}return digest(...args);});try{const pending=previewSourceApproval(f.p,f.loc.id);f.p.revision='9';release();expect((await pending).baseRevision).toBe('0');}finally{second.mockRestore();}
 });
});

it('keeps a storyboard fixed to an unchanged old edition confirmed while live cue dependents require review',async()=>{
 const project=createProject('版付き依存'),line=createEntity(project.projectId,'dialogue_line','元台詞',{text:textToRichText('旧版の台詞')}),cue=createEntity(project.projectId,'cue','現稿の演出',{anchor:{entityId:line.id},cueType:'sound',expression:'初稿'});line.data.cueIds=[cue.id];line.status=cue.status='confirmed';project.entities.push(line,cue);
 const snapshotProject=await createWorldSnapshot(project,'固定した旧版');const pin=snapshotProject.snapshots.at(-1)!;
 const fixed=createEntity(project.projectId,'storyboard_frame','旧版だけのコマ',{anchor:{entityId:line.id,blockId:line.data.text[0].id,sourceVersionId:pin.id},cueIds:[]}),live=createEntity(project.projectId,'storyboard_frame','現稿の演出に依存',{anchor:{entityId:line.id},cueIds:[cue.id]});fixed.status=live.status='confirmed';snapshotProject.entities.push(fixed,live);
 const candidate=structuredClone(snapshotProject),changed=candidate.entities.find(e=>e.id===cue.id)!;if(changed.kind==='cue')changed.data.expression='新稿';const result=await reconcileDeliverables(snapshotProject,candidate);
 expect(result.entities.find(e=>e.id===fixed.id)?.status).toBe('confirmed');expect(result.entities.find(e=>e.id===live.id)?.status).toBe('needs_review');expect(result.snapshots[0]).toEqual(pin);expect(result.entities.find(e=>e.id===fixed.id)?.data).toEqual(fixed.data);
});

it('uses the fixed source speaker for captions after live speaker changes and refuses a corrupt source pin',async()=>{const p=createProject('旧版話者'),a=createEntity(p.projectId,'character','旧話者'),b=createEntity(p.projectId,'character','現稿話者'),line=createEntity(p.projectId,'dialogue_line','元台詞',{speakerId:a.id,text:textToRichText('私の声')}),rule=createEntity(p.projectId,'voice_rule','旧話者の口調',{characterId:a.id,firstPerson:'私'});[a,b,line,rule].forEach(e=>e.status='confirmed');p.entities.push(a,b,line,rule);const pinned=await createWorldSnapshot(p,'話者Aの旧版'),pin=pinned.snapshots.at(-1)!,frame=createEntity(p.projectId,'storyboard_frame','固定字幕',{anchor:{entityId:line.id,sourceVersionId:pin.id},caption:textToRichText('私の声'),cueIds:[]});frame.status='confirmed';pinned.entities.push(frame);const changed=structuredClone(pinned),current=changed.entities.find(e=>e.id===line.id)!;if(current.kind==='dialogue_line')current.data.speakerId=b.id;const checks=checkProductionRules(changed,{verifiedVersionIds:await verifyProductionSources(changed)}).filter(check=>check.lineId===frame.id&&check.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({ruleId:rule.id,value:'true',sourceAnchor:{entityId:line.id,sourceVersionId:pin.id}});expect(checkProductionRules(changed).filter(check=>check.lineId===frame.id).every(check=>check.value==='unknown')).toBe(true);changed.snapshots[0].content.entities[0].name='改ざん';await expect(verifyProductionSources(changed)).rejects.toThrow('固定版hash');});

it('checks a caption against a verified fixed world speaker without copying borrowed records into canonical content',async()=>{const world=createProject('共通世界'),speaker=createEntity(world.projectId,'character','固定話者'),line=createEntity(world.projectId,'dialogue_line','固定台詞',{speakerId:speaker.id,text:textToRichText('固定した声')}),rule=createEntity(world.projectId,'voice_rule','固定口調',{characterId:speaker.id,firstPerson:'私'});[speaker,line,rule].forEach(e=>e.status='confirmed');world.entities.push(speaker,line,rule);const w=await createWorldSnapshot(world,'旧世界'),pin=w.snapshots.at(-1)!,p=createProject('参照作品'),frame=createEntity(p.projectId,'storyboard_frame','共通世界の字幕',{anchor:{entityId:line.id,sourceVersionId:pin.id},caption:textToRichText('固定した声'),cueIds:[]});frame.status='confirmed';p.entities.push(frame);p.worldReferences=[{projectId:world.projectId,immutableSnapshotId:pin.id,contentHash:pin.contentHash}];const before=JSON.stringify(p),view=await productionCheckView(p,{[pin.id]:pin.content}),checks=checkProductionRules(view.project,view).filter(check=>check.lineId===frame.id&&check.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({value:'true',ruleAnchor:{entityId:rule.id,sourceVersionId:pin.id},sourceAnchor:{entityId:line.id,sourceVersionId:pin.id}});expect(JSON.stringify(p)).toBe(before);const corrupt=structuredClone(pin.content);corrupt.entities[0].name='改ざん';await expect(productionCheckView(p,{[pin.id]:corrupt})).rejects.toThrow('ハッシュ');});


it('resolves an outer fixed edition through its verified reuse dependencies for subtitle speakers and refuses damaged dependencies without a fixed caption',async()=>{const f=await fixture(),use=createEntity(f.p.projectId,'scene','共通台詞の使用先');use.status='confirmed';f.p.entities.push(use);let p=(await prepareReuse(f.p,{ownerId:use.id,sourceId:f.scene.id,mode:'reference'})).candidate;const owner=p.entities.find(e=>e.id===use.id)!;if(owner.kind!=='scene')throw Error('fixture');const borrowed=owner.data.reuse!.bindings![f.line.id],block=owner.data.reuse!.bindings![f.blockId],inner=owner.data.reuse!.pinnedSnapshotId;p=await createWorldSnapshot(p,'依存版を持つ外側版');const outer=p.snapshots.at(-1)!,frame=createEntity(p.projectId,'storyboard_frame','共通台詞固定字幕',{anchor:{entityId:borrowed,lineId:borrowed,blockId:block,sourceVersionId:outer.id},caption:textToRichText('旧話者の字幕'),cueIds:[]}),rule=createEntity(p.projectId,'voice_rule','旧話者の口調',{characterId:f.speaker.id,firstPerson:'私'});frame.status=rule.status='confirmed';p.entities.push(frame,rule);const sourceBefore=JSON.stringify(p),view=await productionCheckView(p),checks=checkProductionRules(view.project,view).filter(check=>check.lineId===frame.id&&check.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({value:'true',sourceAnchor:{entityId:borrowed,sourceVersionId:outer.id}});expect(JSON.stringify(p)).toBe(sourceBefore);expect(resolveReuseContent(outer.content,p.snapshots).entities.some(e=>e.id===borrowed)).toBe(true);const damaged=structuredClone(p);damaged.entities=damaged.entities.map(e=>e.id===frame.id?{...frame,data:{...frame.data,anchor:{entityId:f.line.id}}}:e);damaged.snapshots.find(pin=>pin.id===inner)!.content.entities[0].name='改ざん';await expect(productionCheckView(damaged)).rejects.toThrow('hash');const damagedOuter=structuredClone(p);damagedOuter.snapshots.find(pin=>pin.id===inner)!.content.entities[0].name='改ざん';await expect(verifyProductionSources(damagedOuter)).rejects.toThrow('hash');});


it('keeps an explicitly pinned older world caption and voice rule after adopting a newer world, verifies the historical digest and never adds old truth to the active world',async()=>{const world=createProject('共通世界'),a=createEntity(world.projectId,'character','旧話者A'),b=createEntity(world.projectId,'character','新話者B'),line=createEntity(world.projectId,'dialogue_line','元台詞',{speakerId:a.id,text:textToRichText('旧世界の声')}),rule=createEntity(world.projectId,'voice_rule','口調',{characterId:a.id,firstPerson:'私'});[a,b,line,rule].forEach(e=>e.status='confirmed');world.entities.push(a,b,line,rule);let w=await createWorldSnapshot(world,'旧世界');const old=w.snapshots.at(-1)!;const currentLine=w.entities.find(e=>e.id===line.id)!,currentRule=w.entities.find(e=>e.id===rule.id)!;if(currentLine.kind==='dialogue_line')currentLine.data.speakerId=b.id;if(currentRule.kind==='voice_rule')currentRule.data.characterId=b.id;w=await createWorldSnapshot(w,'新世界');const latest=w.snapshots.at(-1)!,p=createProject('作品'),frame=createEntity(p.projectId,'storyboard_frame','旧世界字幕',{anchor:{entityId:line.id,sourceVersionId:old.id},caption:textToRichText('旧話者Aの字幕'),cueIds:[]});frame.status='confirmed';p.entities.push(frame);p.worldReferences=[{projectId:w.projectId,immutableSnapshotId:latest.id,contentHash:latest.contentHash}];const registry=Object.fromEntries(w.snapshots.map(pin=>[pin.id,pin.content])),before=JSON.stringify(p);await expect(productionCheckView(p,registry)).rejects.toThrow('期待hash');const view=await productionCheckView(p,registry,w.snapshots),checks=checkProductionRules(view.project,view).filter(check=>check.lineId===frame.id&&check.kind==='voice');expect(checks).toHaveLength(1);expect(checks[0]).toMatchObject({value:'true',ruleAnchor:{entityId:rule.id,sourceVersionId:old.id},sourceAnchor:{entityId:line.id,sourceVersionId:old.id}});expect(view.project.entities.find(e=>e.id===line.id)).toMatchObject({data:{speakerId:b.id}});expect(JSON.stringify(p)).toBe(before);await expect(productionCheckView(p,registry,w.snapshots.map(pin=>pin.id===old.id?{...pin,contentHash:'0'.repeat(64)}:pin))).rejects.toThrow('期待hash');});


it('includes an explicitly cited old world in complete recovery when the work has only ever adopted the new world',async()=>{const w=createProject('世界'),speaker=createEntity(w.projectId,'character','話者A'),line=createEntity(w.projectId,'dialogue_line','引用元',{speakerId:speaker.id,text:textToRichText('旧世界本文')}),rule=createEntity(w.projectId,'voice_rule','Aの口調',{characterId:speaker.id,firstPerson:'私'});[speaker,line,rule].forEach(e=>e.status='confirmed');w.entities.push(speaker,line,rule);let world=await createWorldSnapshot(w,'旧引用版');const old=world.snapshots.at(-1)!;world=await createWorldSnapshot(world,'現在採用版');const latest=world.snapshots.at(-1)!,holder=createProject('旧版の登録作品'),p=createProject('新版採用と旧版字幕'),frame=createEntity(p.projectId,'storyboard_frame','旧字幕',{anchor:{entityId:line.id,sourceVersionId:old.id},caption:textToRichText('引用字幕'),cueIds:[]});frame.status='confirmed';p.entities.push(frame);holder.worldReferences=[{projectId:world.projectId,immutableSnapshotId:old.id,contentHash:old.contentHash}];p.worldReferences=[{projectId:world.projectId,immutableSnapshotId:latest.id,contentHash:latest.contentHash}];const db=open();await db.saveProject(world,{reason:'元世界'});await db.saveProject(holder,{reason:'別作品で旧版を登録',worldPin:{world,snapshotId:old.id}});const saved=(await db.saveProject(p,{reason:'初回から新版を採用',worldPin:{world,snapshotId:latest.id}})).project,prepared=await inspectScenario(await db.exportProject(saved.projectId),{worker:false});expect(worldSnapshotContents(prepared.worlds)[old.id]).toEqual(old.content);for(const mode of ['new','clone']as const){const target=open(),restored=(await target.importScenario(prepared,{mode})).project,records=await target.listWorldSnapshots(),view=await productionCheckView(restored,worldSnapshotContents(records),Object.values(records).flatMap(world=>world.snapshots)),frame=restored.entities.find(e=>e.kind==='storyboard_frame')!;expect(checkProductionRules(view.project,view).filter(check=>check.lineId===frame.id&&check.kind==='voice')).toContainEqual(expect.objectContaining({value:'true',sourceAnchor:expect.objectContaining({sourceVersionId:old.id})}));expect(restored.entities).toHaveLength(1);}});
