import 'fake-indexeddb/auto';
import {afterEach,it,expect,vi} from 'vitest';
import {createEntity,createProject,newId,textToRichText} from '../domain/model';
import {sharedReviewFixture} from '../testing/sharedReviewFixture';
import {createSharedCommentReview,reviewLatestPosition,commentStage,type SharedComment} from '../domain/sharedReviews';
import {sha256} from './json';
import {ScenarioStore,cloneProject} from './store';
import {exportScenario,inspectScenario} from './archive';
const stores:ScenarioStore[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const db of stores.splice(0))await db.deleteDatabase();});
it('AT-F29 preserves the original version, Unicode quotation and production task through failure, deletion, stages, cold reload and complete clone restoration',async()=>{
 const f=await sharedReviewFixture(),review=await createSharedCommentReview(f.p,f.envelope,f.comment,'https://dedicated.invalid'),task=createEntity(f.p.projectId,'production_task','指摘の対応',{targetIds:[review.id,f.line.id],stage:'review',progress:'todo'});f.p.entities.push(review,task);expect(review.data.quotedText).toBe('😀版');expect(reviewLatestPosition(f.p,review)).toBe('known');
 let fail=false;const name='rb10-review-'+newId(),db=new ScenarioStore({databaseName:name,faultInjector:stage=>{if(fail&&stage==='before-commit')throw new DOMException('quota','QuotaExceededError');}});stores.push(db);let saved=(await db.saveProject(f.p,{reason:'元の引用・指摘・タスクを原子保存'})).project;
 let candidate={...saved,entities:saved.entities.map(e=>e.id===f.line.id&&e.kind==='dialogue_line'?{...e,data:{...e.data,text:[]}}:e.kind==='projection_profile'?{...e,data:{...e.data,blockSources:{},publicTexts:{}}}:e)};fail=true;await expect(db.saveProject(candidate,{reason:'原段落削除'})).rejects.toMatchObject({code:'QUOTA_EXCEEDED'});expect(await db.getProject(saved.projectId)).toEqual(saved);fail=false;saved=(await db.saveProject(candidate,{reason:'原段落削除'})).project;expect(reviewLatestPosition(saved,review)).toBe('unknown');
 await expect(db.saveProject({...saved,entities:saved.entities.map(e=>e.id===review.id&&e.kind==='review'?{...e,data:{...e.data,stage:'verified'}}:e)},{reason:'未処理から確認済みへ飛ばす'})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
 for(const stage of ['fixed','verified'] as const)saved=(await db.saveProject({...saved,entities:saved.entities.map(e=>e.id===review.id&&e.kind==='review'?{...e,data:{...e.data,stage}}:e)},{reason:stage})).project;
 db.close();const cold=new ScenarioStore({databaseName:name});stores.push(cold);const restored=(await cold.getProject(saved.projectId))!,current=restored.entities.find(e=>e.id===review.id)!;expect(current.data).toMatchObject({stage:'verified',quotedText:'😀版',targetVersionId:f.pin.id,sharedSource:{comment:f.comment.id,observedStage:'open'}});expect(restored.snapshots[0].content.entities.find(e=>e.id===f.line.id)?.data).toMatchObject({text:f.line.data.text});
 const archive=await inspectScenario(await cold.exportProject(saved.projectId),{worker:false});expect(archive.manifest.requiredFeatures).toContain('shared-review-source-v1');const {project:clone,idMap}=await cloneProject(archive.project),copy=clone.entities.find(e=>e.id===idMap[review.id])!;expect(copy.data).toMatchObject({sharedSource:review.data.sharedSource,targetVersionId:idMap[f.pin.id]});expect(clone.entities.find(e=>e.id===idMap[task.id])?.data).toMatchObject({targetIds:[idMap[review.id],idMap[f.line.id]]});
 for(const update of [{sharedSource:{...review.data.sharedSource!,quotedText:'別の引用'}},{targetVersionId:newId()},{quotedText:'改変'}])await expect(cold.saveProject({...restored,entities:restored.entities.map(e=>e.id===review.id&&e.kind==='review'?{...e,data:{...e.data,...update}}:e)},{reason:'元出所の改変'})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
});
it('keeps a changed public quote unresolved and refuses unknown, tampered, wrong tenant and out-of-range provenance without creating a review',async()=>{
 const f=await sharedReviewFixture('公開に直した台詞'),review=await createSharedCommentReview(f.p,f.envelope,f.comment,'https://dedicated.invalid');expect(review.data.target).toMatchObject({positionStatus:'unresolved'});expect(review.data.quotedText).toBe('公開');expect(reviewLatestPosition(f.p,review)).toBe('unknown');
 for(const [envelope,comment,url]of [[{...f.envelope,sourceHash:'a'.repeat(64)},f.comment,'https://dedicated.invalid'],[f.envelope,{...f.comment,end_cp:999},'https://dedicated.invalid'],[f.envelope,{...f.comment,public_version_id:'unknown'},'https://dedicated.invalid'],[f.envelope,f.comment,'http://other.invalid']] as const)await expect(createSharedCommentReview(f.p,envelope,comment,url)).rejects.toThrow();expect(commentStage({...f.comment,review_stage:undefined,resolved:true})).toBe('fixed');
 const bytes=await exportScenario({...f.p,entities:[...f.p.entities,review]}),inspection=await inspectScenario(bytes,{worker:false});expect(inspection.project.entities.find(e=>e.id===review.id)?.data).toMatchObject({quotedText:'公開'});
});
it('captures edition, comment body and codepoint target before delayed hash verification',async()=>{const f=await sharedReviewFixture(),body=f.comment.body,expectedHash=await sha256(new TextEncoder().encode(JSON.stringify(body))),digest=crypto.subtle.digest.bind(crypto.subtle);let entered!:()=>void,release!:()=>void;const waiting=new Promise<void>(resolve=>entered=resolve),gate=new Promise<void>(resolve=>release=resolve);let first=true;vi.spyOn(crypto.subtle,'digest').mockImplementation(async(...args)=>{if(first){first=false;entered();await gate;}return digest(...args);});const pending=createSharedCommentReview(f.p,f.envelope,f.comment,'https://dedicated.invalid');await waiting;f.comment.body='遅れて変更した指摘';f.comment.start_cp=2;f.comment.end_cp=3;f.p.snapshots[0].content.entities[0].name='後で変更';release();const review=await pending;expect(review.data).toMatchObject({quotedText:'😀版',target:{start:0,end:2},sharedSource:{commentBodyHash:expectedHash}});expect(review.data.body.map(b=>b.text).join('')).toBe(body);});
